import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const VERSION = "layer1-edge-v1.3.0";
const CHUNK = 250;
const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json", "Cache-Control": "no-store" } });
const clean = (v:any) => String(v ?? "").trim();
const slug = (v:string) => clean(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100);
function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],field="",q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='"'){if(text[i+1]==='"'){field+='"';i++;}else q=false;}else field+=ch;}else if(ch==='"')q=true;else if(ch===','){row.push(field);field="";}else if(ch==='\n'){row.push(field);rows.push(row);row=[];field="";}else if(ch!=='\r')field+=ch;}if(field.length||row.length){row.push(field);rows.push(row);}return rows;}
function mapLevel(raw:string){const s=clean(raw).toLowerCase();if(/doctor|phd/.test(s))return"doctorate";if(/master|m\.sc|m\.a\.|mba|ll\.m/.test(s))return"masters";if(/graduate certificate/.test(s))return"graduate_certificate";if(/graduate diploma/.test(s))return"graduate_diploma";if(/bachelor|b\.sc|b\.a\.|b\.eng/.test(s))return"bachelor";if(/associate/.test(s))return"associate_degree";if(/diploma/.test(s))return"diploma";if(/certificate/.test(s))return"certificate";if(/foundation/.test(s))return"foundation";return"";}
async function fetchT(url:string,ms=30000,init:RequestInit={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal,redirect:"follow",headers:{"user-agent":"coursefinder-pilot/1.3",...(init.headers||{})}});}finally{clearTimeout(t);}}
async function hashBytes(bytes:Uint8Array){const h=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function rpc(c:any,n:string,a:any={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function authAdmin(req:Request,service:any,url:string,key:string){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw new Error("authentication required");const client=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const{data:{user},error}=await client.auth.getUser(token);if(error||!user)throw new Error("invalid user session");if(!await rpc(service,"svc_layer1_authorize_platform_admin",{p_user_id:user.id}))throw new Error("platform_admin required");return {user,token};}
async function evidence(service:any,sourceId:string,jobId:string,url:string,path:string,bytes:Uint8Array,mime:string,metadata:any){const hash=await hashBytes(bytes);const up=await service.storage.from("evidence").upload(path,bytes,{contentType:mime,upsert:true});if(up.error)throw new Error(`evidence upload: ${up.error.message}`);const id=await rpc(service,"svc_layer1_record_evidence",{p_source_id:sourceId,p_job_id:jobId,p_source_url:url,p_storage_path:path,p_content_hash:hash,p_mime_type:mime,p_metadata:metadata});return{id,hash};}
async function applyRecords(service:any,cc:string,sourceId:string,evidenceId:string|null,scheme:string,records:any[],apply:boolean,maxRecords:number){const selected=maxRecords>0?records.slice(0,maxRecords):records;const total:any={records:selected.length,provider_created:0,provider_linked:0,provider_existing:0,course_created:0,course_linked:0,course_existing:0,conflicts:0};if(!apply)return total;for(let i=0;i<selected.length;i+=CHUNK){const r=await rpc(service,"svc_layer1_apply_register_records",{p_country_code:cc,p_source_id:sourceId,p_evidence_id:evidenceId,p_registration_scheme:scheme,p_records:selected.slice(i,i+CHUNK)});for(const k of Object.keys(total))if(k!=="records")total[k]+=Number(r?.[k]||0);}return total;}
async function sources(service:any,cc:string){return await rpc(service,"svc_layer1_resolve_sources",{p_country_code:cc})||[];}
async function startJob(service:any,cc:string,sourceId:string,payload:any){return await rpc(service,"svc_layer1_start_job",{p_country_code:cc,p_source_id:sourceId,p_payload:payload});}
async function finishJob(service:any,id:string,status:string,result:any,error:string|null=null){try{await rpc(service,"svc_layer1_finish_job",{p_job_id:id,p_status:status,p_result:result,p_error:error});}catch{}}
async function health(service:any,id:string,ok:boolean,error:string|null,metadata:any){try{await rpc(service,"svc_layer1_source_health",{p_source_id:id,p_success:ok,p_error:error,p_metadata:metadata});}catch{}}

async function runAU(url:string,anon:string,token:string,apply:boolean,maxRecords:number){const r=await fetchT(`${url}/functions/v1/layer1-au-depth`,120000,{method:"POST",headers:{Authorization:`Bearer ${token}`,apikey:anon,"content-type":"application/json"},body:JSON.stringify({apply,maxRecords})});const text=await r.text();let out:any;try{out=JSON.parse(text)}catch{out={raw:text}};if(!r.ok||out?.error)throw new Error(`layer1-au-depth: ${out?.error||`HTTP ${r.status}`}`);return out;}

async function runSeed(service:any,cc:string,srcs:any[],apply:boolean,maxRecords:number,userId:string){const source=srcs[0];if(!source)throw new Error(`${cc}: source missing`);const snap=await rpc(service,"svc_layer1_get_seed_snapshot",{p_country_code:cc});if(!Array.isArray(snap)||!snap.length)throw new Error(`${cc}: Layer 1 seed snapshot missing`);const records:any[]=[];for(const p of snap){for(const c of p.q||[])records.push({provider_code:p.p,provider_name:p.n,website:p.w,city:p.c,course_name:c[0],course_level:c[1],course_code:c[2],duration_weeks:c[3],field_of_study:c[4]});if(!(p.q||[]).length)records.push({provider_code:p.p,provider_name:p.n,website:p.w,city:p.c});}const scheme=clean(snap[0]?.s||source.system_code||cc).toLowerCase();const jobId=await startJob(service,cc,source.source_id,{country_code:cc,apply,max_records:maxRecords,runtime:"supabase_edge",version:VERSION,mode:"seed_snapshot",requested_by:userId});try{let reachable=false,httpStatus:null|number=null,liveError:null|string=null;try{const r=await fetchT(source.source_url||source.system_base_url,12000);httpStatus=r.status;reachable=r.ok;await r.body?.cancel();}catch(e){liveError=String(e).slice(0,300);}const stamp=new Date().toISOString().replace(/[:.]/g,"-");const bytes=new TextEncoder().encode(JSON.stringify(snap));const ev=await evidence(service,source.source_id,jobId,source.source_url||source.system_base_url,`regulatory/${cc}/seed/${stamp}.json`,bytes,"application/json",{country:cc,mode:"seed_snapshot",live_reachable:reachable,http_status:httpStatus});const rec=await applyRecords(service,cc,source.source_id,ev.id,scheme,records,apply,maxRecords);const result={country:cc,mode:apply?"apply":"dry-run",adapter:"seed_snapshot",parsedRecords:records.length,selectedRecords:maxRecords>0?Math.min(maxRecords,records.length):records.length,reconciliation:rec,evidenceIds:[ev.id],freshness:{reachable,httpStatus,error:liveError},workerVersion:VERSION};await health(service,source.source_id,reachable,liveError,{worker_version:VERSION,last_run_mode:result.mode,last_run_records:result.selectedRecords,seed_snapshot:true});await finishJob(service,jobId,"completed",result);return{...result,jobId};}catch(e){const msg=String(e).slice(0,1800);await health(service,source.source_id,false,msg,{worker_version:VERSION});await finishJob(service,jobId,"failed",{workerVersion:VERSION},msg);throw e;}}

async function runGB(service:any,srcs:any[],apply:boolean,maxRecords:number,userId:string){const live=srcs.find((x:any)=>x.system_code==="gb_ukvi_student_sponsors");let liveProviderRegister:any=null;if(live){const jobId=await startJob(service,"GB",live.source_id,{country_code:"GB",apply,max_records:maxRecords,runtime:"supabase_edge",version:VERSION,mode:"live_provider_register",requested_by:userId});try{const page=await fetchT(live.source_url||live.system_base_url,20000);const html=await page.text();const csvUrl=html.match(/https:\/\/assets\.publishing\.service\.gov\.uk[^"']+?\.csv/)?.[0];if(!csvUrl)throw new Error("UKVI CSV asset not found");const rr=await fetchT(csvUrl,60000);if(!rr.ok)throw new Error(`UKVI CSV HTTP ${rr.status}`);const text=await rr.text(),rows=parseCSV(text),head=rows[0]||[],hx=(n:string)=>head.indexOf(n);const records:any[]=[];for(const r of rows.slice(1)){if(!clean(r[hx("Sponsor Type")]).includes("Higher Education"))continue;if(clean(r[hx("Route")])!=="Student")continue;const name=clean(r[hx("Sponsor Name")]);if(name)records.push({provider_code:slug(name),provider_name:name,city:clean(r[hx("Town/City")])||null});}const stamp=new Date().toISOString().replace(/[:.]/g,"-");const ev=await evidence(service,live.source_id,jobId,csvUrl,`regulatory/GB/ukvi/${stamp}.csv`,new TextEncoder().encode(text),"text/csv",{provider_rows:records.length});const rec=await applyRecords(service,"GB",live.source_id,ev.id,"uk_sponsor",records,apply,0);liveProviderRegister={adapter:"ukvi_live",parsedRecords:records.length,reconciliation:rec,evidenceIds:[ev.id]};await health(service,live.source_id,true,null,{worker_version:VERSION,parsed_records:records.length});await finishJob(service,jobId,"completed",liveProviderRegister);}catch(e){const msg=String(e).slice(0,1500);liveProviderRegister={adapter:"ukvi_live",error:msg};await health(service,live.source_id,false,msg,{worker_version:VERSION});await finishJob(service,jobId,"failed",liveProviderRegister,msg);}}const seedSources=srcs.filter((x:any)=>x.system_code!=="gb_ukvi_student_sponsors");const seed=await runSeed(service,"GB",seedSources,apply,maxRecords,userId);return{...seed,liveProviderRegister};}

async function runDE(service:any,srcs:any[],apply:boolean,maxRecords:number,userId:string){const source=srcs.find((x:any)=>x.system_code==="de_daad_programmes")||srcs[0];if(!source)throw new Error("DE source missing");const jobId=await startJob(service,"DE",source.source_id,{country_code:"DE",apply,max_records:maxRecords,runtime:"supabase_edge",version:VERSION,mode:"live",requested_by:userId});try{const api=source.system_config?.api_url||"https://www2.daad.de/deutschland/studienangebote/international-programmes/api/solr";const u=`${api}/en/search.json?q=&sort=4&page=1`;const r=await fetchT(u,45000,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`DAAD HTTP ${r.status}`);const data=await r.json(),courses=data.courses||[];const records=courses.filter((c:any)=>c.courseName&&c.academy).map((c:any)=>({provider_code:slug(c.academy),provider_name:c.academy,city:c.city||null,course_code:String(c.id),course_name:c.courseName,course_level:mapLevel(c.courseName),field_of_study:c.subject||null}));const stamp=new Date().toISOString().replace(/[:.]/g,"-");const ev=await evidence(service,source.source_id,jobId,u,`regulatory/DE/daad/${stamp}.json`,new TextEncoder().encode(JSON.stringify({numResults:data.numResults,courses})),"application/json",{num_results:data.numResults});const rec=await applyRecords(service,"DE",source.source_id,ev.id,"daad",records,apply,maxRecords);const result={country:"DE",mode:apply?"apply":"dry-run",adapter:"daad_live",parsedRecords:records.length,availableRecords:data.numResults,selectedRecords:maxRecords>0?Math.min(maxRecords,records.length):records.length,reconciliation:rec,evidenceIds:[ev.id],workerVersion:VERSION};await health(service,source.source_id,true,null,{worker_version:VERSION,parsed_records:records.length,available_records:data.numResults});await finishJob(service,jobId,"completed",result);return{...result,jobId};}catch(e){const msg=String(e).slice(0,1800);await health(service,source.source_id,false,msg,{worker_version:VERSION});await finishJob(service,jobId,"failed",{workerVersion:VERSION},msg);throw e;}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,anon=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||serviceKey;const service=createClient(url,serviceKey,{auth:{persistSession:false}});try{const {user,token}=await authAdmin(req,service,url,anon);const body=await req.json().catch(()=>({}));const requested=String(body.country||"ALL").toUpperCase();const apply=Boolean(body.apply);const maxRecords=Math.max(0,Math.min(Number(body.maxRecords??100),30000));const countries=requested==="ALL"?["AU","GB","DE","CA","IE","NZ","US"]:[requested];const results:any[]=[],failures:any[]=[];for(const cc of countries){try{let r:any;if(cc==="AU")r=await runAU(url,anon,token,apply,maxRecords);else{const srcs=await sources(service,cc);if(cc==="GB")r=await runGB(service,srcs,apply,maxRecords,user.id);else if(cc==="DE")r=await runDE(service,srcs,apply,maxRecords,user.id);else if(["CA","IE","NZ","US"].includes(cc))r=await runSeed(service,cc,srcs,apply,maxRecords,user.id);else throw new Error(`No Layer 1 adapter for ${cc}`);}results.push(r);}catch(e){failures.push({country:cc,error:String(e).slice(0,1200)});}}let catalogueStats=null;if(apply&&results.length)catalogueStats=await rpc(service,"svc_layer1_finalize_catalogue");const depthStats=await rpc(service,"svc_layer1_depth_stats");const seedStatus=await rpc(service,"svc_layer1_seed_status");return json({ok:failures.length===0,status:failures.length?"completed_with_errors":"completed",mode:apply?"apply":"dry-run",requestedCountry:requested,maxRecords,countries:results,failures,catalogueStats:{...(catalogueStats||{}),campuses:depthStats?.campuses||0,course_campus_links:depthStats?.course_campus_links||0},depthStats,seedStatus,workerVersion:VERSION,runtime:"supabase_edge"},failures.length&&results.length===0?500:200);}catch(e){return json({error:String(e),workerVersion:VERSION},500);}});
