-- CF-118..124 consolidated repository replay for scoped Scholarship acquisition.
-- Runtime was hardened incrementally; this file captures the final production-replay contract.

create table if not exists pipeline.scholarship_scope_acquisition_requests (
 id uuid primary key default gen_random_uuid(), requested_by uuid not null, country_code text not null,
 scope_type text not null check(scope_type in('country','state','university')), scope_id uuid,
 provider_id uuid references catalogue.providers(id), provider_count integer not null default 0,
 status text not null default 'queued' check(status in('preview','queued','running','completed','partial','failed','cancelled')),
 requested_at timestamptz not null default now(), started_at timestamptz, completed_at timestamptz,
 metadata jsonb not null default '{}'::jsonb
);
alter table pipeline.scholarship_scope_acquisition_requests enable row level security;
revoke all on pipeline.scholarship_scope_acquisition_requests from public,anon,authenticated;
grant select,insert,update,delete on pipeline.scholarship_scope_acquisition_requests to service_role;
create index if not exists scholarship_scope_acquisition_requests_scope_idx on pipeline.scholarship_scope_acquisition_requests(country_code,scope_type,scope_id,requested_at desc);
create index if not exists scholarship_scope_acquisition_requests_provider_idx on pipeline.scholarship_scope_acquisition_requests(provider_id,requested_at desc);

-- Promote first-party catalogue URLs already verified in the acquisition trace into executable Layer 2 profiles.
do $$
declare r record;v_source uuid;v_profile uuid;v_version uuid;v_config jsonb;v_hash text;v_country uuid;
begin
 select id into v_country from ref.countries where upper(iso_alpha2::text)='AU' limit 1;
 for r in select distinct on(t.provider_id)t.provider_id,p.canonical_name,t.first_party_catalogue_url from pipeline.scholarship_acquisition_trace t join catalogue.providers p on p.id=t.provider_id where t.first_party_catalogue_url is not null and t.verification_status='verified_first_party' order by t.provider_id,t.updated_at desc loop
  select id into v_source from pipeline.sources where provider_id=r.provider_id and source_type='scholarship_catalogue' and url=r.first_party_catalogue_url order by trust_rank desc nulls last,created_at desc limit 1;
  if v_source is null then insert into pipeline.sources(source_type,provider_id,country_id,url,label,trust_rank,status,metadata) values('scholarship_catalogue',r.provider_id,v_country,r.first_party_catalogue_url,r.canonical_name||' Scholarships — official first-party catalogue',100,'active',jsonb_build_object('authority','first_party','change_control_ref','CF-CHG-20260904-120')) returning id into v_source;end if;
  select id into v_profile from pipeline.layer2_source_profiles where source_id=v_source and domain='scholarship' and acquisition_method='scholarship_catalogue' limit 1;
  if v_profile is null then insert into pipeline.layer2_source_profiles(source_id,profile_key,domain,acquisition_method,target_entity_type,authority_class,enabled,paused,operational_owner,freshness_sla_hours,schedule_text) values(v_source,'au-scholarship-entry-'||replace(r.provider_id::text,'-','')||'-cf120','scholarship','scholarship_catalogue','scholarship','first_party',true,false,'PIM/Data Operations',168,'weekly; accelerate around application deadlines or changed hash') returning id into v_profile;end if;
  v_config:=jsonb_build_object('retry',jsonb_build_object('backoff','exponential','max_attempts',2),'headers',jsonb_build_object('user_agent','CourseFinder deterministic Layer 2 scholarship acquisition'),'schedule','weekly; accelerate around application deadlines or changed hash','base_domain',regexp_replace(r.first_party_catalogue_url,'^(https?://[^/]+).*$','\\1'),'concurrency',1,'url_patterns',jsonb_build_array(r.first_party_catalogue_url),'discovery_url',r.first_party_catalogue_url,'robots_policy','respect','fanout_domains',jsonb_build_array('scholarship','provider_asset'),'max_payload_mb',20,'timeout_seconds',60,'evidence_required',true,'acquisition_method','scholarship_catalogue','allowed_mime_types',jsonb_build_array('text/html','application/json'),'change_control_ref','CF-CHG-20260904-120','reuse_shared_fetch',true,'target_entity_type','scholarship','freshness_sla_hours',168,'content_change_policy','hash before downstream extraction; no direct canonical mutation','rate_limit_per_minute',20,'shared_fetch_ttl_hours',24);
  v_hash:=encode(extensions.digest(convert_to(v_config::text,'UTF8'),'sha256'),'hex');
  select id into v_version from pipeline.layer2_source_profile_versions where profile_id=v_profile and configuration_hash=v_hash limit 1;
  if v_version is null then insert into pipeline.layer2_source_profile_versions(profile_id,version_no,configuration,configuration_hash,validation_status,validation_result,change_control_ref) values(v_profile,coalesce((select max(version_no)+1 from pipeline.layer2_source_profile_versions where profile_id=v_profile),1),v_config,v_hash,'valid',jsonb_build_object('valid',true,'errors',jsonb_build_array(),'validated_at',now()),'CF-CHG-20260904-120') returning id into v_version;end if;
  update pipeline.layer2_source_profiles set current_version_id=v_version,enabled=true,paused=false,updated_at=now() where id=v_profile;
  v_source:=null;v_profile:=null;v_version:=null;
 end loop;
end $$;

-- Reuse the governed route policy rather than bypassing Direct/Firecrawl/other provider controls.
insert into pipeline.layer2_profile_provider_routes(profile_id,acquisition_provider_id,priority,enabled,required_capabilities,request_overrides,evidence_policy,fallback_on,change_control_ref)
select target.id,r.acquisition_provider_id,r.priority,r.enabled,r.required_capabilities,r.request_overrides,r.evidence_policy,r.fallback_on,'CF-CHG-20260904-123'
from pipeline.layer2_source_profiles target join pipeline.layer2_source_profiles template on template.profile_key='au-provider-scholarship-9cc8ef21-52ec-4c18-849a-598ba1072459' join pipeline.layer2_profile_provider_routes r on r.profile_id=template.id and r.enabled
where target.profile_key like 'au-scholarship-entry-%-cf120' and not exists(select 1 from pipeline.layer2_profile_provider_routes x where x.profile_id=target.id and x.acquisition_provider_id=r.acquisition_provider_id)
on conflict do nothing;

create or replace function public.scholarship_scope_acquisition_service(p_actor uuid,p_action text,p_country_code text,p_scope_type text,p_scope_id uuid default null) returns jsonb language plpgsql security definer set search_path='pg_catalog','public','security','pipeline','catalogue','ref','scholarship' as $$
declare v_rank integer:=0;v_provider_count integer:=0;v_ready integer:=0;v_request uuid;v_scope_name text;v_jobs integer:=0;
begin
 if current_user not in('service_role','postgres') then raise exception 'service_role required' using errcode='42501';end if;select coalesce(max(r.rank),0) into v_rank from security.user_roles ur join security.roles r on r.code=ur.role_code where ur.user_id=p_actor and(ur.expires_at is null or ur.expires_at>now())and r.status='active';if v_rank<4 then raise exception 'pipeline_operator role required' using errcode='42501';end if;
 if lower(coalesce(p_action,'')) not in('preview','start') or lower(coalesce(p_scope_type,'')) not in('country','state','university') then raise exception 'invalid action or scope' using errcode='22023';end if;if lower(p_scope_type) in('state','university') and p_scope_id is null then raise exception 'scope id required' using errcode='22023';end if;
 with scoped as(select distinct p.id from catalogue.providers p join ref.countries c on c.id=p.country_id where upper(c.iso_alpha2::text)=upper(p_country_code) and(lower(p_scope_type)='country' or(lower(p_scope_type)='state' and(p.subdivision_id=p_scope_id or exists(select 1 from catalogue.campuses ca where ca.provider_id=p.id and ca.subdivision_id=p_scope_id)))or(lower(p_scope_type)='university' and p.id=p_scope_id))) select count(*) into v_provider_count from scoped;
 with scoped as(select distinct p.id from catalogue.providers p join ref.countries c on c.id=p.country_id where upper(c.iso_alpha2::text)=upper(p_country_code) and(lower(p_scope_type)='country' or(lower(p_scope_type)='state' and(p.subdivision_id=p_scope_id or exists(select 1 from catalogue.campuses ca where ca.provider_id=p.id and ca.subdivision_id=p_scope_id)))or(lower(p_scope_type)='university' and p.id=p_scope_id))) select count(*) into v_ready from scoped s where exists(select 1 from pipeline.layer2_source_profiles sp join pipeline.sources src on src.id=sp.source_id where src.provider_id=s.id and src.status='active' and src.source_type='scholarship_catalogue' and sp.domain='scholarship' and sp.acquisition_method='scholarship_catalogue' and sp.enabled and not sp.paused and sp.current_version_id is not null and exists(select 1 from pipeline.layer2_profile_provider_routes r where r.profile_id=sp.id and r.enabled));
 if lower(p_scope_type)='state' then select name into v_scope_name from ref.subdivisions where id=p_scope_id;elsif lower(p_scope_type)='university' then select canonical_name into v_scope_name from catalogue.providers where id=p_scope_id;else v_scope_name:=upper(p_country_code);end if;
 if lower(p_action)='preview' then return jsonb_build_object('ok',true,'domain','scholarship','scope_name',v_scope_name,'scope_type',lower(p_scope_type),'provider_count',v_provider_count,'executable_provider_count',v_ready,'jobs_if_started',v_ready,'catalogue_or_route_gap',greatest(v_provider_count-v_ready,0),'publication_changed',false);end if;
 insert into pipeline.scholarship_scope_acquisition_requests(requested_by,country_code,scope_type,scope_id,provider_id,provider_count,status,metadata) values(p_actor,upper(p_country_code),lower(p_scope_type),p_scope_id,case when lower(p_scope_type)='university' then p_scope_id end,v_ready,'queued',jsonb_build_object('scope_name',v_scope_name,'scope_provider_count',v_provider_count,'executable_provider_count',v_ready,'catalogue_or_route_gap',greatest(v_provider_count-v_ready,0),'change_control_ref','CF-CHG-20260904-124')) returning id into v_request;
 with scoped as(select distinct p.id,p.canonical_name from catalogue.providers p join ref.countries c on c.id=p.country_id where upper(c.iso_alpha2::text)=upper(p_country_code) and(lower(p_scope_type)='country' or(lower(p_scope_type)='state' and(p.subdivision_id=p_scope_id or exists(select 1 from catalogue.campuses ca where ca.provider_id=p.id and ca.subdivision_id=p_scope_id)))or(lower(p_scope_type)='university' and p.id=p_scope_id))),ready as(select s.* from scoped s where exists(select 1 from pipeline.layer2_source_profiles sp join pipeline.sources src on src.id=sp.source_id where src.provider_id=s.id and src.status='active' and src.source_type='scholarship_catalogue' and sp.domain='scholarship' and sp.acquisition_method='scholarship_catalogue' and sp.enabled and not sp.paused and sp.current_version_id is not null and exists(select 1 from pipeline.layer2_profile_provider_routes r where r.profile_id=sp.id and r.enabled))),ins as(insert into pipeline.jobs(job_type,domain,provider_id,status,requested_by,payload) select 'scholarship_scope_acquisition','scholarship',s.id,'queued',p_actor,jsonb_build_object('request_id',v_request,'country_code',upper(p_country_code),'scope_type',lower(p_scope_type),'scope_id',p_scope_id,'scope_name',v_scope_name,'provider_name',s.canonical_name,'publication_authorised',false,'change_control_ref','CF-CHG-20260904-124') from ready s returning 1)select count(*) into v_jobs from ins;
 return jsonb_build_object('ok',true,'domain','scholarship','status',case when v_jobs>0 then 'queued' else 'no_executable_provider' end,'request_id',v_request,'scope_name',v_scope_name,'scope_provider_count',v_provider_count,'jobs_queued',v_jobs,'executable_provider_count',v_ready,'catalogue_or_route_gap',greatest(v_provider_count-v_ready,0),'publication_changed',false);
end $$;
revoke all on function public.scholarship_scope_acquisition_service(uuid,text,text,text,uuid) from public,anon,authenticated;grant execute on function public.scholarship_scope_acquisition_service(uuid,text,text,text,uuid) to service_role;

create or replace function public.scholarship_scope_job_execution_context(p_job_id uuid) returns jsonb language plpgsql security definer set search_path='pg_catalog','public','pipeline','catalogue' as $$
declare j record;p record;begin if current_user not in('service_role','postgres')then raise exception 'service_role required' using errcode='42501';end if;select * into j from pipeline.jobs where id=p_job_id and job_type='scholarship_scope_acquisition' and domain='scholarship';if not found then return null;end if;select sp.id profile_id,sp.current_version_id,sp.profile_key,sp.source_id,s.url target_url into p from pipeline.layer2_source_profiles sp join pipeline.sources s on s.id=sp.source_id where s.provider_id=j.provider_id and s.status='active' and sp.domain='scholarship' and sp.acquisition_method='scholarship_catalogue' and sp.enabled and not sp.paused and sp.current_version_id is not null order by case when sp.profile_key like 'au-scholarship-entry-%' then 0 else 1 end,s.trust_rank desc nulls last limit 1;return jsonb_build_object('job_id',j.id,'provider_id',j.provider_id,'payload',coalesce(j.payload,'{}'::jsonb),'profile_id',p.profile_id,'profile_version_id',p.current_version_id,'profile_key',p.profile_key,'source_id',p.source_id,'target_url',p.target_url);end $$;
revoke all on function public.scholarship_scope_job_execution_context(uuid) from public,anon,authenticated;grant execute on function public.scholarship_scope_job_execution_context(uuid) to service_role;

create or replace function public.scholarship_scope_job_mark(p_job_id uuid,p_status text,p_result jsonb default null,p_error text default null,p_execution jsonb default null) returns jsonb language plpgsql security definer set search_path='pg_catalog','public','pipeline' as $$ begin if current_user not in('service_role','postgres')then raise exception 'service_role required' using errcode='42501';end if;update pipeline.jobs set status=p_status,started_at=case when p_status='running' then coalesce(started_at,now()) else started_at end,completed_at=case when p_status in('succeeded','failed') then now() else null end,result=coalesce(p_result,result),error_text=p_error,source_id=coalesce(nullif(p_execution->>'source_id','')::uuid,source_id),source_profile_version_id=coalesce(nullif(p_execution->>'profile_version_id','')::uuid,source_profile_version_id),payload=coalesce(payload,'{}'::jsonb)||coalesce(p_execution,'{}'::jsonb) where id=p_job_id and job_type='scholarship_scope_acquisition' and domain='scholarship';if not found then raise exception 'scope job not found' using errcode='P0002';end if;return jsonb_build_object('ok',true,'job_id',p_job_id,'status',p_status);end $$;
revoke all on function public.scholarship_scope_job_mark(uuid,text,jsonb,text,jsonb) from public,anon,authenticated;grant execute on function public.scholarship_scope_job_mark(uuid,text,jsonb,text,jsonb) to service_role;

-- Scheduler calls scholarship-scope-job-execute, which uses layer2-acquire-v2 and the existing provider-page fanout.
-- Runtime allowlist and scheduler implementation were applied under CF-121; keep this migration paired with the checked-in Edge function.
