-- Mirrors final live state after m2_1_course_decision_context_projection,
-- m2_1_course_decision_context_current_status_fix and m2_1_course_decision_context_state_limit.
create or replace function security.admin_course_decision_context(p_course_id uuid)
returns jsonb language sql stable security invoker set search_path=security,catalogue,ref,public as $$
with course_base as (select c.id course_id,c.provider_id,c.primary_field_id,c.study_level_id from catalogue.courses c where c.id=p_course_id),
campus_states as (select distinct ca.subdivision_id from course_base b join catalogue.course_campuses cc on cc.course_id=b.course_id join catalogue.campuses ca on ca.id=cc.campus_id where ca.subdivision_id is not null),
qilt as (select jsonb_agg(jsonb_build_object('context_type',case when po.external_study_area_id is null then 'qilt_provider' else 'qilt_provider_study_area' end,'grain',case when po.external_study_area_id is null then 'provider' else 'provider_study_area' end,'provider_id',po.provider_id,'external_study_area_id',po.external_study_area_id,'study_level_id',po.study_level_id,'audience',po.audience,'collection_year_from',po.collection_year_from,'collection_year_to',po.collection_year_to,'metric_id',po.metric_id,'metric_value',po.metric_value,'response_count',po.response_count,'national_benchmark',po.national_benchmark,'source_id',po.source_id,'evidence_id',po.evidence_id,'observed_at',po.observed_at,'course_grain',false) order by po.collection_year_to desc nulls last,po.observed_at desc) filter(where po.id is not null) data from course_base b left join lateral (select po.* from catalogue.provider_outcomes po where po.provider_id=b.provider_id and coalesce(po.status,'current') in ('active','current') order by po.collection_year_to desc nulls last,po.observed_at desc limit 30) po on true),
prisms_provider as (select jsonb_agg(jsonb_build_object('context_type','prisms_provider','grain','provider','provider_id',sf.provider_id,'subdivision_id',sf.subdivision_id,'external_study_area_id',sf.external_study_area_id,'field_of_study_id',sf.field_of_study_id,'study_level_id',sf.study_level_id,'audience',sf.audience,'period_start',sf.period_start,'period_end',sf.period_end,'period_type',sf.period_type,'metric_id',sf.metric_id,'metric_value',sf.metric_value,'is_suppressed',sf.is_suppressed,'suppression_code',sf.suppression_code,'source_id',sf.source_id,'evidence_id',sf.evidence_id,'observed_at',sf.observed_at,'course_grain',false) order by sf.period_end desc nulls last,sf.observed_at desc) filter(where sf.id is not null) data from course_base b left join lateral (select sf.* from catalogue.student_flow_observations sf where sf.provider_id=b.provider_id and coalesce(sf.status,'current') in ('active','current') order by sf.period_end desc nulls last,sf.observed_at desc limit 30) sf on true),
prisms_state as (select jsonb_agg(jsonb_build_object('context_type','prisms_state','grain','state_or_subdivision','subdivision_id',sf.subdivision_id,'source_geography_type',sf.source_geography_type,'source_geography_key',sf.source_geography_key,'source_geography_name',sf.source_geography_name,'external_study_area_id',sf.external_study_area_id,'field_of_study_id',sf.field_of_study_id,'study_level_id',sf.study_level_id,'audience',sf.audience,'period_start',sf.period_start,'period_end',sf.period_end,'metric_id',sf.metric_id,'metric_value',sf.metric_value,'is_suppressed',sf.is_suppressed,'suppression_code',sf.suppression_code,'source_id',sf.source_id,'evidence_id',sf.evidence_id,'observed_at',sf.observed_at,'course_grain',false) order by sf.period_end desc nulls last,sf.observed_at desc) data from (select sf.* from catalogue.student_flow_observations sf where sf.subdivision_id in (select subdivision_id from campus_states) and coalesce(sf.status,'current') in ('active','current') order by sf.period_end desc nulls last,sf.observed_at desc limit 30) sf)
select jsonb_build_object('course_id',b.course_id,'provider_id',b.provider_id,'context_semantics','decision_context_not_course_fact','qilt',coalesce(q.data,'[]'::jsonb),'prisms_provider',coalesce(pp.data,'[]'::jsonb),'prisms_state',coalesce(ps.data,'[]'::jsonb)) from course_base b cross join qilt q cross join prisms_provider pp cross join prisms_state ps;
$$;
revoke all on function security.admin_course_decision_context(uuid) from public,anon; grant execute on function security.admin_course_decision_context(uuid) to authenticated,service_role;
create or replace function public.course_decision_context(p_course_id uuid) returns jsonb language plpgsql stable security invoker set search_path=public,security as $$ declare v_ctx jsonb; begin if auth.uid() is null and auth.role()<>'service_role' then raise exception 'authentication required'; end if; select security.admin_course_decision_context(p_course_id) into v_ctx; return coalesce(v_ctx,jsonb_build_object('course_id',p_course_id,'qilt','[]'::jsonb,'prisms_provider','[]'::jsonb,'prisms_state','[]'::jsonb)); end $$;
revoke all on function public.course_decision_context(uuid) from public,anon; grant execute on function public.course_decision_context(uuid) to authenticated,service_role;
