-- CF-247 Phase 2 (8 Oct 2026, Platform Admin: "Build 21, add raw capture to 11"): Alberta ALIS and EducationPlannerBC become register
-- adapters (format text_items), switched off. Their stored evidence is a bundle that keeps the raw pages: ALIS keeps each programme detail
-- page (details[].html, read again for title, programme type, credential type, update date and study level), EPBC keeps each programme
-- list page (raw_pages[].html, whose __NEXT_DATA__ JSON gives each programme's GUID, title, credentials and active flag). References are
-- verbatim copies of the Layer 1 readers (parseDetail; the EPBC page reading, level and lifecycle). Replay on the newest stored bundle of
-- each school (ALIS) and institution (EPBC), with coverage-sweep v0.17.29; the driver is started after the worker deploy.
insert into pipeline.register_adapters(source_id, code, label, country_code, spec, notes)
values ('2455ffdf-66ae-4b82-943c-b7293d996668', 'ca_alis', 'Alberta ALIS post-secondary programme catalogue', 'CA', '{"items": {"json": "details"}, "fields": {"local_program_id": {"json": "guid"}, "html": {"json": "html"}, "text": {"from": "html", "tx": [["replace", "<script[\\s\\S]*?<\\/script>", " ", "gi"], ["replace", "<style[\\s\\S]*?<\\/style>", " ", "gi"], ["replace", "<[^>]+>", " ", "g"], "num_entities", ["replace", "&nbsp;", " ", "gi"], ["replace", "&amp;", "&", "gi"], ["replace", "&quot;", "\"", "gi"], ["replace", "&apos;", "''", "gi"], ["replace", "&lt;", "<", "gi"], ["replace", "&gt;", ">", "gi"], "collapse_ws", "trim"]}, "h1": {"from": "html", "regex": "<h1[^>]*>([\\s\\S]*?)<\\/h1>", "flags": "i"}, "course_title": {"from": "h1", "tx": [["replace", "<script[\\s\\S]*?<\\/script>", " ", "gi"], ["replace", "<style[\\s\\S]*?<\\/style>", " ", "gi"], ["replace", "<[^>]+>", " ", "g"], "num_entities", ["replace", "&nbsp;", " ", "gi"], ["replace", "&amp;", "&", "gi"], ["replace", "&quot;", "\"", "gi"], ["replace", "&apos;", "''", "gi"], ["replace", "&lt;", "<", "gi"], ["replace", "&gt;", ">", "gi"], "collapse_ws", "trim"]}, "program_type": {"from": "text", "regex": "Program Type\\s+(.+?)\\s+Credential Type\\s+", "flags": "i", "tx": ["collapse_ws", "trim"]}, "credential_type": {"from": "text", "regex": "Credential Type\\s+(.+?)\\s+Length\\s+", "flags": "i", "tx": ["collapse_ws", "trim"]}, "updated": {"from": "text", "regex": "Updated\\s+([A-Za-z]+\\s+\\d{1,2},\\s+\\d{4})\\.", "flags": "i", "tx": ["collapse_ws", "trim"]}, "study_level_code": {"from": "program_type", "tx": ["lower"], "map": [["^bachelor''s$", "bachelor"], ["^master''s$", "masters"], ["^doctoral$", "doctorate"]], "else": "", "null_if_empty": true}, "issuing_authority": {"const": "Government of Alberta ALIS"}, "lifecycle_status": {"const": "active"}, "metadata": {"object": [["scope", {"const": "ca-intl-bachelor-plus-v1"}], ["program_type", {"field": "program_type"}], ["credential_type", {"field": "credential_type"}], ["profile_updated", {"field": "updated"}], ["international_gate", {"const": "current public Alberta/IRCC DLI designation"}], ["current_catalogue_membership", {"const": true}]]}}, "require": ["local_program_id", "study_level_code"], "skip": [{"field": "credential_type", "regex": "^degree$", "flags": "i", "not": true}], "key": "local_program_id", "dedupe": "last", "out": ["local_program_id", "course_title", "issuing_authority", "lifecycle_status", "study_level_code", "metadata"], "format": "text_items"}'::jsonb,
        'Phase 2 register adapter (Canada, text_items, detail-page bundle). Not switched on: the Layer 1 reader stays in charge until the replay passes and a Platform Admin switches it.'),
       ('e2169f33-8b81-4895-8dc1-8d5a0b08d8a5', 'ca_epbc', 'EducationPlannerBC public post-secondary programme catalogue', 'CA', '{"items": {"bundle": {"pages": "raw_pages", "body": "html", "embedded_json": {"regex": "<script id=\"__NEXT_DATA__\" type=\"application\\/json\">([\\s\\S]*?)<\\/script>", "path": "props.pageProps.searchResults.results"}}}, "fields": {"local_program_id": {"json": "guid", "tx": ["lower"]}, "course_title": {"json": "title", "tx": ["collapse_ws", "trim"]}, "cred_join": {"json_list": {"path": "credentials", "key": "type"}, "join": "|"}, "cred_types": {"json_list": {"path": "credentials", "key": "type"}, "tx": ["collapse_ws", "trim"]}, "cred_desc": {"json_list": {"path": "credentials", "key": "description"}, "tx": ["collapse_ws", "trim"]}, "study_level_code": {"from": "cred_join", "map": [["(^|\\|)DoctoralDegree(\\||$)", "doctorate"], ["(^|\\|)FirstProfessionalDeg(\\||$)", "professional_degree"], ["(^|\\|)MastersDegree(\\||$)", "masters"], ["(^|\\|)BachelorsDegree(\\||$)", "bachelor"]], "else": "", "null_if_empty": true}, "lifecycle": {"json_find": {"path": "properties", "match": "Type.Code", "equals": "IS_ACTIVE", "value": "Value"}, "tx": ["lower"], "map": [["^no$", "inactive"]], "else": "active"}, "issuing_authority": {"const": "EducationPlannerBC"}, "lifecycle_status": {"const": "active"}, "metadata": {"object": [["scope", {"const": "ca-intl-bachelor-plus-v1"}], ["credential_types", {"field": "cred_types"}], ["credential_descriptions", {"field": "cred_desc"}], ["international_gate", {"const": "current_ircc_dli"}]]}}, "require": ["local_program_id", "course_title", "study_level_code"], "skip": [{"field": "lifecycle", "regex": "^active$", "not": true}], "key": "local_program_id", "dedupe": "throw_dup", "out": ["local_program_id", "course_title", "issuing_authority", "lifecycle_status", "study_level_code", "metadata"], "format": "text_items"}'::jsonb,
        'Phase 2 register adapter (Canada, text_items, programme-page bundle). Not switched on: the Layer 1 reader stays in charge until the replay passes and a Platform Admin switches it.')
on conflict (source_id) do nothing;

insert into pipeline.register_replay_runs(source_id, label, storage_path, zip_hash, keep_fields, created_at)
select e.source_id, a.code || ' ' || split_part(e.storage_path, '/', 5) || ' ' || to_char(e.created_at at time zone 'Australia/Melbourne', 'DD Mon HH24:MI'),
       e.storage_path, e.content_hash, false, now() + make_interval(secs => (row_number() over (order by a.code, e.storage_path))::int)
  from (select distinct on (source_id, split_part(storage_path, '/', 5)) * from pipeline.evidence_artifacts
         where (source_id = '2455ffdf-66ae-4b82-943c-b7293d996668' and storage_path ~ '/details-[^/]*\.json$')
            or (source_id = 'e2169f33-8b81-4895-8dc1-8d5a0b08d8a5' and storage_path ~ '/pages-[^/]*\.json$')
         order by source_id, split_part(storage_path, '/', 5), created_at desc) e
  join pipeline.register_adapters a on a.source_id = e.source_id;
select cron.schedule('register-replay', '* * * * *', 'select security.register_replay_tick_v1()');
