-- CF-125: Admin scoped Scholarship Start dispatches executable jobs immediately.
-- Preview remains cost-free; non-executable Providers remain qualification gaps.

create or replace function public.scholarship_scope_acquisition_service(p_actor uuid,p_action text,p_country_code text,p_scope_type text,p_scope_id uuid default null)
returns jsonb language plpgsql security definer
set search_path='pg_catalog','public','security','pipeline','catalogue','ref','scholarship'
as $$
declare v_rank integer:=0;v_provider_count integer:=0;v_ready integer:=0;v_request uuid;v_scope_name text;v_jobs integer:=0;v_dispatch jsonb;
begin
 if current_user not in('service_role','postgres') then raise exception 'service_role required' using errcode='42501';end if;
 select coalesce(max(r.rank),0) into v_rank from security.user_roles ur join security.roles r on r.code=ur.role_code where ur.user_id=p_actor and(ur.expires_at is null or ur.expires_at>now())and r.status='active';if v_rank<4 then raise exception 'pipeline_operator role required' using errcode='42501';end if;
 if lower(coalesce(p_action,'')) not in('preview','start') then raise exception 'unsupported action' using errcode='22023';end if;if lower(coalesce(p_scope_type,'')) not in('country','state','university') then raise exception 'invalid scope type' using errcode='22023';end if;if lower(p_scope_type) in('state','university') and p_scope_id is null then raise exception 'scope id required' using errcode='22023';end if;
 with scoped as(select distinct p.id from catalogue.providers p join ref.countries c on c.id=p.country_id where upper(c.iso_alpha2::text)=upper(p_country_code) and(lower(p_scope_type)='country' or(lower(p_scope_type)='state' and(p.subdivision_id=p_scope_id or exists(select 1 from catalogue.campuses ca where ca.provider_id=p.id and ca.subdivision_id=p_scope_id)))or(lower(p_scope_type)='university' and p.id=p_scope_id))) select count(*) into v_provider_count from scoped;
 with scoped as(select distinct p.id from catalogue.providers p join ref.countries c on c.id=p.country_id where upper(c.iso_alpha2::text)=upper(p_country_code) and(lower(p_scope_type)='country' or(lower(p_scope_type)='state' and(p.subdivision_id=p_scope_id or exists(select 1 from catalogue.campuses ca where ca.provider_id=p.id and ca.subdivision_id=p_scope_id)))or(lower(p_scope_type)='university' and p.id=p_scope_id))) select count(*) into v_ready from scoped s where exists(select 1 from pipeline.layer2_source_profiles sp join pipeline.sources src on src.id=sp.source_id where src.provider_id=s.id and src.status='active' and src.source_type='scholarship_catalogue' and sp.domain='scholarship' and sp.acquisition_method='scholarship_catalogue' and sp.enabled and not sp.paused and sp.current_version_id is not null and exists(select 1 from pipeline.layer2_profile_provider_routes r where r.profile_id=sp.id and r.enabled));
 if lower(p_scope_type)='state' then select name into v_scope_name from ref.subdivisions where id=p_scope_id;elsif lower(p_scope_type)='university' then select canonical_name into v_scope_name from catalogue.providers where id=p_scope_id;else v_scope_name:=upper(p_country_code);end if;
 if lower(p_action)='preview' then return jsonb_build_object('ok',true,'domain','scholarship','action','preview','country_code',upper(p_country_code),'scope_type',lower(p_scope_type),'scope_id',p_scope_id,'scope_name',v_scope_name,'provider_count',v_provider_count,'executable_provider_count',v_ready,'jobs_if_started',v_ready,'catalogue_or_route_gap',greatest(v_provider_count-v_ready,0),'publication_changed',false);end if;
 insert into pipeline.scholarship_scope_acquisition_requests(requested_by,country_code,scope_type,scope_id,provider_id,provider_count,status,metadata) values(p_actor,upper(p_country_code),lower(p_scope_type),p_scope_id,case when lower(p_scope_type)='university' then p_scope_id else null end,v_ready,'queued',jsonb_build_object('scope_name',v_scope_name,'scope_provider_count',v_provider_count,'executable_provider_count',v_ready,'catalogue_or_route_gap',greatest(v_provider_count-v_ready,0),'change_control_ref','CF-CHG-20260904-125')) returning id into v_request;
 with scoped as(select distinct p.id,p.canonical_name from catalogue.providers p join ref.countries c on c.id=p.country_id where upper(c.iso_alpha2::text)=upper(p_country_code) and(lower(p_scope_type)='country' or(lower(p_scope_type)='state' and(p.subdivision_id=p_scope_id or exists(select 1 from catalogue.campuses ca where ca.provider_id=p.id and ca.subdivision_id=p_scope_id)))or(lower(p_scope_type)='university' and p.id=p_scope_id))),ready as(select s.* from scoped s where exists(select 1 from pipeline.layer2_source_profiles sp join pipeline.sources src on src.id=sp.source_id where src.provider_id=s.id and src.status='active' and src.source_type='scholarship_catalogue' and sp.domain='scholarship' and sp.acquisition_method='scholarship_catalogue' and sp.enabled and not sp.paused and sp.current_version_id is not null and exists(select 1 from pipeline.layer2_profile_provider_routes r where r.profile_id=sp.id and r.enabled))),ins as(insert into pipeline.jobs(job_type,domain,provider_id,status,requested_by,payload) select 'scholarship_scope_acquisition','scholarship',s.id,'queued',p_actor,jsonb_build_object('request_id',v_request,'country_code',upper(p_country_code),'scope_type',lower(p_scope_type),'scope_id',p_scope_id,'scope_name',v_scope_name,'provider_name',s.canonical_name,'acquisition_stage','first_party_catalogue_then_detail','publication_authorised',false,'change_control_ref','CF-CHG-20260904-125') from ready s returning 1)select count(*) into v_jobs from ins;
 if v_jobs>0 then v_dispatch:=security.scholarship_scope_scheduler_tick_impl(now(),least(v_jobs,20),true);update pipeline.scholarship_scope_acquisition_requests set status='running',started_at=now(),metadata=metadata||jsonb_build_object('dispatch',v_dispatch) where id=v_request;else v_dispatch:=jsonb_build_object('ok',true,'dispatched',0);update pipeline.scholarship_scope_acquisition_requests set status='completed',completed_at=now() where id=v_request;end if;
 return jsonb_build_object('ok',true,'domain','scholarship','action','start','status',case when v_jobs>0 then 'dispatched' else 'no_executable_provider' end,'request_id',v_request,'scope_name',v_scope_name,'scope_provider_count',v_provider_count,'jobs_queued',v_jobs,'executable_provider_count',v_ready,'catalogue_or_route_gap',greatest(v_provider_count-v_ready,0),'dispatch',v_dispatch,'publication_changed',false);
end $$;
revoke all on function public.scholarship_scope_acquisition_service(uuid,text,text,text,uuid) from public,anon,authenticated;grant execute on function public.scholarship_scope_acquisition_service(uuid,text,text,text,uuid) to service_role;
revoke all on function security.scholarship_scope_scheduler_tick_impl(timestamptz,integer,boolean) from public,anon,authenticated;grant execute on function security.scholarship_scope_scheduler_tick_impl(timestamptz,integer,boolean) to service_role;