create or replace function security.admin_layer1_operations_read(p_args jsonb default '{}'::jsonb)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog,security,pipeline,ref,auth as $$
declare v_rank integer; v_country text:=upper(nullif(p_args->>'country_code','')); v_result jsonb;
begin
 if auth.uid() is null then raise exception 'authentication required' using errcode='42501'; end if;
 select security.current_role_rank() into v_rank;
 if coalesce(v_rank,0)<4 then raise exception 'pipeline_operator role required' using errcode='42501'; end if;
 with src as (
  select s.id source_id,co.iso_alpha2::text country_code,co.name country_name,s.label source_label,s.source_type,s.url source_url,s.status source_status,s.trust_rank,s.last_checked_at,s.last_success_at,s.last_failure_at,s.last_error,
   o.authority_name,o.authority_domains,o.expected_format,o.expected_count_kind,o.active,o.paused,o.verification_cadence_days,o.ingestion_cadence_days,o.variance_warn_percent,o.variance_block_percent,o.min_expected_records,o.max_expected_records,o.previous_accepted_count,o.last_expected_count,o.previous_accepted_hash,o.last_source_hash,o.last_verified_at,o.verification_status,o.verification_message,o.variance_percent,o.variance_decision,o.next_verification_at,o.next_ingestion_at,o.last_schedule_status,o.last_schedule_error,o.consecutive_failures,o.updated_at,
   coalesce((select max(v.version_no) from pipeline.layer1_source_operation_versions v where v.source_id=s.id),0) source_config_version,
   case when o.last_verified_at is null then 'never_verified' when o.paused then 'paused' when o.verification_status in ('blocked','failed') then 'unhealthy' when exists(select 1 from pipeline.layer1_run_queue q where q.source_id=s.id and q.status='running' and coalesce(q.heartbeat_at,q.started_at,q.requested_at)<now()-interval '30 minutes') then 'stuck' when o.next_verification_at is not null and o.next_verification_at<now() then 'stale' else 'healthy' end source_health,
   case when o.paused then 'Source processing is paused.' when exists(select 1 from pipeline.layer1_run_queue q where q.source_id=s.id and q.status='running' and coalesce(q.heartbeat_at,q.started_at,q.requested_at)<now()-interval '30 minutes') then 'Running job heartbeat is stale; Platform Admin may recover it after confirming the prior worker is no longer active.' when o.verification_status='blocked' then 'Resolve source authority/count blocker before run.' when o.verification_status='failed' then 'Revalidate source before run.' when o.last_verified_at is null then 'Validate source before run.' when o.next_verification_at is not null and o.next_verification_at<now() then 'Source verification is stale; recheck before run.' when o.variance_decision='warn' then 'Review variance warning; explicit acknowledgement required for APPLY.' else 'Source is eligible for governed queueing.' end next_action,
   (select jsonb_build_object('id',q.id,'mode',q.mode,'status',q.status,'requested_at',q.requested_at,'started_at',q.started_at,'completed_at',q.completed_at,'current_stage',q.current_stage,'heartbeat_at',q.heartbeat_at,'stuck',q.status='running' and coalesce(q.heartbeat_at,q.started_at,q.requested_at)<now()-interval '30 minutes','expected_count',q.expected_count,'processed_count',q.processed_count,'progress_percent',case when q.expected_count is null or q.expected_count=0 then null else round(least(100,(q.processed_count::numeric/q.expected_count::numeric)*100),1) end,'queue_position',case when q.status='queued' then 1 else null end,'runtime_seconds',case when q.started_at is null then null else greatest(0,round(extract(epoch from (coalesce(q.completed_at,now())-q.started_at))::numeric,1)) end,'created_count',q.created_count,'updated_count',q.updated_count,'unchanged_count',q.unchanged_count,'rejected_count',q.rejected_count,'conflicted_count',q.conflicted_count,'failed_count',q.failed_count,'resume_cursor',q.resume_cursor,'actual_job_id',q.actual_job_id,'retry_of_run_id',q.retry_of_run_id,'error_text',q.error_text,'result',q.result) from pipeline.layer1_run_queue q where q.source_id=s.id order by q.requested_at desc limit 1) latest_run,
   (select count(*)::bigint from pipeline.layer1_run_queue q where q.source_id=s.id and q.status='queued') queue_depth,
   (select count(*)::bigint from pipeline.evidence_artifacts e where e.source_id=s.id) evidence_count,
   (select max(e.captured_at) from pipeline.evidence_artifacts e where e.source_id=s.id) latest_evidence_at,
   (select max(j.completed_at) from pipeline.jobs j where j.source_id=s.id and j.status='completed') latest_job_success_at,
   (select count(*)::bigint from pipeline.jobs j where j.source_id=s.id and j.status='running' and j.started_at<now()-interval '30 minutes') stale_running_jobs,
   p.enabled schedule_enabled,p.cadence_interval,p.next_due_at schedule_next_due_at,p.freshness_class schedule_freshness_class,p.hash_sensitive schedule_hash_sensitive,p.updated_at schedule_policy_updated_at
  from pipeline.layer1_source_operations o join pipeline.sources s on s.id=o.source_id left join ref.countries co on co.id=s.country_id left join pipeline.refresh_policies p on p.layer=1 and p.source_id=s.id where v_country is null or co.iso_alpha2=v_country
 )
 select jsonb_build_object('sources',coalesce(jsonb_agg(to_jsonb(src) order by country_code,source_label),'[]'::jsonb),'retention',jsonb_build_object('transient_run_queue_days',30,'governed_evidence_deleted_by_housekeeping',false,'source_versions_deleted_by_housekeeping',false),'stuck_threshold_minutes',30,'alerts',jsonb_build_object('stale_source','next verification overdue','abnormal_variance','configured warn/block thresholds','failed_validation','verification_status failed/blocked','stuck_job','queue heartbeat older than 30 minutes','repeated_failure','consecutive_failures > 1','schedule_failure','source operation schedule error','storage_growth','Evidence count and storage capacity remain governed by Evidence operations'),'authority_model','Layer 1 regulatory/authoritative; downstream layers cannot redefine identity.') into v_result from src;
 return v_result;
end $$;
revoke all on function security.admin_layer1_operations_read(jsonb) from public,anon; grant execute on function security.admin_layer1_operations_read(jsonb) to authenticated,service_role;

create or replace function security.admin_layer1_command(p_operation text,p_args jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,security,pipeline,ref,auth as $$
declare v_rank integer; v_source uuid; v_reason text; v_id uuid; v_country text; v_mode text; v_version integer; v_warning boolean; v_url text; v_profile jsonb; v_domains text[];
begin
 if auth.uid() is null then raise exception 'authentication required' using errcode='42501'; end if; select security.current_role_rank() into v_rank; if coalesce(v_rank,0)<6 then raise exception 'platform_admin role required' using errcode='42501'; end if; v_source:=nullif(p_args->>'source_id','')::uuid; if v_source is null then raise exception 'source_id required' using errcode='22023'; end if; v_reason:=trim(coalesce(p_args->>'reason','')); if length(v_reason)<5 then raise exception 'governance reason required' using errcode='22023'; end if;
 if p_operation='save_source' then
  select url into v_url from pipeline.sources where id=v_source; if not found then raise exception 'source not found' using errcode='22023'; end if; v_url:=coalesce(nullif(trim(p_args->>'source_url',''),''),v_url); if v_url !~* '^https://[^[:space:]]+$' then raise exception 'https source_url required' using errcode='22023'; end if; select array_agg(lower(trim(x))) into v_domains from jsonb_array_elements_text(coalesce(p_args->'authority_domains','[]'::jsonb)) x where trim(x)<>''; if coalesce(cardinality(v_domains),0)=0 then raise exception 'at least one authority domain required' using errcode='22023'; end if; if length(trim(coalesce(p_args->>'authority_name','')))<3 then raise exception 'authority_name required' using errcode='22023'; end if; if length(trim(coalesce(p_args->>'expected_format','')))<2 then raise exception 'expected_format required' using errcode='22023'; end if;
  update pipeline.sources set url=v_url,updated_at=now() where id=v_source;
  insert into pipeline.layer1_source_operations(source_id,authority_name,authority_domains,expected_format,expected_count_kind,active,paused,verification_cadence_days,ingestion_cadence_days,variance_warn_percent,variance_block_percent,min_expected_records,max_expected_records,verification_status,variance_decision,last_verified_at,verification_message,next_verification_at,change_reason,updated_by,updated_at)
  values(v_source,trim(p_args->>'authority_name'),v_domains,trim(p_args->>'expected_format'),coalesce(nullif(trim(p_args->>'expected_count_kind'),''),'records'),coalesce((p_args->>'active')::boolean,true),coalesce((p_args->>'paused')::boolean,false),coalesce(nullif(p_args->>'verification_cadence_days','')::integer,1),nullif(p_args->>'ingestion_cadence_days','')::integer,coalesce(nullif(p_args->>'variance_warn_percent','')::numeric,5),coalesce(nullif(p_args->>'variance_block_percent','')::numeric,20),nullif(p_args->>'min_expected_records','')::bigint,nullif(p_args->>'max_expected_records','')::bigint,'unverified','unknown',null,'Source configuration changed; source must be revalidated before execution.',now(),v_reason,auth.uid(),now())
  on conflict(source_id) do update set authority_name=excluded.authority_name,authority_domains=excluded.authority_domains,expected_format=excluded.expected_format,expected_count_kind=excluded.expected_count_kind,active=excluded.active,paused=excluded.paused,verification_cadence_days=excluded.verification_cadence_days,ingestion_cadence_days=excluded.ingestion_cadence_days,variance_warn_percent=excluded.variance_warn_percent,variance_block_percent=excluded.variance_block_percent,min_expected_records=excluded.min_expected_records,max_expected_records=excluded.max_expected_records,verification_status='unverified',variance_decision='unknown',last_verified_at=null,verification_message='Source configuration changed; source must be revalidated before execution.',next_verification_at=now(),change_reason=excluded.change_reason,updated_by=auth.uid(),updated_at=now();
  select coalesce(max(version_no),0)+1 into v_version from pipeline.layer1_source_operation_versions where source_id=v_source; select to_jsonb(o)-'updated_by' into v_profile from pipeline.layer1_source_operations o where o.source_id=v_source; insert into pipeline.layer1_source_operation_versions(source_id,version_no,snapshot,changed_by,change_reason) values(v_source,v_version,v_profile,auth.uid(),v_reason); return jsonb_build_object('source_id',v_source,'version_no',v_version,'status','saved_revalidation_required');
 elsif p_operation='set_pause' then update pipeline.layer1_source_operations set paused=coalesce((p_args->>'paused')::boolean,true),change_reason=v_reason,updated_by=auth.uid(),updated_at=now() where source_id=v_source returning to_jsonb(layer1_source_operations)-'updated_by' into v_profile; if not found then raise exception 'source operations profile missing' using errcode='22023'; end if; select coalesce(max(version_no),0)+1 into v_version from pipeline.layer1_source_operation_versions where source_id=v_source; insert into pipeline.layer1_source_operation_versions(source_id,version_no,snapshot,changed_by,change_reason) values(v_source,v_version,v_profile,auth.uid(),v_reason); update pipeline.refresh_policies set enabled=not coalesce((p_args->>'paused')::boolean,true),updated_at=now(),change_control_ref='CF-CHG-20260826-043' where layer=1 and source_id=v_source; return jsonb_build_object('source_id',v_source,'paused',v_profile->'paused','version_no',v_version);
 elsif p_operation='queue_run' then select to_jsonb(o) into v_profile from pipeline.layer1_source_operations o where o.source_id=v_source; if not found then raise exception 'source operations profile missing' using errcode='22023'; end if; select co.iso_alpha2::text into v_country from pipeline.sources s join ref.countries co on co.id=s.country_id where s.id=v_source; v_mode:=lower(coalesce(nullif(p_args->>'mode',''),'dry_run')); if v_mode not in ('validate','dry_run','apply','recheck') then raise exception 'invalid mode' using errcode='22023'; end if; if not coalesce((v_profile->>'active')::boolean,false) or coalesce((v_profile->>'paused')::boolean,false) then raise exception 'source is inactive or paused' using errcode='55000'; end if; if v_mode in ('dry_run','apply','recheck') then if coalesce(v_profile->>'verification_status','') not in ('passed','warning') then raise exception 'source verification must pass before run' using errcode='55000'; end if; if nullif(v_profile->>'next_verification_at','')::timestamptz is not null and (v_profile->>'next_verification_at')::timestamptz<now() then raise exception 'source verification is stale' using errcode='55000'; end if; if v_profile->>'variance_decision'='block' then raise exception 'record-count variance is blocked' using errcode='55000'; end if; v_warning:=v_profile->>'variance_decision'='warn'; if v_mode='apply' and v_warning and not coalesce((p_args->>'acknowledge_warning')::boolean,false) then raise exception 'variance warning acknowledgement required for APPLY' using errcode='55000'; end if; end if; insert into pipeline.layer1_run_queue(source_id,country_code,mode,status,idempotency_key,requested_by,expected_count,resume_cursor,source_hash,warning_acknowledged,current_stage,heartbeat_at,retry_of_run_id) values(v_source,v_country,v_mode,'queued',coalesce(nullif(p_args->>'idempotency_key',''),md5(v_source::text||':'||v_mode||':'||coalesce(v_profile->>'last_source_hash','nohash')||':'||coalesce(p_args->>'resume_cursor','0')||':'||current_date::text)),auth.uid(),nullif(v_profile->>'last_expected_count','')::bigint,coalesce(nullif(p_args->>'resume_cursor','')::bigint,0),v_profile->>'last_source_hash',coalesce((p_args->>'acknowledge_warning')::boolean,false),'queued',now(),nullif(p_args->>'retry_of_run_id','')::uuid) returning id into v_id; return jsonb_build_object('run_id',v_id,'status','queued','country_code',v_country,'mode',v_mode);
 elsif p_operation='recover_stuck' then
  v_id:=nullif(p_args->>'run_id','')::uuid; if v_id is null then raise exception 'run_id required' using errcode='22023'; end if;
  update pipeline.layer1_run_queue set status='failed',current_stage='stuck_recovered',completed_at=now(),heartbeat_at=now(),error_text='Recovered by Platform Admin after stale heartbeat: '||v_reason,updated_at=now() where id=v_id and source_id=v_source and status='running' and coalesce(heartbeat_at,started_at,requested_at)<now()-interval '30 minutes';
  if not found then raise exception 'only a running job with heartbeat older than 30 minutes may be recovered' using errcode='55000'; end if;
  update pipeline.layer1_source_operations set last_schedule_status='failed',last_schedule_error='Stuck run recovered: '||left(v_reason,900),consecutive_failures=consecutive_failures+1,updated_at=now() where source_id=v_source;
  return jsonb_build_object('run_id',v_id,'status','failed','stage','stuck_recovered');
 elsif p_operation='cancel_queued' then v_id:=nullif(p_args->>'run_id','')::uuid; update pipeline.layer1_run_queue set status='cancelled',current_stage='cancelled_before_start',completed_at=now(),updated_at=now(),error_text='Cancelled by Platform Admin: '||v_reason where id=v_id and source_id=v_source and status='queued'; if not found then raise exception 'only queued run may be cancelled' using errcode='55000'; end if; return jsonb_build_object('run_id',v_id,'status','cancelled'); else raise exception 'unsupported Layer 1 command: %',p_operation using errcode='22023'; end if;
end $$;
revoke all on function security.admin_layer1_command(text,jsonb) from public,anon; grant execute on function security.admin_layer1_command(text,jsonb) to authenticated,service_role;

create or replace function security.layer1_housekeeping_tick_impl()
returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select public.svc_layer1_housekeeping() $$;
revoke all on function security.layer1_housekeeping_tick_impl() from public,anon,authenticated;
grant execute on function security.layer1_housekeeping_tick_impl() to service_role;
select cron.schedule('coursefinder-layer1-housekeeping','17 3 * * *','select security.layer1_housekeeping_tick_impl();') where not exists(select 1 from cron.job where jobname='coursefinder-layer1-housekeeping');