import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2";
const FN="provider-contact-enrich-apollo",VERSION="provider-contact-enrich-apollo-v1.0.0";
const J=(s:number,b:any)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:any)=>String(v??"").replace(/\s+/g," ").trim();
const norm=(v:any)=>clean(v).toLowerCase().replace(/[^a-z0-9@.+-]+/g," ").trim();
async function rpc(c:any,n:string,a:any={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(n+": "+error.message);return data}
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
const territoryTerms=["South Asia","India","Nepal","Pakistan","Bangladesh","Sri Lanka","Middle East","Southeast Asia","South East Asia","China","Hong Kong","Taiwan","Vietnam","Indonesia","Malaysia","Singapore","Philippines","Thailand","Africa","Europe","North America","Latin America"];
function territory(title:string){return territoryTerms.filter(t=>new RegExp(t.replace(/\s+/g,"\\s+"),"i").test(title||"")).join(", ")||null}
async function save(svc:any,profile:any,p:any){
  const externalId=clean(p.id||p.person_id);if(!externalId)return null;
  const identity=await sha(profile.provider_id+"|apollo|"+externalId),{data:prior}=await svc.schema("pipeline").from("provider_contact_observations").select("*").eq("identity_hash",identity).maybeSingle(),now=new Date().toISOString();
  const title=clean(p.title),row={provider_id:profile.provider_id,profile_id:profile.id,source_class:"licensed_enrichment",source_provider:"apollo",source_url:null,external_person_id:externalId,full_name:clean(p.name)||null,job_title:title||null,team_name:/admission/i.test(title)?"International Admissions":/recruit/i.test(title)?"International Recruitment":null,territory_text:territory(title),territory_codes:[],work_email:null,work_phone:null,professional_profile_url:clean(p.linkedin_url)||null,evidence_id:null,identity_hash:identity,verification_state:"unverified",observed_at:now,last_verified_at:now,is_current:true,confidence:null,metadata:{worker_version:VERSION,business_contact:true,licensed_enrichment:true,personal_email_requested:false,phone_requested:false,employer_domain:profile.domain}};
  if(prior){const before={job_title:prior.job_title,territory_text:prior.territory_text,professional_profile_url:prior.professional_profile_url},after={job_title:row.job_title,territory_text:row.territory_text,professional_profile_url:row.professional_profile_url};let event=null;if(before.job_title!==after.job_title)event="title_changed";else if(before.territory_text!==after.territory_text)event="territory_changed";else if(before.professional_profile_url!==after.professional_profile_url)event="contact_changed";await svc.schema("pipeline").from("provider_contact_observations").update(row).eq("id",prior.id);if(event)await svc.schema("pipeline").from("provider_contact_watch_events").insert({provider_id:profile.provider_id,observation_id:prior.id,event_type:event,source_class:"licensed_enrichment",before_state:before,after_state:after,metadata:{worker_version:VERSION,source_provider:"apollo"}});return prior.id}
  const{data:n,error}=await svc.schema("pipeline").from("provider_contact_observations").insert(row).select("id").single();if(error)throw error;await svc.schema("pipeline").from("provider_contact_watch_events").insert({provider_id:profile.provider_id,observation_id:n.id,event_type:"new_contact",source_class:"licensed_enrichment",after_state:{job_title:row.job_title,territory_text:row.territory_text,professional_profile_url:row.professional_profile_url},metadata:{worker_version:VERSION,source_provider:"apollo"}});return n.id
}
Deno.serve(async(req)=>{if(req.method!=="POST")return J(405,{ok:false,error:"POST required",worker_version:VERSION});const sb=Deno.env.get("SUPABASE_URL")!,sk=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,apiKey=Deno.env.get("APOLLO_API_KEY")||"",svc=createClient(sb,sk,{auth:{persistSession:false}});try{const nonce=clean(req.headers.get("x-cf-run-nonce"));if(!nonce)throw new Error("one-time schedule nonce required");if(!await rpc(svc,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce}))throw new Error("invalid, expired or already-used schedule nonce");if(!apiKey)return J(503,{ok:false,error:"APOLLO_API_KEY not configured",worker_version:VERSION,personal_email_requested:false,phone_requested:false});const b=await req.json().catch(()=>({})),providerId=clean(b.provider_id),limit=Math.min(Math.max(Number(b.limit||2),1),5);let q=svc.schema("pipeline").from("provider_contact_profiles").select("*").eq("enabled",true).eq("paused",false).limit(limit);if(providerId)q=q.eq("provider_id",providerId);const{data:profiles,error}=await q;if(error)throw error;const titles=["International Recruitment Manager","Regional Manager","Regional Director","International Manager","International Admissions","Country Manager","Market Manager"],results=[];for(const profile of profiles||[]){const st=performance.now(),params=new URLSearchParams();for(const t of titles)params.append("person_titles[]",t);params.append("q_organization_domains_list[]",profile.domain);params.set("include_similar_titles","true");params.set("per_page","25");params.set("page","1");let status="failed",err:string|null=null,count=0;try{const res=await fetch("https://api.apollo.io/api/v1/mixed_people/api_search?"+params.toString(),{method:"POST",headers:{"accept":"application/json","x-api-key":apiKey}}),text=await res.text();if(!res.ok)throw new Error("Apollo HTTP "+res.status+": "+text.slice(0,400));const parsed=JSON.parse(text),people=Array.isArray(parsed?.people)?parsed.people:Array.isArray(parsed?.contacts)?parsed.contacts:[];for(const person of people){await save(svc,profile,person);count++}status="succeeded"}catch(e:any){err=String(e.message||e)}const latency=Math.round(performance.now()-st);await svc.schema("pipeline").from("provider_contact_enrichment_attempts").insert({provider_id:profile.provider_id,source_provider:"apollo",request_type:"people_api_search",domain:profile.domain,requested_titles:titles,status,external_call_count:1,vendor_units:0,estimated_cost_usd:null,latency_ms:latency,error:err,metadata:{worker_version:VERSION,endpoint:"mixed_people/api_search",documented_search_credit_units:0,personal_email_requested:false,phone_requested:false}});results.push({provider_id:profile.provider_id,status,people:count,latency_ms:latency,error:err})}return J(200,{ok:true,worker_version:VERSION,personal_email_requested:false,phone_requested:false,processed:results.length,results})}catch(e:any){return J(500,{ok:false,error:String(e.message||e),worker_version:VERSION})}});
