import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const FN = "layer2-scope-discover-scheduled";
const BUCKET = "evidence";
const VERSION = "layer2-scope-discover-scheduled-v1.0.2";
const J = (status:number, body:unknown) => new Response(JSON.stringify(body), {status, headers:{"content-type":"application/json","cache-control":"no-store"}});
const clean = (v:unknown) => String(v ?? "").replace(/\s+/g," ").trim();
const norm = (v:unknown) => clean(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const mimeOnly=(v:unknown)=>clean(v||"text/html").split(";")[0].trim().toLowerCase()||"text/html";
async function rpc(c:any,n:string,a:any={}){const {data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function digest(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function similarity(a:string,b:string){const A=new Set(norm(a).split(" ").filter(x=>x.length>2));const B=new Set(norm(b).split(" ").filter(x=>x.length>2));if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,B.size);}
function stripHtml(s:string){return clean(s.replace(/<[^>]+>/g," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&nbsp;/gi," "));}
function extractLinks(html:string,base:string){const out:any[]=[];const seen=new Set<string>();const re=/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))){try{const u=new URL(m[1],base);if(!["http:","https:"].includes(u.protocol))continue;u.hash="";const url=u.toString();if(seen.has(url))continue;seen.add(url);out.push({url,title:stripHtml(m[2])});}catch{}}return out;}
function approvedUrl(raw:string,cfg:any){const u=new URL(raw);if(u.protocol!=="https:")throw new Error("https source required");const refs=[cfg.base_domain,cfg.discovery_url,...(cfg.url_patterns||[]),cfg.discovery_strategy?.catalogue_url,cfg.discovery_strategy?.search_url_template].filter(Boolean);const hosts=new Set<string>();for(const x of refs){try{hosts.add(new URL(String(x).replace("{query}","x")).hostname.toLowerCase());}catch{}}if(!hosts.has(u.hostname.toLowerCase()))throw new Error(`discovery host not approved: ${u.hostname}`);return u.toString();}
function discoveryUrl(cfg:any,course:any){const d=cfg.discovery_strategy||{};if(d.type==="first_party_search"&&d.search_url_template){const q=encodeURIComponent(clean(`${course.course_code||""} ${course.canonical_title||course.display_title||""}`));return approvedUrl(String(d.search_url_template).replace("{query}",q),cfg);}const url=d.catalogue_url||cfg.discovery_url;if(!url)throw new Error("profile discovery URL missing");return approvedUrl(String(url),cfg);}
async function fetchHtml(url:string,ua:string,seconds:number){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),Math.min(Math.max(Number(seconds||30),5),60)*1000);try{const r=await fetch(url,{signal:ctl.signal,redirect:"follow",headers:{"user-agent":ua||"CourseFinder deterministic acquisition","accept":"text/html,application/xhtml+xml"}});const html=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}`);return {url:r.url,status:r.status,mime:mimeOnly(r.headers.get("content-type")),html};}finally{clearTimeout(timer);}}
function rankCandidates(course:any,html:string,base:string){const expectedTitle=clean(course.canonical_title||course.display_title);const expectedCode=clean(course.course_code).toUpperCase();const esc=expectedCode.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const candidates=extractLinks(html,base).map((x:any)=>{const titleScore=similarity(expectedTitle,x.title||"");const codeInTitle=Boolean(expectedCode)&&new RegExp(`\b${esc}\b`,"i").test(x.title||"");const codeInUrl=Boolean(expectedCode)&&x.url.toUpperCase().includes(expectedCode);const matchScore=Math.min(1,titleScore+(codeInTitle?0.35:0)+(codeInUrl?0.25:0));return {...x,title_score:Number(titleScore.toFixed(3)),regulatory_code_seen:Boolean(codeInTitle||codeInUrl),match_score:Number(matchScore.toFixed(3))};}).filter((x:any)=>x.match_score>=0.35).sort((a:any,b:any)=>b.match_score-a.match_score).slice(0,20);
 let status="current_page_not_found";let blocker:string|null="no plausible current first-party Course page found";
 if(candidates.length){const top=candidates[0],second=candidates[1];if(top.regulatory_code_seen&&top.match_score>=0.8)status="exact_match";else if(top.match_score>=0.75&&(!second||top.match_score-second.match_score>=0.12))status="likely_match";else if(top.match_score>=0.55)status="ambiguous";else status="identity_mismatch";blocker=status==="ambiguous"?"multiple plausible current Course pages":status==="identity_mismatch"?"current page candidate does not sufficiently match selected Course identity":null;}
 return {expectedTitle,expectedCode,candidates,status,blocker,selected:["exact_match","likely_match"].includes(status)};
}

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return J(405,{ok:false,error:"POST required",workerVersion:VERSION});
 const sb=Deno.env.get("SUPABASE_URL")!;const sk=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const svc=createClient(sb,sk,{auth:{persistSession:false}});
 try{
  const nonce=clean(req.headers.get("x-cf-run-nonce"));if(!nonce)throw new Error("one-time schedule nonce required");
  if(!await rpc(svc,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce}))throw new Error("invalid, expired or already-used schedule nonce");
  const body=await req.json().catch(()=>({}));const profileId=clean(body.profile_id);const limit=Math.min(Math.max(Number(body.limit||10),1),50);if(!profileId)throw new Error("profile_id required");
  const ctx=await rpc(svc,"layer2_discovery_context",{p_profile_id:profileId,p_limit:limit});const rt=ctx.runtime;const cfg=rt.configuration||{};const courses=ctx.courses||[];
  const actor=await rpc(svc,"layer2_automation_actor");const job=await rpc(svc,"layer2_prepare_job",{p_actor:actor,p_profile_id:profileId,p_job_type:"layer2_discovery"});const jobId=job.job_id;
  await rpc(svc,"layer2_runtime_job_mark",{p_job_id:jobId,p_status:"running",p_payload:{layer:2,profile_id:profileId,operation:"scope_discovery"},p_result:{},p_error:null,p_attempt_count:0});
  const cache=new Map<string,any>();const results:any[]=[];
  for(const course of courses){let attemptId:string|null=null;try{
    const target=discoveryUrl(cfg,course);let fetched=cache.get(target);if(!fetched){fetched=await fetchHtml(target,cfg.headers?.user_agent,cfg.timeout_seconds);cache.set(target,fetched);}
    attemptId=await rpc(svc,"layer2_provider_attempt_start",{p_job_id:jobId,p_provider_id:ctx.direct_provider_id,p_request_url:target});
    const bytes=new TextEncoder().encode(fetched.html);const rawHash=await digest(bytes);const rawPath=`layer2/v2/discovery/${profileId}/${jobId}/${course.id}/source.html`;
    const up=await svc.storage.from(BUCKET).upload(rawPath,bytes,{contentType:fetched.mime,upsert:false});if(up.error)throw new Error(`evidence upload: ${up.error.message}`);
    const raw=await rpc(svc,"layer2_evidence_capture",{p_source_id:rt.source_id,p_job_id:jobId,p_evidence_type:"layer2_html_snapshot",p_source_url:fetched.url,p_storage_path:rawPath,p_content_hash:rawHash,p_mime_type:fetched.mime,p_profile_version_id:rt.version_id,p_group_key:await digest(new TextEncoder().encode(`${rt.version_id}|${course.id}|discovery|${rawHash}`)),p_retention_class:"standard_365",p_retain_until:null,p_metadata:{layer:2,operation:"course_url_discovery",worker_version:VERSION,course_id:course.id,canonical_mutation_authorised:false}});
    const normalized={layer:2,runtime_version:VERSION,attempt_id:attemptId,job_id:jobId,provider_key:"direct-http",source_evidence_id:raw.evidence_id,source_url:fetched.url,html:fetched.html,text:fetched.html,structured:null,canonical_mutation_authorised:false};const normBytes=new TextEncoder().encode(JSON.stringify(normalized));const normHash=await digest(normBytes);const normPath=`layer2/v2/discovery/${profileId}/${jobId}/${course.id}/extraction-input.json`;
    const nu=await svc.storage.from(BUCKET).upload(normPath,normBytes,{contentType:"application/json",upsert:false});if(nu.error)throw new Error(`normalized upload: ${nu.error.message}`);
    const nev=await rpc(svc,"layer2_evidence_capture",{p_source_id:rt.source_id,p_job_id:jobId,p_evidence_type:"layer2_extraction_input",p_source_url:fetched.url,p_storage_path:normPath,p_content_hash:normHash,p_mime_type:"application/json",p_profile_version_id:rt.version_id,p_group_key:await digest(new TextEncoder().encode(`${raw.evidence_id}|scope-discovery`)),p_retention_class:"standard_365",p_retain_until:null,p_metadata:{layer:2,operation:"course_url_discovery",worker_version:VERSION,course_id:course.id,source_evidence_id:raw.evidence_id,attempt_id:attemptId,canonical_mutation_authorised:false}});
    const ranked=rankCandidates(course,fetched.html,fetched.url);const rows:any[]=[];
    if(ranked.candidates.length){ranked.candidates.forEach((x:any,i:number)=>rows.push({course_id:course.id,source_profile_version_id:rt.version_id,provider_attempt_id:attemptId,evidence_id:nev.evidence_id,discovered_url:x.url,discovered_title:x.title,discovered_regulatory_code:x.regulatory_code_seen?ranked.expectedCode:null,match_score:x.match_score,match_basis:{title_score:x.title_score,regulatory_code_seen:x.regulatory_code_seen,expected_title:ranked.expectedTitle,expected_course_code:ranked.expectedCode,worker_version:VERSION},status:i===0?ranked.status:"candidate",selected:i===0&&ranked.selected,blocker:i===0?ranked.blocker:null}));}
    else rows.push({course_id:course.id,source_profile_version_id:rt.version_id,provider_attempt_id:attemptId,evidence_id:nev.evidence_id,status:"current_page_not_found",selected:false,match_basis:{expected_title:ranked.expectedTitle,expected_course_code:ranked.expectedCode,worker_version:VERSION},blocker:ranked.blocker});
    const ins=await svc.schema("pipeline").from("layer2_course_discovery_candidates").insert(rows);if(ins.error)throw new Error(`candidate write: ${ins.error.message}`);
    await rpc(svc,"layer2_provider_attempt_finish",{p_attempt_id:attemptId,p_status:"completed",p_http_status:fetched.status,p_mime:fetched.mime,p_raw_evidence:raw.evidence_id,p_html_evidence:raw.evidence_id,p_screenshot_evidence:null,p_extraction_status:"discovery_evaluated",p_blocker:ranked.blocker,p_metrics:{operation:"scope_discovery",candidate_count:ranked.candidates.length,selected:ranked.selected,worker_version:VERSION}});
    results.push({course_id:course.id,status:ranked.status,selected_url:ranked.selected?ranked.candidates[0]?.url:null,candidates:ranked.candidates.length});
  }catch(e:any){if(attemptId)try{await rpc(svc,"layer2_provider_attempt_finish",{p_attempt_id:attemptId,p_status:"failed",p_http_status:null,p_mime:null,p_raw_evidence:null,p_html_evidence:null,p_screenshot_evidence:null,p_extraction_status:"blocked",p_blocker:String(e.message||e).slice(0,1000),p_metrics:{operation:"scope_discovery",worker_version:VERSION}});}catch{}results.push({course_id:course.id,status:"failed",error:String(e.message||e)});}}
  const selected=results.filter(x=>x.selected_url).length;const failed=results.filter(x=>x.status==="failed").length;const finalStatus=results.length>0&&failed===results.length?"failed":"completed";
  await rpc(svc,"layer2_runtime_job_mark",{p_job_id:jobId,p_status:finalStatus,p_payload:{layer:2,profile_id:profileId,operation:"scope_discovery"},p_result:{processed:results.length,selected,failed,results},p_error:finalStatus==="failed"?"all discovery items failed":null,p_attempt_count:results.length});
  return J(200,{ok:true,workerVersion:VERSION,profile_id:profileId,job_id:jobId,processed:results.length,selected,failed,results});
 }catch(e:any){return J(500,{ok:false,error:String(e.message||e),workerVersion:VERSION});}
});