import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const VERSION="coursefacts-au-uq-v0.2.0";
const FN="coursefacts-au-uq";
const PROVIDER_CRICOS="00025B";
const RECORDS=[
 {courseCricos:"102784C",sourceRecordId:"uq-2452-2027",url:"https://study.uq.edu.au/study-options/programs/bachelor-computer-science-honours-2452?year=2027",proof:["102784C","60,952","2027","22 Feb, 2027","26 Jul, 2027","IELTS overall 6.5","Overall 87","Overall Score of 64"],payload:{course_url:"https://study.uq.edu.au/study-options/programs/bachelor-computer-science-honours-2452?year=2027",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:60952,currency_code:"AUD",fee_basis:"indicative_annual",fee_key:"uq:102784C:international:2027:indicative_annual",fee_notes:"UQ published 2027 indicative annual international tuition fee for 16 units",intakes:[{intake_year:2027,intake_label:"Semester 1",start_date:"2027-02-22",application_deadline:"2026-11-30",source_intake_key:"uq:102784C:2027:s1"},{intake_year:2027,intake_label:"Semester 2",start_date:"2027-07-26",application_deadline:"2027-05-31",source_intake_key:"uq:102784C:2027:s2"}],english_requirements:[{test_code:"IELTS",overall_score:6.5,component_scores:{reading:6,listening:6,speaking:6,writing:6},valid_from:"2026-08-20"},{test_code:"TOEFL_IBT",overall_score:87,component_scores:{reading:19,listening:19,speaking:19,writing:21},valid_from:"2026-08-20"},{test_code:"PTE",overall_score:64,component_scores:{minimum_each:60},valid_from:"2026-08-20"}]}},
 {courseCricos:"082960F",sourceRecordId:"uq-2243-2027",url:"https://study.uq.edu.au/study-options/programs/bachelor-nursing-honours-2243?year=2027",proof:["082960F","48,080","2027","22 Feb, 2027","IELTS overall 7","Overall 100","Overall 72"],payload:{course_url:"https://study.uq.edu.au/study-options/programs/bachelor-nursing-honours-2243?year=2027",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:48080,currency_code:"AUD",fee_basis:"indicative_annual",fee_key:"uq:082960F:international:2027:indicative_annual",fee_notes:"UQ published 2027 indicative annual international tuition fee for 16 units",intakes:[{intake_year:2027,intake_label:"Semester 1",start_date:"2027-02-22",application_deadline:"2026-11-30",source_intake_key:"uq:082960F:2027:s1"}],english_requirements:[{test_code:"IELTS",overall_score:7,component_scores:{reading:7,listening:7,speaking:7,writing:7},valid_from:"2026-08-20"},{test_code:"TOEFL_IBT",overall_score:100,component_scores:{reading:25,listening:25,speaking:23,writing:27},valid_from:"2026-08-20"},{test_code:"PTE",overall_score:72,component_scores:{minimum_each:72},valid_from:"2026-08-20"}]}},
 {courseCricos:"045401M",sourceRecordId:"uq-2572-2027",url:"https://study.uq.edu.au/study-options/programs/bachelors-commerce-information-technology-2572?year=2027",proof:["045401M","60,952","2027","22 Feb, 2027","26 Jul, 2027","IELTS overall 6.5","Overall 87","Overall Score of 64"],payload:{course_url:"https://study.uq.edu.au/study-options/programs/bachelors-commerce-information-technology-2572?year=2027",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:60952,currency_code:"AUD",fee_basis:"indicative_annual",fee_key:"uq:045401M:international:2027:indicative_annual",fee_notes:"UQ published 2027 indicative annual international tuition fee",intakes:[{intake_year:2027,intake_label:"Semester 1",start_date:"2027-02-22",application_deadline:"2026-11-30",source_intake_key:"uq:045401M:2027:s1"},{intake_year:2027,intake_label:"Semester 2",start_date:"2027-07-26",application_deadline:"2027-05-31",source_intake_key:"uq:045401M:2027:s2"}],english_requirements:[{test_code:"IELTS",overall_score:6.5,component_scores:{reading:6,listening:6,speaking:6,writing:6},valid_from:"2026-08-20"},{test_code:"TOEFL_IBT",overall_score:87,component_scores:{reading:19,listening:19,speaking:19,writing:21},valid_from:"2026-08-20"},{test_code:"PTE",overall_score:64,component_scores:{minimum_each:60},valid_from:"2026-08-20"}]}},
 {courseCricos:"013827E",sourceRecordId:"uq-2478-2027",url:"https://study.uq.edu.au/study-options/programs/bachelors-science-arts-2478?year=2027",proof:["013827E","56,800","2027","22 Feb, 2027","26 Jul, 2027","IELTS overall 6.5","Overall 87","Overall Score of 64"],payload:{course_url:"https://study.uq.edu.au/study-options/programs/bachelors-science-arts-2478?year=2027",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:56800,currency_code:"AUD",fee_basis:"indicative_annual",fee_key:"uq:013827E:international:2027:indicative_annual",fee_notes:"UQ published 2027 indicative annual international tuition fee",intakes:[{intake_year:2027,intake_label:"Semester 1",start_date:"2027-02-22",application_deadline:"2026-11-30",source_intake_key:"uq:013827E:2027:s1"},{intake_year:2027,intake_label:"Semester 2",start_date:"2027-07-26",application_deadline:"2027-05-31",source_intake_key:"uq:013827E:2027:s2"}],english_requirements:[{test_code:"IELTS",overall_score:6.5,component_scores:{reading:6,listening:6,speaking:6,writing:6},valid_from:"2026-08-20"},{test_code:"TOEFL_IBT",overall_score:87,component_scores:{reading:19,listening:19,speaking:19,writing:21},valid_from:"2026-08-20"},{test_code:"PTE",overall_score:64,component_scores:{minimum_each:60},valid_from:"2026-08-20"}]}}
];
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-cf-run-nonce","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown)=>String(v??"").trim();
async function rpc(c:any,n:string,a:Record<string,unknown>={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function auth(req:Request,svc:any){const nonce=clean(req.headers.get("x-cf-run-nonce"));if(!nonce||!await rpc(svc,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce}))throw new Error("valid one-time Pilot nonce required");}
async function sha(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function visible(html:string){return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#36;/g,"$").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ");}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"POST required"},405);const svc=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});try{await auth(req,svc);const body=await req.json().catch(()=>({}));const apply=body.apply===true;const source=await rpc(svc,"svc_coursefacts_resolve_source",{p_system_code:"au_uq_course_pages",p_provider_cricos:PROVIDER_CRICOS});if(!source?.source_id)throw new Error("UQ source not resolved");const results:any[]=[];for(const rec of RECORDS){const resp=await fetch(rec.url,{redirect:"follow",headers:{"user-agent":"CourseFinder-Pilot/CourseFacts-UQ-0.2.0","accept":"text/html,application/xhtml+xml"}});if(!resp.ok)throw new Error(`${rec.courseCricos} HTTP ${resp.status}`);const bytes=new Uint8Array(await resp.arrayBuffer()),html=new TextDecoder().decode(bytes),text=visible(html),hash=await sha(bytes);const missing=rec.proof.filter(x=>!text.toLowerCase().includes(x.toLowerCase()));if(missing.length)throw new Error(`${rec.courseCricos} source proof failed: ${missing.join(", ")}`);const stamp=new Date().toISOString().replace(/[:.]/g,"-");const storagePath=`layer2a/AU/coursefacts/uq/${rec.courseCricos}/${stamp}.html`;const up=await svc.storage.from("evidence").upload(storagePath,bytes,{contentType:"text/html",upsert:false});if(up.error)throw new Error(up.error.message);const evidenceId=await rpc(svc,"svc_coursefacts_register_evidence",{p_source_id:source.source_id,p_source_url:rec.url,p_storage_path:storagePath,p_content_hash:hash,p_mime_type:"text/html",p_metadata:{worker_version:VERSION,provider_cricos:PROVIDER_CRICOS,course_cricos:rec.courseCricos,http_status:resp.status,identity_authority:false,search_admitted:false}});const applied=await rpc(svc,"svc_coursefacts_apply_record",{p_source_id:source.source_id,p_evidence_id:evidenceId,p_provider_cricos:PROVIDER_CRICOS,p_course_cricos:rec.courseCricos,p_source_record_id:rec.sourceRecordId,p_source_url:rec.url,p_content_hash:hash,p_payload:rec.payload,p_apply:apply});results.push({courseCricos:rec.courseCricos,url:rec.url,hash,evidenceId,proof:true,applyResult:applied});}return out({ok:true,workerVersion:VERSION,mode:apply?"apply":"dry-run",records:results});}catch(e){return out({error:e instanceof Error?e.message:String(e),workerVersion:VERSION},500);}});