from pathlib import Path
import re

path=Path('src/mature-main.jsx')
text=path.read_text()

# Native QS/THE actions: make Open Dataset explicit alongside Compare while preserving import controls.
text=text.replace("<div>{qs?.accepted_editions?<><button onClick={()=>navigate('Compare',{type:'provider'})}>Compare</button><button onClick={()=>navigate('Administration',{section:'sources-imports',system:'qs_wur',year:'2027'})}>Manage imports</button></>:<button onClick={()=>navigate('Administration',{section:'sources-imports',system:'qs_wur',year:'2027'})}>Manage imports</button>}</div>","<div>{qs?.accepted_editions?<><button onClick={()=>{location.hash=`#statistics-rankings?dataset=qs_wur&year=${qs.latest_edition||2027}`}}>Open Dataset</button><button onClick={()=>navigate('Compare',{type:'provider'})}>Compare</button><button onClick={()=>navigate('Administration',{section:'sources-imports',system:'qs_wur',year:String(qs.latest_edition||2027)})}>Manage imports</button></>:<button onClick={()=>navigate('Administration',{section:'sources-imports',system:'qs_wur',year:'2027'})}>Manage imports</button>}</div>")
text=text.replace("<div>{the?.accepted_editions?<><button onClick={()=>navigate('Compare',{type:'provider'})}>Compare</button><button onClick={()=>navigate('Administration',{section:'sources-imports',system:'the_wur',year:'2026'})}>Manage imports</button></>:<button onClick={()=>navigate('Administration',{section:'sources-imports',system:'the_wur',year:'2026'})}>Manage imports</button>}</div>","<div>{the?.accepted_editions?<><button onClick={()=>{location.hash=`#statistics-rankings?dataset=the_wur&year=${the.latest_edition||2026}`}}>Open Dataset</button><button onClick={()=>navigate('Compare',{type:'provider'})}>Compare</button><button onClick={()=>navigate('Administration',{section:'sources-imports',system:'the_wur',year:String(the.latest_edition||2026)})}>Manage imports</button></>:<button onClick={()=>navigate('Administration',{section:'sources-imports',system:'the_wur',year:'2026'})}>Manage imports</button>}</div>")

# Catalogue: expose every sort already governed by the restored scholarship page contract.
old="return[{key:'name',label:'Scholarship',width:310,sortKey:'scholarship'},{key:'provider_name',label:'Provider',width:250},{key:'scholarship_type',label:'Type',width:170},{key:'audience',label:'Audience',width:150},{key:'award_value_text',label:'Award',width:180},{key:'publication_status',label:'Publication',width:130}]}"
new="return[{key:'name',label:'Scholarship',width:310,sortKey:'scholarship'},{key:'provider_name',label:'Provider',width:250,sortKey:'provider'},{key:'scholarship_type',label:'Type',width:170},{key:'audience',label:'Audience',width:150},{key:'award_value_text',label:'Award',width:180,sortKey:'award'},{key:'academic_year',label:'Year',width:110,sortKey:'year'},{key:'application_close_date',label:'Close',width:130,sortKey:'close'},{key:'mapped_course_count',label:'Mapped Courses',width:120,sortKey:'courses'},{key:'evidence_count',label:'Evidence',width:100,sortKey:'evidence'},{key:'publication_status',label:'Publication',width:130}]}"
if old not in text: raise SystemExit('scholarship columns anchor missing')
text=text.replace(old,new)

# Fluid/responsive catalogue widths: retain column hints as maxima, not rigid widths.
old_dt="function DataTable({rows,columns,loading,sort,direction,onSort,onRow,selected}){return <div className=\"m-table-wrap\"><table className=\"m-table\"><thead><tr>{columns.map((c,i)=><th key={c.key} className={i===0?'sticky-col':''} style={{minWidth:c.width||120}}><button disabled={!c.sortKey} onClick={()=>onSort(c.sortKey)}>{c.label}{c.sortKey&&sort===c.sortKey&&(direction==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>)}</button></th>)}</tr></thead><tbody>{loading&&rows.length===0?Array.from({length:8}).map((_,i)=><tr key={i}>{columns.map((c,j)=><td className={j===0?'sticky-col':''} key={c.key}><span className=\"m-row-skeleton\"/></td>)}</tr>):rows.length?rows.map((r,i)=><tr key={r.id??r.course_id??i} className={String(selected)===String(r.id??r.course_id)?'selected':''} onClick={()=>onRow?.(r)}>{columns.map((c,j)=><td key={c.key} className={j===0?'sticky-col':''}>{cell(r,c.key)}</td>)}</tr>):<tr><td colSpan={columns.length}><EmptyInline text=\"No records match the current filters.\"/></td></tr>}</tbody></table></div>}"
new_dt="function DataTable({rows,columns,loading,sort,direction,onSort,onRow,selected}){return <div className=\"m-table-wrap\"><table className=\"m-table m-fluid-table\" style={{width:'100%',minWidth:'max-content'}}><thead><tr>{columns.map((c,i)=>{const max=Number(c.width||180),min=Math.min(max,96),vw=Math.max(9,Math.round(max/18));return <th key={c.key} className={i===0?'sticky-col':''} style={{minWidth:`clamp(${min}px,${vw}vw,${max}px)`}}><button disabled={!c.sortKey} onClick={()=>onSort(c.sortKey)}>{c.label}{c.sortKey&&sort===c.sortKey&&(direction==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>)}</button></th>})}</tr></thead><tbody>{loading&&rows.length===0?Array.from({length:8}).map((_,i)=><tr key={i}>{columns.map((c,j)=><td className={j===0?'sticky-col':''} key={c.key}><span className=\"m-row-skeleton\"/></td>)}</tr>):rows.length?rows.map((r,i)=><tr key={r.id??r.course_id??i} className={String(selected)===String(r.id??r.course_id)?'selected':''} onClick={()=>onRow?.(r)}>{columns.map((c,j)=><td key={c.key} className={j===0?'sticky-col':''}>{cell(r,c.key)}</td>)}</tr>):<tr><td colSpan={columns.length}><EmptyInline text=\"No records match the current filters.\"/></td></tr>}</tbody></table></div>}"
if old_dt not in text: raise SystemExit('DataTable anchor missing')
text=text.replace(old_dt,new_dt)

# QILT / PRISMS: authoritative server sorting only for keys supported by the restored contracts.
new_insight=r'''function Qilt({onError}){return <InsightWorkspace kind="qilt" onError={onError}/>}function Prisms({onError}){return <InsightWorkspace kind="prisms" onError={onError}/>} 
function InsightWorkspace({kind,onError}){
 const[filters,setFilters]=useState({}),[filterLabels,setFilterLabels]=useState({}),[options,setOptions]=useState({}),[data,setData]=useState(null),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[query,setQuery]=useState(''),[sort,setSort]=useState(kind==='qilt'?'provider':'geography'),[direction,setDirection]=useState('asc')
 useEffect(()=>{const p=kind==='qilt'?api.qiltFilterOptions(filters.survey||''):api.prismsFilterOptions();p.then(setOptions).catch(e=>onError(e.message))},[kind,filters.survey])
 const debounced=useDebounce(query,280)
 useEffect(()=>{setBusy(true);const p=kind==='qilt'?api.qiltPage({limit:PAGE_SIZE,offset,query:debounced,survey:filters.survey||'',metric:filters.metric||'',provider:filters.provider||'',status:filters.status||'',year:filters.year||'',sort,direction}):api.prismsPage({limit:PAGE_SIZE,offset,query:debounced,subdivision:filters.subdivision||'',studyArea:filters.studyArea||'',sector:filters.sector||'',remoteness:filters.remoteness||'',suppressed:filters.suppressed===''?null:filters.suppressed==='true',sort,direction});p.then(setData).catch(e=>onError(e.message)).finally(()=>setBusy(false))},[kind,offset,debounced,JSON.stringify(filters),sort,direction])
 useEffect(()=>setOffset(0),[debounced,JSON.stringify(filters),sort,direction])
 const rows=rowsOf(data),total=Number(data?.total??rows.length)
 function patch(k,v,label=''){setFilters(f=>{const n={...f,[k]:v};if(kind==='qilt'&&k==='survey'){n.metric='';n.provider=''}return n});setFilterLabels(l=>{const n={...l,[k]:label||''};if(kind==='qilt'&&k==='survey'){delete n.metric;delete n.provider}return n})}
 function changeSort(k){if(!k)return;if(sort===k)setDirection(d=>d==='asc'?'desc':'asc');else{setSort(k);setDirection('asc')}}
 const sortMap=kind==='qilt'?{provider_name:'provider',survey_code:'survey',survey_name:'survey',metric_code:'metric',metric_name:'metric',metric_value:'value',national_benchmark:'benchmark',response_count:'responses',collection_year_from:'year',collection_year_to:'year'}:{source_geography_name:'geography',subdivision_code:'state',subdivision_name:'state',source_study_area_code:'study_area',source_study_area_name:'study_area',enrolments:'enrolments',commencements:'commencements',period_start:'period',period_end:'period'}
 return <div className="m-page-stack"><section className="m-panel"><div className="m-workspace-head"><div><h2>{kind==='qilt'?'QILT outcomes':'PRISMS student flow'}</h2><p>Structured Layer 2 observations remain separate from canonical identity. Sort controls use the governed dataset contract.</p></div><div className="m-result-count"><strong>{fmtNumber(total)}</strong><span>matching</span></div></div><div className="m-search-row"><label className="m-searchbox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search governed observations…"/></label></div><div className="m-filter-bar">{kind==='qilt'?<><FilterSelect label="Survey" value={filters.survey||''} onChange={(v,l)=>patch('survey',v,l)} options={normaliseOptions(options.surveys)}/><AsyncPagedFilterSelect kind="qilt_metric" label="Metric" value={filters.metric||''} valueLabel={filterLabels.metric||''} survey={filters.survey||''} onChange={(v,l)=>patch('metric',v,l)}/><AsyncPagedFilterSelect kind="qilt_provider" label="Provider" value={filters.provider||''} valueLabel={filterLabels.provider||''} survey={filters.survey||''} onChange={(v,l)=>patch('provider',v,l)}/><FilterSelect label="Year" value={filters.year||''} onChange={(v,l)=>patch('year',v,l)} options={normaliseOptions(options.years)}/><FilterSelect label="Status" value={filters.status||''} onChange={(v,l)=>patch('status',v,l)} options={normaliseOptions(options.statuses)}/></>:<><FilterSelect label="State / Region" value={filters.subdivision||''} onChange={(v,l)=>patch('subdivision',v,l)} options={normaliseOptions(options.subdivisions)}/><AsyncPagedFilterSelect kind="prisms_study_area" label="Study area" value={filters.studyArea||''} valueLabel={filterLabels.studyArea||''} onChange={(v,l)=>patch('studyArea',v,l)}/><FilterSelect label="Sector" value={filters.sector||''} onChange={(v,l)=>patch('sector',v,l)} options={normaliseOptions(options.sectors)}/><FilterSelect label="Remoteness" value={filters.remoteness||''} onChange={(v,l)=>patch('remoteness',v,l)} options={normaliseOptions(options.remoteness)}/></>}</div><DynamicTable rows={rows} loading={busy} sort={sort} direction={direction} sortMap={sortMap} onSort={changeSort}/><Pager offset={offset} limit={PAGE_SIZE} total={total} onOffset={setOffset}/></section></div>
}
'''
text,n=re.subn(r'function Qilt\(\{onError\}\)\{return <InsightWorkspace kind="qilt" onError=\{onError\}/>\}function Prisms\(\{onError\}\)\{return <InsightWorkspace kind="prisms" onError=\{onError\}/>\} \nfunction InsightWorkspace\(\{kind,onError\}\)\{.*?\n\n\n\nfunction OperationalList',new_insight+'\n\nfunction OperationalList',text,count=1,flags=re.S)
if n!=1: raise SystemExit(f'InsightWorkspace anchor count {n}')

old_dyn=re.search(r'function DynamicTable\(\{rows,loading\}\)\{.*?\}\nfunction dynamicColumns',text,re.S)
if not old_dyn: raise SystemExit('DynamicTable anchor missing')
new_dyn='''function DynamicTable({rows,loading,sort='',direction='asc',sortMap={},onSort}){const cols=useMemo(()=>dynamicColumns(rows),[rows]);return <div className="m-table-wrap"><table className="m-table dynamic m-fluid-table" style={{width:'100%',minWidth:'max-content'}}><thead><tr>{cols.map((c,i)=>{const sk=sortMap[c]||'';return <th key={c} className={i===0?'sticky-col':''} style={{minWidth:`clamp(96px,12vw,220px)`}}>{sk?<button onClick={()=>onSort?.(sk)}>{humanise(c)}{sort===sk&&(direction==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>)}</button>:<span>{humanise(c)}</span>}</th>})}</tr></thead><tbody>{loading&&rows.length===0?Array.from({length:6}).map((_,i)=><tr key={i}>{Array.from({length:Math.max(cols.length,5)}).map((_,j)=><td key={j}><span className="m-row-skeleton"/></td>)}</tr>):rows.length?rows.map((r,i)=><tr key={r.id??i}>{cols.map((c,j)=><td key={c} className={j===0?'sticky-col':''}>{genericCell(c,r[c])}</td>)}</tr>):<tr><td colSpan={Math.max(cols.length,1)}><EmptyInline text="No governed records are currently available."/></td></tr>}</tbody></table></div>}
function dynamicColumns'''
text=text[:old_dyn.start()]+new_dyn+text[old_dyn.end():]

path.write_text(text)
print('M2.4.5 native UI patch applied')
