import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const VERSION="coursefacts-au-qut-v0.1.1";
const FN="coursefacts-au-qut";
const PROVIDER_CRICOS="00213J";
const RECORDS=[
 {courseCricos:"083019B",sourceRecordId:"qut-bs08-2027",url:"https://www.qut.edu.au/courses/bachelor-of-business-international",proof:["083019B","46,800","2027","February","July","IELTS Academic","6.5","Cambridge C1 Advanced","176","PTE Academic","58","TOEFL iBT","79"],payload:{course_url:"https://www.qut.edu.au/courses/bachelor-of-business-international",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:46800,currency_code:"AUD",fee_basis:"annual_full_time_96_credit_points",fee_key:"qut:083019B:international:2027:annual_96cp",fee_notes:"QUT published 2027 international fee per year full-time (96 credit points)",intakes:[{intake_year:2027,intake_label:"February",source_intake_key:"qut:083019B:2027:feb"},{intake_year:2027,intake_label:"July",source_intake_key:"qut:083019B:2027:jul"}],english_requirements:[{test_code:"IELTS",overall_score:6.5,component_scores:{listening:6,reading:6,writing:6,speaking:6},valid_from:"2026-08-20"},{test_code:"CAE",overall_score:176,component_scores:{listening:169,reading:169,writing:169,speaking:169},valid_from:"2026-08-20"},{test_code:"PTE",overall_score:58,component_scores:{listening:50,reading:50,writing:50,speaking:50},valid_from:"2026-08-20"},{test_code:"TOEFL_IBT",overall_score:79,component_scores:{listening:16,reading:16,writing:21,speaking:18},valid_from:"2026-08-20"}]}},
 {courseCricos:"017323G",sourceRecordId:"qut-in10-2027",url:"https://www.qut.edu.au/courses/bachelor-of-information-technology-honours",proof:["017323G","47,300","2027","February","July","IELTS Academic","6.5","Cambridge C1 Advanced","176","PTE Academic","58","TOEFL iBT","79"],payload:{course_url:"https://www.qut.edu.au/courses/bachelor-of-information-technology-honours",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:47300,currency_code:"AUD",fee_basis:"annual_full_time_96_credit_points",fee_key:"qut:017323G:international:2027:annual_96cp",fee_notes:"QUT published 2027 international fee per year full-time (96 credit points)",intakes:[{intake_year:2027,intake_label:"February",source_intake_key:"qut:017323G:2027:feb"},{intake_year:2027,intake_label:"July",source_intake_key:"qut:017323G:2027:jul"}],english_requirements:[{test_code:"IELTS",overall_score:6.5,component_scores:{listening:6,reading:6,writing:6,speaking:6},valid_from:"2026-08-20"},{test_code:"CAE",overall_score:176,component_scores:{listening:169,reading:169,writing:169,speaking:169},valid_from:"2026-08-20"},{test_code:"PTE",overall_score:58,component_scores:{listening:50,reading:50,writing:50,speaking:50},valid_from:"2026-08-20"},{test_code:"TOEFL_IBT",overall_score:79,component_scores:{listening:16,reading:16,writing:21,speaking:18},valid_from:"2026-08-20"}]}}
];
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-cf-run-nonce","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown)=>String(v??"").trim();
async function rpc(c:any,n:string,a:Record<string,unknown>={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function auth(req:Request,svc:any){const nonce=clean(req.headers.get("x-cf-run-nonce"));if(!nonce||!await rpc(svc,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce}))throw new Error("valid one-time Pilot nonce required");}
async function sha(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function visible(html:string){return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#36;/g,"$").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ");}
const browserHeaders={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-language":"en-AU,en;q=0.9","cache-control":"no-cache","pragma":"no-cache","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"none","upgrade-insecure-requests":"1"};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"POST required"},405);const svc=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});try{await auth(req,svc);const body=await req.json().catch(()=>({}));const apply=body.apply===true;const source=await rpc(svc,"svc_coursefacts_resolve_source",{p_system_code:"au_qut_course_pages",p_provider_cricos:PROVIDER_CRICOS});if(!source?.source_id)throw new Error("QUT source not resolved");const results:any[]=[];for(const rec of RECORDS){const resp=await fetch(rec.url,{redirect:"follow",headers:browserHeaders});if(!resp.ok)throw new Error(`${rec.courseCricos} HTTP ${resp.status}`);const bytes=new Uint8Array(await resp.arrayBuffer()),html=new TextDecoder().decode(bytes),text=visible(html),hash=await sha(bytes);const missing=rec.proof.filter(x=>!text.toLowerCase().includes(x.toLowerCase()));if(missing.length)throw new Error(`${rec.courseCricos} source proof failed: ${missing.join(", ")}`);const stamp=new Date().toISOString().replace(/[:.]/g,"-");const storagePath=`layer2a/AU/coursefacts/qut/${rec.courseCricos}/${stamp}.html`;const up=await svc.storage.from("evidence").upload(storagePath,bytes,{contentType:"text/html",upsert:false});if(up.error)throw new Error(up.error.message);const evidenceId=await rpc(svc,"svc_coursefacts_register_evidence",{p_source_id:source.source_id,p_source_url:rec.url,p_storage_path:storagePath,p_content_hash:hash,p_mime_type:"text/html",p_metadata:{worker_version:VERSION,provider_cricos:PROVIDER_CRICOS,course_cricos:rec.courseCricos,http_status:resp.status,identity_authority:false,search_admitted:false}});const applied=await rpc(svc,"svc_coursefacts_apply_record",{p_source_id:source.source_id,p_evidence_id:evidenceId,p_provider_cricos:PROVIDER_CRICOS,p_course_cricos:rec.courseCricos,p_source_record_id:rec.sourceRecordId,p_source_url:rec.url,p_content_hash:hash,p_payload:rec.payload,p_apply:apply});results.push({courseCricos:rec.courseCricos,url:rec.url,hash,evidenceId,proof:true,applyResult:applied});}return out({ok:true,workerVersion:VERSION,mode:apply?"apply":"dry-run",records:results});}catch(e){return out({error:e instanceof Error?e.message:String(e),workerVersion:VERSION},500);}});