import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { unzipSync } from "npm:fflate@0.8.2";

const VERSION="layer1-operations-control-v1.8.0";
const FN="layer1-operations-control";
const TYPES=["UNI","POLLY","WANA","PTE","GTE"];
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown)=>String(v??"").trim();
async function rpc(c:any,n:string,a:Record<string,unknown>={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function sha(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function fetchT(url:string,ms=90000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:"follow",headers:{"user-agent":"coursefinder-pilot-layer1-operations/1.0","accept":"*/*"}});if(!r.ok)throw new Error(`HTTP ${r.status} from ${new URL(url).hostname}`);return r;}finally{clearTimeout(t);}}
function hostAllowed(raw:string,domains:string[]){let u:URL;try{u=new URL(raw)}catch{throw new Error("source URL is malformed")}if(u.protocol!=="https:")throw new Error("regulatory source must use HTTPS");const host=u.hostname.toLowerCase();if(!domains.some(d=>host===d.toLowerCase()||host.endsWith(`.${d.toLowerCase()}`)))throw new Error(`source authority mismatch: ${host} is not an approved authority domain`);return u;}
function nk(v:string){return clean(v).replace(/^\uFEFF/,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function scanRows(text:string,onRow:(get:(name:string)=>string)=>void){let header:string[]|null=null,index:Record<string,number>={},row:string[]=[],field="",quoted=false,rows=0;const push=()=>{row.push(field);field="";if(!header){header=row.map(x=>clean(x).replace(/^\uFEFF/,""));index=Object.fromEntries(header.map((h,i)=>[nk(h),i]));row=[];return;}if(!row.some(x=>clean(x))){row=[];return;}rows++;const current=row,get=(name:string)=>clean(current[index[nk(name)]]);onRow(get);row=[];};for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++;}else quoted=false;}else field+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(field);field="";}else if(c==='\n')push();else if(c!=='\r')field+=c;}if(field.length||row.length)push();return{columns:header||[],rows};}
function activeCourseCount(text:string){let active=0,expired=0;const scan=scanRows(text,get=>{const ex=get("Expired"),isActive=!ex||/^(no|false|n|0)$/i.test(ex);if(isActive)active++;else expired++;});if(!scan.columns.some(x=>nk(x)==="cricos course code"))throw new Error("CRICOS Courses payload does not contain expected identity column");if(!active)throw new Error("CRICOS active course count is zero");return{active,expired,total:scan.rows};}
function archiveCourse(zip:Record<string,Uint8Array>){const e=Object.entries(zip).find(([name])=>{const n=name.toLowerCase().replace(/[_-]+/g," ");return/courses.*\.csv$/.test(n)&&!/course locations/.test(n)});if(!e)throw new Error("CRICOS archive missing Courses.csv");return{name:e[0],bytes:e[1]};}
function parseNzProviders(html:string,type:string){const out:{providerId:string,type:string}[]=[];for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const pm=m[1].match(/href=["']\/providers\/details\.do\?providerId=([0-9]+)["']/i);if(pm)out.push({providerId:pm[1],type});}return out;}
async function authenticate(req:Request,service:any,url:string,anon:string){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw new Error("authentication required");const user=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const r=await user.auth.getUser(token);if(r.error||!r.data.user)throw new Error("invalid user session");return{token,user,userId:r.data.user.id};}
async function requireOperator(service:any,userId:string){if(!await rpc(service,"svc_layer1_authorize_operator",{p_user_id:userId}))throw new Error("pipeline_operator required");}
async function requirePlatformAdmin(service:any,userId:string){if(!await rpc(service,"svc_layer1_authorize_platform_admin",{p_user_id:userId}))throw new Error("platform_admin required");}
async function sourceContext(service:any,sourceId:string){const x=await rpc(service,"svc_layer1_operation_context",{p_source_id:sourceId});if(!x?.source||!x?.profile)throw new Error("Layer 1 source operations profile missing");return x;}async function invokeStatWorker(url:string,serviceKey:string,worker:string,payload:any){const r=await fetch(`${url}/functions/v1/${worker}`,{method:"POST",headers:{authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"x-cf-layer1-service-key":serviceKey,"content-type":"application/json"},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok||body?.error||body?.ok===false)throw new Error(body?.error||`${worker} HTTP ${r.status}`);return body;}
function qiltSurvey(meta:any){const code=String(meta?.survey_code||"").toLowerCase();return code==="qilt_gosl"?"gosl":code==="qilt_ses"?"ses":code==="qilt_ess"?"ess":"gos";}
// v1.8.0 (CF-247): Canadian catalogue and register readers on Layer 1. Each source names its reader in
// metadata.layer1_reader {function, payload, auth: "nonce" | "service_key", paging?: "offset", batch?}. A reader is
// called with a one-time run token (or the service key), in dry run to verify (count + content hash) and in apply to run.
async function invokeReader(service:any,url:string,serviceKey:string,cfg:any,extra:any){const fn=String(cfg?.function||"");if(!/^layer1-ca-[a-z0-9-]+$/.test(fn))throw new Error(`no Canadian reader configured (${fn||"none"})`);const headers:Record<string,string>={authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"content-type":"application/json"};if(cfg.auth==="service_key")headers["x-cf-layer1-service-key"]=serviceKey;else headers["x-cf-run-nonce"]=String(await rpc(service,"svc_pilot_issue_nonce",{p_function:fn}));const r=await fetch(`${url}/functions/v1/${fn}`,{method:"POST",headers,body:JSON.stringify({...(cfg.payload||{}),...extra})});const body=await r.json().catch(()=>({}));if(!r.ok||body?.error||body?.ok===false)throw new Error(String(body?.error||`${fn} HTTP ${r.status}`));return body;}
const readerCount=(b:any)=>Number(b?.parsedRecords??b?.currentFullTime??b?.totalRecords??b?.selectedRecords??0);
function registerFeed(code:string){return code==="au_study_australia"?"study_australia_register":code==="au_dfat_australia_awards"?"australia_awards":code==="nz_mfat_manaaki"?"nz_manaaki":null;}
async function validateScholarshipRegister(service:any,url:string,serviceKey:string,sourceId:string,source:any,country:string){const code=String(source.metadata?.register_code||""),feed=registerFeed(code);if(!feed)throw new Error(`no reader for scholarship register ${code||"(none)"}`);const body=await invokeStatWorker(url,serviceKey,"scholarships-au-etl",{feed,mode:"dry_run"}),expected=Number(body.candidateObservations??0),hash=String(body.sourceHash||"");if(!expected||!hash)throw new Error("scholarship register dry-run did not return a count and hash");const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:true,p_expected_count:expected,p_source_hash:hash,p_message:`Scholarship register ${code} verified. Listings=${expected}${body.totalShown?`; shown on the site=${body.totalShown}; pages=${body.pages}; providers=${body.providers}`:""}.`});return{...v,country_code:country,source_system:"SCHOLARSHIP_REGISTER",register_code:code,source_url:source.url,source_hash:hash,count_basis:feed==="study_australia_register"?"Study Australia scholarship listings (unique listing IDs)":feed==="nz_manaaki"?"Manaaki New Zealand government award schemes":"DFAT government award schemes",discovered:{listings:expected,total_shown:body.totalShown??null,pages:body.pages??null,providers:body.providers??null},worker_version:VERSION,source_worker_version:body.workerVersion};}
async function validateSource(service:any,url:string,serviceKey:string,sourceId:string,editionYearOverride?:number){const ctx=await sourceContext(service,sourceId),source=ctx.source,profile=ctx.profile,domains=(profile.authority_domains||[]).map((x:any)=>String(x).toLowerCase());hostAllowed(source.url,domains);const country=String(ctx.country_code||"").toUpperCase(),system=String(source.metadata?.source_system||source.metadata?.publisher||"").toUpperCase();
 if(system==="SCHOLARSHIP_REGISTER")return validateScholarshipRegister(service,url,serviceKey,sourceId,source,country);
 if(system==="CA_READER"){const cfg=source.metadata?.layer1_reader,body=await invokeReader(service,url,serviceKey,cfg,{apply:false}),expected=readerCount(body),hash=String(body.evidenceHash||"");if(!expected||!hash)throw new Error(`${cfg?.function} dry run did not return a record count and content hash`);const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:true,p_expected_count:expected,p_source_hash:hash,p_message:`Canadian reader ${cfg.function} verified. Records=${expected}.`});return{...v,country_code:country,source_system:"CA_READER",source_url:source.url,source_hash:hash,count_basis:"records parsed by the source's Layer 1 reader",discovered:{records:expected,reader:cfg.function,reader_version:body.workerVersion},worker_version:VERSION,source_worker_version:body.workerVersion};}
 if(system==="QILT"){const survey=qiltSurvey(source.metadata);const body=await invokeStatWorker(url,serviceKey,"qilt-au-etl",{survey,mode:"dry_run"}),expected=Number(body.candidateObservations??body.parsedMetricCells??0),hash=String(body.workbookSha256||body.zipSha256||"");if(!expected||!hash)throw new Error("QILT dry-run did not return governed observation count/hash");const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:true,p_expected_count:expected,p_source_hash:hash,p_message:`QILT ${survey.toUpperCase()} authority/workbook/parser verified. Candidate observations=${expected}; mapped institutions=${body.exactUniqueCricosMappings??"—"}.`});return{...v,country_code:country,source_system:"QILT",source_url:source.url,source_hash:hash,count_basis:"QILT candidate statistical observations",discovered:{candidate_observations:expected,parsed_metric_cells:body.parsedMetricCells,provider_mappings:body.exactUniqueCricosMappings,collection_version:body.collectionVersion},worker_version:VERSION,source_worker_version:body.workerVersion};}
 if(system==="PRISMS"){const body=await invokeStatWorker(url,serviceKey,"prisms-au-etl",{mode:"dry_run"}),expected=Number(body.candidateObservations??0),hash=String(body.workbookSha256||"");if(!expected||!hash)throw new Error("PRISMS dry-run did not return governed observation count/hash");const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:true,p_expected_count:expected,p_source_hash:hash,p_message:`PRISMS authority/workbook/parser verified. Candidate observations=${expected}; period=${body.collectionVersion||"current"}.`});return{...v,country_code:country,source_system:"PRISMS",source_url:source.url,source_hash:hash,count_basis:"PRISMS candidate statistical observations",discovered:{candidate_observations:expected,parsed_rows:body.parsedRows,collection_version:body.collectionVersion,period_end:body.periodEnd},worker_version:VERSION,source_worker_version:body.workerVersion};}
 if(system==="QS"||system==="THE"){const systemCode=String(source.metadata?.ranking_system_code||"").toLowerCase(),editionYear=Number(editionYearOverride||source.metadata?.edition_year);if(!systemCode||!editionYear)throw new Error("ranking source metadata missing system/edition");const body=await invokeStatWorker(url,serviceKey,"ranking-layer1-etl",{system_code:systemCode,edition_year:editionYear,source_id:sourceId,mode:"dry_run"}),expected=Number(body.candidateObservations??0),hash=String(body.sourceHash||"");if(!expected||!hash)throw new Error(`${system} ${editionYear} dry-run did not return governed observation count/hash`);const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:true,p_expected_count:expected,p_source_hash:hash,p_message:`${system} ${editionYear} publisher artifact/parser verified. Candidate ranking observations=${expected}; unknown rank semantics=${body.unknownRankSemantics??0}.`});return{...v,country_code:"GLOBAL",source_system:system,source_url:source.url,source_hash:hash,count_basis:`${system} ${editionYear} ranking observations`,discovered:{candidate_observations:expected,edition_year:editionYear,evidence_artifact_id:body.evidenceArtifactId,filename:body.filename,unknown_rank_semantics:body.unknownRankSemantics,reconciliation_preview:body.reconciliationPreview||null},worker_version:VERSION,source_worker_version:body.workerVersion};}
 if(country==="AU"){
 const discovery=source.metadata?.discovery_url||"https://data.gov.au/data/api/3/action/package_show?id=cricos";hostAllowed(discovery,domains);const pkg=await(await fetchT(discovery,30000)).json();if(!pkg?.success||!Array.isArray(pkg?.result?.resources))throw new Error("CRICOS CKAN package response malformed");const resources=pkg.result.resources;const required=["CRICOS Institutions.csv","CRICOS Courses.csv","CRICOS Locations.csv","CRICOS Course Locations.csv"];for(const name of required)if(!resources.some((r:any)=>clean(r.name).toLowerCase()===name.toLowerCase()))throw new Error(`CRICOS required resource missing: ${name}`);
 const zipResource=resources.find((r:any)=>String(r.format||"").toUpperCase()==="ZIP"&&/Providers,? Courses,? (and )?Locations/i.test(String(r.name||"")))||resources.find((r:any)=>String(r.format||"").toUpperCase()==="ZIP"&&/CRICOS/i.test(String(r.name||"")));if(!zipResource?.url)throw new Error("CRICOS consolidated archive missing");hostAllowed(zipResource.url,domains);const zipBytes=new Uint8Array(await(await fetchT(zipResource.url,90000)).arrayBuffer());const course=archiveCourse(unzipSync(zipBytes));const counts=activeCourseCount(new TextDecoder().decode(course.bytes));const hash=await sha(course.bytes);const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:true,p_expected_count:counts.active,p_source_hash:hash,p_message:`Authority, package shape and CRICOS Courses payload verified. Active=${counts.active}; expired=${counts.expired}; rows=${counts.total}.`});return{...v,country_code:"AU",source_url:source.url,source_hash:hash,count_basis:"active CRICOS course rows (Expired=false)",discovered:{active:counts.active,expired:counts.expired,total:counts.total},worker_version:VERSION};
 }
 if(country==="NZ"){
 const base="https://www.nzqa.govt.nz";hostAllowed(base,domains);const pages=await Promise.all(TYPES.map(async type=>{const endpoint=`${base}/providers/results.do?regionCode=0&typeCode=${type}&category=&copApprovalStatus=&nameQuery=`;hostAllowed(endpoint,domains);const r=await fetchT(endpoint,60000);const html=await r.text();return{type,url:r.url,html};}));const providers=new Map<string,string>();for(const p of pages)for(const row of parseNzProviders(p.html,p.type))if(!providers.has(row.providerId))providers.set(row.providerId,row.type);if(!providers.size)throw new Error("NZQA tertiary provider register returned zero providers");const bytes=new TextEncoder().encode(JSON.stringify(pages.map(p=>({type:p.type,url:p.url,html:p.html}))));const hash=await sha(bytes);const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:true,p_expected_count:providers.size,p_source_hash:hash,p_message:`Authority and NZQA tertiary listing pages verified. Providers=${providers.size}; pages=${pages.length}.`});return{...v,country_code:"NZ",source_url:source.url,source_hash:hash,count_basis:"unique provider IDs across NZQA UNI/POLLY/WANA/PTE/GTE listings",discovered:{providers:providers.size,pages:pages.length,providers_by_type:Object.fromEntries(TYPES.map(t=>[t,[...providers.values()].filter(x=>x===t).length]))},worker_version:VERSION};
 }
 throw new Error(`M2.4.1 governed validation is limited to AU/NZ; got ${country}`);
}
async function markFailure(service:any,runId:string,error:unknown){const message=error instanceof Error?error.message:String(error);try{await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"failed",p_stage:"failed",p_error:message,p_failed:1})}catch{}return message;}
function reconciliation(body:any){const r=body?.reconciliation||{};return{created:Number(r.created??r.course_created??r.provider_created??0),updated:Number(r.updated??r.course_updated??0),unchanged:Number(r.unchanged??r.course_unchanged??r.course_existing??0),rejected:Number(r.rejected??0),conflicted:Number(r.conflicts??r.conflicted??0),failed:Number(r.failed??0)};}
const TRANSIENT=/HTTP (5\d\d|429)\b|timed? ?out|aborted|network|connection (reset|closed|refused)|ECONNRESET|fetch failed|temporarily|unavailable|worker (limit|resource)/i;
const RETRY_MINUTES=[1,2,4,8,15];
function batchPlan(country:string){return country==="NZ"?{size:20,unit:"providers",worker:"layer1-nz-live"}:{size:500,unit:"courses",worker:"layer1-au-depth"};}
async function scheduleRetry(service:any,runId:string,q:any,message:string){const prior=Number(q?.retry_attempt||0),attempt=prior+1;if(attempt>RETRY_MINUTES.length)return false;const next=new Date(Date.now()+RETRY_MINUTES[attempt-1]*60000).toISOString();await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"running",p_stage:"retry_waiting",p_result:{retry:{attempt,max:RETRY_MINUTES.length,next_at:next,last_error:message.slice(0,500),at:new Date().toISOString()},workerVersion:VERSION}});return true;}
async function processRun(service:any,url:string,serviceKey:string,_token:string,runId:string){let claimed=false,q:any=null;try{q=await rpc(service,"svc_layer1_queue_context",{p_run_id:runId});if(!q||!["queued","running"].includes(q.status))return;claimed=await rpc(service,"svc_layer1_run_claim",{p_run_id:runId,p_seconds:300});if(!claimed)return;if(q.mode==="apply"&&q.source_hash&&q.previous_accepted_hash&&q.source_hash===q.previous_accepted_hash){await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"no_change",p_stage:"source_unchanged",p_processed:0,p_unchanged:q.expected_count??0,p_source_hash:q.source_hash,p_result:{message:"Validated source hash matches the last accepted source version; downstream ingestion skipped.",workerVersion:VERSION}});return;}
 const firstPickup=q.status==="queued";await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"running",p_stage:q.resume_cursor>0?"resuming_ingestion":"starting_ingestion",p_processed:Number(q.resume_cursor||0),p_resume_cursor:q.resume_cursor,p_result:firstPickup?{start_cursor:Number(q.resume_cursor||0),started_by:_token===serviceKey?"background":"operator",workerVersion:VERSION}:{workerVersion:VERSION}});const ctx=await sourceContext(service,q.source_id),system=String(ctx.source?.metadata?.source_system||ctx.source?.metadata?.publisher||"").toUpperCase(),country=String(q.country_code).trim().toUpperCase(),apply=q.mode==="apply";
 if(system==="CA_READER"){const cfg=ctx.source?.metadata?.layer1_reader||{};
  if(cfg.paging!=="offset"){const body=await invokeReader(service,url,serviceKey,cfg,{apply}),rc=reconciliation(body),seen=readerCount(body);await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"completed",p_stage:apply?"reader_records_applied":"reader_validation_completed",p_processed:seen,p_created:rc.created,p_updated:rc.updated,p_unchanged:apply?rc.unchanged:seen,p_rejected:rc.rejected,p_conflicted:rc.conflicted,p_failed:rc.failed,p_actual_job_id:body.jobId||null,p_result:{source_system:system,reader:cfg.function,body:{...body,selectedProviders:undefined,rows:undefined},workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:seen});return;}
  const cursor=Number(q.resume_cursor||0),size=Math.max(1,Math.min(Number(cfg.batch||200),500)),batchStarted=Date.now();await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"running",p_stage:"batch_running",p_result:{live:{unit:"records",cursor_from:cursor,batch_size:size,batch_started_at:new Date(batchStarted).toISOString(),total:q.expected_count??null}}});
  const body=await invokeReader(service,url,serviceKey,cfg,{apply,offset:cursor,batchSize:size}),rc=reconciliation(body),next=Number(body.nextOffset??cursor+size),hasMore=apply&&body.hasMore===true,total=readerCount(body);
  await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:hasMore?"running":"completed",p_stage:hasMore?"batch_completed_resume_pending":(apply?"reconciled":"reader_validation_completed"),p_processed:Math.min(next,total||next),p_created:rc.created,p_updated:rc.updated,p_unchanged:rc.unchanged,p_rejected:rc.rejected,p_conflicted:rc.conflicted,p_failed:rc.failed,p_actual_job_id:body.jobId||null,p_result:{reader:cfg.function,last_batch:{...body,selectedProviders:undefined},retry:null,live:{unit:"records",cursor_from:cursor,cursor_to:next,total,batch_size:size,batch_ms:Date.now()-batchStarted,batch_finished_at:new Date().toISOString()},workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:next});
  await rpc(service,"svc_layer1_run_release",{p_run_id:runId});claimed=false;
  if(hasMore){const continuation=fetch(`${url}/functions/v1/${FN}`,{method:"POST",headers:{authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"content-type":"application/json"},body:JSON.stringify({action:"continue",run_id:runId})});EdgeRuntime.waitUntil(continuation.then(async rr=>{if(!rr.ok)console.error("continuation HTTP",rr.status,await rr.text())}).catch(console.error));}
  return;}
 if(system==="SCHOLARSHIP_REGISTER"){const code=String(ctx.source?.metadata?.register_code||""),feed=registerFeed(code),worker="scholarships-au-etl";if(!feed)throw new Error(`no reader for scholarship register ${code||"(none)"}`);
  if(feed==="australia_awards"||feed==="nz_manaaki"||!apply){const body=await invokeStatWorker(url,serviceKey,worker,{feed,mode:apply?"apply":"dry_run",source_id:q.source_id}),seen=Number(body.candidateObservations??body.candidateScholarships??0);await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"completed",p_stage:apply?"register_records_applied":"register_validation_completed",p_processed:seen,p_created:0,p_updated:apply?seen:0,p_unchanged:apply?0:seen,p_rejected:0,p_conflicted:0,p_failed:0,p_actual_job_id:null,p_result:{source_system:system,register:code,worker,body:{...body,sample:undefined,results:undefined},workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:seen});return;}
  const cursor=Number(q.resume_cursor||0),batchStarted=Date.now();await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"running",p_stage:cursor===0?"register_listing_read":"register_detail_batch",p_result:{live:{unit:cursor===0?"listing pages":"listing details",cursor_from:cursor,batch_started_at:new Date(batchStarted).toISOString(),total:q.expected_count??null}}});
  const body=await invokeStatWorker(url,serviceKey,worker,{feed,mode:"apply",source_id:q.source_id,runId,offset:cursor,batchSize:40}),rc=reconciliation(body),next=Number(body.nextOffset??cursor+1),hasMore=body.hasMore===true,remaining=Number(body.result?.remaining??0),total=Number(body.totalRecords??q.expected_count??0)||0,processed=body.phase==="listing"?0:Math.max(0,total-remaining);
  await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:hasMore?"running":"completed",p_stage:hasMore?"batch_completed_resume_pending":"reconciled",p_processed:processed,p_created:rc.created,p_updated:rc.updated,p_unchanged:rc.unchanged,p_rejected:rc.rejected,p_conflicted:rc.conflicted,p_failed:rc.failed,p_actual_job_id:null,p_result:{register:code,last_batch:{phase:body.phase,result:body.result,workerVersion:body.workerVersion},retry:null,live:{unit:"listing details",cursor_from:cursor,cursor_to:next,total,remaining,batch_ms:Date.now()-batchStarted,batch_finished_at:new Date().toISOString()},workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:next});
  await rpc(service,"svc_layer1_run_release",{p_run_id:runId});claimed=false;
  if(hasMore){const continuation=fetch(`${url}/functions/v1/${FN}`,{method:"POST",headers:{authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"content-type":"application/json"},body:JSON.stringify({action:"continue",run_id:runId})});EdgeRuntime.waitUntil(continuation.then(async rr=>{if(!rr.ok)console.error("continuation HTTP",rr.status,await rr.text())}).catch(console.error));}
  return;}
 if(system==="QS"||system==="THE"){const worker="ranking-layer1-etl",systemCode=String(ctx.source?.metadata?.ranking_system_code||"").toLowerCase(),editionYear=Number(ctx.source?.metadata?.edition_year),body=await invokeStatWorker(url,serviceKey,worker,{system_code:systemCode,edition_year:editionYear,source_id:q.source_id,mode:apply?"apply":"dry_run"}),seen=Number(body.candidateObservations??0),mapped=Number(body.reconciliation?.mapped??0),unmapped=Number(body.reconciliation?.unmapped??0);await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"completed",p_stage:apply?"ranking_observations_reconciled":"ranking_validation_completed",p_processed:seen,p_created:0,p_updated:apply?seen:0,p_unchanged:apply?0:seen,p_rejected:0,p_conflicted:unmapped,p_failed:0,p_actual_job_id:null,p_result:{source_system:system,worker,edition_year:editionYear,body,workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:seen});return;}
 if(system==="QILT"||system==="PRISMS"){const worker=system==="QILT"?"qilt-au-etl":"prisms-au-etl",payload=system==="QILT"?{survey:qiltSurvey(ctx.source.metadata),mode:apply?"apply":"dry_run"}:{mode:apply?"apply":"dry_run"},body=await invokeStatWorker(url,serviceKey,worker,payload),seen=Number(body.observationsSeen??body.candidateObservations??0),changed=Number(body.observationsChanged??0);await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"completed",p_stage:apply?"statistical_observations_reconciled":"statistical_validation_completed",p_processed:seen,p_created:0,p_updated:changed,p_unchanged:Math.max(0,seen-changed),p_rejected:Number(body.unmatchedOrAmbiguous??body.suppressedObservations??0),p_conflicted:0,p_failed:0,p_actual_job_id:null,p_result:{source_system:system,worker,body,workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:seen});return;}
 const plan=batchPlan(country),cursor=Number(q.resume_cursor||0);
 // Decision 155 step 2: an AU run first plans (download once, fingerprint every course) and then applies only new and changed courses.
 if(country==="AU"){const info=await rpc(service,"svc_layer1_plan_slice",{p_run_id:runId,p_offset:0,p_limit:1});if(!info?.exists){await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"running",p_stage:"planning",p_result:{live:{unit:plan.unit,batch_started_at:new Date().toISOString()}}});const pr=await fetch(`${url}/functions/v1/${plan.worker}`,{method:"POST",headers:{authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"content-type":"application/json"},body:JSON.stringify({plan:true,runId,apply})});const pb=await pr.json().catch(()=>({}));if(!pr.ok||pb?.error||pb?.ok===false)throw new Error(String(pb?.error||`${plan.worker} HTTP ${pr.status}`).replace(/^Error:\s*/,""));const pl=pb.plan||{},toApply=Number(pl.to_apply||0),planInfo={register_total:Number(pl.register_total||pb.registerTotal||0),new:Number(pl.new||0),changed:Number(pl.changed||0),unchanged:Number(pl.unchanged||0),departed:Number(pl.departed||0),to_apply:toApply,course_hash:pb.courseHash||null,snapshot_at:pb.courseSnapshotAt||null};const done=!apply||toApply===0,departures=done&&apply?await rpc(service,"svc_layer1_plan_finish",{p_run_id:runId}):null;await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:done?"completed":"running",p_stage:done?(apply?"no_changes_to_apply":"planned_dry_run"):"planned",p_processed:0,p_unchanged:planInfo.unchanged,p_actual_job_id:pb.jobId||null,p_result:{plan:planInfo,departures,live:{unit:plan.unit,total:toApply,cursor_from:0,cursor_to:0,batch_size:plan.size},workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:0});await rpc(service,"svc_layer1_run_release",{p_run_id:runId});claimed=false;if(!done){const continuation=fetch(`${url}/functions/v1/${FN}`,{method:"POST",headers:{authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"content-type":"application/json"},body:JSON.stringify({action:"continue",run_id:runId})});EdgeRuntime.waitUntil(continuation.then(async rr=>{if(!rr.ok)console.error("continuation HTTP",rr.status,await rr.text())}).catch(console.error));}return;}q.expected_count=Number(info.to_apply||0);}
 const payload=country==="NZ"?{apply,offset:cursor,batchSize:plan.size}:{apply,planRunId:runId,offset:cursor,batchSize:plan.size},batchStarted=Date.now();await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:"running",p_stage:"batch_running",p_result:{live:{unit:plan.unit,cursor_from:cursor,batch_size:plan.size,batch_started_at:new Date(batchStarted).toISOString(),total:q.expected_count??null}}});const r=await fetch(`${url}/functions/v1/${plan.worker}`,{method:"POST",headers:{authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"content-type":"application/json"},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok||body?.error||body?.ok===false)throw new Error(String(body?.error||body?.failures?.[0]?.error||`${plan.worker} HTTP ${r.status}`).replace(/^Error:\s*/,""));const rc=reconciliation(body),selected=Number(body.selectedProviders??body.selected??body.totalRecords??body.reconciliation?.records??0),next=Number(body.nextOffset??(cursor+Math.max(selected,0))),hasMore=body.hasMore===true,total=Number(body.totalProviders??body.totalRecords??q.expected_count??0)||0,departures=!hasMore&&apply&&country==="AU"?await rpc(service,"svc_layer1_plan_finish",{p_run_id:runId}):undefined;await rpc(service,"svc_layer1_run_progress",{p_run_id:runId,p_status:hasMore?"running":"completed",p_stage:hasMore?"batch_completed_resume_pending":"reconciled",p_processed:next,p_created:rc.created,p_updated:rc.updated,p_unchanged:rc.unchanged,p_rejected:rc.rejected,p_conflicted:rc.conflicted,p_failed:rc.failed,p_actual_job_id:body.jobId||null,p_result:{last_batch:body,retry:null,...(departures!==undefined?{departures}:{}),live:{unit:plan.unit,cursor_from:cursor,cursor_to:next,total,batch_size:plan.size,batch_ms:Date.now()-batchStarted,batch_finished_at:new Date().toISOString()},workerVersion:VERSION},p_source_hash:q.source_hash,p_resume_cursor:next});await rpc(service,"svc_layer1_run_release",{p_run_id:runId});claimed=false;if(hasMore){const continuation=fetch(`${url}/functions/v1/${FN}`,{method:"POST",headers:{authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"content-type":"application/json"},body:JSON.stringify({action:"continue",run_id:runId})});EdgeRuntime.waitUntil(continuation.then(async rr=>{if(!rr.ok)console.error("continuation HTTP",rr.status,await rr.text())}).catch(console.error));}}
 catch(e){const message=e instanceof Error?e.message:String(e);let retried=false;if(TRANSIENT.test(message)){try{retried=await scheduleRetry(service,runId,q,message);}catch(re){console.error("retry scheduling failed",re);}}if(!retried)await markFailure(service,runId,retried===false&&TRANSIENT.test(message)?`${message} (gave up after ${RETRY_MINUTES.length} automatic retries)`:message);}
 finally{if(claimed){try{await rpc(service,"svc_layer1_run_release",{p_run_id:runId})}catch{}}}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,anon=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;const service=createClient(url,serviceKey,{auth:{persistSession:false}});try{const body=await req.json().catch(()=>({})),action=clean(body.action||"status").toLowerCase();
 const bearer=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,""),nonce=clean(req.headers.get("x-cf-run-nonce"));
 if(nonce||bearer===serviceKey){if(action!=="continue")throw new Error("internal callers may only continue a run");if(nonce&&!await rpc(service,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce}))throw new Error("invalid, expired or already-used run nonce");const runId=clean(body.run_id);if(!runId)throw new Error("run_id required");EdgeRuntime.waitUntil(processRun(service,url,serviceKey,serviceKey,runId));return json({ok:true,run_id:runId,status:"continuation_accepted",caller:nonce?"driver":"chain",workerVersion:VERSION},202);}
 const auth=await authenticate(req,service,url,anon);
 // Decision 134: apply a statistics edition that the discovery job found and checked (Pipeline Operator).
 if(action==="apply_edition"){await requireOperator(service,auth.userId);const id=Number(body.candidate_id);if(!Number.isInteger(id))throw new Error("candidate_id required");const cand=await rpc(service,"svc_statistics_candidate_context",{p_candidate_id:id});if(!cand?.id)throw new Error("edition candidate not found");if(cand.status!=="checked")throw new Error("only a checked edition can be applied");const payload:any={mode:"apply",url:cand.file_url};if(cand.worker_member)payload.survey=cand.worker_member;if(cand.edition_year)payload.year=cand.edition_year;const out=await invokeStatWorker(url,serviceKey,cand.worker,payload);await rpc(service,"svc_statistics_candidate_applied",{p_candidate_id:id,p_actor:auth.userId,p_result:{sourceId:out.sourceId||out.source_id||null,candidateObservations:out.candidateObservations??out.parsedMetricCells??null,collectionVersion:out.collectionVersion??null,workerVersion:out.workerVersion??null}});return json({ok:true,action,candidate_id:id,source_id:out.sourceId||null,workerVersion:VERSION});}
 if(action==="validate"){await requireOperator(service,auth.userId);const sourceId=clean(body.source_id);if(!sourceId)throw new Error("source_id required");const editionOverride=Number(body.edition_year)||undefined,ctx=await sourceContext(service,sourceId),system=String(ctx.source?.metadata?.source_system||ctx.source?.metadata?.publisher||"").toUpperCase();let jobId:string|null=null;if(system==="QS"||system==="THE"){const systemCode=String(ctx.source?.metadata?.ranking_system_code||"").toLowerCase(),editionYear=Number(editionOverride||ctx.source?.metadata?.edition_year);const {data:j,error:je}=await service.rpc("svc_ranking_job_start",{p_job_type:"ranking_import_validate",p_source_id:sourceId,p_requested_by:auth.userId,p_payload:{system_code:systemCode,edition_year:editionYear,source_id:sourceId,origin:"layer1_source_settings"}});if(je)throw new Error(je.message||"ranking job create failed");jobId=j;}try{const validation=await validateSource(service,url,serviceKey,sourceId,editionOverride);if(jobId){const {error:fe}=await service.rpc("svc_ranking_job_finish",{p_job_id:jobId,p_status:"completed",p_result:{validation,workerVersion:VERSION},p_error_text:null});if(fe)throw new Error(fe.message||"ranking job completion failed")}return json({ok:true,validation,job_id:jobId,workerVersion:VERSION});}catch(e){const message=e instanceof Error?e.message:String(e);if(jobId)await service.rpc("svc_ranking_job_finish",{p_job_id:jobId,p_status:"failed",p_result:{},p_error_text:message});throw new Error(message);}}
 await requirePlatformAdmin(service,auth.userId);
 if(action==="run"){const sourceId=clean(body.source_id);if(!sourceId)throw new Error("source_id required");const mode=clean(body.mode||"dry_run").toLowerCase();const validation=await validateSource(service,url,serviceKey,sourceId,Number(body.edition_year)||undefined);if(validation.variance_decision==="block")return json({ok:false,error:"source variance is blocked",validation},409);const {data,error}=await auth.user.rpc("layer1_admin_command",{p_operation:"queue_run",p_args:{source_id:sourceId,mode,reason:clean(body.reason||"M2.4.1 governed Layer 1 operation"),resume_cursor:Number(body.offset||0),acknowledge_warning:body.acknowledge_warning===true,idempotency_key:body.idempotency_key||null,retry_of_run_id:body.retry_of_run_id||null}});if(error)throw error;const runId=data?.run_id;if(!runId)throw new Error("queue command did not return run_id");EdgeRuntime.waitUntil(processRun(service,url,serviceKey,auth.token,runId));return json({ok:true,run_id:runId,status:"queued",validation,workerVersion:VERSION},202);}
 if(action==="continue"){const runId=clean(body.run_id);if(!runId)throw new Error("run_id required");EdgeRuntime.waitUntil(processRun(service,url,serviceKey,auth.token,runId));return json({ok:true,run_id:runId,status:"continuation_accepted",workerVersion:VERSION},202);}
 throw new Error("unsupported action");}catch(e){const message=e instanceof Error?e.message:String(e);const denied=/required|invalid user|operator/i.test(message),qualifiedBlock=/cloudflare|challenge|publisher file required|approved access route|requires.*file/i.test(message);return json({ok:false,error:message,workerVersion:VERSION},denied?403:qualifiedBlock?409:500);}});
