import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { unzipSync } from "npm:fflate@0.8.2";

const VERSION="layer1-operations-scheduled-v1.1.0";
const FN="layer1-operations-scheduled";
const TYPES=["UNI","POLLY","WANA","PTE","GTE"];
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown)=>String(v??"").trim();
async function rpc(c:any,n:string,a:Record<string,unknown>={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function sha(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function fetchT(url:string,ms=90000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(url,{signal:ctl.signal,redirect:"follow",headers:{"user-agent":"coursefinder-layer1-scheduled/1.0","accept":"*/*"}});if(!r.ok)throw new Error(`HTTP ${r.status} from ${new URL(url).hostname}`);return r;}finally{clearTimeout(timer);}}
function hostAllowed(raw:string,domains:string[]){let u:URL;try{u=new URL(raw)}catch{throw new Error("source URL is malformed")}if(u.protocol!=="https:")throw new Error("regulatory source must use HTTPS");const host=u.hostname.toLowerCase();if(!domains.some(d=>host===d.toLowerCase()||host.endsWith(`.${d.toLowerCase()}`)))throw new Error(`source authority mismatch: ${host} is not an approved authority domain`);return u;}
function nk(v:string){return clean(v).replace(/^\uFEFF/,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function scanRows(text:string,onRow:(get:(name:string)=>string)=>void){let header:string[]|null=null,index:Record<string,number>={},row:string[]=[],field="",quoted=false,rows=0;const push=()=>{row.push(field);field="";if(!header){header=row.map(x=>clean(x).replace(/^\uFEFF/,""));index=Object.fromEntries(header.map((h,i)=>[nk(h),i]));row=[];return;}if(!row.some(x=>clean(x))){row=[];return;}rows++;const current=row,get=(name:string)=>clean(current[index[nk(name)]]);onRow(get);row=[];};for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++;}else quoted=false;}else field+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(field);field="";}else if(c==='\n')push();else if(c!=='\r')field+=c;}if(field.length||row.length)push();return{columns:header||[],rows};}
function activeCourseCount(text:string){let active=0,expired=0;const scan=scanRows(text,get=>{const ex=get("Expired"),isActive=!ex||/^(no|false|n|0)$/i.test(ex);if(isActive)active++;else expired++;});if(!scan.columns.some(x=>nk(x)==="cricos course code"))throw new Error("CRICOS Courses payload does not contain expected identity column");if(!active)throw new Error("CRICOS active course count is zero");return{active,expired,total:scan.rows};}
function archiveCourse(zip:Record<string,Uint8Array>){const e=Object.entries(zip).find(([name])=>{const n=name.toLowerCase().replace(/[_-]+/g," ");return/courses.*\.csv$/.test(n)&&!/course locations/.test(n)});if(!e)throw new Error("CRICOS archive missing Courses.csv");return{name:e[0],bytes:e[1]};}
function parseNzProviders(html:string,type:string){const out:{providerId:string,type:string}[]=[];for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const pm=m[1].match(/href=["']\/providers\/details\.do\?providerId=([0-9]+)["']/i);if(pm)out.push({providerId:pm[1],type});}return out;}
async function validate(service:any,ctx:any,url:string,serviceKey:string){const source=ctx.source,profile=ctx.profile,domains=(profile.authority_domains||[]).map((x:any)=>String(x).toLowerCase());hostAllowed(source.url,domains);const country=String(ctx.country_code||"").toUpperCase(),system=String(source.metadata?.source_system||source.metadata?.publisher||"").toUpperCase();
 if(system==="QILT"){const survey=qiltSurvey(source.metadata),body=await invokeStatWorker(url,serviceKey,"qilt-au-etl",{survey,mode:"dry_run"}),expected=Number(body.candidateObservations??body.parsedMetricCells??0),hash=String(body.workbookSha256||body.zipSha256||"");if(!expected||!hash)throw new Error("QILT scheduled validation did not return governed observation count/hash");const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:ctx.source_id,p_success:true,p_expected_count:expected,p_source_hash:hash,p_message:`Scheduled QILT ${survey.toUpperCase()} validation passed. Candidate observations=${expected}.`});return{...v,country_code:country,source_system:"QILT",source_hash:hash,discovered:{candidate_observations:expected,collection_version:body.collectionVersion}};}
 if(system==="PRISMS"){const body=await invokeStatWorker(url,serviceKey,"prisms-au-etl",{mode:"dry_run"}),expected=Number(body.candidateObservations??0),hash=String(body.workbookSha256||"");if(!expected||!hash)throw new Error("PRISMS scheduled validation did not return governed observation count/hash");const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:ctx.source_id,p_success:true,p_expected_count:expected,p_source_hash:hash,p_message:`Scheduled PRISMS validation passed. Candidate observations=${expected}; period=${body.collectionVersion||"current"}.`});return{...v,country_code:country,source_system:"PRISMS",source_hash:hash,discovered:{candidate_observations:expected,collection_version:body.collectionVersion}};}
 if(country==="AU"){
 const discovery=source.metadata?.discovery_url||"https://data.gov.au/data/api/3/action/package_show?id=cricos";hostAllowed(discovery,domains);const pkg=await(await fetchT(discovery,30000)).json();if(!pkg?.success||!Array.isArray(pkg?.result?.resources))throw new Error("CRICOS CKAN package response malformed");const resources=pkg.result.resources;for(const name of ["CRICOS Institutions.csv","CRICOS Courses.csv","CRICOS Locations.csv","CRICOS Course Locations.csv"])if(!resources.some((r:any)=>clean(r.name).toLowerCase()===name.toLowerCase()))throw new Error(`CRICOS required resource missing: ${name}`);const z=resources.find((r:any)=>String(r.format||"").toUpperCase()==="ZIP"&&/Providers,? Courses,? (and )?Locations/i.test(String(r.name||"")))||resources.find((r:any)=>String(r.format||"").toUpperCase()==="ZIP"&&/CRICOS/i.test(String(r.name||"")));if(!z?.url)throw new Error("CRICOS consolidated archive missing");hostAllowed(z.url,domains);const bytes=new Uint8Array(await(await fetchT(z.url,90000)).arrayBuffer()),course=archiveCourse(unzipSync(bytes)),counts=activeCourseCount(new TextDecoder().decode(course.bytes)),hash=await sha(course.bytes);const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:ctx.source_id,p_success:true,p_expected_count:counts.active,p_source_hash:hash,p_message:`Scheduled authority/package verification passed. Active=${counts.active}; expired=${counts.expired}; rows=${counts.total}.`});return{...v,country_code:"AU",source_hash:hash,discovered:{active:counts.active,expired:counts.expired,total:counts.total}};
 }
 if(country==="NZ"){
 const base="https://www.nzqa.govt.nz";hostAllowed(base,domains);const pages=await Promise.all(TYPES.map(async type=>{const endpoint=`${base}/providers/results.do?regionCode=0&typeCode=${type}&category=&copApprovalStatus=&nameQuery=`;hostAllowed(endpoint,domains);const r=await fetchT(endpoint,60000);return{type,url:r.url,html:await r.text()};}));const providers=new Map<string,string>();for(const p of pages)for(const row of parseNzProviders(p.html,p.type))if(!providers.has(row.providerId))providers.set(row.providerId,row.type);if(!providers.size)throw new Error("NZQA tertiary provider register returned zero providers");const bytes=new TextEncoder().encode(JSON.stringify(pages.map(p=>({type:p.type,url:p.url,html:p.html})))),hash=await sha(bytes);const v=await rpc(service,"svc_layer1_record_validation",{p_source_id:ctx.source_id,p_success:true,p_expected_count:providers.size,p_source_hash:hash,p_message:`Scheduled authority verification passed. Providers=${providers.size}; pages=${pages.length}.`});return{...v,country_code:"NZ",source_hash:hash,discovered:{providers:providers.size,pages:pages.length}};
 }
 throw new Error(`scheduled Layer 1 verification limited to AU/NZ; got ${country}`);
}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({ok:false,error:"POST required",workerVersion:VERSION},405);const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,service=createClient(url,serviceKey,{auth:{persistSession:false}});let requestId:string|null=null,sourceId:string|null=null;try{
 const nonce=clean(req.headers.get("x-cf-run-nonce"));if(!nonce)throw new Error("one-time schedule nonce required");const consumed=await rpc(service,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce});if(!consumed)throw new Error("invalid, expired or already-used schedule nonce");const body=await req.json().catch(()=>({}));requestId=clean(body.refresh_request_id);if(!requestId)throw new Error("refresh_request_id required");const ctx=await rpc(service,"svc_layer1_scheduled_context",{p_refresh_request_id:requestId});sourceId=ctx.source_id;const beforeAccepted=clean(ctx.profile?.previous_accepted_hash),result=await validate(service,ctx,url,serviceKey);if(result.variance_decision==="block"){await rpc(service,"svc_layer1_schedule_complete",{p_refresh_request_id:requestId,p_success:false,p_changed:true,p_message:`Scheduled verification blocked by source variance (${result.variance_percent??'unknown'}%).`});return json({ok:false,status:"blocked",validation:result,workerVersion:VERSION},409);}const changed=Boolean(beforeAccepted&&result.source_hash&&beforeAccepted!==result.source_hash);await rpc(service,"svc_layer1_schedule_complete",{p_refresh_request_id:requestId,p_success:true,p_changed:changed,p_message:changed?"Authoritative source changed; operator ingestion review required.":"Authoritative source unchanged."});return json({ok:true,status:changed?"completed_changed":"completed_unchanged",validation:result,workerVersion:VERSION});
 }catch(e){const message=e instanceof Error?e.message:String(e);if(sourceId)try{await rpc(service,"svc_layer1_record_validation",{p_source_id:sourceId,p_success:false,p_expected_count:null,p_source_hash:null,p_message:message})}catch{};if(requestId)try{await rpc(service,"svc_layer1_schedule_complete",{p_refresh_request_id:requestId,p_success:false,p_changed:false,p_message:message})}catch{};return json({ok:false,error:message,workerVersion:VERSION},403);}});
