CREATE OR REPLACE FUNCTION public.layer2_provider_control(p_actor uuid, p_action text, p_payload jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'public', 'security', 'pipeline', 'vault'
AS $function$declare v_rank int:=0;v_id uuid;v_secret_id uuid;v_profile uuid;v_provider uuid;begin
 select coalesce(max(r.rank),0) into v_rank from security.user_roles ur join security.roles r on r.code=ur.role_code where ur.user_id=p_actor and (ur.expires_at is null or ur.expires_at>now()) and r.status='active';
 if p_action in ('create_provider','update_provider','set_secret') and v_rank<6 then raise exception 'platform_admin role required' using errcode='42501'; end if;
 if p_action='upsert_route' and v_rank<5 then raise exception 'pim_admin role required' using errcode='42501'; end if;
 if p_action in ('create_provider','update_provider') and (security.layer2_provider_has_secret_keys(p_payload->'capabilities') or security.layer2_provider_has_secret_keys(p_payload->'request_template') or security.layer2_provider_has_secret_keys(p_payload->'billing_config')) then raise exception 'provider configuration contains secret-like keys; use credential control' using errcode='22023';end if;
 if p_action='upsert_route' and (security.layer2_provider_has_secret_keys(p_payload->'request_overrides') or security.layer2_provider_has_secret_keys(p_payload->'required_capabilities')) then raise exception 'route configuration contains secret-like keys' using errcode='22023';end if;
 if p_action='create_provider' then
   if coalesce(trim(p_payload->>'provider_key'),'')='' or coalesce(trim(p_payload->>'display_name'),'')='' then raise exception 'provider key and display name required' using errcode='22023';end if;
   insert into pipeline.layer2_acquisition_providers(provider_key,display_name,adapter_type,base_url,auth_scheme,auth_field_name,capabilities,request_template,billing_config,enabled,priority,rate_limit_per_minute,concurrency,timeout_seconds,operational_owner,change_control_ref)
   values(trim(p_payload->>'provider_key'),trim(p_payload->>'display_name'),p_payload->>'adapter_type',nullif(trim(p_payload->>'base_url'),''),coalesce(nullif(p_payload->>'auth_scheme',''),'none'),nullif(trim(p_payload->>'auth_field_name'),''),coalesce(p_payload->'capabilities','{}'::jsonb),coalesce(p_payload->'request_template','{}'::jsonb),coalesce(p_payload->'billing_config','{}'::jsonb),coalesce((p_payload->>'enabled')::boolean,true),coalesce((p_payload->>'priority')::int,100),nullif(p_payload->>'rate_limit_per_minute','')::int,coalesce((p_payload->>'concurrency')::int,1),coalesce((p_payload->>'timeout_seconds')::int,30),nullif(trim(p_payload->>'operational_owner'),''),coalesce(nullif(trim(p_payload->>'change_control_ref'),''),'CF-CHG-20260823-029')) returning id into v_id; return jsonb_build_object('ok',true,'id',v_id);
 elsif p_action='update_provider' then
   v_id:=(p_payload->>'id')::uuid; update pipeline.layer2_acquisition_providers set display_name=coalesce(nullif(trim(p_payload->>'display_name'),''),display_name),base_url=case when p_payload?'base_url' then nullif(trim(p_payload->>'base_url'),'') else base_url end,auth_scheme=coalesce(nullif(p_payload->>'auth_scheme',''),auth_scheme),auth_field_name=case when p_payload?'auth_field_name' then nullif(trim(p_payload->>'auth_field_name'),'') else auth_field_name end,capabilities=coalesce(p_payload->'capabilities',capabilities),request_template=coalesce(p_payload->'request_template',request_template),billing_config=coalesce(p_payload->'billing_config',billing_config),enabled=coalesce((p_payload->>'enabled')::boolean,enabled),priority=coalesce((p_payload->>'priority')::int,priority),rate_limit_per_minute=case when p_payload?'rate_limit_per_minute' then nullif(p_payload->>'rate_limit_per_minute','')::int else rate_limit_per_minute end,concurrency=coalesce((p_payload->>'concurrency')::int,concurrency),timeout_seconds=coalesce((p_payload->>'timeout_seconds')::int,timeout_seconds),operational_owner=case when p_payload?'operational_owner' then nullif(trim(p_payload->>'operational_owner'),'') else operational_owner end,updated_at=now() where id=v_id; if not found then raise exception 'provider not found' using errcode='22023';end if;return jsonb_build_object('ok',true,'id',v_id);
 elsif p_action='set_secret' then
   v_id:=(p_payload->>'id')::uuid;if coalesce(p_payload->>'secret','')='' then raise exception 'secret required' using errcode='22023';end if;select vault_secret_id into v_secret_id from pipeline.layer2_acquisition_providers where id=v_id for update;if not found then raise exception 'provider not found' using errcode='22023';end if;if v_secret_id is null then select vault.create_secret(p_payload->>'secret','coursefinder_l2_provider_'||v_id::text,'CourseFinder Layer 2 provider credential',null) into v_secret_id;update pipeline.layer2_acquisition_providers set vault_secret_id=v_secret_id,updated_at=now() where id=v_id;else perform vault.update_secret(v_secret_id,p_payload->>'secret',null,null,null);end if;return jsonb_build_object('ok',true,'id',v_id,'credential_configured',true);
 elsif p_action='upsert_route' then
   v_profile:=(p_payload->>'profile_id')::uuid;v_provider:=(p_payload->>'provider_id')::uuid;
   insert into pipeline.layer2_profile_provider_routes(profile_id,acquisition_provider_id,priority,enabled,required_capabilities,request_overrides,evidence_policy,fallback_on,change_control_ref) values(v_profile,v_provider,coalesce((p_payload->>'priority')::int,100),coalesce((p_payload->>'enabled')::boolean,true),coalesce(p_payload->'required_capabilities','{}'::jsonb),coalesce(p_payload->'request_overrides','{}'::jsonb),coalesce(p_payload->'evidence_policy','{"capture_raw":true,"capture_html":true,"capture_screenshot_on_failure":true}'::jsonb),coalesce(p_payload->'fallback_on','["blocked","timeout","403","429","5xx","extraction_failed"]'::jsonb),coalesce(nullif(trim(p_payload->>'change_control_ref'),''),'CF-CHG-20260823-029')) on conflict(profile_id,acquisition_provider_id) do update set priority=excluded.priority,enabled=excluded.enabled,required_capabilities=excluded.required_capabilities,request_overrides=excluded.request_overrides,evidence_policy=excluded.evidence_policy,fallback_on=excluded.fallback_on,updated_at=now();return jsonb_build_object('ok',true);
 end if;raise exception 'unsupported provider action' using errcode='22023';
end$function$
