import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import * as XLSX from "npm:xlsx@0.18.5";
const VERSION="ranking-the-official-etl-v1.0.0";
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown)=>String(v??"").replace(/^\uFEFF/,"").trim();
const key=(v:unknown)=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const score=(v:unknown)=>{const s=clean(v);if(!s||/^(?:-|—|n\/?a|null)$/i.test(s))return null;const n=Number(s.replace(/,/g,""));return Number.isFinite(n)&&n>=0&&n<=100?n:null};
function parseRank(v:unknown){const display=clean(v).replace(/[–—]/g,"-");const tied=/^=/.test(display);const x=display.replace(/^=/,"").trim();let m=x.match(/^(\d+)\s*-\s*(\d+)$/);if(m)return{rank_display:display,rank_exact:null,rank_low:+m[1],rank_high:+m[2],is_tied:tied,rank_status:"ranked_band"};m=x.match(/^(\d+)\+$/);if(m)return{rank_display:display,rank_exact:null,rank_low:+m[1],rank_high:null,is_tied:tied,rank_status:"ranked_band"};m=x.match(/^(\d+)$/);if(m)return{rank_display:display,rank_exact:+m[1],rank_low:null,rank_high:null,is_tied:tied,rank_status:"ranked_exact"};return{rank_display:display||null,rank_exact:null,rank_low:null,rank_high:null,is_tied:tied,rank_status:display?"unknown":"unranked"}}
function indicator(label:string,value:unknown,rank:unknown,year:number,group:string){const pr=parseRank(rank),s=score(value);return{label,value_display:s===null?null:clean(value),value_numeric:s,unit:"score",methodology_version:String(year),group,...pr}}
const DEFS=[
 ["teaching","Teaching","Teaching"],["research","Research","Research"],["research_environment","Research Environment","Research Environment"],["citations","Citations","Citations"],["research_quality","Research Quality","Research Quality"],["industry_income","Industry Income","Industry Income"],["industry","Industry","Industry"],["international_outlook","International Outlook","International Outlook"]
] as const;
function minRows(year:number){if(year<=2012)return 200;if(year<=2015)return 350;if(year<=2017)return 750;if(year<=2020)return 1200;if(year<=2022)return 1500;if(year<=2024)return 1750;return 1900}
function parseWorkbook(bytes:Uint8Array,year:number){const wb=XLSX.read(bytes,{type:"array",cellDates:false,raw:false});const name=wb.SheetNames.find(n=>/^rankings$/i.test(n))||wb.SheetNames[0];const a=XLSX.utils.sheet_to_json<any[]>(wb.Sheets[name],{header:1,defval:"",raw:false});if(!a.length)throw new Error("THE workbook contains no rows");const title=a.slice(0,4).flat().map(clean).find(x=>/Times Higher Education.*World University Rankings|THE World University Rankings/i.test(x))||"";let hi=-1;for(let i=0;i<Math.min(a.length,8);i++){const h=a[i].map(key);if((h.includes("name")||h.includes("institution"))&&h.includes("rank")&&(h.includes("overall")||h.includes("overall score"))){hi=i;break}}if(hi<0)throw new Error("THE Evidence workbook header row not found");const h=a[hi].map(key),pos=(...xs:string[])=>{for(const x of xs){const i=h.indexOf(key(x));if(i>=0)return i}return-1};const nameI=pos("name","institution"),rankI=pos("rank"),countryI=pos("location","country territory","country"),overallI=pos("overall","overall score");if([nameI,rankI,countryI,overallI].some(i=>i<0))throw new Error("THE Evidence workbook required columns missing");const rows:any[]=[];for(let i=hi+1;i<a.length;i++){const r=a[i],n=clean(r[nameI]);if(!n)continue;const inds:any={};for(const[code,label,group]of DEFS){const aliases=[label+" Score",label],si=pos(...aliases),ri=pos(label+" Rank");if(si>=0||ri>=0)inds[code]=indicator(label,si>=0?r[si]:null,ri>=0?r[ri]:null,year,group)}const src:any={};h.forEach((x,j)=>{if(x&&clean(r[j]))src[x]=r[j]});rows.push({publisher_institution_id:clean(src["publisher id"]||src["nid"]||src["institution id"])||null,institution_name:n,profile_url:clean(src["profile url"]||src["url"])||null,country_text:clean(r[countryI])||null,location_text:clean(r[countryI])||null,...parseRank(r[rankI]),overall_score:score(r[overallI]),overall_score_display:score(r[overallI])===null?null:clean(r[overallI]),overall_score_low:null,overall_score_high:null,source_row_ordinal:rows.length+1,indicators:inds,source_row_payload:{...src,the_evidence_workbook:true}})}if(rows.length<minRows(year))throw new Error(`THE World workbook parsed only ${rows.length} rows; edition ${year} requires at least ${minRows(year)}`);const unknown=rows.filter(r=>r.rank_status==="unknown").length;if(unknown>Math.max(10,Math.floor(rows.length*.02)))throw new Error(`THE workbook has ${unknown} unknown rank semantics`);return{rows,sheetName:name,headerRow:hi+1,title}}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"POST required",workerVersion:VERSION},405);const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;if(!url||!serviceKey)return json({error:"service configuration missing",workerVersion:VERSION},500);if((req.headers.get("x-cf-layer1-service-key")||"")!==serviceKey)return json({error:"service authorization required",workerVersion:VERSION},403);const svc=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});try{const body=await req.json(),year=Number(body.edition_year),mode=clean(body.mode||"dry_run"),importId=clean(body.import_id);if(!Number.isInteger(year)||year<2011||!importId)throw new Error("THE edition_year >= 2011 and import_id required");const{data:imp,error:ie}=await svc.rpc("svc_ranking_import_control_context",{p_import_id:importId});if(ie)throw ie;if(!imp?.id||imp.system_code!=="the_wur"||Number(imp.edition_year)!==year)throw new Error("selected import is not requested THE edition");if(!/\.xlsx$/i.test(String(imp.original_filename||"")))throw new Error("THE URL/file workflow requires XLSX Evidence");const dl=await svc.storage.from("evidence").download(imp.storage_path);if(dl.error||!dl.data)throw new Error(dl.error?.message||"THE Evidence download failed");const parsed=parseWorkbook(new Uint8Array(await dl.data.arrayBuffer()),year),rows=parsed.rows,indicatorCells=rows.reduce((n,r)=>n+Object.keys(r.indicators||{}).length,0);const{data:preview,error:pe}=await svc.rpc("svc_ranking_reconciliation_preview_system",{p_rows:rows,p_country_code:"AU",p_system_code:"the_wur"});if(pe)throw pe;const base={ok:true,mode:mode==="apply"?"apply":"dry_run",systemCode:"the_wur",editionYear:year,acquisitionMode:"the_xlsx_evidence",candidateObservations:rows.length,unknownRankSemantics:rows.filter(r=>r.rank_status==="unknown").length,indicatorCells,sourceHash:imp.content_hash,evidenceArtifactId:imp.evidence_artifact_id,filename:imp.original_filename,sourceUrl:imp.source_url,reconciliationPreview:preview,workbook:{sheet:parsed.sheetName,header_row:parsed.headerRow,title:parsed.title},workerVersion:VERSION};if(mode!=="apply")return json(base);for(let i=0;i<rows.length;i+=200){const{error:e}=await svc.rpc("svc_ranking_ingest_apply",{p_system_code:"the_wur",p_edition_year:year,p_source_url:imp.source_url,p_methodology_url:imp.methodology_url||null,p_source_artifact_id:imp.evidence_artifact_id,p_source_fingerprint:imp.content_hash,p_source_revision:"the_xlsx_evidence_v1",p_rows:rows.slice(i,i+200)});if(e)throw e}const{data:finalized,error:fe}=await svc.rpc("svc_ranking_ingest_finalize",{p_system_code:"the_wur",p_edition_year:year,p_source_artifact_id:imp.evidence_artifact_id});if(fe)throw fe;return json({...base,reconciliation:finalized})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e),workerVersion:VERSION},422)}});
