import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const VERSION="layer1-au-completeness-v0.1.0";
const FN="layer1-au-completeness";
const PKG="https://data.gov.au/data/api/3/action/package_show?id=cricos";
const RPC_CHUNK=250;
const MAX_BATCH=5000;
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-cf-run-nonce","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:any)=>String(v??"").trim();
const nk=(v:any)=>clean(v).replace(/^\uFEFF/,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function parse(t:string){const rows:string[][]=[];let r:string[]=[],f="",q=false;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'){if(t[i+1]==='"'){f+='"';i++;}else q=false;}else f+=c;}else if(c==='"')q=true;else if(c===','){r.push(f);f="";}else if(c==='\n'){r.push(f);rows.push(r);r=[];f="";}else if(c!=='\r')f+=c;}if(f.length||r.length){r.push(f);rows.push(r);}return rows;}
function objs(t:string){const rows=parse(t);if(!rows.length)return[];const h=rows[0].map(nk);return rows.slice(1).filter(r=>r.some(clean)).map(r=>Object.fromEntries(h.map((x,i)=>[x,clean(r[i])])));}
function val(r:any,names:string[]){for(const n of names){const v=r[nk(n)];if(clean(v))return clean(v);}return"";}
function level(raw:string){const s=clean(raw).toLowerCase();if(/doctor|phd/.test(s))return"doctorate";if(/master|m\.sc|m\.a\.|mba|ll\.m/.test(s))return"masters";if(/graduate certificate/.test(s))return"graduate_certificate";if(/graduate diploma/.test(s))return"graduate_diploma";if(/bachelor|b\.sc|b\.a\.|b\.eng/.test(s))return"bachelor";if(/associate/.test(s))return"associate_degree";if(/diploma/.test(s))return"diploma";if(/certificate/.test(s))return"certificate";if(/foundation/.test(s))return"foundation";return"";}
function field(raw:string){const s=clean(raw),m=s.match(/^\s*(\d{4})\b\s*(?:[-–—:]\s*)?(.*)$/);return m?{code:m[1],name:clean(m[2])||s.replace(/^\s*\d{4}\b\s*/,"")}:{code:"",name:s};}
async function rpc(c:any,n:string,a:any={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function fetchT(u:string,ms=90000){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);try{const r=await fetch(u,{signal:ac.signal,redirect:"follow",headers:{"user-agent":"coursefinder-au-completeness/0.1"}});if(!r.ok)throw new Error(`${u} HTTP ${r.status}`);return r;}finally{clearTimeout(tm);}}
async function hash(b:Uint8Array){const d=await crypto.subtle.digest("SHA-256",b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function auth(req:Request,svc:any){const nonce=clean(req.headers.get("x-cf-run-nonce"));if(!nonce)throw new Error("valid one-time Pilot nonce required");if(!await rpc(svc,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce}))throw new Error("valid one-time Pilot nonce required");}
async function ev(svc:any,sourceId:string,jobId:string,url:string,path:string,bytes:Uint8Array,meta:any){const h=await hash(bytes);const up=await svc.storage.from("evidence").upload(path,bytes,{contentType:"text/csv",upsert:true});if(up.error)throw new Error(up.error.message);const id=await rpc(svc,"svc_layer1_record_evidence",{p_source_id:sourceId,p_job_id:jobId,p_source_url:url,p_storage_path:path,p_content_hash:h,p_mime_type:"text/csv",p_metadata:meta});return{id,hash:h};}
async function core(svc:any,sourceId:string,evidenceId:string,rows:any[],apply:boolean){const t:any={records:rows.length,provider_created:0,provider_linked:0,provider_existing:0,course_created:0,course_linked:0,course_existing:0,provider_unmapped_subdivision:0,field_mapped:0,field_unmapped:0,conflicts:0};if(!apply){for(const r of rows){if(r.field_code&&/^\d{4}$/.test(r.field_code)&&r.field_name)t.field_mapped++;else if(r.field_code||r.field_name)t.field_unmapped++;}return t;}for(let i=0;i<rows.length;i+=RPC_CHUNK){const x=await rpc(svc,"svc_layer1_apply_register_records",{p_country_code:"AU",p_source_id:sourceId,p_evidence_id:evidenceId,p_registration_scheme:"cricos",p_records:rows.slice(i,i+RPC_CHUNK)});for(const k of Object.keys(t))if(k!=="records")t[k]+=Number(x?.[k]||0);}return t;}
async function loc(svc:any,sourceId:string,evidenceId:string,rows:any[],apply:boolean){const t:any={location_records:rows.length,campuses_created:0,campuses_existing:0,provider_missing:0,unmapped_subdivision:0,conflicts:0};if(!apply)return t;for(let i=0;i<rows.length;i+=RPC_CHUNK){const x=await rpc(svc,"svc_layer1_apply_location_records",{p_country_code:"AU",p_source_id:sourceId,p_evidence_id:evidenceId,p_registration_scheme:"cricos",p_records:rows.slice(i,i+RPC_CHUNK)});t.campuses_created+=Number(x?.campuses_created||0);t.campuses_existing+=Number(x?.campuses_existing||0);t.provider_missing+=Number(x?.provider_missing||0);t.unmapped_subdivision+=Number(x?.unmapped_subdivision||0);t.conflicts+=Number(x?.conflicts||0);}return t;}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"POST required"},405);const svc=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});let jobId:string|null=null,source:any=null;try{await auth(req,svc);const b=await req.json().catch(()=>({})),apply=b.apply===true,offset=Math.max(0,Number(b.offset??0)),batchSize=Math.max(1,Math.min(Number(b.batchSize??2500),MAX_BATCH));const ss=await rpc(svc,"svc_layer1_resolve_sources",{p_country_code:"AU"});source=(ss||[]).find((x:any)=>x.system_code==="au_cricos")||(ss||[])[0];if(!source)throw new Error("AU source missing");jobId=await rpc(svc,"svc_layer1_start_job",{p_country_code:"AU",p_source_id:source.source_id,p_payload:{apply,offset,batch_size:batchSize,version:VERSION,mode:"direct_csv_completeness"}});const pd=await(await fetchT(source.source_metadata?.discovery_url||PKG,30000)).json(),rs=pd?.result?.resources||[];const pick=(re:RegExp)=>rs.find((x:any)=>String(x.format||"").toUpperCase()==="CSV"&&re.test(String(x.name||"")));const ir=pick(/CRICOS Institutions/i),cr=pick(/CRICOS Courses/i),lr=pick(/CRICOS Locations/i);if(!ir?.url||!cr?.url||!lr?.url)throw new Error("required direct CRICOS CSV resources missing");const [ib,cb,lb]=await Promise.all([fetchT(ir.url),fetchT(cr.url),fetchT(lr.url)]).then(async a=>Promise.all(a.map(async r=>new Uint8Array(await r.arrayBuffer()))));const ih=await hash(ib),ch=await hash(cb),lh=await hash(lb);if(b.expectedHashes&&(b.expectedHashes.institutions!==ih||b.expectedHashes.courses!==ch||b.expectedHashes.locations!==lh))throw new Error("CRICOS source changed since evidence capture");const it=new TextDecoder().decode(ib),ct=new TextDecoder().decode(cb),lt=new TextDecoder().decode(lb);let evidenceIds=b.evidenceIds||null;if(!evidenceIds){const stamp=new Date().toISOString().replace(/[:.]/g,"-");const ie=await ev(svc,source.source_id,jobId,ir.url,`regulatory/AU/cricos/${stamp}-institutions.csv`,ib,{resource_id:ir.id,resource_name:ir.name,last_modified:ir.last_modified,columns:parse(it)[0]||[]});const ce=await ev(svc,source.source_id,jobId,cr.url,`regulatory/AU/cricos/${stamp}-courses.csv`,cb,{resource_id:cr.id,resource_name:cr.name,last_modified:cr.last_modified,columns:parse(ct)[0]||[]});const le=await ev(svc,source.source_id,jobId,lr.url,`regulatory/AU/cricos/${stamp}-locations.csv`,lb,{resource_id:lr.id,resource_name:lr.name,last_modified:lr.last_modified,columns:parse(lt)[0]||[]});evidenceIds={institutions:ie.id,courses:ce.id,locations:le.id};}
const pm=new Map<string,any>();for(const r of objs(it)){const pc=val(r,["CRICOS Provider Code"]),pn=val(r,["Trading Name","Institution Name"]);if(!pc||!pn)continue;let w=val(r,["Website"]);if(w&&!/^https?:\/\//i.test(w))w="https://"+w;pm.set(pc,{name:pn,website:w||null,city:val(r,["Postal Address City","Postal City"])||null,state:val(r,["Postal Address State","Postal State","State"])||null,address_line1:val(r,["Postal Address Line 1","Postal Address 1"])||null,address_line2:[val(r,["Postal Address Line 2","Postal Address 2"]),val(r,["Postal Address Line 3","Postal Address 3"]),val(r,["Postal Address Line 4","Postal Address 4"])].filter(Boolean).join(", ")||null,postcode:val(r,["Postal Address Postcode","Postal Postcode","Postcode"])||null});}
const all:any[]=[];for(const r of objs(ct)){const ex=val(r,["Expired"]);if(ex&&!/^(no|false|n|0)$/i.test(ex))continue;const pc=val(r,["CRICOS Provider Code"]),p=pm.get(pc),cc=val(r,["CRICOS Course Code"]),title=val(r,["Course Name"]);if(!p||!cc||!title)continue;const f=field(val(r,["Field of Education 1 Narrow Field"]));all.push({provider_code:pc,provider_name:p.name,website:p.website,city:p.city,state:p.state,address_line1:p.address_line1,address_line2:p.address_line2,postcode:p.postcode,course_code:cc,course_name:title,course_level:level(val(r,["Course Level"])),duration_weeks:val(r,["Duration (Weeks)"]),field_code:f.code,field_name:f.name});}
const selected=all.slice(offset,offset+batchSize),pcs=new Set(selected.map(x=>x.provider_code)),locations:any[]=[];for(const r of objs(lt)){const pc=val(r,["CRICOS Provider Code"]),name=val(r,["Location Name"]);if(!pc||!name||!pcs.has(pc))continue;locations.push({provider_code:pc,location_code:name,location_name:name,address_line1:val(r,["Address Line 1"]),address_line2:[val(r,["Address Line 2"]),val(r,["Address Line 3"]),val(r,["Address Line 4"])].filter(Boolean).join(", "),city:val(r,["City"]),state:val(r,["State"]),postcode:val(r,["Postcode"])});}const coreResult=await core(svc,source.source_id,evidenceIds.courses,selected,apply),locationResult=await loc(svc,source.source_id,evidenceIds.locations,locations,apply),nextOffset=offset+selected.length,hasMore=nextOffset<all.length;const result={country:"AU",mode:apply?"apply":"dry-run",workerVersion:VERSION,offset,batchSize,totalRecords:all.length,selectedRecords:selected.length,nextOffset,hasMore,selectedLocations:locations.length,providerStateTokens:[...new Set(selected.map(x=>x.state).filter(Boolean))].sort(),locationStateTokens:[...new Set(locations.map(x=>x.state).filter(Boolean))].sort(),reconciliation:coreResult,locationReconciliation:locationResult,evidenceIds,hashes:{institutions:ih,courses:ch,locations:lh},resources:{institutions:{id:ir.id,last_modified:ir.last_modified},courses:{id:cr.id,last_modified:cr.last_modified},locations:{id:lr.id,last_modified:lr.last_modified}}};await rpc(svc,"svc_layer1_finish_job",{p_job_id:jobId,p_status:"completed",p_result:result,p_error:null});return out({ok:true,jobId,...result});}catch(e){const m=e instanceof Error?e.message:String(e);if(jobId)try{await rpc(svc,"svc_layer1_finish_job",{p_job_id:jobId,p_status:"failed",p_result:{workerVersion:VERSION},p_error:m});}catch{}return out({error:m,jobId,workerVersion:VERSION},500);}});