import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

// NZQA tertiary register worker (Layer 1, NZ).
// v1.2.0 (Decision 155): background-run caller accepted (service key), temporary NZQA errors retried,
// unchanged listing snapshot stored once, up to 20 providers per batch fetched 5 at a time,
// catalogue finalised once at the end of the run instead of after every batch.
const VERSION="layer1-nz-live-v1.2.1";
const BASE="https://www.nzqa.govt.nz";
const TYPES=["UNI","POLLY","WANA","PTE","GTE"];
const RPC_CHUNK=250;
const DEFAULT_BATCH=5;
const MAX_BATCH=20;
const CONCURRENCY=5;
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown)=>String(v??"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function mapLevel(t:string){const s=t.toLowerCase();if(/doctor|phd/.test(s))return"doctorate";if(/master/.test(s))return"masters";if(/graduate certificate/.test(s))return"graduate_certificate";if(/graduate diploma/.test(s))return"graduate_diploma";if(/bachelor/.test(s))return"bachelor";if(/associate/.test(s))return"associate_degree";if(/diploma/.test(s))return"diploma";if(/certificate/.test(s))return"certificate";if(/foundation/.test(s))return"foundation";return"";}
async function fetchT(url:string,ms=60000){const c=new AbortController();const timer=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{signal:c.signal,redirect:"follow",headers:{"user-agent":"coursefinder-pilot-nz/1.2","accept":"text/html,application/xhtml+xml"}})}finally{clearTimeout(timer)}}
// Retry temporary NZQA failures (5xx, 429, network/timeouts) up to 3 attempts with back-off.
async function fetchR(url:string,label:string,ms=60000){let last="";for(let attempt=1;attempt<=3;attempt++){try{const r=await fetchT(url,ms);if(r.ok)return r;last=`${label} HTTP ${r.status}`;await r.body?.cancel();if(r.status<500&&r.status!==429)break;}catch(e){last=`${label} ${e instanceof Error?e.message:String(e)}`;}if(attempt<3)await sleep(attempt===1?1500:4000);}throw new Error(last||`${label} failed`);}
async function pool<T,R>(items:T[],size:number,fn:(x:T)=>Promise<R>){const out:R[]=new Array(items.length);let i=0;await Promise.all(Array.from({length:Math.min(size,items.length)},async()=>{while(i<items.length){const k=i++;out[k]=await fn(items[k]);}}));return out;}
async function rpc(c:any,n:string,a:Record<string,unknown>={}){const {data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function sha(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function evidence(service:any,sourceId:string,jobId:string,url:string,path:string,bytes:Uint8Array,mime:string,metadata:unknown,reuse=false){const h=await sha(bytes);if(reuse){const existing=await rpc(service,"svc_layer1_evidence_by_hash",{p_source_id:sourceId,p_hash:h});if(existing)return{id:existing,hash:h,reused:true};}const up=await service.storage.from("evidence").upload(path,bytes,{contentType:mime,upsert:true});if(up.error)throw new Error(`evidence upload: ${up.error.message}`);const id=await rpc(service,"svc_layer1_record_evidence",{p_source_id:sourceId,p_job_id:jobId,p_source_url:url,p_storage_path:path,p_content_hash:h,p_mime_type:mime,p_metadata:metadata});return{id,hash:h,reused:false};}
async function authorize(req:Request,body:any,service:any,url:string,anon:string,serviceKey:string){if(body?.uatJobId&&body?.uatNonce){const ok=await rpc(service,"svc_layer1_validate_nz_gate_uat_token",{p_job_id:body.uatJobId,p_nonce:body.uatNonce});if(!ok)throw new Error("invalid or expired UAT authorisation");return{userId:null,mode:"controlled_uat"};}const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw new Error("authentication required");if(token===serviceKey)return{userId:null,mode:"service_role_internal"};const userClient=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data:{user},error}=await userClient.auth.getUser(token);if(error||!user)throw new Error("invalid user session");if(!await rpc(service,"svc_layer1_authorize_platform_admin",{p_user_id:user.id}))throw new Error("platform_admin required");return{userId:user.id,mode:"platform_admin"};}
function parseProviders(html:string,type:string){const out:any[]=[];for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const row=m[1];const pm=row.match(/href=["']\/providers\/details\.do\?providerId=([0-9]+)["']/i);if(!pm)continue;const cells=[...row.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>clean(x[1]));out.push({providerId:pm[1],listingName:cells[0]||null,city:cells[1]||null,type});}return out;}
function providerNumber(html:string){const text=clean(html);return text.match(/Education Organisation number\s+([0-9]{3,8})/i)?.[1]||text.match(/provider number\s+([0-9]{3,8})/i)?.[1]||"";}
function providerName(html:string,fallback:string){let n=clean(html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||fallback);n=n.replace(/^Organisations\s*>>\s*NZQA\s*-\s*/i,"").replace(/^Organisations\s*>>\s*/i,"");return n.trim();}
function providerWebsite(html:string){const text=html.match(/Website[\s\S]{0,400}?href=["']([^"']+)["']/i)?.[1]||"";return text?text.trim().replace(/^(https?:\/\/)+/i,"https://"):null;}
function parseQualifications(html:string){const rows:any[]=[];const seen=new Set<string>();for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const row=m[1];const qm=row.match(/viewQualification\.do\?selectedItemKey=([^&"']+)[^>]*>([\s\S]*?)<\/a>/i);if(!qm)continue;const code=decodeURIComponent(qm[1]).trim().toUpperCase();const title=clean(qm[2]);const text=clean(row);if(!code||!title||seen.has(code)||!/(^|\s)Current(\s|$)/i.test(text))continue;seen.add(code);const cells=[...row.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>clean(x[1]));const level=(title.match(/\(Level\s+([1-9]|10)\)/i)?.[1])||null;const credits=(cells.find((x:string)=>/^[0-9]{2,4}$/.test(x)&&Number(x)>=20&&Number(x)<=1000))||null;rows.push({code,title,status:"Current",level,credits});}return rows;}
async function applyRecords(service:any,sourceId:string,evidenceId:string,records:any[],doApply:boolean){const total:any={records:records.length,provider_created:0,provider_linked:0,provider_existing:0,course_created:0,course_linked:0,course_existing:0,conflicts:0};if(!doApply)return total;for(let i=0;i<records.length;i+=RPC_CHUNK){const r=await rpc(service,"svc_layer1_apply_register_records",{p_country_code:"NZ",p_source_id:sourceId,p_evidence_id:evidenceId,p_registration_scheme:"nzqa",p_records:records.slice(i,i+RPC_CHUNK)});for(const k of Object.keys(total))if(k!=="records")total[k]+=Number(r?.[k]||0);}return total;}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,anon=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||serviceKey;const service=createClient(url,serviceKey,{auth:{persistSession:false}});let jobId:string|null=null;let source:any=null;try{const body=await req.json().catch(()=>({}));const auth=await authorize(req,body,service,url,anon,serviceKey);const doApply=body.apply===true;const offset=Math.max(0,Number(body.offset??0));const batchSize=Math.max(1,Math.min(Number(body.batchSize??DEFAULT_BATCH),MAX_BATCH));const sourceRows=await rpc(service,"svc_layer1_resolve_sources",{p_country_code:"NZ"})||[];source=sourceRows.find((x:any)=>x.system_code==="nz_nzqa")||sourceRows[0];if(!source)throw new Error("NZQA source missing");jobId=await rpc(service,"svc_layer1_start_job",{p_country_code:"NZ",p_source_id:source.source_id,p_payload:{country_code:"NZ",apply:doApply,offset,batch_size:batchSize,runtime:"supabase_edge",version:VERSION,mode:"nzqa_live_tertiary_bounded",requested_by:auth.userId,authorisation_mode:auth.mode}});const started=Date.now();
 const listingPages=await Promise.all(TYPES.map(async type=>{const endpoint=`${BASE}/providers/results.do?regionCode=0&typeCode=${type}&category=&copApprovalStatus=&nameQuery=`;const r=await fetchR(endpoint,`NZQA ${type} register`);return{type,endpoint:r.url,html:await r.text()};}));
 const providers=new Map<string,any>();for(const page of listingPages){for(const p of parseProviders(page.html,page.type)){if(!providers.has(p.providerId))providers.set(p.providerId,p);}}const providerList=[...providers.values()].sort((a,b)=>a.providerId.localeCompare(b.providerId));if(!providerList.length)throw new Error("NZQA tertiary provider register returned zero providers");const selected=providerList.slice(offset,offset+batchSize);
 const acquired=await pool(selected,CONCURRENCY,async(p:any)=>{const detailsUrl=`${BASE}/providers/details.do?providerId=${p.providerId}`;const qualUrl=`${BASE}/nzqf/search/results.do?org=${p.providerId}&status=Current`;const [dr,qr]=await Promise.all([fetchR(detailsUrl,`NZQA provider ${p.providerId}`),fetchR(qualUrl,`NZQA qualifications ${p.providerId}`)]);const details=await dr.text(),qualsHtml=await qr.text();const code=providerNumber(details);const name=providerName(details,p.listingName||"");if(!code||!name)throw new Error(`NZQA stable provider identity missing for providerId ${p.providerId}`);const quals=parseQualifications(qualsHtml);return{...p,provider_code:code,provider_name:name,website:providerWebsite(details),detailsUrl:dr.url,qualUrl:qr.url,detailsHtml:details,qualsHtml,quals};});
 const records:any[]=[];for(const p of acquired){if(!p.quals.length)records.push({provider_code:p.provider_code,provider_name:p.provider_name,website:p.website,city:p.city,provider_type:p.type});for(const q of p.quals)records.push({provider_code:p.provider_code,provider_name:p.provider_name,website:p.website,city:p.city,provider_type:p.type,course_code:q.code,course_name:q.title,course_level:mapLevel(q.title),nzqf_level:q.level,credits:q.credits,source_status:q.status});}
 const stamp=new Date().toISOString().replace(/[:.]/g,"-");const listingBytes=new TextEncoder().encode(JSON.stringify(listingPages.map(x=>({type:x.type,endpoint:x.endpoint,html:x.html}))));
 // The listing is the same for every batch of a run: store it once and reuse it by content hash.
 const listEv=await evidence(service,source.source_id,jobId,listingPages[0].endpoint,`regulatory/NZ/nzqa/${stamp}-tertiary-register.json`,listingBytes,"application/json",{types:TYPES,total_providers:providerList.length,offset,batch_size:batchSize},true);
 const batchBytes=new TextEncoder().encode(JSON.stringify(acquired));const batchEv=await evidence(service,source.source_id,jobId,selected[0]?.detailsUrl||listingPages[0].endpoint,`regulatory/NZ/nzqa/${stamp}-offset-${offset}-batch-${batchSize}.json`,batchBytes,"application/json",{selected_providers:selected.length,record_count:records.length,provider_ids:selected.map(x=>x.providerId)});
 const reconciliation=await applyRecords(service,source.source_id,batchEv.id,records,doApply);const nextOffset=offset+selected.length,hasMore=nextOffset<providerList.length;let catalogueStats=null;if(doApply&&!hasMore)catalogueStats=await rpc(service,"svc_layer1_finalize_catalogue");const byType=Object.fromEntries(TYPES.map(t=>[t,providerList.filter(x=>x.type===t).length]));
 const result={country:"NZ",mode:doApply?"apply":"dry-run",adapter:"nzqa_live_tertiary_bounded",workerVersion:VERSION,offset,batchSize,totalProviders:providerList.length,providersByType:byType,selectedProviders:selected.length,totalRecords:records.length,nextOffset,hasMore,reconciliation,catalogueStats,evidenceIds:[listEv.id,batchEv.id],evidenceHashes:[listEv.hash,batchEv.hash],listingEvidenceReused:listEv.reused,runtimeMs:Date.now()-started};
 await rpc(service,"svc_layer1_source_health",{p_source_id:source.source_id,p_success:true,p_error:null,p_metadata:{worker_version:VERSION,total_providers:providerList.length,providers_by_type:byType,last_run_mode:result.mode,last_run_offset:offset,last_run_batch_size:batchSize,next_offset:nextOffset,has_more:hasMore,evidence_hashes:result.evidenceHashes}});await rpc(service,"svc_layer1_finish_job",{p_job_id:jobId,p_status:"completed",p_result:result,p_error:null});return json({ok:true,jobId,...result});}catch(e){const msg=e instanceof Error?e.message:String(e);if(jobId)try{await rpc(service,"svc_layer1_finish_job",{p_job_id:jobId,p_status:"failed",p_result:{workerVersion:VERSION},p_error:msg})}catch{};if(source)try{await rpc(service,"svc_layer1_source_health",{p_source_id:source.source_id,p_success:false,p_error:msg,p_metadata:{worker_version:VERSION}})}catch{};return json({ok:false,error:msg,jobId,workerVersion:VERSION},500);}});
