import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const ORIGIN="https://coursefinder-pilot.techm.workers.dev";
const cors=(r:Request)=>{const o=r.headers.get('origin')||'';return{'access-control-allow-origin':o===ORIGIN||o.startsWith('http://localhost')?o:ORIGIN,'access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json','cache-control':'no-store','vary':'origin'}};
const out=(r:Request,s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:cors(r)});
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return out(req,405,{error:'method_not_allowed'});const ah=req.headers.get('authorization')||'';if(!ah.toLowerCase().startsWith('bearer '))return out(req,401,{error:'authentication_required'});const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!anon||!secret)return out(req,500,{error:'service_configuration_error'});const user=createClient(url,anon,{global:{headers:{Authorization:ah}},auth:{persistSession:false,autoRefreshToken:false}}),svc=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const{data:ctx,error:ce}=await user.rpc('admin_read',{p_operation:'context',p_args:{}});if(ce||!ctx?.authenticated)return out(req,401,{error:'authentication_required'});if(Number(ctx.role_rank||0)<4)return out(req,403,{error:'pipeline_operator_role_required'});let b:any;try{b=await req.json()}catch{return out(req,400,{error:'invalid_json'})}const action=String(b?.action||'list');try{
 if(action==='create'){const providerId=String(b?.provider_id||''),country=String(b?.country_code||'AU'),batch=Number(b?.batch_size||10);if(!providerId)return out(req,400,{error:'provider_id_required'});const{data,error}=await svc.rpc('layer2_completeness_trial_create',{p_country_code:country,p_provider_id:providerId,p_batch_size:batch});if(error)throw error;return out(req,200,{ok:true,...data})}
 if(action==='list'){const{data,error}=await svc.rpc('svc_layer2_trial_list');if(error)throw error;return out(req,200,data||{ok:true,trials:[]})}
 if(action==='detail'){const id=String(b?.trial_id||'');if(!id)return out(req,400,{error:'trial_id_required'});const{data,error}=await svc.rpc('svc_layer2_trial_detail',{p_trial_id:id});if(error)throw error;return out(req,200,data)}
 if(action==='context'){const courseId=String(b?.course_id||'');if(!courseId)return out(req,400,{error:'course_id_required'});const{data,error}=await svc.rpc('course_decision_context',{p_course_id:courseId});if(error)throw error;return out(req,200,{ok:true,context:data})}
 if(action==='record'){const x=b?.result||{},trialCourseId=String(x.trial_course_id||'');if(!trialCourseId)return out(req,400,{error:'trial_course_id_required'});let providerId=String(x.acquisition_provider_id||'');if(!providerId){const providerKey=String(x.provider_key||x.metrics?.provider_key||'');if(!providerKey)return out(req,400,{error:'acquisition_provider_required'});const{data:p,error:pe}=await svc.rpc('svc_layer2_trial_provider_id',{p_provider_key:providerKey});if(pe||!p)throw pe||new Error('provider_not_found');providerId=String(p)}const{data,error}=await svc.rpc('layer2_provider_trial_record',{p_trial_course_id:trialCourseId,p_acquisition_provider_id:providerId,p_domain_key:String(x.domain_key||'course_facts'),p_provider_attempt_id:x.provider_attempt_id||null,p_acquisition_success:x.acquisition_success??null,p_gatekeeping_bypassed:x.gatekeeping_bypassed??null,p_javascript_rendered:x.javascript_rendered??null,p_evidence_quality_score:x.evidence_quality_score??null,p_deterministic_extraction_success:x.deterministic_extraction_success??null,p_correctness_status:x.correctness_status||'unverified',p_latency_ms:x.latency_ms??null,p_request_count:x.request_count??1,p_vendor_cost_usd:x.vendor_cost_usd??null,p_fields_targeted:x.fields_targeted??0,p_fields_resolved:x.fields_resolved??0,p_layer3_required:x.layer3_required??false,p_layer4_required:x.layer4_required??false,p_blocker:x.blocker||null,p_metrics:x.metrics||{}});if(error)throw error;const next=x.layer4_required?'layer4_required':x.layer3_required?'layer3_required':x.correctness_status==='correct'?'resolved':'extracted';const{error:ue}=await svc.rpc('svc_layer2_trial_course_update',{p_trial_course_id:trialCourseId,p_status:next,p_post_factual:x.post_factual||{},p_post_context:x.post_context||{}});if(ue)throw ue;return out(req,200,{ok:true,result_id:data,status:next,acquisition_provider_id:providerId})}
 return out(req,400,{error:'unsupported_action'});
 }catch(e:any){console.error('layer2-trial-control',action,e);return out(req,500,{error:e?.message||String(e)})}});
