import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const VERSION="coursefacts-au-rmit-v0.2.0";
const FN="coursefacts-au-rmit";
const PROVIDER_CRICOS="00122A";
const RECORDS=[
 {courseCricos:"111279A",sourceRecordId:"rmit-ad029-2027",url:"https://www.rmit.edu.au/study-with-us/levels-of-study/undergraduate-study/associate-degrees/associate-degree-in-business-ad029",proof:["111279A","37,440","2027","February","July","IELTS","6.0","TOEFL","60","Pearson","50","C1 Advanced","169"],payload:{course_url:"https://www.rmit.edu.au/study-with-us/levels-of-study/undergraduate-study/associate-degrees/associate-degree-in-business-ad029",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:37440,currency_code:"AUD",fee_basis:"annual",fee_key:"rmit:111279A:international:2027:annual",fee_notes:"RMIT published 2027 annual international tuition fee",intakes:[{intake_year:2027,intake_label:"Semester 1 / February",start_date:"2027-03-01",application_deadline:"2027-03-03",source_intake_key:"rmit:111279A:2027:s1"},{intake_year:2027,intake_label:"Semester 2 / July",start_date:"2027-07-19",source_intake_key:"rmit:111279A:2027:s2"}],english_requirements:[{test_code:"IELTS",overall_score:6.0,component_scores:{reading:5.5,listening:5.5,speaking:5.5,writing:5.5},valid_from:"2026-08-19",notes:"No individual band below 5.5"},{test_code:"TOEFL_IBT",overall_score:60,component_scores:{reading:10,listening:9,speaking:16,writing:19},valid_from:"2026-08-19"},{test_code:"PTE",overall_score:50,component_scores:{minimum_communication_band:42},valid_from:"2026-08-19"},{test_code:"CAE",overall_score:169,component_scores:{minimum_each:162},valid_from:"2026-08-19"}] }},
 {courseCricos:"103390B",sourceRecordId:"rmit-c6178-2027",url:"https://www.rmit.edu.au/study-with-us/levels-of-study/vocational-study/advanced-diplomas/advanced-diploma-of-electronics-and-communications-engineering-c6178",proof:["103390B","49,250","2027","February","IELTS","5.5","TOEFL","50","Pearson","42","C1 Advanced","162"],payload:{course_url:"https://www.rmit.edu.au/study-with-us/levels-of-study/vocational-study/advanced-diplomas/advanced-diploma-of-electronics-and-communications-engineering-c6178",link_type:"official_course",audience:"international",fee_year:2027,fee_amount:49250,currency_code:"AUD",fee_basis:"total_indicative",fee_key:"rmit:103390B:international:2027:total_indicative",fee_notes:"RMIT published 2027 total indicative international tuition fee",intakes:[{intake_year:2027,intake_label:"Semester 1 / February",start_date:"2027-02-08",application_deadline:"2027-02-10",source_intake_key:"rmit:103390B:2027:s1"}],english_requirements:[{test_code:"IELTS",overall_score:5.5,component_scores:{reading:5.0,listening:5.0,speaking:5.0,writing:5.0},valid_from:"2026-08-19",notes:"No individual band below 5.0"},{test_code:"TOEFL_IBT",overall_score:50,component_scores:{reading:5,listening:5,speaking:14,writing:15},valid_from:"2026-08-19"},{test_code:"PTE",overall_score:42,component_scores:{minimum_communication_band:36},valid_from:"2026-08-19"},{test_code:"CAE",overall_score:162,component_scores:{minimum_each:154},valid_from:"2026-08-19"}] }}
];
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-cf-run-nonce","Access-Control-Allow-Methods":"POST,OPTIONS"};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown)=>String(v??"").trim();
async function rpc(c:any,n:string,a:Record<string,unknown>={}){const{data,error}=await c.rpc(n,a);if(error)throw new Error(`${n}: ${error.message}`);return data;}
async function auth(req:Request,svc:any){const nonce=clean(req.headers.get("x-cf-run-nonce"));if(!nonce||!await rpc(svc,"svc_pilot_consume_nonce",{p_function:FN,p_nonce:nonce}))throw new Error("valid one-time Pilot nonce required");}
async function sha(bytes:Uint8Array){const d=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function visible(html:string){return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#36;/g,"$").replace(/\s+/g," ");}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"POST required"},405);const svc=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});try{await auth(req,svc);const body=await req.json().catch(()=>({}));const apply=body.apply===true;const source=await rpc(svc,"svc_coursefacts_resolve_source",{p_system_code:"au_rmit_course_pages",p_provider_cricos:PROVIDER_CRICOS});if(!source?.source_id)throw new Error("RMIT source not resolved");const results:any[]=[];for(const rec of RECORDS){const resp=await fetch(rec.url,{redirect:"follow",headers:{"user-agent":"CourseFinder-Pilot/CourseFacts-0.2.0","accept":"text/html,application/xhtml+xml"}});if(!resp.ok)throw new Error(`${rec.courseCricos} HTTP ${resp.status}`);const bytes=new Uint8Array(await resp.arrayBuffer()),html=new TextDecoder().decode(bytes),text=visible(html),hash=await sha(bytes);const missing=rec.proof.filter(x=>!text.toLowerCase().includes(x.toLowerCase()));if(missing.length)throw new Error(`${rec.courseCricos} source proof failed: ${missing.join(", ")}`);const stamp=new Date().toISOString().replace(/[:.]/g,"-");const storagePath=`layer2a/AU/coursefacts/rmit/${rec.courseCricos}/${stamp}.html`;const up=await svc.storage.from("evidence").upload(storagePath,bytes,{contentType:"text/html",upsert:false});if(up.error)throw new Error(up.error.message);const evidenceId=await rpc(svc,"svc_coursefacts_register_evidence",{p_source_id:source.source_id,p_source_url:rec.url,p_storage_path:storagePath,p_content_hash:hash,p_mime_type:"text/html",p_metadata:{worker_version:VERSION,provider_cricos:PROVIDER_CRICOS,course_cricos:rec.courseCricos,http_status:resp.status,identity_authority:false,search_admitted:false}});const applied=await rpc(svc,"svc_coursefacts_apply_record",{p_source_id:source.source_id,p_evidence_id:evidenceId,p_provider_cricos:PROVIDER_CRICOS,p_course_cricos:rec.courseCricos,p_source_record_id:rec.sourceRecordId,p_source_url:rec.url,p_content_hash:hash,p_payload:rec.payload,p_apply:apply});results.push({courseCricos:rec.courseCricos,url:rec.url,hash,evidenceId,proof:true,applyResult:applied});}return out({ok:true,workerVersion:VERSION,mode:apply?"apply":"dry-run",records:results});}catch(e){return out({error:e instanceof Error?e.message:String(e),workerVersion:VERSION},500);}});