import React from'react'
import{Activity,BookOpen,CircleGauge,Sparkles}from'lucide-react'

const human=v=>String(v??'').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())
const fmt=v=>v==null||v===''?'—':typeof v==='number'?v.toLocaleString():String(v)
const date=v=>{if(!v)return'';const d=new Date(v);return Number.isNaN(+d)?String(v):d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'})}
function EvidenceButton({id,navigate}){return id?<button className="m-secondary compact" onClick={e=>{e.stopPropagation();navigate?.('Evidence',{evidence_id:id})}}><BookOpen size={10}/>Evidence</button>:null}
function State({value}){return <span className="m-status status-neutral">{human(value||'not available')}</span>}
function OutcomeRows({group,navigate}){const rows=group?.items||[];if(!rows.length)return <div className="m-empty-inline"><span>{group?.relationship_state==='country_counterpart_not_available'?'No governed country-equivalent outcome source is currently available.':'No governed outcome rows are currently related to this entity.'}</span></div>;return <div className="m-record-list">{rows.slice(0,5).map((x,i)=><div className="m-record" key={x.id||i}><strong>{x.metric_name||x.metric_code||'Outcome metric'}</strong><span>{[x.study_area,x.study_level,x.audience,[x.collection_year_from,x.collection_year_to].filter(Boolean).join('–')].filter(Boolean).join(' · ')}</span><span>Value: {fmt(x.metric_value)}{x.unit?' '+x.unit:''}{x.national_benchmark!=null?' · Benchmark '+fmt(x.national_benchmark):''}</span><EvidenceButton id={x.evidence_id} navigate={navigate}/></div>)}</div>}
function FlowRows({group,navigate}){const rows=group?.items||[];if(!rows.length)return <div className="m-empty-inline"><span>{group?.relationship_state==='not_mapped'?'No direct governed Provider/Course relationship is currently available for this student-flow dataset.':'No governed student-flow context is currently available.'}</span></div>;return <div className="m-record-list">{rows.slice(0,5).map((x,i)=><div className="m-record" key={x.id||i}><strong>{x.metric_name||x.metric_code||'Student flow'}</strong><span>{[x.subdivision,x.study_area,x.nationality,x.period_end&&date(x.period_end)].filter(Boolean).join(' · ')}</span><span>{x.is_suppressed?'Suppressed':fmt(x.metric_value)}</span><EvidenceButton id={x.evidence_id} navigate={navigate}/></div>)}</div>}
function ScholarshipRows({group,navigate}){const rows=group?.items||[];if(!rows.length)return <div className="m-empty-inline"><span>No governed Scholarship scope is currently related to this entity.</span></div>;return <div className="m-record-list">{rows.slice(0,5).map((x,i)=><div className="m-record" key={x.id||i}><strong>{x.name||'Scholarship'}</strong><span>{[human(x.relationship),x.audience,x.academic_year,x.application_close_date?'Closes '+date(x.application_close_date):null].filter(Boolean).join(' · ')}</span><span>{x.award_value_text||'See award details'}{x.granularity==='contextual_eligibility'?' · Contextual eligibility — verify criteria':''}</span><EvidenceButton id={x.evidence_id} navigate={navigate}/></div>)}</div>}
function Group({icon:Icon,title,group,children,navigate,target}){return <div className="m-record"><div className="m-panel-heading"><span className="m-panel-icon"><Icon size={15}/></span><div><strong>{title}</strong><span>{group?.source_label||'Governed source'} · {human(group?.granularity||'none')} · <State value={group?.relationship_state}/></span></div></div>{children}{target&&<button className="m-secondary compact" onClick={()=>navigate?.(target)}>Open full workspace →</button>}</div>}
export default function ContextualInsights({data,navigate,entityType='provider'}){if(!data)return null;const outcomes=data.student_outcomes||{},flow=data.student_flow||{},sch=data.scholarships||{};return <section className="m-detail-section"><h3>Related insights & funding</h3><p className="m-help">{entityType==='course'?'Contextual statistics retain their actual Provider/regional granularity; they are not Course facts.':'Relevant governed outcomes, student-flow context and funding linked to this Provider.'}</p><div className="m-record-list"><Group icon={Activity} title="Student outcomes / benchmarks" group={outcomes} navigate={navigate} target="Outcomes (QILT)"><OutcomeRows group={outcomes} navigate={navigate}/></Group><Group icon={CircleGauge} title="International student flow" group={flow} navigate={navigate} target="Student Flow (PRISMS)"><FlowRows group={flow} navigate={navigate}/></Group><Group icon={Sparkles} title="Scholarships / funding" group={sch} navigate={navigate} target="Scholarships"><ScholarshipRows group={sch} navigate={navigate}/></Group></div><p className="m-help">{data.authority_note}</p></section>}
