import React,{useEffect,useMemo,useState}from'react'
import{BookOpen,ExternalLink,Pencil,Save,X}from'lucide-react'
import{api}from'./lib/supabase'
import{resolveCourseScalar}from'./layer4-course-resolution'

const empty=v=>v==null||v===''||(Array.isArray(v)&&v.length===0)||(typeof v==='object'&&!Array.isArray(v)&&Object.keys(v||{}).length===0)
const fmtDate=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(+d)?String(v):d.toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'})}
const money=x=>x?.amount==null?'—':`${x.currency||x.currency_code||'AUD'} ${Number(x.amount).toLocaleString()}`
const evidenceIdOf=v=>v?.evidence_id||v?.source_evidence_id||(v?.storage_path&&v?.id?v.id:null)
const stateMap=rows=>new Map((Array.isArray(rows)?rows:[]).map(x=>[x.code,x]))
const scalarEditable=new Set(['course_description','official_course_url','delivery_mode','duration'])
const safeText=v=>{
  if(v==null||v==='')return'—'
  if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v)
  if(Array.isArray(v))return v.length?`${v.length} record${v.length===1?'':'s'}`:'0 records'
  if(typeof v==='object'){
    for(const k of['count','fields','field_count','total','records','value'])if(v[k]!=null&&typeof v[k]!=='object')return String(v[k])
    const keys=Object.keys(v);return keys.length?`${keys.length} field${keys.length===1?'':'s'}`:'—'
  }
  return String(v)
}

function LayerBadge({layer,struck=false}){const n=Number(layer);if(!n)return null;return <span style={{display:'inline-flex',alignItems:'center',padding:'2px 6px',borderRadius:999,border:'1px solid #cbd5e1',background:'#f8fafc',fontSize:9,fontWeight:800,color:'#475569',whiteSpace:'nowrap',textDecoration:struck?'line-through':'none',opacity:struck?.6:1}}>L{n}</span>}
function StateTrail({state}){
  const s=state?.value_state||'awaiting_l2'
  if(s==='resolved')return <span style={{display:'inline-flex',gap:5,alignItems:'center'}}><LayerBadge layer={state?.resolved_layer}/><small>Resolved</small></span>
  if(s==='source_missing')return <span style={{display:'inline-flex',gap:5,alignItems:'center'}}><LayerBadge layer={1} struck/><small style={{fontWeight:700,color:'#b45309'}}>Regulatory correction</small></span>
  if(s==='awaiting_l2')return <span style={{display:'inline-flex',gap:5,alignItems:'center'}}><LayerBadge layer={2}/><small style={{fontWeight:700,color:'#64748b'}}>Awaiting L2</small></span>
  if(s==='l2_unresolved'||s==='awaiting_l3')return <span aria-label="Layer 2 attempted and unresolved; awaiting Layer 3" style={{display:'inline-flex',gap:5,alignItems:'center'}}><LayerBadge layer={2} struck/><span>→</span><LayerBadge layer={3}/><small style={{fontWeight:700,color:'#7c3aed'}}>Awaiting L3</small></span>
  if(s==='awaiting_l4')return <span aria-label="Layers 2 and 3 exhausted; awaiting Layer 4 input" style={{display:'inline-flex',gap:5,alignItems:'center'}}><LayerBadge layer={2} struck/><LayerBadge layer={3} struck/><span>→</span><LayerBadge layer={4}/><small style={{fontWeight:800,color:'#b45309'}}>L4 input</small></span>
  if(s==='l4_input')return <span aria-label="Direct Layer 4 input" style={{display:'inline-flex',gap:5,alignItems:'center'}}><LayerBadge layer={4}/><small style={{fontWeight:800,color:'#b45309'}}>L4 input</small></span>
  return <small>{String(s).replaceAll('_',' ')}</small>
}
function Section({title,help,children}){return <section className="m-detail-section"><h3 style={{margin:0}}>{title}</h3>{help&&<p className="m-help">{help}</p>}{children}</section>}
function Blank(){return <span style={{color:'#94a3b8',fontStyle:'italic'}}>—</span>}
function EvidenceButton({id,navigate,courseId}){if(!id)return null;return <button className="m-secondary compact" onClick={e=>{e.stopPropagation();navigate?.('Evidence',{evidence_id:id,return_course_id:courseId||''})}}><BookOpen size={11}/>Evidence</button>}

function AttributeMatrix({data,states,rank,onEdit}){
  const current=data.fee_summary?.provider_current||[],english=data.english||[],intakes=data.intakes||[]
  const attrs=[
    ['provider','Provider',data.provider_name],['course_code','CRICOS / Course code',data.course_code],['study_level','Study level',data.level_name||data.level_code],['field_of_study','Field of study',data.field_name||data.field_code],
    ['duration','Duration',data.duration_value?`${data.duration_value} ${data.duration_unit||''}`.trim():null],['delivery_mode','Delivery mode',data.delivery_mode],['official_course_url','Official Course URL',data.course_url],['course_description','Course description',data.description],
    ['provider_current_tuition','Current Provider tuition',current.length?current.map(money).join(', '):null],['intakes','Intakes',intakes.length?intakes.map(x=>[x.label,x.year].filter(Boolean).join(' ')).join(', '):null],['english_requirement','English requirement',english.length?english.map(x=>`${x.test_name||x.test_code||'English'}${x.overall_score!=null?` · Overall ${x.overall_score}`:''}`).join(', '):null],
    ['campuses','Campuses',(data.campuses||[]).length?`${data.campuses.length} campus${data.campuses.length===1?'':'es'}`:null],['academic_options','Academic options',(data.academic_options||[]).length?`${data.academic_options.length} option${data.academic_options.length===1?'':'s'}`:null],['categories','Categories',(data.categories||[]).length?`${data.categories.length} categor${data.categories.length===1?'y':'ies'}`:null],['collections','Collections',(data.collections||[]).length?`${data.collections.length} collection${data.collections.length===1?'':'s'}`:null],['regulatory_facts','Regulatory facts',(data.regulatory_facts||[]).length?`${data.regulatory_facts.length} current observation${data.regulatory_facts.length===1?'':'s'}`:null]
  ]
  return <Section title="Course attributes" help="Every governed attribute remains visible. A blank value shows which layer owns the next action."><div style={{display:'grid',gap:7}}>{attrs.map(([code,label,value])=>{
    const st=states.get(code)||{},l4Ready=['l4_input','awaiting_l4'].includes(st.value_state)||(st.value_state==='resolved'&&Number(st.resolved_layer)===4),l4=Boolean(st.editable_l4)&&rank>=3&&l4Ready,scalar=scalarEditable.has(code)
    return <div key={code} data-field-code={code} style={{display:'grid',gap:7,padding:'9px 10px',border:'1px solid #e2e8f0',borderRadius:8,background:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong style={{fontSize:11}}>{label}</strong><StateTrail state={st}/></div><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'flex-start',flexWrap:'wrap'}}><div style={{minWidth:0,flex:'1 1 180px',fontSize:11,wordBreak:code==='official_course_url'?'break-all':'normal'}}>{empty(value)?<Blank/>:code==='official_course_url'?<a href={String(value)} target="_blank" rel="noreferrer" style={{color:'#4f46e5'}}>Open first-party page <ExternalLink size={10}/></a>:safeText(value)}</div><div>{l4&&scalar?<button className="m-secondary compact" onClick={()=>onEdit(code,label,value)}><Pencil size={12}/>L4 edit</button>:l4?<button className="m-secondary compact" onClick={()=>{location.hash=`#review-queue?entity_id=${encodeURIComponent(data.id)}&field=${encodeURIComponent(code)}`}}>L4 review</button>:null}</div></div></div>
  })}</div></Section>
}

function Fees({data,navigate,states}){const f=data.fee_summary||{},registered=f.cricos_registered||[],current=f.provider_current||[];return <Section title="Fees" help="Registered CRICOS course costs and current Provider tuition are separate facts."><div className="m-semantic-grid"><div><small>Registered CRICOS course cost <LayerBadge layer={1}/></small><strong>{registered.length}</strong><div className="m-record-list">{registered.length?registered.map((x,i)=><div className="m-record" key={x.id||i}><strong>{String(x.fee_type||'Registered cost').replaceAll('_',' ')}</strong><div style={{fontSize:17,fontWeight:800}}>{money(x)}</div><span>{[x.fee_year&&`Year ${x.fee_year}`,x.audience&&`Audience ${x.audience}`,x.basis&&`Basis ${String(x.basis).replaceAll('_',' ')}`].filter(Boolean).join(' · ')}</span><EvidenceButton id={evidenceIdOf(x)} navigate={navigate} courseId={data.id}/></div>):<div className="m-record"><Blank/></div>}</div></div><div><small>Current Provider tuition</small><StateTrail state={states.get('provider_current_tuition')}/><div className="m-record-list">{current.length?current.map((x,i)=><div className="m-record" key={x.id||i}><strong>{money(x)}</strong><span>{[x.fee_year&&`Year ${x.fee_year}`,x.audience&&`Audience ${x.audience}`,x.basis&&`Basis ${String(x.basis).replaceAll('_',' ')}`].filter(Boolean).join(' · ')}</span><EvidenceButton id={evidenceIdOf(x)} navigate={navigate} courseId={data.id}/></div>):<div className="m-record"><Blank/></div>}</div></div></div></Section>}
function Entry({data,states}){const intakes=data.intakes||[],english=data.english||[];return <Section title="Intakes & English"><div className="m-kv-list"><div><span>Intakes</span><strong>{intakes.length?intakes.map(x=>[x.label,x.year].filter(Boolean).join(' ')).join(', '):<Blank/>}</strong><StateTrail state={states.get('intakes')}/></div><div><span>English requirement</span><strong>{english.length?english.map(x=>[x.test_name||x.test_code||'English test',x.overall_score!=null?`Overall score ${x.overall_score}`:null,x.confidence!=null?`Confidence ${x.confidence}`:null].filter(Boolean).join(' · ')).join('; '):<Blank/>}</strong><StateTrail state={states.get('english_requirement')}/></div></div></Section>}
function DetailList({title,rows,state,render}){return <Section title={title}><StateTrail state={state}/><div className="m-record-list">{rows?.length?rows.map((x,i)=><div className="m-record" key={x.id||i}>{render(x)}</div>):<div className="m-record"><Blank/></div>}</div></Section>}
function Evidence({rows,navigate,courseId}){return <Section title="Evidence" help="Open supporting provenance in the Evidence workspace."><div className="m-record-list">{rows?.length?rows.map((x,i)=><button key={x.id||i} className="m-record" style={{textAlign:'left',width:'100%',cursor:'pointer'}} onClick={()=>x.id&&navigate?.('Evidence',{evidence_id:x.id,return_course_id:courseId})}><strong>{x.evidence_type||x.type||'Evidence artifact'}</strong><span>{[x.captured_at?`Captured ${fmtDate(x.captured_at)}`:null,x.source_url||null,x.content_hash?`SHA ${String(x.content_hash).slice(0,12)}…`:null].filter(Boolean).join(' · ')}</span><span style={{display:'inline-flex',gap:4,alignItems:'center',fontWeight:700,color:'#4f46e5'}}><BookOpen size={11}/>Open Evidence</span></button>):<div className="m-record"><Blank/></div>}</div></Section>}
function Operational({data}){const s=data.state_summary||{};return <Section title="Operational state" help="Completeness does not publish automatically. Publication remains an explicit governed action."><div className="m-kv-list"><div><span>Publication</span><strong>{safeText(data.publication_status)}</strong></div><div><span>Search projection</span><strong>{safeText(s.search??s.search_fields)}</strong></div><div><span>Canonical coverage</span><strong>{safeText(s.canonical??s.canonical_fields)}</strong></div><div><span>Admin readiness</span><strong>{safeText(s.admin_readiness??s.admin_readiness_fields)}</strong></div></div></Section>}

function L4Editor({courseId,fieldCode,label,current,onClose,onSaved}){const[text,setText]=useState(String(current||'')),[unit,setUnit]=useState('weeks'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function save(){setBusy(true);setError('');try{let value;if(fieldCode==='duration'){const m=text.match(/^\s*([0-9.]+)(?:\s+(.+))?$/);value={value:m?Number(m[1]):Number(text),unit:m?.[2]||unit}}else value=text;const result=await resolveCourseScalar(courseId,fieldCode,value,reason);onSaved(fieldCode,value,result);onClose()}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}return <div style={{position:'sticky',bottom:0,zIndex:3,background:'#fff',border:'1px solid #cbd5e1',borderRadius:10,padding:12,boxShadow:'0 -4px 18px rgba(15,23,42,.08)'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><div><strong>Layer 4 resolution · {label}</strong><div style={{fontSize:10,color:'#64748b'}}>Human resolution is audit-recorded and does not publish the Course.</div></div><button className="m-secondary compact" onClick={onClose}><X size={12}/></button></div><div style={{display:'grid',gap:8,marginTop:10}}><label style={{display:'grid',gap:4,fontSize:10}}>Value{fieldCode==='duration'?<div style={{display:'grid',gridTemplateColumns:'1fr 120px',gap:6}}><input value={text} onChange={e=>setText(e.target.value)}/><input value={unit} onChange={e=>setUnit(e.target.value)}/></div>:<textarea rows={fieldCode==='course_description'?4:2} value={text} onChange={e=>setText(e.target.value)}/>}</label><label style={{display:'grid',gap:4,fontSize:10}}>Resolution reason<textarea rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<div style={{color:'#b91c1c',fontSize:10}}>{error}</div>}<button className="m-primary" disabled={busy||reason.trim().length<5||!text.trim()} onClick={save}><Save size={13}/>{busy?'Saving…':'Apply L4 resolution'}</button></div></div>}

export default function CourseDetailPolish({data,navigate}){
  const[rank,setRank]=useState(0),[working,setWorking]=useState(data),[editor,setEditor]=useState(null),[saved,setSaved]=useState('')
  useEffect(()=>setWorking(data),[data])
  useEffect(()=>{let live=true;api.context().then(x=>{if(live)setRank(Number(x?.role_rank||0))}).catch(()=>{});return()=>{live=false}},[])
  const states=useMemo(()=>stateMap(working?.field_states),[working?.field_states])
  if(!working)return null
  function onSaved(code,value){setWorking(prev=>{const next={...prev};if(code==='course_description')next.description=String(value);if(code==='official_course_url')next.course_url=String(value);if(code==='delivery_mode')next.delivery_mode=String(value);if(code==='duration'){next.duration_value=value.value;next.duration_unit=value.unit}next.field_states=(prev.field_states||[]).map(x=>x.code===code?{...x,value_state:'resolved',resolved_layer:4}:x);return next});setSaved('Layer 4 resolution saved')}
  return <div className="m-drawer-body"><div className="m-detail-grid"><div><small>Provider</small><strong>{safeText(working.provider_name)}</strong></div><div><small>CRICOS / Course code</small><strong>{safeText(working.course_code)}</strong></div><div><small>Lifecycle</small><strong>{safeText(working.lifecycle_status)}</strong></div><div><small>Publication</small><strong>{safeText(working.publication_status)}</strong></div><div><small>Last verified</small><strong>{fmtDate(working.last_verified_at)}</strong></div></div>{saved&&<div className="m-help" style={{padding:'8px 10px',border:'1px solid #bbf7d0',background:'#f0fdf4',borderRadius:8,color:'#166534'}}>{saved}</div>}<AttributeMatrix data={working} states={states} rank={rank} onEdit={(code,label,value)=>{setSaved('');setEditor({code,label,value})}}/><Fees data={working} navigate={navigate} states={states}/><Entry data={working} states={states}/><DetailList title="Campuses" rows={working.campuses} state={states.get('campuses')} render={x=><><strong>{x.name||x.campus_name||'Campus'}</strong><span>{[x.city,x.subdivision_name||x.state,x.postcode].filter(Boolean).join(' · ')}</span></>}/><DetailList title="Academic options" rows={working.academic_options} state={states.get('academic_options')} render={x=><><strong>{x.name||x.code||'Option'}</strong><span>{safeText(x.description||x.type)}</span></>}/><DetailList title="Categories" rows={working.categories} state={states.get('categories')} render={x=><><strong>{x.name||x.code||'Category'}</strong><span>{safeText(x.type)}</span></>}/><DetailList title="Collections" rows={working.collections} state={states.get('collections')} render={x=><><strong>{x.name||x.code||'Collection'}</strong><span>{safeText(x.relationship_type)}</span></>}/><DetailList title="Regulatory facts" rows={working.regulatory_facts} state={states.get('regulatory_facts')} render={x=><><strong>{String(x.scheme||'CRICOS').toUpperCase()} registration</strong><span>{[x.status&&`Status ${x.status}`,x.course_language&&`Language ${x.course_language}`,x.work_component!=null&&`Work component ${x.work_component?'Yes':'No'}`].filter(Boolean).join(' · ')||'Current regulatory registration'}</span><EvidenceButton id={evidenceIdOf(x)} navigate={navigate} courseId={working.id}/></>}/><Evidence rows={working.evidence} navigate={navigate} courseId={working.id}/><Operational data={working}/>{editor&&<L4Editor courseId={working.id} fieldCode={editor.code} label={editor.label} current={editor.value} onClose={()=>setEditor(null)} onSaved={onSaved}/>}</div>
}
