import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{Activity,AlertTriangle,Archive,ChevronRight,Clock3,Cog,Database,Gauge,RefreshCw,ShieldCheck,SlidersHorizontal,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import'./layer2-operations.css'

const human=x=>String(x||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())
const fmtDate=x=>x?new Date(x).toLocaleString():'—'
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
const pct=(a,b)=>b>0?Math.round((100*a/b)*10)/10:0
const measuredBilling=b=>{if(!b)return'Not configured';if(b.subscription_cost_usd==null&&b.monetary_cost_basis==='subscription_cost_not_recorded')return'Quota measured · subscription cost not recorded';if(b.unit_cost_usd===0)return b.source==='internal_no_vendor_fee'?'Measured: no vendor fee':'Configured: $0 cash/unit';return b.unit_cost_usd!=null?`Configured: $${Number(b.unit_cost_usd).toFixed(4)}/unit`:'Cost not available'}

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false);useEffect(()=>{let live=true,seq=0;const resolve=async()=>{const call=++seq;try{const{data}=await supabase.auth.getSession();if(!data.session){if(live&&call===seq)setRank(0);return}let ctx=null,last=null;for(let i=0;i<4&&!ctx;i++){try{ctx=await api.context()}catch(e){last=e;if(i<3)await sleep(250*(i+1))}}if(!ctx)throw last||new Error('context unavailable');if(live&&call===seq)setRank(Number(ctx?.role_rank||0))}catch{if(live&&call===seq){const{data}=await supabase.auth.getSession().catch(()=>({data:{session:null}}));if(!data?.session)setRank(0)}}};resolve();const{data}=supabase.auth.onAuthStateChange(()=>resolve());return()=>{live=false;seq++;data.subscription.unsubscribe()}},[]);if(rank<4)return null;return <><button className="l2o-launcher" onClick={()=>setOpen(true)}><Activity size={15}/><span>Layer 2 Operations</span></button>{open&&<Workspace rank={rank} onClose={()=>setOpen(false)}/>}</>}

function Workspace({rank,onClose}){const[data,setData]=useState(null),[alerts,setAlerts]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[country,setCountry]=useState(''),[scopeType,setScopeType]=useState('country'),[scopeId,setScopeId]=useState(''),[scopeOptions,setScopeOptions]=useState({countries:[]}),[scopeOptionLabel,setScopeOptionLabel]=useState(''),[preview,setPreview]=useState(null),[syncResult,setSyncResult]=useState(null)
 const invoke=async body=>{const{data:r,error:e}=await supabase.functions.invoke('layer2-sync-control',{body});if(e)throw e;if(r?.error)throw new Error(r.error);return r}
 const scopePage=async(kind,{countryCode=country,stateId=null,query='',offset=0}={})=>invoke({action:'scope_options_page',country_code:countryCode,kind,state_id:stateId,query,limit:10,offset})
 const loadScope=async(c,type=scopeType,current=scopeId)=>{if(!c)return;if(type==='country'){setScopeId('');setScopeOptionLabel('');setPreview(await invoke({action:'preview_scope',country_code:c,scope_type:type,scope_id:null}));return}let id=current,label=scopeOptionLabel;if(!id){const page=await scopePage(type,{countryCode:c,offset:0});const first=page.items?.[0];id=first?.value||'';label=first?.label||''}setScopeId(id);setScopeOptionLabel(label);if(!id){setPreview(null);return}setPreview(await invoke({action:'preview_scope',country_code:c,scope_type:type,scope_id:id}))}
 const load=async()=>{setBusy(true);setError('');try{const[next,opts]=await Promise.all([adminRead('layer2_ops_overview'),invoke({action:'options'})]);let nextAlerts=[];try{nextAlerts=await adminRead('layer2_ops_alerts')}catch{}setData(next);setAlerts(Array.isArray(nextAlerts)?nextAlerts:[]);const available=opts.countries||[],chosen=available.some(x=>x.code===country)?country:(available[0]?.code||'');setCountry(chosen);setScopeOptions({countries:available});if(chosen)await loadScope(chosen,scopeType,scopeId)}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[])
 const sources=data?.sources||[],runs=data?.recent_runs||[],ev=data?.evidence_summary||{},health=data?.health||{},outcomes=data?.outcomes||{},scope=data?.scope_summary||{}
 const active=runs.find(r=>['queued','running'].includes(r.status)),queueable=Number(scope.course_queueable_total||0),catalogue=Number(scope.course_catalogue_total||0),sourceLimited=Math.max(0,catalogue-queueable)
 const blockers=useMemo(()=>{const x=[];for(const a of alerts||[])if(a?.message)x.push(a.message);if(Number(preview?.qualification_required_count||0)>0)x.push(`${preview.qualification_required_count} Layer 1 institution(s) in the selected scope need Layer 2 source qualification before full sync.`);return [...new Set(x)]},[alerts,preview?.qualification_required_count])
 const openChild=selector=>{onClose();let tries=0;const launch=()=>{const el=document.querySelector(selector);if(el){el.click();return}if(++tries<30)setTimeout(launch,100)};setTimeout(launch,0)}
 const openNav=label=>{onClose();requestAnimationFrame(()=>{const b=[...document.querySelectorAll('.m-nav-item')].find(x=>(x.textContent||'').trim()===label);b?.click()})}
 const chooseCountry=async c=>{setCountry(c);setScopeId('');setScopeOptionLabel('');setSyncResult(null);setPreview(null);setBusy(true);setError('');try{await loadScope(c,scopeType,'')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const chooseType=async type=>{setScopeType(type);setScopeId('');setScopeOptionLabel('');setSyncResult(null);setPreview(null);setBusy(true);setError('');try{await loadScope(country,type,'')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const chooseScope=async(id,label)=>{setScopeId(id);setScopeOptionLabel(label||'');setSyncResult(null);setPreview(null);setBusy(true);setError('');try{setPreview(await invoke({action:'preview_scope',country_code:country,scope_type:scopeType,scope_id:id||null}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 const runSync=async()=>{if(!preview)return;setBusy(true);setError('');setSyncResult(null);try{const qualifying=preview.recommended_action==='qualify_wave';const r=await invoke({action:qualifying?'qualify_scope':'start_scope',country_code:country,scope_type:scopeType,scope_id:scopeId||null,wave_size:5,sample_size:10});setSyncResult(r);if(qualifying)setPreview(await invoke({action:'preview_scope',country_code:country,scope_type:scopeType,scope_id:scopeId||null}));else await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const countryRows=scopeOptions.countries||[],scopeLabel=scopeType==='country'?country:(scopeOptionLabel||(scopeType==='state'?'State':'University'))
 return <div className="l2o-shell" role="dialog" aria-label="Layer 2 Operations"><header className="l2o-top"><div><span>M2.4.2 · scope sync</span><h1>Layer 2 — Enrichment</h1><p>Layer 1 defines the full catalogue scope. Layer 2 shows what is qualified, samples what is not, then handles governed acquisition, Evidence and deterministic fall-out.</p></div><div className="l2o-top-actions"><button onClick={()=>openChild('.l2-launcher')}><Cog size={14}/> Advanced configuration</button><button onClick={load} disabled={busy} aria-label="Refresh Layer 2"><RefreshCw size={15}/></button><button onClick={onClose} aria-label="Close Layer 2"><X size={16}/></button></div></header><main className="l2o-main">{error&&<div className="l2o-error">{error}</div>}
 <section className="l2o-panel l2o-sync-panel"><div className="l2o-panel-head"><div><h2>Sync Course enrichment</h2><p>Country, State or University is resolved from the full Layer 1 catalogue. Qualified institutions can sync; unqualified institutions enter bounded sample qualification waves.</p></div></div>
 <div className="l2o-sync-selectors"><label>Country<select aria-label="Layer 2 sync country" value={country} onChange={e=>chooseCountry(e.target.value)}>{countryRows.map(x=><option key={x.code} value={x.code}>{x.name} ({x.code}) · {x.providers||0} institutions · {x.courses||0} Courses</option>)}</select></label><label>Fetch scope<select aria-label="Layer 2 fetch scope" value={scopeType} onChange={e=>chooseType(e.target.value)}><option value="country">Country — full Layer 1 catalogue</option><option value="state">State — full Layer 1 catalogue in state</option><option value="university">University / provider — all Layer 1 Courses</option></select></label>{scopeType==='state'&&<PagedScopeSelect ariaLabel="Layer 2 sync state" label="State" kind="state" country={country} value={scopeId} valueLabel={scopeOptionLabel} loadPage={scopePage} onChange={chooseScope}/>} {scopeType==='university'&&<PagedScopeSelect ariaLabel="Layer 2 sync university" label="University" kind="university" country={country} value={scopeId} valueLabel={scopeOptionLabel} loadPage={scopePage} onChange={chooseScope}/>} </div>
 {preview?<div className="l2o-sync-card"><div><strong>{scopeLabel}</strong><span>{preview.university_count||0} institution{Number(preview.university_count||0)===1?'':'s'} · {preview.qualified_provider_count||0} Layer 2 qualified · {preview.active_run_count||0} active managed run(s)</span><small>Layer 1 catalogue visibility is complete. Unqualified institutions are sampled in bounded 5-institution × 10-Course waves before any full Layer 2 execution.</small></div><div className="l2o-sync-counts"><Metric label="Layer 1 Institutions" value={preview.university_count||0}/><Metric label="Layer 1 Courses" value={preview.catalogue_count||0}/><Metric label="L2 Qualified" value={preview.qualified_provider_count||0}/><Metric label="Needs qualification" value={preview.qualification_required_count||0}/><Metric label="Ready with governed URL" value={preview.queueable_count||0}/></div>{scopeType==='state'&&scopeId&&<ScopeUniversityList country={country} stateId={scopeId} total={Number(preview.university_count||0)} loadPage={scopePage}/>} <div className="l2o-sync-action"><div><strong>{preview.recommended_action==='qualify_wave'?'Qualification wave required':Number(preview.active_run_count||0)>0?'Existing run(s) will be preserved':Number(preview.needs_discovery_count||0)>0?'Discover then sync':'Ready for managed sync'}</strong><span>{preview.recommended_action==='qualify_wave'?'The next bounded wave selects up to 5 unqualified Layer 1 institutions and 10 representative Courses per institution. It authorises no canonical, Search or Publication mutation.':Number(preview.needs_discovery_count||0)>0?'Layer 2 discovers only Courses inside the qualified scope, then queues governed URLs. Unresolved pages remain explicit fall-out.':'All scoped qualified Courses with governed URLs use the stored ordered route policy.'}</span></div><button disabled={busy||Number(preview.catalogue_count||0)===0} onClick={runSync}>{preview.recommended_action==='qualify_wave'?'Qualify next wave':Number(preview.needs_discovery_count||0)>0?'Discover & sync':'Sync now'}</button></div>{syncResult&&<div className="l2o-success">{syncResult.status==='qualification_wave_planned'?`Qualification wave planned: ${syncResult.provider_count||0} institutions / ${syncResult.course_sample_count||0} Course samples. No canonical/Search/Publication mutation authorised.`:`Scope accepted. ${syncResult.profiles?.length||0} qualified profile workflow(s) started or reconciled. Progress is available below and in Jobs & Runs.`}</div>}</div>:<div className="l2o-empty">{busy?'Resolving scope…':'No authorised Courses found for this scope.'}</div>}</section>
 <section className="l2o-kpis"><Kpi icon={<Activity/>} value={active?human(active.status):'Idle'} label="Layer 2 current run"/><Kpi icon={<Database/>} value={preview?preview.catalogue_count||0:catalogue} label="Selected scope Courses"/><Kpi icon={<Gauge/>} value={preview?preview.queueable_count||0:queueable} label="Ready with governed URL"/><Kpi icon={<Archive/>} value={ev.count||0} label="Layer 2 Evidence"/></section>
 <section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Current progress</h2><p>Bounded execution continues automatically until each managed batch is exhausted.</p></div><button className="l2o-icontext" onClick={()=>openNav('Jobs & Runs')}>Jobs & Runs</button></div>{active?<div className="l2o-active"><strong>{human(active.status)} · {active.processed_count}/{active.target_count}</strong><div className="l2o-progress"><i style={{width:`${active.progress_percent||pct(active.processed_count,active.target_count)}%`}}/></div><span>{active.progress_percent||pct(active.processed_count,active.target_count)}% · L2 {active.resolved_l2_count} · L3 {active.escalated_l3_count} · blocked {active.blocked_count}</span><small>Heartbeat {fmtDate(active.heartbeat_at)} · runtime {active.runtime_seconds??'—'}s</small></div>:<div className="l2o-empty">No active managed Layer 2 run.</div>}</section>
 <div className="l2o-two"><section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Results / Data Quality</h2><p>Resolved and unresolved deterministic enrichment outcomes.</p></div></div><div className="l2o-metric-grid"><Metric label="L2 resolved" value={outcomes.enriched||0}/><Metric label="To Layer 3" value={outcomes.unresolved||0}/><Metric label="Blocked" value={outcomes.failed||0}/><Metric label="Fields resolved" value={outcomes.fields_resolved||0}/></div><button className="l2o-wide" onClick={()=>openNav('Data Quality')}>Open Data Quality <ChevronRight size={14}/></button></section><section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Evidence</h2><p>Native and normalized Layer 2 Evidence remains private and versioned.</p></div></div><div className="l2o-evidence"><ShieldCheck size={22}/><div><strong>{ev.count||0} artifacts · {ev.unreviewed||0} unreviewed</strong><span>Retention and audit history are preserved.</span><small>Latest capture {fmtDate(ev.latest)}</small></div></div><button className="l2o-wide" onClick={()=>openNav('Evidence & Provenance')}>Open Evidence <ChevronRight size={14}/></button></section></div>
 <section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Recent managed runs</h2><p>Simple run history; detailed provider attempts remain in Advanced/Jobs.</p></div></div>{runs.length?<div className="l2o-runs"><div className="l2o-run-head"><span>Status</span><span>Progress</span><span>L2 resolved</span><span>To L3</span><span>Blocked</span><span>Cost</span><span>Runtime</span></div>{runs.map(r=><div className="l2o-run" key={r.id}><span className={`l2o-state ${r.status}`}>{human(r.status)}</span><span>{r.processed_count}/{r.target_count} · {r.progress_percent||0}%</span><span>{r.resolved_l2_count}</span><span>{r.escalated_l3_count}</span><span>{r.blocked_count}</span><span>{Number(r.vendor_cost_usd||0)>0?`$${Number(r.vendor_cost_usd).toFixed(2)}`:'—'}</span><span>{r.runtime_seconds!=null?`${r.runtime_seconds}s`:'—'}</span></div>)}</div>:<div className="l2o-empty">No managed Layer 2 batches yet.</div>}</section>
 <section className="l2o-panel l2o-blockers"><div className="l2o-panel-head"><div><h2>Blockers / required actions</h2><p>Only conditions requiring operator attention are shown here.</p></div></div>{blockers.length?blockers.map((b,i)=><div className="l2o-blocker" key={i}><AlertTriangle size={15}/><span>{b}</span></div>):<div className="l2o-ok">No current operational blocker detected.</div>}</section>
 </main></div>}


function PagedScopeSelect({ariaLabel,label,kind,country,value,valueLabel,loadPage,onChange}){const[open,setOpen]=useState(false),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[data,setData]=useState({items:[],total:0,has_more:false}),[loading,setLoading]=useState(false);const debounced=useMemo(()=>search,[search]);useEffect(()=>{setOffset(0)},[search,country,kind]);useEffect(()=>{if(!open)return;let live=true;setLoading(true);const t=setTimeout(()=>loadPage(kind,{countryCode:country,query:search,offset}).then(x=>live&&setData(x||{items:[],total:0,has_more:false})).catch(()=>live&&setData({items:[],total:0,has_more:false})).finally(()=>live&&setLoading(false)),220);return()=>{live=false;clearTimeout(t)}},[open,kind,country,search,offset]);const page=Math.floor(offset/10)+1,pages=Math.max(1,Math.ceil(Number(data.total||0)/10));return <label className="l2o-paged-scope">{label}<button type="button" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(x=>!x)}><span>{valueLabel||`Choose ${label.toLowerCase()}`}</span><ChevronRight size={14}/></button>{open&&<div className="l2o-scope-popover" role="listbox" aria-label={`${label} options`}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${label.toLowerCase()}…`}/>{loading&&<small>Loading…</small>}{(data.items||[]).map(x=><button type="button" role="option" aria-selected={String(value)===String(x.value)} key={x.value} onClick={()=>{onChange(x.value,x.label);setOpen(false);setSearch('');setOffset(0)}}><span>{x.label}</span>{x.meta&&<small>{x.meta}</small>}</button>)}{!loading&&!(data.items||[]).length&&<small>No matching options</small>}{Number(data.total||0)>10&&<div className="l2o-scope-pager"><button type="button" disabled={offset===0} onClick={()=>setOffset(o=>Math.max(0,o-10))}>Previous</button><span>{page} / {pages}</span><button type="button" disabled={!data.has_more} onClick={()=>setOffset(o=>o+10)}>Next</button></div>}</div>}</label>}

function ScopeUniversityList({country,stateId,total,loadPage}){const[offset,setOffset]=useState(0),[data,setData]=useState({items:[],total:0,has_more:false}),[loading,setLoading]=useState(false);useEffect(()=>{setOffset(0)},[country,stateId]);useEffect(()=>{let live=true;setLoading(true);loadPage('university',{countryCode:country,stateId,offset}).then(x=>live&&setData(x||{items:[],total:0,has_more:false})).catch(()=>live&&setData({items:[],total:0,has_more:false})).finally(()=>live&&setLoading(false));return()=>{live=false}},[country,stateId,offset]);const count=Number(data.total||total||0),page=Math.floor(offset/10)+1,pages=Math.max(1,Math.ceil(count/10));return <div className="l2o-scope-universities"><div><strong>Institutions included in this State</strong><span>{count} Layer 1 institution(s)</span></div><div className="l2o-scope-university-list">{loading?<small>Loading…</small>:(data.items||[]).map(x=><div key={x.value}><span>{x.label}</span><small>{x.meta}</small></div>)}</div>{count>10&&<div className="l2o-scope-pager"><button disabled={offset===0} onClick={()=>setOffset(o=>Math.max(0,o-10))}>Previous</button><span>{page} / {pages}</span><button disabled={!data.has_more} onClick={()=>setOffset(o=>o+10)}>Next</button></div>}</div>}

function PolicyModal({source,rank,onClose,onSaved}){const[mode,setMode]=useState(source.schedule_mode||'manual'),[batch,setBatch]=useState(source.batch_size||10),[routing,setRouting]=useState(source.routing_strategy||'direct_then_best_value'),[paid,setPaid]=useState(source.max_paid_attempts_per_entity||2),[concurrency,setConcurrency]=useState(source.max_concurrency||1),[busy,setBusy]=useState(false),[error,setError]=useState('');const save=async()=>{if(rank<5){setError('PIM Admin role required');return}setBusy(true);setError('');try{const patch={schedule_mode:mode,batch_size:Number(batch),routing_strategy:routing,max_paid_attempts_per_entity:Number(paid),max_concurrency:Number(concurrency),auto_handoff_layer3:true,stop_on_identity_mismatch:true};const{data,e}=await supabase.functions.invoke('layer2-config-control',{body:{action:'update_policy',profile_id:source.profile_id,patch}});if(e)throw e;if(data?.error)throw new Error(data.error);await onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="l2o-modal"><div className="l2o-card"><div className="l2o-modal-head"><div><small>{source.country_code} · {source.data_type}</small><h2>{source.provider_name||source.source_label}</h2></div><button onClick={onClose}><X size={15}/></button></div><label>Automation<select value={mode} onChange={e=>setMode(e.target.value)}><option value="manual">Manual</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="disabled">Disabled</option></select></label><label>Batch size<input type="number" min="1" max="500" value={batch} onChange={e=>setBatch(e.target.value)}/></label><label>Run concurrency<input type="number" min="1" max="8" value={concurrency} onChange={e=>setConcurrency(e.target.value)}/></label><label>Provider routing<select value={routing} onChange={e=>setRouting(e.target.value)}><option value="direct_then_best_value">Direct first · best-value fallback</option><option value="lowest_cost_proven">Lowest-cost proven</option><option value="highest_success">Highest success</option><option value="manual_provider">Manual provider</option></select></label><label>Maximum paid attempts / item<input type="number" min="0" max="5" value={paid} onChange={e=>setPaid(e.target.value)}/></label><div className="l2o-note">Run concurrency controls this source profile. Acquisition-vendor concurrency (Firecrawl, Scrape.do, etc.) is configured separately under Advanced provider config.</div>{error&&<div className="l2o-error">{error}</div>}<div className="l2o-actions"><button disabled={busy} onClick={save}>Save policy</button><button onClick={onClose}>Cancel</button></div></div></div>}
function Kpi({icon,value,label}){return <div className="l2o-kpi"><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>}
function Metric({label,value}){return <div className="l2o-metric"><strong>{value}</strong><span>{label}</span></div>}
const root=document.getElementById('layer2-operations-root');if(root)createRoot(root).render(<Entry/>)