import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{RefreshCw,Settings2,ShieldCheck,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import'./layer2-platform.css'

const VERSION='1.0.2'
const CC='CF-CHG-20260823-029'
const SAFE_KEYS=['acquisition_method','base_domain','discovery_url','discovery_strategy','url_patterns','inclusion_rules','exclusion_rules','pagination','headers','authentication','rate_limit_per_minute','concurrency','timeout_seconds','retry','robots_policy','allowed_mime_types','max_payload_mb','parser_profile','target_entity_type','mapping_strategy','stable_identifier_strategy','regulatory_code_extraction','evidence_required','freshness_sla_hours','schedule','content_change_policy','source_authority','operational_owner','change_control_ref']

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false);useEffect(()=>{let live=true;const resolve=async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setRank(0);return}const ctx=await api.context();if(live)setRank(Number(ctx?.role_rank||0))}catch{if(live)setRank(0)}};resolve();const{data}=supabase.auth.onAuthStateChange(()=>resolve());return()=>{live=false;data.subscription.unsubscribe()}},[]);if(rank<4)return null;return <><button className="l2-launcher" onClick={()=>setOpen(true)} title="Open Layer 2 enrichment configuration"><Settings2 size={15}/><span>Layer 2 Config</span></button>{open&&<Console rank={rank} onClose={()=>setOpen(false)}/>}</>}

export function Console({rank,onClose=()=>{},embedded=false,onOpenProviders=()=>{}}){
  const[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[country,setCountry]=useState(''),[method,setMethod]=useState(''),[health,setHealth]=useState(''),[offset,setOffset]=useState(0),[pageMeta,setPageMeta]=useState({total:0,limit:50,has_more:false,summary:{},options:{countries:[],methods:[],health:[]}}),[detail,setDetail]=useState(null),[controlBusy,setControlBusy]=useState(false)
  const load=async(nextOffset=offset)=>{setBusy(true);setError('');try{const r=await adminRead('layer2_profiles',{limit:50,offset:nextOffset,query:q,country,method,health});setRows(r?.items||[]);setPageMeta({total:Number(r?.total||0),limit:Number(r?.limit||50),has_more:Boolean(r?.has_more),summary:r?.summary||{},options:r?.options||{countries:[],methods:[],health:[]}});setOffset(Number(r?.offset||0))}catch(e){setError(e.message)}finally{setBusy(false)}}
  useEffect(()=>{load(0)},[])
  useEffect(()=>{const t=setTimeout(()=>load(0),250);return()=>clearTimeout(t)},[q,country,method,health])
  const shown=rows
  const countries=pageMeta.options?.countries||[],methods=pageMeta.options?.methods||[],healths=pageMeta.options?.health||[]
  const counts={profiles:Number(pageMeta.summary?.profiles||0),valid:Number(pageMeta.summary?.valid||0),healthy:Number(pageMeta.summary?.healthy||0)}
  const openDetail=async id=>{setError('');try{setDetail(await adminRead('layer2_profile_detail',{id}))}catch(e){setError(e.message)}}
  const invoke=async body=>{const{data,error:e}=await supabase.functions.invoke('layer2-config-control',{body});if(e)throw e;if(data?.error)throw new Error(data.error);return data}
  const control=async action=>{if(!detail?.profile?.id)return;setControlBusy(true);setError('');try{await invoke({action,profile_id:detail.profile.id});await load();setDetail(await adminRead('layer2_profile_detail',{id:detail.profile.id}))}catch(e){setError(e.message)}finally{setControlBusy(false)}}
  const createVersion=async({configuration,change_control_ref,uat_ref})=>{if(!detail?.profile?.id)return;setControlBusy(true);setError('');try{await invoke({action:'create_version',profile_id:detail.profile.id,configuration,change_control_ref,uat_ref});await load();setDetail(await adminRead('layer2_profile_detail',{id:detail.profile.id}))}catch(e){setError(e.message);throw e}finally{setControlBusy(false)}}
  return <div className={`l2-shell${embedded?' l2-admin-embedded':''}`} role={embedded?'region':'dialog'} aria-modal={embedded?undefined:'true'} aria-label="Layer 2 enrichment configuration console"><header className="l2-top"><div><span className="l2-kicker">Administration · Layer 2 deterministic enrichment</span><h1>Enrichment Source Configuration</h1><p>Configuration → Acquisition → Evidence → Observation → Canonical Mapping → Review → Search Eligibility → Publication</p></div><div className="l2-actions"><span>v{VERSION}</span><button onClick={load} title="Refresh"><RefreshCw size={16}/></button>{!embedded&&<button onClick={onClose} aria-label="Close"><X size={17}/></button>}</div></header><main className="l2-main">
    <section className="l2-guard"><ShieldCheck size={19}/><div><strong>Configuration is separate from execution.</strong><span>Discovery or successful acquisition never authorises direct canonical mutation. Credentials and service-role secrets are never browser configuration.</span></div></section>
    <div className="l2-cards"><Card label="Profiles" value={counts.profiles}/><Card label="Valid versions" value={counts.valid}/><Card label="Healthy" value={counts.healthy}/><Card label="Matching" value={pageMeta.total}/></div>
    <div className="l2-toolbar"><button type="button" className="l2-btn" onClick={()=>embedded?onOpenProviders():document.querySelector('.l2p-launcher')?.click()}>Acquisition providers</button><input aria-label="Search profiles" placeholder="Search source, provider, profile or blocker…" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Country filter" value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{countries.map(x=><option key={x} value={x}>{x}</option>)}</select><select aria-label="Acquisition method filter" value={method} onChange={e=>setMethod(e.target.value)}><option value="">All methods</option>{methods.map(x=><option key={x} value={x}>{human(x)}</option>)}</select><select aria-label="Health filter" value={health} onChange={e=>setHealth(e.target.value)}><option value="">All health</option>{healths.map(x=><option key={x} value={x}>{human(x)}</option>)}</select></div>
    <section className="l2-panel">{error&&<div className="l2-error">{error}</div>}{busy?<div className="l2-spinner">Loading Layer 2 profiles…</div>:shown.length?<div className="l2-table-wrap"><table className="l2-table"><thead><tr><th>Source / profile</th><th>Country</th><th>Method</th><th>Affected scope</th><th>Version</th><th>Validation</th><th>Health</th><th>Last success</th><th>Inventory</th><th>Jobs / Evidence</th><th>Blocker</th></tr></thead><tbody>{shown.map(r=><tr key={r.profile_id} onClick={()=>openDetail(r.profile_id)}><td><div className="l2-title"><strong>{r.source_label}</strong><span>{r.profile_key}</span></div></td><td>{r.country_code||'—'}</td><td>{human(r.acquisition_method)}</td><td><div className="l2-title"><strong>{r.affected_provider_name||human(r.target_entity_type)}</strong><span>{human(r.target_entity_type)}</span></div></td><td>v{r.current_version||'—'}</td><td><Badge value={r.validation_status}/></td><td><Badge value={r.health}/></td><td>{dateTime(r.last_success_at)}</td><td><div className="l2-title"><strong>{r.last_inventory_count==null?'Not inventoried':Number(r.last_inventory_count).toLocaleString()}</strong><span>{dateTime(r.last_inventory_at)}</span></div></td><td>{Number(r.job_count||0).toLocaleString()} / {Number(r.evidence_count||0).toLocaleString()}</td><td>{blocker(r)}</td></tr>)}</tbody></table></div>:<div className="l2-empty">No profiles match the current filters.</div>}<div className="l2-pager"><span>{pageMeta.total?`${offset+1}–${Math.min(offset+pageMeta.limit,pageMeta.total)} of ${pageMeta.total}`:'0 results'}</span><div><button className="l2-btn" disabled={offset===0||busy} onClick={()=>load(Math.max(0,offset-pageMeta.limit))}>Previous</button><button className="l2-btn" disabled={!pageMeta.has_more||busy} onClick={()=>load(offset+pageMeta.limit)}>Next</button></div></div></section>
    <p className="l2-note">Governance: {CC}. Read requires Pipeline Operator (rank 4); governed version creation requires PIM Admin (rank 5); state controls require Platform Admin (rank 6). All mutations are re-authorised server-side.</p>
  </main>{detail&&<Drawer data={detail} rank={rank} busy={controlBusy} onClose={()=>setDetail(null)} onControl={control} onCreateVersion={createVersion}/>}</div>
}

function Drawer({data,rank,busy,onClose,onControl,onCreateVersion}){
  const p=data.profile||{},v=data.current_version||{},history=data.history||[],cfg=v.configuration||{},previous=history.find(h=>Number(h.version_no)===Number(v.version_no)-1),diff=configDiff(cfg,previous?.configuration||null)
  const[editing,setEditing]=useState(false),[text,setText]=useState(JSON.stringify(cfg,null,2)),[cc,setCc]=useState(CC),[uat,setUat]=useState(''),[editError,setEditError]=useState('')
  useEffect(()=>{setText(JSON.stringify(cfg,null,2));setEditing(false);setEditError('')},[v.id])
  const save=async()=>{setEditError('');try{const parsed=JSON.parse(text);await onCreateVersion({configuration:parsed,change_control_ref:cc,uat_ref:uat});setEditing(false)}catch(e){setEditError(e.message||'Unable to create configuration version.')}}
  return <aside className="l2-drawer" aria-label="Layer 2 profile detail"><div className="l2-drawer-head"><div><span className="l2-kicker">{p.profile_key}</span><h2>{p.source_label||'Layer 2 profile'}</h2></div><button className="l2-btn" onClick={onClose}><X size={15}/></button></div><div className="l2-drawer-body">
    <div className="l2-grid"><Fact label="Country" value={p.country_code}/><Fact label="Acquisition" value={human(p.acquisition_method)}/><Fact label="Affected Provider" value={p.affected_provider_name||'Source-scoped / not Provider-linked'}/><Fact label="Target entity" value={human(p.target_entity_type)}/><Fact label="Authority" value={p.authority_class}/><Fact label="Current version" value={`v${v.version_no||'—'} · ${v.validation_status||'unknown'}`}/><Fact label="Last successful run" value={dateTime(p.last_success_at)}/><Fact label="Last failure" value={dateTime(p.last_failure_at)}/><Fact label="Freshness SLA" value={p.freshness_sla_hours?`${p.freshness_sla_hours} hours`:'Not set'}/><Fact label="Schedule" value={p.schedule_text}/><Fact label="Inventory" value={p.last_inventory_count==null?'Not yet inventoried':`${p.last_inventory_count} · ${dateTime(p.last_inventory_at)}`}/><Fact label="Blocker / last error" value={p.last_error||(!p.enabled?'Disabled':p.paused?'Paused':'None')}/></div>
    <div className="l2-section"><h3>Governed non-secret configuration</h3><div className="l2-config">{SAFE_KEYS.filter(k=>cfg[k]!==undefined).map(k=><div className="l2-config-row" key={k}><small>{human(k)}</small><code>{render(cfg[k])}</code></div>)}</div></div>
    <div className="l2-section"><h3>Changes from previous version</h3>{previous?diff.length?<div className="l2-config">{diff.map(d=><div className="l2-config-row" key={d.key}><small>{human(d.key)}</small><code>Previous: {render(d.before)}{`\n`}Current: {render(d.after)}</code></div>)}</div>:<p className="l2-note">No semantic configuration changes detected.</p>:<p className="l2-note">Initial version — no predecessor.</p>}</div>
    <div className="l2-section"><h3>Configuration history</h3><table className="l2-history"><thead><tr><th>Version</th><th>Status</th><th>Hash</th><th>Change Control</th><th>UAT</th><th>Created</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>v{h.version_no}</td><td><Badge value={h.validation_status}/></td><td>{String(h.configuration_hash||'').slice(0,12)}…</td><td>{h.change_control_ref||'—'}</td><td>{h.uat_ref||'—'}</td><td>{dateTime(h.created_at)}</td></tr>)}</tbody></table></div>
    <div className="l2-section"><h3>Traceability</h3><div className="l2-grid"><Fact label="Recent Jobs" value={(data.recent_jobs||[]).length}/><Fact label="Recent Evidence" value={(data.recent_evidence||[]).length}/></div></div>
    {rank>=5&&<div className="l2-section"><h3>Govern configuration</h3>{!editing?<button className="l2-btn" disabled={busy} onClick={()=>setEditing(true)}>Create new version</button>:<div className="l2-editor"><label>Non-secret configuration JSON<textarea aria-label="Layer 2 configuration JSON" value={text} onChange={e=>setText(e.target.value)} rows={18}/></label><div className="l2-editor-grid"><label>Change Control<input value={cc} onChange={e=>setCc(e.target.value)}/></label><label>UAT reference<input value={uat} onChange={e=>setUat(e.target.value)} placeholder="optional until UAT"/></label></div><p className="l2-note">The server rejects secret-like keys and unsafe/incomplete settings before creating the immutable version. Acquisition method and target entity are stable profile identity; create a different profile to change either.</p>{editError&&<div className="l2-error">{editError}</div>}<div className="l2-controlbar"><button className="l2-btn" disabled={busy} onClick={save}>Validate & create version</button><button className="l2-btn" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></div>}</div>}
    {rank>=6?<div className="l2-controlbar"><button className="l2-btn" disabled={busy} onClick={()=>onControl('validate')}>Validate current</button>{p.paused?<button className="l2-btn" disabled={busy} onClick={()=>onControl('resume')}>Resume</button>:<button className="l2-btn" disabled={busy} onClick={()=>onControl('pause')}>Pause</button>}{p.enabled?<button className="l2-btn danger" disabled={busy} onClick={()=>onControl('disable')}>Disable</button>:<button className="l2-btn" disabled={busy} onClick={()=>onControl('enable')}>Enable</button>}</div>:<p className="l2-note">Operational pause/disable controls require Platform Admin.</p>}
  </div></aside>
}

const Card=({label,value})=><div className="l2-card"><small>{label}</small><strong>{Number(value||0).toLocaleString()}</strong></div>
const Fact=({label,value})=><div className="l2-fact"><small>{label}</small><strong>{value??'—'}</strong></div>
const Badge=({value})=><span className={`l2-badge ${String(value||'').toLowerCase()}`}>{human(value||'unknown')}</span>
const human=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const render=v=>v===undefined?'—':typeof v==='string'?v:JSON.stringify(v,null,2)
const dateTime=v=>v?new Date(v).toLocaleString():'—'
const blocker=r=>r.validation_status!=='valid'?(r.validation_result?.errors?.[0]||'Configuration invalid'):!r.enabled?'Disabled':r.paused?'Paused':r.health==='stale'?'Freshness SLA exceeded':r.last_error||'None'
function configDiff(current,previous){if(!previous)return[];const keys=[...new Set([...Object.keys(previous),...Object.keys(current)])].sort();return keys.filter(k=>JSON.stringify(previous[k])!==JSON.stringify(current[k])).map(k=>({key:k,before:previous[k],after:current[k]}))}

const root=document.getElementById('layer2-platform-root');if(root)createRoot(root).render(<Entry/>)
