import React,{useEffect,useState}from'react'
import{createRoot}from'react-dom/client'
import{Activity,Archive,ChevronRight,Clock3,Cog,Database,FileSearch,RefreshCw,ShieldCheck,SlidersHorizontal,WalletCards,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import'./layer2-operations.css'

const labelRouting=x=>({direct_then_best_value:'Direct first · best-value fallback',lowest_cost_proven:'Lowest-cost proven',highest_success:'Highest success',manual_provider:'Manual provider'})[x]||x
const human=x=>String(x||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())
const fmtDate=x=>x?new Date(x).toLocaleString():'—'

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false);useEffect(()=>{let live=true;const load=async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setRank(0);return}const c=await api.context();if(live)setRank(Number(c?.role_rank||0))}catch{if(live)setRank(0)}};load();const{data}=supabase.auth.onAuthStateChange(load);return()=>{live=false;data.subscription.unsubscribe()}},[]);if(rank<4)return null;return <><button className="l2o-launcher" onClick={()=>setOpen(true)}><Activity size={15}/><span>Layer 2 Operations</span></button>{open&&<Workspace rank={rank} onClose={()=>setOpen(false)}/>}</>}

function Workspace({rank,onClose}){const[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(null)
 const load=async()=>{setBusy(true);setError('');try{setData(await adminRead('layer2_ops_overview'))}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[])
 const sources=data?.sources||[],providers=data?.providers||[],runs=data?.recent_runs||[],ev=data?.evidence_summary||{}
 const healthy=providers.filter(p=>p.credential_configured||p.provider_key==='direct-http').length
 const openChild=selector=>{onClose();requestAnimationFrame(()=>requestAnimationFrame(()=>document.querySelector(selector)?.click()))}
 const openNav=label=>{onClose();requestAnimationFrame(()=>{const b=[...document.querySelectorAll('.m-nav-item')].find(x=>(x.textContent||'').trim()===label);b?.click()})}
 return <div className="l2o-shell" role="dialog" aria-label="Layer 2 Operations"><header className="l2o-top"><div><span>M2.1 · operational control</span><h1>Layer 2 Operations</h1><p>Courses and Scholarships only</p></div><div className="l2o-top-actions"><button onClick={load} disabled={busy}><RefreshCw size={15}/></button><button onClick={onClose}><X size={16}/></button></div></header><main className="l2o-main">{error&&<div className="l2o-error">{error}</div>}
 <section className="l2o-kpis"><Kpi icon={<Database/>} value={sources.length} label="Enrichment sources"/><Kpi icon={<WalletCards/>} value={`${healthy}/${providers.length}`} label="Acquisition methods ready"/><Kpi icon={<Archive/>} value={ev.count||0} label="Layer 2 Evidence"/><Kpi icon={<FileSearch/>} value={ev.unreviewed||0} label="Needs review"/></section>
 <section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Enrichment plan</h2><p>Schedule, batch size and cost-routing policy.</p></div><button className="l2o-ghost" onClick={()=>openChild('.l2t-launcher')}>Run bounded trial</button></div><div className="l2o-source-list">{sources.map(s=><div className="l2o-source" key={s.profile_id}><div className="l2o-source-main"><div className="l2o-badge">{s.country_code}</div><div><strong>{s.data_type} · {s.provider_name||s.source_label}</strong><span>{s.schedule_mode==='manual'?'Manual':human(s.schedule_mode)} · Batch {s.batch_size} · {labelRouting(s.routing_strategy)}</span><small>Version {s.current_version||'—'} · Last success {fmtDate(s.last_success_at)}</small></div></div><div className="l2o-source-actions"><button onClick={()=>setEditing(s)}><Clock3 size={14}/> Schedule</button><button onClick={()=>openChild('.l2-launcher')}><Cog size={14}/> Advanced</button></div></div>)}</div></section>
 <div className="l2o-two"><section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Provider health</h2><p>Only what affects routing.</p></div><button className="l2o-icontext" onClick={()=>openChild('.l2p-launcher')}><SlidersHorizontal size={14}/> Configure</button></div><div className="l2o-provider-list">{providers.map(p=><div key={p.id}><div><strong>{p.display_name}</strong><span>{p.credential_configured||p.provider_key==='direct-http'?'Ready':'Credential missing'} · concurrency {p.concurrency||1}</span></div><small>{p.last_test_status?`${p.last_test_status} · ${fmtDate(p.last_tested_at)}`:'Not tested'}</small></div>)}</div></section>
 <section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Evidence</h2><p>Private, versioned and reviewable.</p></div></div><div className="l2o-evidence"><ShieldCheck size={22}/><div><strong>{ev.count||0} artifacts</strong><span>Default Layer 2 retention: 365 days. Referenced/held Evidence is protected from routine expiry.</span><small>Latest capture {fmtDate(ev.latest)}</small></div></div><button className="l2o-wide" onClick={()=>openNav('Evidence')}>Open Evidence workspace <ChevronRight size={14}/></button></section></div>
 <section className="l2o-panel"><div className="l2o-panel-head"><div><h2>Recent runs</h2><p>Summary first; drill into Jobs/Evidence only when needed.</p></div><button className="l2o-icontext" onClick={()=>openNav('Jobs')}>Jobs</button></div>{runs.length?<div className="l2o-runs"><div className="l2o-run-head"><span>Status</span><span>Processed</span><span>L2 resolved</span><span>To L3</span><span>Cost</span><span>Started</span></div>{runs.map(r=><div className="l2o-run" key={r.id}><span className={`l2o-state ${r.status}`}>{human(r.status)}</span><span>{r.processed_count}/{r.target_count}</span><span>{r.resolved_l2_count}</span><span>{r.escalated_l3_count}</span><span>{Number(r.vendor_cost_usd||0)>0?`$${Number(r.vendor_cost_usd).toFixed(2)}`:'—'}</span><span>{fmtDate(r.started_at||r.created_at)}</span></div>)}</div>:<div className="l2o-empty">No managed Layer 2 batches yet. Existing provider trials remain available under bounded trial.</div>}</section>
 </main>{editing&&<PolicyModal source={editing} rank={rank} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load()}}/>}</div>}

function PolicyModal({source,rank,onClose,onSaved}){const[mode,setMode]=useState(source.schedule_mode||'manual'),[batch,setBatch]=useState(source.batch_size||10),[routing,setRouting]=useState(source.routing_strategy||'direct_then_best_value'),[paid,setPaid]=useState(source.max_paid_attempts_per_entity||2),[busy,setBusy]=useState(false),[error,setError]=useState('');const save=async()=>{if(rank<5){setError('PIM Admin role required');return}setBusy(true);setError('');try{const ctx=await api.context();const{error:e}=await supabase.rpc('layer2_ops_policy_update',{p_actor:ctx.user_id,p_profile_id:source.profile_id,p_patch:{schedule_mode:mode,batch_size:Number(batch),routing_strategy:routing,max_paid_attempts_per_entity:Number(paid),auto_handoff_layer3:true,stop_on_identity_mismatch:true}});if(e)throw e;await onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="l2o-modal"><div className="l2o-card"><div className="l2o-modal-head"><div><small>{source.country_code} · {source.data_type}</small><h2>{source.provider_name||source.source_label}</h2></div><button onClick={onClose}><X size={15}/></button></div><label>Automation<select value={mode} onChange={e=>setMode(e.target.value)}><option value="manual">Manual</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="disabled">Disabled</option></select></label><label>Batch size<input type="number" min="1" max="500" value={batch} onChange={e=>setBatch(e.target.value)}/></label><label>Provider routing<select value={routing} onChange={e=>setRouting(e.target.value)}><option value="direct_then_best_value">Direct first · best-value fallback</option><option value="lowest_cost_proven">Lowest-cost proven</option><option value="highest_success">Highest success</option><option value="manual_provider">Manual provider</option></select></label><label>Maximum paid attempts / item<input type="number" min="0" max="5" value={paid} onChange={e=>setPaid(e.target.value)}/></label><div className="l2o-note">Unresolved items may pass to Layer 3. Identity mismatches stop automatically. Layer 2 never sends directly to Layer 4.</div>{error&&<div className="l2o-error">{error}</div>}<div className="l2o-actions"><button disabled={busy} onClick={save}>Save policy</button><button onClick={onClose}>Cancel</button></div></div></div>}
function Kpi({icon,value,label}){return <div className="l2o-kpi"><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>}
const root=document.getElementById('layer2-operations-root');if(root)createRoot(root).render(<Entry/>)
