import React,{useEffect,useMemo,useState}from'react'
import{Button,Metric as KitMetric}from'./ui-kit'
import{createRoot}from'react-dom/client'
import{Activity,AlertTriangle,Archive,ChevronRight,Clock3,Cog,Database,Gauge,RefreshCw,ShieldCheck,SlidersHorizontal,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import EnrichmentOperations from'./EnrichmentOperations'
import'./layer2-operations.css'
import{fmtDateTime,fmtMoney,fmtNumber}from'./lib/format.js'
import{jobState}from'./LiveActivity'
import{errorReading}from'./lib/workerErrors'

const human=x=>String(x||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())
const fmtDate=x=>x?fmtDateTime(x):'—'
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
const pct=(a,b)=>b>0?Math.round((100*a/b)*10)/10:0
const measuredBilling=b=>{if(!b)return'Not configured';if(b.subscription_cost_usd==null&&b.monetary_cost_basis==='subscription_cost_not_recorded')return'Quota measured · subscription cost not recorded';if(b.unit_cost_usd===0)return b.source==='internal_no_vendor_fee'?'Measured: no vendor fee':'Configured: US$0 cash/unit';return b.unit_cost_usd!=null?`Configured: ${fmtMoney(b.unit_cost_usd,'USD',{decimals:4})}/unit`:'Cost not available'}

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false);useEffect(()=>{let live=true,seq=0;const resolve=async()=>{const call=++seq;try{const{data}=await supabase.auth.getSession();if(!data.session){if(live&&call===seq)setRank(0);return}let ctx=null,last=null;for(let i=0;i<4&&!ctx;i++){try{ctx=await api.context()}catch(e){last=e;if(i<3)await sleep(250*(i+1))}}if(!ctx)throw last||new Error('context unavailable');if(live&&call===seq)setRank(Number(ctx?.role_rank||0))}catch{if(live&&call===seq){const{data}=await supabase.auth.getSession().catch(()=>({data:{session:null}}));if(!data?.session)setRank(0)}}};resolve();const{data}=supabase.auth.onAuthStateChange(()=>resolve());return()=>{live=false;seq++;data.subscription.unsubscribe()}},[]);if(rank<4)return null;return <><button className="l2o-launcher" onClick={()=>setOpen(true)}><Activity size={15}/><span>Layer 2 Operations</span></button>{open&&<Workspace rank={rank} onClose={()=>setOpen(false)}/>}</>}

export function Workspace({rank,onClose=()=>{},embedded=false,view='overview',navigate=null}){const[data,setData]=useState(null),[parentRuns,setParentRuns]=useState([]),[alerts,setAlerts]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[country,setCountry]=useState(''),[scopeType,setScopeType]=useState('country'),[scopeId,setScopeId]=useState(''),[scopeOptions,setScopeOptions]=useState({countries:[]}),[scopeOptionLabel,setScopeOptionLabel]=useState(''),[preview,setPreview]=useState(null),[syncResult,setSyncResult]=useState(null)
 const invoke=async body=>{const{data:r,error:e}=await supabase.functions.invoke('layer2-sync-control',{body});if(e)throw e;if(r?.error)throw new Error(r.error);return r}
 const scopePage=async(kind,{countryCode=country,stateId=null,query='',offset=0}={})=>invoke({action:'scope_options_page',country_code:countryCode,kind,state_id:stateId,query,limit:10,offset})
 const loadScope=async(c,type=scopeType,current=scopeId)=>{if(!c)return;if(type==='country'){setScopeId('');setScopeOptionLabel('');setPreview(await invoke({action:'preview_background',country_code:c,scope_type:type,scope_id:null}));return}let id=current,label=scopeOptionLabel;if(!id){const page=await scopePage(type,{countryCode:c,offset:0});const first=page.items?.[0];id=first?.value||'';label=first?.label||''}setScopeId(id);setScopeOptionLabel(label);if(!id){setPreview(null);return}setPreview(await invoke({action:'preview_background',country_code:c,scope_type:type,scope_id:id}))}
 const load=async()=>{setBusy(true);setError('');try{const[next,opts,parents]=await Promise.all([adminRead('layer2_ops_overview'),invoke({action:'options'}),adminRead('layer2_parent_runs',{limit:10})]);setData(next);setParentRuns(Array.isArray(parents)?parents:[]);const available=opts.countries||[],chosen=available.some(x=>x.code===country)?country:(available[0]?.code||'');setCountry(chosen);setScopeOptions({countries:available});if(chosen)await loadScope(chosen,scopeType,scopeId)}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[])
 const sources=data?.sources||[],runs=data?.recent_runs||[],attempts=data?.recent_provider_attempts||[],demoFirecrawl=data?.demo_firecrawl_attempt||null,ev=data?.evidence_summary||{},health=data?.health||{},outcomes=data?.outcomes||{},scope=data?.scope_summary||{}
 const active=runs.find(r=>['queued','running'].includes(r.status)),parentActive=parentRuns.find(r=>['planned','scheduled','running','wave1_dispatched'].includes(r.status))||null,latestParent=parentRuns[0]||null,queueable=Number(scope.course_queueable_total||0),catalogue=Number(scope.course_catalogue_total||0),sourceLimited=Math.max(0,catalogue-queueable)
 const openChild=selector=>{onClose();let tries=0;const launch=()=>{const el=document.querySelector(selector);if(el){el.click();return}if(++tries<30)setTimeout(launch,100)};setTimeout(launch,0)}
 const go=(page,params={})=>{if(navigate){navigate(page,params);return}onClose();location.hash=`#${page}${params.tab?`/${params.tab}`:''}`}
 const openNav=label=>{onClose();requestAnimationFrame(()=>{const b=[...document.querySelectorAll('.m-nav-item')].find(x=>(x.textContent||'').trim()===label);b?.click()})}
 const openEvidence=id=>{onClose();location.hash=`#evidence${id?`?evidence_id=${encodeURIComponent(id)}`:''}`}
 const chooseCountry=async c=>{setCountry(c);setScopeId('');setScopeOptionLabel('');setSyncResult(null);setPreview(null);setBusy(true);setError('');try{await loadScope(c,scopeType,'')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const chooseType=async type=>{setScopeType(type);setScopeId('');setScopeOptionLabel('');setSyncResult(null);setPreview(null);setBusy(true);setError('');try{await loadScope(country,type,'')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const chooseScope=async(id,label)=>{setScopeId(id);setScopeOptionLabel(label||'');setSyncResult(null);setPreview(null);setBusy(true);setError('');try{setPreview(await invoke({action:'preview_background',country_code:country,scope_type:scopeType,scope_id:id||null}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 const runSync=async()=>{if(!preview)return;setBusy(true);setError('');setSyncResult(null);try{const r=await invoke({action:'start_background',country_code:country,scope_type:scopeType,scope_id:scopeId||null});setSyncResult(r);setPreview(await invoke({action:'preview_background',country_code:country,scope_type:scopeType,scope_id:scopeId||null}));try{const[next,parents]=await Promise.all([adminRead('layer2_ops_overview'),adminRead('layer2_parent_runs',{limit:10})]);setData(next);setParentRuns(Array.isArray(parents)?parents:[])}catch(refreshError){setError('Production request was accepted, but the operator view could not refresh: '+(refreshError?.message||String(refreshError)))} }catch(e){setError(e.message)}finally{setBusy(false)}}
 const countryRows=scopeOptions.countries||[],scopeLabel=scopeType==='country'?country:(scopeOptionLabel||(scopeType==='state'?'State':'University'))
 // v2.15.128: one view per tab — overview (outcomes), start (fetch a whole area), history (progress, runs, fetches,
 // trace). Provider onboarding moved to Providers › Onboarding (v2.15.131). Removed as duplicates:
 // acquisition policy (Scrapers & fetchers), Data Quality and Evidence boxes (Coverage, Evidence) and the extra tiles row.
 return <div className={embedded?'l2o-shell l2o-embedded':'l2o-shell'} role={embedded?'region':'dialog'} aria-label="Layer 2 Operations" data-l2-view={view}><main className="l2o-main">{error&&<div className="fr-error" role="alert">{error}</div>}
 {view==='overview'&&<>
 <ActionRequired go={go}/>
 <EnrichmentOperations rank={rank} view="overview" openNav={openNav} openEvidence={openEvidence}/>
 </>}
 {view==='start'&&<>
 <section className="l2o-panel l2o-sync-panel"><div className="l2o-panel-head"><div><h2>Fetch an area</h2><p>Pick a country, state or university. Sites not yet checked are checked first in the background; then the courses are fetched in waves on the schedule.</p></div></div>
 <div className="l2o-sync-selectors"><label>Country<select aria-label="Layer 2 sync country" value={country} onChange={e=>chooseCountry(e.target.value)}>{countryRows.map(x=><option key={x.code} value={x.code}>{x.name} ({x.code}) · {x.providers||0} institutions · {x.courses||0} Courses</option>)}</select></label><label>Fetch scope<select aria-label="Layer 2 fetch scope" value={scopeType} onChange={e=>chooseType(e.target.value)}><option value="country">Country — full Layer 1 catalogue</option><option value="state">State — full Layer 1 catalogue in state</option><option value="university">University / provider — all Layer 1 Courses</option></select></label>{scopeType==='state'&&<PagedScopeSelect ariaLabel="Layer 2 sync state" label="State" kind="state" country={country} value={scopeId} valueLabel={scopeOptionLabel} loadPage={scopePage} onChange={chooseScope}/>} {scopeType==='university'&&<PagedScopeSelect ariaLabel="Layer 2 sync university" label="University" kind="university" country={country} value={scopeId} valueLabel={scopeOptionLabel} loadPage={scopePage} onChange={chooseScope}/>} </div>
 {preview?<div className="l2o-sync-card"><div className="cf-metric-grid">
 <KitMetric label="Institutions" value={Number(preview.university_count||0)} detail={`${preview.qualified_provider_count||0} sites checked · ${preview.qualification_required_count||0} still to check`}/>
 <KitMetric label="Courses" value={Number(preview.catalogue_count||0)} detail={`${preview.queueable_count||0} ready to fetch now`}/>
 <KitMetric label="Firecrawl this month" value={`${preview.firecrawl_budget?.used_units??'—'} of ${preview.firecrawl_budget?.limit_units??'—'}`} detail={`${preview.firecrawl?.usable_remaining_units??'—'} usable before the reserve`}/>
 <KitMetric label="Each wave" value={`${preview.production_accepted_wave_size||0} courses`} detail={`Sites are checked ${preview.execution_policy?.qualification_provider_wave_size||'—'} at a time, ${preview.execution_policy?.qualification_sample_size||'—'} sample pages each`}/>
</div>
 {scopeType==='state'&&scopeId&&<ScopeUniversityList country={country} stateId={scopeId} total={Number(preview.university_count||0)} loadPage={scopePage}/>}
 <div className="l2o-sync-action l2-start-row"><div><strong>{Number(preview.qualification_required_count||0)>0?'Sites will be checked first, in the background':'Ready to fetch'}</strong><span>{Number(preview.qualification_required_count||0)>0?('The next scheduler batch can qualify up to '+(preview.execution_policy?.qualification_provider_wave_size||'policy')+' Providers. Each Provider uses one seed acquisition plus '+(preview.execution_policy?.qualification_sample_size||'policy')+' identity samples; the scheduler chains remaining Providers automatically.'):('Production starts up to '+(preview.production_accepted_wave_size||0)+' Courses in the next background wave with Firecrawl, then schedules the rest automatically.')}</span></div><Button disabled={busy||Number(preview.catalogue_count||0)===0} onClick={runSync}>Start production enrichment</Button></div>
 {syncResult&&<div className="l2o-success"><strong>{syncResult.status==='qualification_waiting'?'Production request checked · qualification waiting':syncResult.status==='background_qualification_scheduled'?'Production request accepted · qualification phase':syncResult.status==='background_enrichment_started'?'Production enrichment running':human(syncResult.status||'Production request accepted')}</strong><span>{syncResult.status==='qualification_waiting'?(syncResult.reason||'No Provider is eligible for a new qualification batch inside the current retry window.'):syncResult.status==='background_qualification_scheduled'?('Run '+String(syncResult.qualification?.qualification_run_id||syncResult.run_id||'').slice(0,8)+'… · '+(syncResult.qualification?.provider_count||0)+' Provider(s) scheduled for qualification · scheduler continues automatically.'):syncResult.status==='background_enrichment_started'?('Run '+String(syncResult.production?.run_id||syncResult.production?.batch_id||syncResult.run_id||'').slice(0,8)+'… · '+(syncResult.production?.dispatched_now||0)+' Course(s) dispatched · '+(syncResult.production?.remaining||0)+' scheduled remainder.'):syncResult.reason||'The governed background scheduler owns the next action.'}</span>{syncResult.next_step&&<small>{syncResult.next_step}</small>}<small>Server observed {fmtDate(syncResult.observed_at)}</small><div><button className="l2o-icontext" onClick={()=>openNav('Jobs')}>Open Jobs</button><button className="l2o-icontext" onClick={()=>openNav('Evidence')}>Open Evidence</button></div></div>}
 </div>:<div className="l2o-empty">{busy?'Resolving scope and provider budget…':'No authorised Courses found for this scope.'}</div>}</section>
 </>}
 {view==='history'&&<>
 <DailyProgress/>
 <EnrichmentOperations rank={rank} view="trace" openNav={openNav} openEvidence={openEvidence}/>
 </>}
 </main></div>}

// Decision 220 (v2.15.147): Action required lists only what someone can act on now — Layer 2 jobs (course pages and
// provider reading) that are failing or stuck, and workers sending back errors — each with what it means, what to do
// and a button to the screen where it is done. The old pipeline's alerts (stuck batches, paused profiles) are gone with it.
const L2_AREAS=new Set(['Course pages','Layer 2 reading'])
const TODO={failing:'Open Live activity to read the error. If it keeps failing, switch the job off on Scheduled jobs and report it.',
  stuck:'Work is waiting but none finished in 24 hours. Check Live activity for worker errors — usually the Firecrawl reserve or a site refusing reads.'}
function ActionRequired({go}){const[d,setD]=useState(null),[err,setErr]=useState('')
  useEffect(()=>{let live=true;adminRead('live_activity',{}).then(x=>live&&setD(x||{})).catch(e=>live&&setErr(e.message||String(e)));return()=>{live=false}},[])
  if(err)return <section className="l2o-panel" data-l2-action><div className="fr-error" role="alert">Could not check Layer 2 jobs: {err}</div></section>
  if(!d)return null
  const jobs=(d.jobs||[]).filter(j=>L2_AREAS.has(j.area)),labels=new Set(jobs.map(j=>j.label))
  const items=[...jobs.map(j=>{const[st,,why]=jobState(j);return st==='failing'||st==='stuck'?{key:j.job,title:j.label,state:st==='failing'?'Failing':'Stuck',means:why,todo:TODO[st],jobs:true}:null}).filter(Boolean),
    ...(d.worker_errors||[]).filter(e=>labels.has(e.job)||e.function==='coverage-sweep').map((e,i)=>({key:'w'+i,title:e.job||e.function,state:e.timed_out?'Timed out':e.status==null?'No reply':`Error ${e.status}`,means:errorReading(e),todo:`Seen ${fmtNumber(e.count)} times. Once it is understood, mark it as seen on Live activity; it shows again only if it happens again.`}))]
  return <section className={items.length?'l2o-panel l2o-blockers':'l2o-panel'} data-l2-action>
    <div className="l2o-panel-head"><div><h2>Action required</h2><p>Layer 2 jobs that need someone now, with what to do.</p></div></div>
    {items.length?items.map(it=><div className="l2o-blocker l2o-action" key={it.key} data-l2-action-item>
      <AlertTriangle size={15}/><div><strong>{it.title} · {it.state}</strong><span>{it.means}</span><small>What to do: {it.todo}</small>
        <div className="l2o-action-buttons"><Button compact onClick={()=>go('activity')}>Open Live activity</Button>{it.jobs&&<Button compact onClick={()=>go('jobs',{tab:'automations'})}>Open Scheduled jobs</Button>}</div></div></div>)
    :<div className="l2o-ok" data-l2-action-none>Nothing needs action. Layer 2 jobs are running normally. <Button compact onClick={()=>go('activity')}>Open Live activity</Button></div>}
  </section>}

// Decision 220 (v2.15.147): History shows each country's daily progress — courses with each fact admitted, one row per
// day, with the change from the day before — from the hourly coverage build. It replaces the old pipeline's batch,
// run and fetch lists, which stopped when that pipeline was retired.
const FACTS=[['official_url','Official page'],['english','English'],['intakes','Intakes'],['provider_tuition','Tuition']]
function DailyProgress(){const[country,setCountry]=useState(''),[d,setD]=useState(null),[err,setErr]=useState('')
  useEffect(()=>{let live=true;setErr('');adminRead('course_coverage',country?{country}:{}).then(x=>{if(!live)return;setD(x||{});if(!country){const top=(x?.countries||[])[0]?.code;if(top)setCountry(top)}}).catch(e=>live&&setErr(e.message||String(e)));return()=>{live=false}},[country])
  const days=useMemo(()=>{const m=new Map();for(const t of d?.trend||[]){if(!m.has(t.date))m.set(t.date,{date:t.date,total:0});const r=m.get(t.date);r[t.attribute]=Number(t.admitted||0);r.total=Math.max(r.total,Number(t.total||0))}return[...m.values()].sort((a,b)=>a.date<b.date?1:-1).slice(0,14)},[d])
  return <section className="l2o-panel" data-l2-daily>
    <div className="l2o-panel-head"><div><h2>Daily progress</h2><p>Courses with each fact admitted, by day, for one country. The last build of each day is kept; today updates every hour.</p></div>
      <label className="l2o-country">Country <select aria-label="Daily progress country" value={country} onChange={e=>setCountry(e.target.value)}>{(d?.countries||[]).map(c=><option key={c.code} value={c.code}>{c.code} · {fmtNumber(c.courses)} courses</option>)}</select></label></div>
    {err?<div className="fr-error" role="alert">{err}</div>:!d?<div className="l2o-empty">Loading…</div>:days.length?<div className="cf-table-wrap"><table className="cf-table"><thead><tr><th>Day</th>{FACTS.map(([,l])=><th key={l} className="num">{l}</th>)}<th className="num">Courses</th></tr></thead><tbody>
      {days.map((r,i)=>{const prev=days[i+1];return <tr key={r.date} data-l2-day={r.date}><td>{r.date}</td>{FACTS.map(([k])=>{const v=r[k]||0,ch=prev?v-(prev[k]||0):null;return <td key={k} className="num">{fmtNumber(v)}{ch?<small className="l2o-delta">{ch>0?'+':''}{fmtNumber(ch)}</small>:null}</td>})}<td className="num">{fmtNumber(r.total)}</td></tr>})}
    </tbody></table></div>:<div className="l2o-empty">No daily figures for this country yet.</div>}
  </section>}

function PagedScopeSelect({ariaLabel,label,kind,country,value,valueLabel,loadPage,onChange}){const[open,setOpen]=useState(false),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[data,setData]=useState({items:[],total:0,has_more:false}),[loading,setLoading]=useState(false);const debounced=useMemo(()=>search,[search]);useEffect(()=>{setOffset(0)},[search,country,kind]);useEffect(()=>{if(!open)return;let live=true;setLoading(true);const t=setTimeout(()=>loadPage(kind,{countryCode:country,query:search,offset}).then(x=>live&&setData(x||{items:[],total:0,has_more:false})).catch(()=>live&&setData({items:[],total:0,has_more:false})).finally(()=>live&&setLoading(false)),220);return()=>{live=false;clearTimeout(t)}},[open,kind,country,search,offset]);const page=Math.floor(offset/10)+1,pages=Math.max(1,Math.ceil(Number(data.total||0)/10));return <label className="l2o-paged-scope">{label}<button type="button" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(x=>!x)}><span>{valueLabel||`Choose ${label.toLowerCase()}`}</span><ChevronRight size={14}/></button>{open&&<div className="l2o-scope-popover" role="listbox" aria-label={`${label} options`}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${label.toLowerCase()}…`}/>{loading&&<small>Loading…</small>}{(data.items||[]).map(x=><button type="button" role="option" aria-selected={String(value)===String(x.value)} key={x.value} onClick={()=>{onChange(x.value,x.label);setOpen(false);setSearch('');setOffset(0)}}><span>{x.label}</span>{x.meta&&<small>{x.meta}</small>}</button>)}{!loading&&!(data.items||[]).length&&<small>No matching options</small>}{Number(data.total||0)>10&&<div className="l2o-scope-pager"><button type="button" disabled={offset===0} onClick={()=>setOffset(o=>Math.max(0,o-10))}>Previous</button><span>{page} / {pages}</span><button type="button" disabled={!data.has_more} onClick={()=>setOffset(o=>o+10)}>Next</button></div>}</div>}</label>}

function ScopeUniversityList({country,stateId,total,loadPage}){const[offset,setOffset]=useState(0),[data,setData]=useState({items:[],total:0,has_more:false}),[loading,setLoading]=useState(false);useEffect(()=>{setOffset(0)},[country,stateId]);useEffect(()=>{let live=true;setLoading(true);loadPage('university',{countryCode:country,stateId,offset}).then(x=>live&&setData(x||{items:[],total:0,has_more:false})).catch(()=>live&&setData({items:[],total:0,has_more:false})).finally(()=>live&&setLoading(false));return()=>{live=false}},[country,stateId,offset]);const count=Number(data.total||total||0),page=Math.floor(offset/10)+1,pages=Math.max(1,Math.ceil(count/10));return <div className="l2o-scope-universities"><div><strong>Institutions included in this State</strong><span>{count} Layer 1 institution(s)</span></div><div className="l2o-scope-university-list">{loading?<small>Loading…</small>:(data.items||[]).map(x=><div key={x.value}><span>{x.label}</span><small>{x.meta}</small></div>)}</div>{count>10&&<div className="l2o-scope-pager"><button disabled={offset===0} onClick={()=>setOffset(o=>Math.max(0,o-10))}>Previous</button><span>{page} / {pages}</span><button disabled={!data.has_more} onClick={()=>setOffset(o=>o+10)}>Next</button></div>}</div>}

function PolicyModal({source,rank,onClose,onSaved}){const[mode,setMode]=useState(source.schedule_mode||'manual'),[batch,setBatch]=useState(source.batch_size||10),[routing,setRouting]=useState(source.routing_strategy||'direct_then_best_value'),[paid,setPaid]=useState(source.max_paid_attempts_per_entity||2),[concurrency,setConcurrency]=useState(source.max_concurrency||1),[busy,setBusy]=useState(false),[error,setError]=useState('');const save=async()=>{if(rank<5){setError('PIM Admin role required');return}setBusy(true);setError('');try{const patch={schedule_mode:mode,batch_size:Number(batch),routing_strategy:routing,max_paid_attempts_per_entity:Number(paid),max_concurrency:Number(concurrency),auto_handoff_layer3:true,stop_on_identity_mismatch:true};const{data,e}=await supabase.functions.invoke('layer2-config-control',{body:{action:'update_policy',profile_id:source.profile_id,patch}});if(e)throw e;if(data?.error)throw new Error(data.error);await onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="l2o-modal"><div className="l2o-card"><div className="l2o-modal-head"><div><small>{source.country_code} · {source.data_type}</small><h2>{source.provider_name||source.source_label}</h2></div><button onClick={onClose}><X size={15}/></button></div><label>Automation<select value={mode} onChange={e=>setMode(e.target.value)}><option value="manual">Manual</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="disabled">Disabled</option></select></label><label>Batch size<input type="number" min="1" max="500" value={batch} onChange={e=>setBatch(e.target.value)}/></label><label>Run concurrency<input type="number" min="1" max="8" value={concurrency} onChange={e=>setConcurrency(e.target.value)}/></label><label>Provider routing<select value={routing} onChange={e=>setRouting(e.target.value)}><option value="direct_then_best_value">Direct first · best-value fallback</option><option value="lowest_cost_proven">Lowest-cost proven</option><option value="highest_success">Highest success</option><option value="manual_provider">Manual provider</option></select></label><label>Maximum paid attempts / item<input type="number" min="0" max="5" value={paid} onChange={e=>setPaid(e.target.value)}/></label><div className="l2o-note">Run concurrency controls this source profile. Acquisition-vendor concurrency, credentials and paid-provider ceilings are managed centrally under Administration.</div>{error&&<div className="l2o-error">{error}</div>}<div className="l2o-actions"><button disabled={busy} onClick={save}>Save policy</button><button onClick={onClose}>Cancel</button></div></div></div>}
function Kpi({icon,value,label}){return <KitMetric icon={()=>icon} label={label} value={value}/>}
function Metric({label,value}){return <KitMetric label={label} value={value}/>}
const root=document.getElementById('layer2-operations-root');if(root)createRoot(root).render(<Entry/>)