import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{KeyRound,Network,Plus,RefreshCw,Route,ShieldCheck,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import'./layer2-provider.css'

const CC='CF-CHG-20260823-029'
const EMPTY={provider_key:'',display_name:'',adapter_type:'scraper_api',base_url:'',auth_scheme:'query_param',auth_field_name:'token',capabilities:{raw:true,html:true,json:true,screenshot:false,javascript:true,anti_bot:true,proxy:true},request_template:{target_url_parameter:'url'},enabled:true,priority:100,rate_limit_per_minute:60,concurrency:2,timeout_seconds:45,operational_owner:'Platform Operations',change_control_ref:CC}

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false);useEffect(()=>{let live=true;const resolve=async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setRank(0);return}const ctx=await api.context();if(live)setRank(Number(ctx?.role_rank||0))}catch{if(live)setRank(0)}};resolve();const{data}=supabase.auth.onAuthStateChange(()=>resolve());return()=>{live=false;data.subscription.unsubscribe()}},[]);if(rank<4)return null;return <><button className="l2p-launcher" onClick={()=>setOpen(true)} title="Configure Layer 2 acquisition providers"><Network size={15}/><span>L2 Providers</span></button>{open&&<Console rank={rank} onClose={()=>setOpen(false)}/>}</>}

function Console({rank,onClose}){const[providers,setProviders]=useState([]),[profiles,setProfiles]=useState([]),[selected,setSelected]=useState(null),[profileId,setProfileId]=useState(''),[routes,setRoutes]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[newOpen,setNewOpen]=useState(false)
 const load=async()=>{setBusy(true);setError('');try{const[p,s]=await Promise.all([adminRead('layer2_acquisition_providers'),adminRead('layer2_profiles')]);setProviders(p||[]);setProfiles(s||[]);if(!profileId&&s?.[0]?.profile_id)setProfileId(s[0].profile_id)}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[]);useEffect(()=>{if(!profileId){setRoutes([]);return}adminRead('layer2_provider_routes',{profile_id:profileId}).then(setRoutes).catch(e=>setError(e.message))},[profileId,providers.length]);
 const invoke=async(action,payload)=>{const{data,error:e}=await supabase.functions.invoke('layer2-provider-control',{body:{action,payload}});if(e)throw e;if(data?.error)throw new Error(data.error);return data}
 const saveProvider=async cfg=>{setBusy(true);setError('');try{await invoke('create_provider',cfg);setNewOpen(false);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const setSecret=async(id,secret)=>{setBusy(true);setError('');try{await invoke('set_secret',{id,secret});await load();if(selected?.id===id)setSelected({...selected,credential_configured:true})}catch(e){setError(e.message)}finally{setBusy(false)}}
 const routeProvider=async provider=>{if(!profileId)return;const current=routes.find(r=>r.provider_id===provider.id);const priority=current?.priority||((routes.length+1)*10);setBusy(true);setError('');try{await invoke('upsert_route',{profile_id:profileId,provider_id:provider.id,priority,enabled:true,required_capabilities:{},request_overrides:{},evidence_policy:{capture_raw:true,capture_html:true,capture_screenshot_on_failure:true,capture_screenshot_on_extraction_failure:true},fallback_on:['blocked','timeout','403','429','extraction_failed'],change_control_ref:CC});setRoutes(await adminRead('layer2_provider_routes',{profile_id:profileId}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 const selectedProfile=profiles.find(p=>p.profile_id===profileId)
 return <div className="l2p-shell"><header className="l2p-top"><div><span>M2.1 · acquisition provider control plane</span><h1>Layer 2 Acquisition Providers</h1><p>Provider credential/capability → source route → acquisition attempt → JSON/HTML/screenshot Evidence → extraction/fallback/review</p></div><div><button onClick={load}><RefreshCw size={15}/></button><button onClick={onClose}><X size={16}/></button></div></header><main className="l2p-main">{error&&<div className="l2p-error">{error}</div>}<section className="l2p-guard"><ShieldCheck size={18}/><div><strong>API keys are write-only from the browser.</strong><span>Credentials are stored in Supabase Vault. This screen exposes only whether a credential is configured; it never reads the secret back.</span></div></section>
 <div className="l2p-grid"><section className="l2p-panel"><div className="l2p-panel-head"><div><h2>Acquisition providers</h2><p>Trial multiple scraping/rendering/API providers without changing university-source schema.</p></div>{rank>=6&&<button onClick={()=>setNewOpen(true)}><Plus size={14}/> Add provider</button>}</div><div className="l2p-provider-list">{providers.map(p=><button key={p.id} className={selected?.id===p.id?'active':''} onClick={()=>setSelected(p)}><div><strong>{p.display_name}</strong><span>{p.provider_key} · {human(p.adapter_type)}</span></div><div className="l2p-tags"><Tag text={p.enabled?'Enabled':'Disabled'}/><Tag text={p.credential_configured?'Credential set':p.auth_scheme==='none'?'No credential':'Credential missing'}/>{capLabels(p.capabilities).slice(0,4).map(x=><Tag key={x} text={x}/>)}</div><small>{p.last_test_status?`Last test: ${p.last_test_status}`:'Not yet tested'} · routes {p.route_count||0}</small></button>)}</div></section>
 <section className="l2p-panel"><div className="l2p-panel-head"><div><h2>Provider routing & fallback</h2><p>Choose one university/source profile, then order which acquisition providers may attempt it.</p></div></div><label className="l2p-field">Source profile<select value={profileId} onChange={e=>setProfileId(e.target.value)}>{profiles.map(p=><option key={p.profile_id} value={p.profile_id}>{p.source_label} · {p.profile_key}</option>)}</select></label>{selectedProfile&&<div className="l2p-source-summary"><strong>{selectedProfile.source_label}</strong><span>{selectedProfile.country_code} · {human(selectedProfile.acquisition_method)} · {selectedProfile.affected_provider_name||human(selectedProfile.target_entity_type)}</span></div>}<div className="l2p-route-list">{routes.length?routes.map(r=><div key={r.id}><span className="l2p-order">{r.priority}</span><div><strong>{r.display_name}</strong><small>{human(r.adapter_type)} · {r.credential_configured?'credential ready':'credential not required/missing'}</small><small>Fallback: {(r.fallback_on||[]).join(', ')}</small><small>Evidence: {evidenceText(r.evidence_policy)}</small></div></div>):<p className="l2p-empty">No acquisition providers routed to this source yet.</p>}</div><div className="l2p-add-route"><h3>Add/ensure route</h3>{providers.map(p=><button key={p.id} disabled={busy||routes.some(r=>r.provider_id===p.id)} onClick={()=>routeProvider(p)}><Route size={13}/>{p.display_name}</button>)}</div></section></div>
 {selected&&<ProviderDrawer provider={selected} rank={rank} busy={busy} onClose={()=>setSelected(null)} onSecret={setSecret}/>} {newOpen&&<NewProvider busy={busy} onClose={()=>setNewOpen(false)} onSave={saveProvider}/>}</main></div>}

function ProviderDrawer({provider:p,rank,busy,onClose,onSecret}){const[secret,setSecret]=useState('');return <aside className="l2p-drawer"><div className="l2p-drawer-head"><div><small>{p.provider_key}</small><h2>{p.display_name}</h2></div><button onClick={onClose}><X size={15}/></button></div><div className="l2p-drawer-body"><Info label="Adapter" value={human(p.adapter_type)}/><Info label="Base URL" value={p.base_url||'Provider-specific/runtime'}/><Info label="Auth" value={p.auth_scheme==='none'?'None':`${human(p.auth_scheme)} · ${p.auth_field_name||'provider defined'}`}/><Info label="Credential" value={p.credential_configured?'Configured in Vault':'Not configured'}/><Info label="Timeout / concurrency" value={`${p.timeout_seconds}s / ${p.concurrency}`}/><Info label="Rate limit" value={p.rate_limit_per_minute?`${p.rate_limit_per_minute}/min`:'Not set'}/><section><h3>Capabilities</h3><div className="l2p-tags">{capLabels(p.capabilities).map(x=><Tag key={x} text={x}/>)}</div></section><section><h3>Request template</h3><pre>{JSON.stringify(p.request_template||{},null,2)}</pre></section>{rank>=6&&p.auth_scheme!=='none'&&<section><h3><KeyRound size={15}/> Set / rotate API credential</h3><label className="l2p-field">New credential<input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Stored in Vault; never displayed again"/></label><button disabled={busy||!secret} onClick={async()=>{await onSecret(p.id,secret);setSecret('')}}>Save credential securely</button></section>}<p className="l2p-note">A provider being configured does not authorise canonical mutation. It only makes the provider eligible for a source route and acquisition attempt.</p></div></aside>}

function NewProvider({busy,onClose,onSave}){const[cfg,setCfg]=useState(EMPTY),[caps,setCaps]=useState(JSON.stringify(EMPTY.capabilities,null,2)),[templ,setTempl]=useState(JSON.stringify(EMPTY.request_template,null,2)),[error,setError]=useState('');const save=()=>{try{onSave({...cfg,capabilities:JSON.parse(caps),request_template:JSON.parse(templ)})}catch(e){setError(e.message)}};return <div className="l2p-modal"><div className="l2p-form"><div className="l2p-drawer-head"><h2>Add acquisition provider</h2><button onClick={onClose}><X size={15}/></button></div><label className="l2p-field">Provider key<input value={cfg.provider_key} onChange={e=>setCfg(x=>({...x,provider_key:e.target.value}))} placeholder="e.g. browser-provider-a"/></label><label className="l2p-field">Display name<input value={cfg.display_name} onChange={e=>setCfg(x=>({...x,display_name:e.target.value}))}/></label><label className="l2p-field">Adapter type<select value={cfg.adapter_type} onChange={e=>setCfg(x=>({...x,adapter_type:e.target.value}))}>{['scraper_api','browser_api','structured_api_proxy','direct_http','custom'].map(x=><option key={x} value={x}>{human(x)}</option>)}</select></label><label className="l2p-field">Base URL<input value={cfg.base_url} onChange={e=>setCfg(x=>({...x,base_url:e.target.value}))}/></label><div className="l2p-two"><label className="l2p-field">Auth scheme<select value={cfg.auth_scheme} onChange={e=>setCfg(x=>({...x,auth_scheme:e.target.value}))}>{['none','bearer','header','query_param'].map(x=><option key={x}>{x}</option>)}</select></label><label className="l2p-field">Auth field<input value={cfg.auth_field_name} onChange={e=>setCfg(x=>({...x,auth_field_name:e.target.value}))}/></label></div><label className="l2p-field">Capabilities JSON<textarea rows={7} value={caps} onChange={e=>setCaps(e.target.value)}/></label><label className="l2p-field">Request template JSON<textarea rows={6} value={templ} onChange={e=>setTempl(e.target.value)}/></label>{error&&<div className="l2p-error">{error}</div>}<div className="l2p-actions"><button disabled={busy||!cfg.provider_key||!cfg.display_name} onClick={save}>Create provider</button><button onClick={onClose}>Cancel</button></div></div></div>}

const Tag=({text})=><span className="l2p-tag">{text}</span>;const Info=({label,value})=><div className="l2p-info"><small>{label}</small><strong>{value}</strong></div>;const human=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());const capLabels=c=>Object.entries(c||{}).filter(([,v])=>v===true).map(([k])=>human(k));const evidenceText=p=>Object.entries(p||{}).filter(([,v])=>v===true).map(([k])=>human(k)).join(', ')||'Not specified';
const root=document.getElementById('layer2-provider-root');if(root)createRoot(root).render(<Entry/>);
