import React,{useEffect,useState}from'react'
import{createRoot}from'react-dom/client'
import{KeyRound,Network,Play,Plus,RefreshCw,Route,Search,ShieldCheck,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import ScholarshipRuntimeWorkspace from'./ScholarshipRuntimeWorkspace'
import'./layer2-provider.css'

const CC='CF-CHG-20260827-044'
const EMPTY={provider_key:'',display_name:'',adapter_type:'scraper_api',base_url:'',auth_scheme:'query_param',auth_field_name:'token',capabilities:{raw:true,html:true,json:true,screenshot:false,javascript:true,anti_bot:true,proxy:true},request_template:{target_url_parameter:'url'},billing_config:{currency:'USD',unit:'request'},enabled:true,priority:100,rate_limit_per_minute:60,concurrency:2,timeout_seconds:45,operational_owner:'Platform Operations',change_control_ref:CC}

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false);useEffect(()=>{let live=true;const resolve=async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setRank(0);return}const ctx=await api.context();if(live)setRank(Number(ctx?.role_rank||0))}catch{if(live)setRank(0)}};resolve();const{data}=supabase.auth.onAuthStateChange(()=>resolve());return()=>{live=false;data.subscription.unsubscribe()}},[]);if(rank<4)return null;return <><button className="l2p-launcher" onClick={()=>setOpen(true)} title="Configure Layer 2 acquisition providers"><Network size={15}/><span>L2 Providers</span></button>{open&&<Console rank={rank} onClose={()=>setOpen(false)}/>}</>}

export function Console({rank,onClose=()=>{},embedded=false}){
 const[providers,setProviders]=useState([]),[profiles,setProfiles]=useState([]),[selected,setSelected]=useState(null),[profileId,setProfileId]=useState(''),[routes,setRoutes]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[newOpen,setNewOpen]=useState(false),[run,setRun]=useState(null),[routeOpen,setRouteOpen]=useState(false),[profileQuery,setProfileQuery]=useState(''),[profileMeta,setProfileMeta]=useState({total:0}),[profileBusy,setProfileBusy]=useState(false),[probeBusyId,setProbeBusyId]=useState('')
 const control=async(action,payload={})=>{const{data,error:e}=await supabase.functions.invoke('layer2-provider-control',{body:{action,payload}});if(e)throw e;if(data?.error)throw new Error(data.error);return data}
 const load=async()=>{setBusy(true);setError('');try{const p=await adminRead('layer2_acquisition_providers');setProviders(p||[]);setSelected(current=>current?(p||[]).find(x=>x.id===current.id)||current:current)}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(!routeOpen)return;let live=true;setProfileBusy(true);const t=setTimeout(async()=>{try{const r=await control('profile_options',{query:profileQuery,limit:10,offset:0});if(!live)return;const items=r?.items||[];setProfiles(items);setProfileMeta(r||{total:items.length});if(!profileId&&items[0]?.profile_id)setProfileId(items[0].profile_id);else if(profileId&&!items.some(x=>x.profile_id===profileId)&&items[0]?.profile_id)setProfileId(items[0].profile_id)}catch(e){if(live)setError(e.message)}finally{if(live)setProfileBusy(false)}},220);return()=>{live=false;clearTimeout(t)}},[routeOpen,profileQuery])
 useEffect(()=>{if(!routeOpen||!profileId){setRoutes([]);return}let live=true;adminRead('layer2_provider_routes',{profile_id:profileId}).then(x=>live&&setRoutes(x||[])).catch(e=>live&&setError(e.message));return()=>{live=false}},[routeOpen,profileId,providers.length])
 const saveProvider=async cfg=>{setBusy(true);setError('');try{await control('create_provider',cfg);setNewOpen(false);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const updateProvider=async cfg=>{setBusy(true);setError('');try{await control('update_provider',cfg);const next=await adminRead('layer2_acquisition_providers');const saved=(next||[]).find(x=>x.id===cfg.id);if(!saved)throw new Error('Provider update could not be verified after save');if(Number(saved.concurrency)!==Number(cfg.concurrency)||Number(saved.timeout_seconds)!==Number(cfg.timeout_seconds)||((saved.rate_limit_per_minute??null)!==(cfg.rate_limit_per_minute??null)))throw new Error('Provider settings did not persist exactly; refresh and retry');if(saved.provider_key==='firecrawl'&&Number(saved.billing_config?.monthly_vendor_units_limit)!==Number(cfg.billing_config?.monthly_vendor_units_limit))throw new Error('Firecrawl monthly limit did not persist exactly; refresh and retry');if(saved.provider_key==='firecrawl'&&Number(saved.billing_config?.stop_at_vendor_units_remaining)!==Number(cfg.billing_config?.stop_at_vendor_units_remaining))throw new Error('Firecrawl safety reserve did not persist exactly; refresh and retry');setProviders(next||[]);setSelected(saved);return saved}catch(e){setError(e.message);throw e}finally{setBusy(false)}}
 const setSecret=async(id,secret)=>{setBusy(true);setError('');try{await control('set_secret',{id,secret});await load();setSelected(x=>x?.id===id?{...x,credential_configured:true}:x)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const probeProvider=async provider=>{setProbeBusyId(provider.id);setError('');try{const result=await control('probe_provider',{id:provider.id});await load();return result}catch(e){setError(e.message);throw e}finally{setProbeBusyId('')}}
 const routeProvider=async provider=>{if(!profileId)return;setBusy(true);setError('');try{await control('upsert_route',{profile_id:profileId,provider_id:provider.id,priority:(routes.length+1)*10,enabled:true,required_capabilities:{},request_overrides:{},evidence_policy:{capture_raw:true,capture_html:true,capture_screenshot_on_failure:true,capture_screenshot_on_extraction_failure:true},fallback_on:['blocked','timeout','403','429','5xx','extraction_failed'],change_control_ref:CC});setRoutes(await adminRead('layer2_provider_routes',{profile_id:profileId}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 const acquire=async()=>{if(!profileId)return;setBusy(true);setError('');setRun(null);try{const{data,error:e}=await supabase.functions.invoke('layer2-acquire',{body:{action:'acquire',profile_id:profileId}});if(e)throw e;if(data?.error)throw new Error(data.error);setRun(data)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const selectedProfile=profiles.find(p=>p.profile_id===profileId)
 const canonicalHeader=embedded?<header className="l2p-canonical-head"><div className="m-panel-heading"><span className="m-panel-icon"><Network size={16}/></span><div><h2>Scraper Config</h2><p>Acquisition providers, credentials, limits and profile routing. Routine Layer 2 execution stays in Data Operations.</p></div></div><button className="m-secondary compact" onClick={load} disabled={busy}><RefreshCw size={13}/>Refresh</button></header>:<header className="l2p-top"><div><span>Administration · Scraper Config</span><h1>Scraper Config</h1><p>Acquisition providers, credentials, limits and profile routing.</p></div><div><button onClick={load}><RefreshCw size={15}/></button><button onClick={onClose}><X size={16}/></button></div></header>
 return <div className={`l2p-shell${embedded?' l2p-admin-embedded':''}`} role={embedded?'region':'dialog'} aria-label="Layer 2 acquisition providers">{canonicalHeader}<main className="l2p-main">{error&&<div className="l2p-error">{error}</div>}<section className="l2p-guard"><ShieldCheck size={18}/><div><strong>Credentials stay write-only.</strong><span>Vendor concurrency limits simultaneous calls to one scraper. Run concurrency and enrichment waves are operational controls in Layer 2 — Enrichment.</span></div></section>
 <div className="l2p-grid"><section className="l2p-panel"><div className="l2p-panel-head"><div><h2>Acquisition providers</h2><p>Enablement, credential status, rate, concurrency, timeout and quota.</p></div>{rank>=6&&<button onClick={()=>setNewOpen(true)}><Plus size={14}/> Add provider</button>}</div><div className="l2p-provider-list">{providers.map(p=><button key={p.id} className={selected?.id===p.id?'active':''} onClick={()=>setSelected(p)}><div><strong>{p.display_name}</strong><span>{p.provider_key} · {human(p.adapter_type)}</span></div><div className="l2p-tags"><Tag text={p.enabled?'Enabled':'Disabled'}/><Tag text={p.credential_configured?'Credential set':p.auth_scheme==='none'?'No credential':'Credential missing'}/>{p.last_test_status&&<Tag text={p.last_test_status==='passed'?'Connection passed':'Connection failed'}/>} {capLabels(p.capabilities).slice(0,3).map(x=><Tag key={x} text={x}/>)}</div><small>Concurrency {p.concurrency||1} · rate {p.rate_limit_per_minute??'unlimited'}/min · timeout {p.timeout_seconds}s · routes {p.route_count||0}</small></button>)}</div></section>
 <section className="l2p-panel l2p-routing-panel"><div className="l2p-panel-head"><div><h2>Profile routing</h2><p>Advanced mapping of extraction profiles to ordered acquisition providers.</p></div><button onClick={()=>setRouteOpen(x=>!x)}><Route size={14}/>{routeOpen?'Hide routing':'Manage routes'}</button></div>
 {!routeOpen?<div className="l2p-route-collapsed"><Route size={18}/><div><strong>Loaded only when needed</strong><p>Scraper Config no longer downloads every Layer 2 extraction profile on page load. Open routing only when changing or testing a profile route.</p></div></div>:<>
 <label className="l2p-profile-search"><Search size={15}/><input aria-label="Search extraction profiles" value={profileQuery} onChange={e=>setProfileQuery(e.target.value)} placeholder="Search Provider, source or profile…"/></label>
 <label className="l2p-field">Extraction profile<select aria-label="Layer 2 provider source profile" value={profileId} onChange={e=>{setProfileId(e.target.value);setRun(null)}} disabled={profileBusy}>{profiles.map(p=><option key={p.profile_id} value={p.profile_id}>{p.source_label} · {p.country_code||'—'} · {p.profile_key}</option>)}</select><small>{profileBusy?'Loading up to 10 matches…':`${profiles.length} shown of ${Number(profileMeta.total||0).toLocaleString()} matching profiles`}</small></label>
 {selectedProfile&&<div className="l2p-source-summary"><strong>{selectedProfile.source_label}</strong><span>{selectedProfile.country_code||'—'} · {human(selectedProfile.domain)} · {selectedProfile.affected_provider_name||human(selectedProfile.target_entity_type)}</span></div>}
 <div className="l2p-route-list">{routes.length?routes.map(r=><div key={r.id}><span className="l2p-order">{r.priority}</span><div><strong>{r.display_name}</strong><small>{human(r.adapter_type)} · {r.credential_configured?'credential ready':r.adapter_type==='direct_http'?'no credential required':'credential missing'} · {costText(r.estimated_request_cost_usd)}</small><small>Fallback: {(r.fallback_on||[]).join(', ')}</small></div></div>):<p className="l2p-empty">No providers routed to the selected profile.</p>}</div>
 <div className="l2p-route-actions"><button disabled={busy||!profileId} onClick={acquire}><Play size={14}/> Test selected route</button></div>
 {run&&<div className="l2p-run"><strong>Acquisition PASS · {run.provider_key}</strong><span>HTTP {run.http_status}</span><code>Job {run.job_id} · Evidence {run.evidence_id}</code></div>}
 {rank>=5&&<div className="l2p-add-route"><h3>Add/ensure route</h3>{providers.map(p=><button key={p.id} disabled={busy||routes.some(r=>r.provider_id===p.id)} onClick={()=>routeProvider(p)}><Route size={13}/>{p.display_name}</button>)}</div>}
 </>}</section></div>
 {embedded&&<details className="m-admin-advanced" style={{marginTop:12}}><summary>Scholarship runtime settings</summary><ScholarshipRuntimeWorkspace rank={rank} adminOnly onError={setError}/></details>}
 {selected&&<ProviderDrawer provider={selected} rank={rank} busy={busy} probeBusy={probeBusyId===selected.id} onClose={()=>setSelected(null)} onSecret={setSecret} onUpdate={updateProvider} onProbe={probeProvider}/>} {newOpen&&<NewProvider busy={busy} onClose={()=>setNewOpen(false)} onSave={saveProvider}/>}</main></div>
}
function ProviderDrawer({provider:p,rank,busy,probeBusy,onClose,onSecret,onUpdate,onProbe}){
 const isFirecrawl=p.provider_key==='firecrawl',isParsebot=p.provider_key==='parsebot'
 const[secret,setSecret]=useState(''),[editing,setEditing]=useState(false),[cfg,setCfg]=useState({...p}),[caps,setCaps]=useState(JSON.stringify(p.capabilities||{},null,2)),[templ,setTempl]=useState(JSON.stringify(p.request_template||{},null,2)),[billing,setBilling]=useState(JSON.stringify(p.billing_config||{},null,2)),[monthlyLimit,setMonthlyLimit]=useState(p.billing_config?.monthly_vendor_units_limit??''),[safetyReserve,setSafetyReserve]=useState(p.billing_config?.stop_at_vendor_units_remaining??''),[err,setErr]=useState(''),[saved,setSaved]=useState(''),[probe,setProbe]=useState(null)
 useEffect(()=>{setCfg({...p});setCaps(JSON.stringify(p.capabilities||{},null,2));setTempl(JSON.stringify(p.request_template||{},null,2));setBilling(JSON.stringify(p.billing_config||{},null,2));setMonthlyLimit(p.billing_config?.monthly_vendor_units_limit??'');setSafetyReserve(p.billing_config?.stop_at_vendor_units_remaining??'')},[p.id,p.updated_at,p.concurrency,p.timeout_seconds,p.rate_limit_per_minute,p.billing_config?.monthly_vendor_units_limit,p.billing_config?.stop_at_vendor_units_remaining])
 const save=async()=>{setErr('');setSaved('');try{
  const concurrency=Number(cfg.concurrency),timeout=Number(cfg.timeout_seconds),rate=cfg.rate_limit_per_minute===''||cfg.rate_limit_per_minute==null?null:Number(cfg.rate_limit_per_minute)
  if(!Number.isInteger(concurrency)||concurrency<1||concurrency>20)throw new Error('Vendor concurrency must be an integer from 1 to 20')
  if(!Number.isInteger(timeout)||timeout<1||timeout>120)throw new Error('Timeout must be an integer from 1 to 120 seconds')
  if(rate!=null&&(!Number.isInteger(rate)||rate<1||rate>10000))throw new Error('Rate limit must be an integer from 1 to 10000 requests/minute')
  let billingCfg=JSON.parse(billing)
  if(isFirecrawl){
   const limit=Number(monthlyLimit),reserve=Number(safetyReserve)
   if(!Number.isInteger(limit)||limit<1)throw new Error('Firecrawl monthly limit must be a positive whole number')
   if(!Number.isInteger(reserve)||reserve<0||reserve>=limit)throw new Error('Firecrawl safety reserve must be zero or greater and lower than the monthly limit')
   billingCfg={...billingCfg,monthly_vendor_units_limit:limit,stop_at_vendor_units_remaining:reserve,safety_reserve_percent:Number(((reserve/limit)*100).toFixed(2))}
  }
  const persisted=await onUpdate({id:p.id,display_name:cfg.display_name,base_url:cfg.base_url,auth_scheme:cfg.auth_scheme,auth_field_name:cfg.auth_field_name,capabilities:JSON.parse(caps),request_template:JSON.parse(templ),billing_config:billingCfg,enabled:cfg.enabled,priority:Number(cfg.priority||100),rate_limit_per_minute:rate,concurrency,timeout_seconds:timeout,operational_owner:cfg.operational_owner})
  setCfg({...persisted});setBilling(JSON.stringify(persisted.billing_config||{},null,2));setMonthlyLimit(persisted.billing_config?.monthly_vendor_units_limit??'');setSafetyReserve(persisted.billing_config?.stop_at_vendor_units_remaining??'')
  setSaved(isFirecrawl?`Saved and verified: Firecrawl monthly limit ${Number(persisted.billing_config?.monthly_vendor_units_limit||0).toLocaleString()}, reserve ${Number(persisted.billing_config?.stop_at_vendor_units_remaining||0).toLocaleString()}, rate ${persisted.rate_limit_per_minute??'unlimited'}/min.`:`Saved and verified: vendor concurrency ${persisted.concurrency}, rate ${persisted.rate_limit_per_minute??'unlimited'}/min, timeout ${persisted.timeout_seconds}s.`)
  setEditing(false)
 }catch(e){setErr(e.message)}}
 return <aside className="l2p-drawer"><div className="l2p-drawer-head"><div><small>{p.provider_key}</small><h2>{p.display_name}</h2></div><button onClick={onClose}><X size={15}/></button></div><div className="l2p-drawer-body">
  <Info label="Adapter" value={human(p.adapter_type)}/><Info label="Base URL" value={p.base_url||'Provider-specific/runtime'}/><Info label="Credential" value={p.credential_configured?'Configured in Vault':'Not configured'}/><Info label="Vendor concurrency" value={p.concurrency}/><Info label="Rate / timeout" value={`${p.rate_limit_per_minute??'unlimited'}/min · ${p.timeout_seconds}s`}/>
  {isFirecrawl&&<><Info label="Monthly Firecrawl limit" value={Number(p.billing_config?.monthly_vendor_units_limit||0).toLocaleString()}/><Info label="Safety reserve" value={Number(p.billing_config?.stop_at_vendor_units_remaining||0).toLocaleString()}/></>}
  {saved&&<div className="l2p-run"><strong>{saved}</strong></div>}
  {isParsebot&&<section className="l2p-parsebot-status"><h3>Parse.bot connection & qualification</h3><p><strong>Base URL:</strong> https://api.parse.bot · <strong>Auth:</strong> X-API-Key. Connection testing calls GET /dispatch/tasks and never returns the stored key.</p><p>Parse.bot is not a generic URL proxy. CourseFinder must first create or select a generated Parse API, then store its scraper_id + endpoint_name on the specific extraction profile before runtime execution is qualified.</p><button disabled={probeBusy} onClick={async()=>{setProbe(null);try{setProbe(await onProbe(p))}catch(e){setProbe({ok:false,error:e.message})}}}>{probeBusy?'Testing…':'Test Parse.bot connection'}</button>{probe&&<div className={probe.ok?'l2p-probe pass':'l2p-probe fail'}>{probe.ok?`Connected · HTTP ${probe.http_status} · ${probe.latency_ms}ms`:`Connection failed · ${probe.probe_error||(`HTTP ${probe.http_status||'n/a'}`)}`}<small>Execution qualification: pending generated API route.</small></div>}</section>}
  <section><h3>Capabilities</h3><div className="l2p-tags">{capLabels(p.capabilities).map(x=><Tag key={x} text={x}/>)}</div></section>
  <section><h3>Request template</h3><pre>{JSON.stringify(p.request_template||{},null,2)}</pre></section>
  <section><h3>Billing / effective-cost model</h3>{isFirecrawl?<div className="l2p-budget-summary"><Info label="Plan" value={human(p.billing_config?.plan_tier||'paid')}/><Info label="Monthly units" value={Number(p.billing_config?.monthly_vendor_units_limit||0).toLocaleString()}/><Info label="Reserve" value={Number(p.billing_config?.stop_at_vendor_units_remaining||0).toLocaleString()}/></div>:<pre>{JSON.stringify(p.billing_config||{},null,2)}</pre>}</section>
  {rank>=6&&<section><h3>{isFirecrawl?'Firecrawl scraper configuration':'Provider settings'}</h3>{!editing?<button onClick={()=>{setSaved('');setEditing(true)}}>{isFirecrawl?'Edit Firecrawl configuration':'Edit provider settings'}</button>:<>
   <label className="l2p-field">Display name<input value={cfg.display_name||''} onChange={e=>setCfg(x=>({...x,display_name:e.target.value}))}/></label>
   <label className="l2p-field">Base URL<input value={cfg.base_url||''} onChange={e=>setCfg(x=>({...x,base_url:e.target.value}))}/></label>
   {isFirecrawl&&<div className="l2p-budget-editor"><h4>Plan & budget</h4><div className="l2p-two"><label className="l2p-field">Monthly Firecrawl limit<input aria-label="Firecrawl monthly limit" type="number" min="1" step="1" value={monthlyLimit} onChange={e=>setMonthlyLimit(e.target.value)}/></label><label className="l2p-field">Safety reserve<input aria-label="Firecrawl safety reserve" type="number" min="0" step="1" value={safetyReserve} onChange={e=>setSafetyReserve(e.target.value)}/></label></div><p className="l2p-note">This is the authoritative Firecrawl entitlement used by Layer 2 execution policy and wave clamping. Change it here when the vendor plan changes.</p></div>}
   <div className="l2p-two"><label className="l2p-field">Timeout seconds<input type="number" min="1" max="120" value={cfg.timeout_seconds??30} onChange={e=>setCfg(x=>({...x,timeout_seconds:e.target.value}))}/></label><label className="l2p-field">Vendor concurrency<input aria-label="Acquisition provider concurrency" type="number" min="1" max="20" value={cfg.concurrency??1} onChange={e=>setCfg(x=>({...x,concurrency:e.target.value}))}/></label></div>
   <label className="l2p-field">Rate limit / minute<input aria-label="Acquisition provider rate limit" type="number" min="1" max="10000" value={cfg.rate_limit_per_minute??''} onChange={e=>setCfg(x=>({...x,rate_limit_per_minute:e.target.value}))} placeholder="Blank = provider/runtime default"/></label>
   <label className="l2p-field">Capabilities JSON<textarea rows={7} value={caps} onChange={e=>setCaps(e.target.value)}/></label>
   <label className="l2p-field">Request template JSON<textarea rows={6} value={templ} onChange={e=>setTempl(e.target.value)}/></label>
   {!isFirecrawl&&<label className="l2p-field">Billing / cost model JSON<textarea rows={7} value={billing} onChange={e=>setBilling(e.target.value)}/></label>}
   {isFirecrawl&&<details className="l2p-advanced"><summary>Advanced billing metadata</summary><label className="l2p-field">Billing JSON<textarea rows={7} value={billing} onChange={e=>setBilling(e.target.value)}/></label></details>}
   {err&&<div className="l2p-error">{err}</div>}<div className="l2p-actions"><button disabled={busy} onClick={save}>Save & verify</button><button onClick={()=>setEditing(false)}>Cancel</button></div>
  </>}</section>}
  {rank>=6&&p.auth_scheme!=='none'&&<section><h3><KeyRound size={15}/> Set / rotate API credential</h3><label className="l2p-field">New credential<input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Stored in Vault; never displayed again"/></label><button disabled={busy||!secret} onClick={async()=>{await onSecret(p.id,secret);setSecret('')}}>Save credential securely</button></section>}
  <p className="l2p-note">Scraper/provider settings are the authority for vendor endpoint, credential, rate, concurrency and entitlement. Layer 2 execution policy consumes these effective values; it does not own the vendor quota.</p>
 </div></aside>
}
function NewProvider({busy,onClose,onSave}){const[cfg,setCfg]=useState(EMPTY),[caps,setCaps]=useState(JSON.stringify(EMPTY.capabilities,null,2)),[templ,setTempl]=useState(JSON.stringify(EMPTY.request_template,null,2)),[billing,setBilling]=useState(JSON.stringify(EMPTY.billing_config,null,2)),[error,setError]=useState('');const save=()=>{try{onSave({...cfg,capabilities:JSON.parse(caps),request_template:JSON.parse(templ),billing_config:JSON.parse(billing)})}catch(e){setError(e.message)}};return <div className="l2p-modal"><div className="l2p-form"><div className="l2p-drawer-head"><h2>Add acquisition provider</h2><button onClick={onClose}><X size={15}/></button></div><label className="l2p-field">Provider key<input value={cfg.provider_key} onChange={e=>setCfg(x=>({...x,provider_key:e.target.value}))}/></label><label className="l2p-field">Display name<input value={cfg.display_name} onChange={e=>setCfg(x=>({...x,display_name:e.target.value}))}/></label><label className="l2p-field">Adapter type<select value={cfg.adapter_type} onChange={e=>setCfg(x=>({...x,adapter_type:e.target.value}))}>{['scraper_api','browser_api','structured_api_proxy','direct_http','custom'].map(x=><option key={x} value={x}>{human(x)}</option>)}</select></label><label className="l2p-field">Base URL<input value={cfg.base_url} onChange={e=>setCfg(x=>({...x,base_url:e.target.value}))}/></label><label className="l2p-field">Capabilities JSON<textarea rows={7} value={caps} onChange={e=>setCaps(e.target.value)}/></label><label className="l2p-field">Request template JSON<textarea rows={6} value={templ} onChange={e=>setTempl(e.target.value)}/></label><label className="l2p-field">Billing / cost model JSON<textarea rows={7} value={billing} onChange={e=>setBilling(e.target.value)}/></label>{error&&<div className="l2p-error">{error}</div>}<div className="l2p-actions"><button disabled={busy||!cfg.provider_key||!cfg.display_name} onClick={save}>Create provider</button><button onClick={onClose}>Cancel</button></div></div></div>}

const Tag=({text})=><span className="l2p-tag">{text}</span>;const Info=({label,value})=><div className="l2p-info"><small>{label}</small><strong>{value}</strong></div>;const human=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());const capLabels=c=>Object.entries(c||{}).filter(([,v])=>v===true).map(([k])=>human(k));const costText=v=>v==null?'Cost not configured':Number(v)===0?'No vendor request fee':`Est. US$${Number(v).toFixed(6)} / request`;
const root=document.getElementById('layer2-provider-root');if(root)createRoot(root).render(<Entry/>);