import React,{useEffect,useMemo,useRef,useState}from'react'
import{createRoot}from'react-dom/client'
import{Activity,Database,Play,RefreshCw,Search,Settings2,ShieldCheck,X}from'lucide-react'
import{Button,Empty,Loading,Metric,SectionTitle,StatusChip}from'./ui-kit'
import{adminRead,api,supabase}from'./lib/supabase'
import'./layer2-platform.css'
import{fmtNumber,fmtDateTime}from'./lib/format.js'

const VERSION='1.0.2'
const CC='CF-CHG-20260823-029'
const SAFE_KEYS=['acquisition_method','base_domain','discovery_url','discovery_strategy','url_patterns','inclusion_rules','exclusion_rules','pagination','headers','authentication','rate_limit_per_minute','concurrency','timeout_seconds','retry','robots_policy','allowed_mime_types','max_payload_mb','parser_profile','target_entity_type','mapping_strategy','stable_identifier_strategy','regulatory_code_extraction','evidence_required','freshness_sla_hours','schedule','content_change_policy','source_authority','operational_owner','change_control_ref']

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false);useEffect(()=>{let live=true;const resolve=async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setRank(0);return}const ctx=await api.context();if(live)setRank(Number(ctx?.role_rank||0))}catch{if(live)setRank(0)}};resolve();const{data}=supabase.auth.onAuthStateChange(()=>resolve());return()=>{live=false;data.subscription.unsubscribe()}},[]);if(rank<4)return null;return <><button className="l2-launcher" onClick={()=>setOpen(true)} title="Open Layer 2 enrichment configuration"><Settings2 size={15}/><span>Layer 2 Config</span></button>{open&&<Console rank={rank} onClose={()=>setOpen(false)}/>}</>}

export function Console({rank,onClose=()=>{},embedded=false,onOpenProviders=()=>{}}){
  const[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[country,setCountry]=useState(''),[method,setMethod]=useState(''),[health,setHealth]=useState(''),[offset,setOffset]=useState(0),[pageMeta,setPageMeta]=useState({total:0,limit:50,has_more:false,summary:{},options:{countries:[],methods:[],health:[]}}),[detail,setDetail]=useState(null),[controlBusy,setControlBusy]=useState(false)
  const requestSeq=useRef(0)
  const load=async(nextOffset=offset)=>{const seq=++requestSeq.current;setBusy(true);setError('');try{const r=await adminRead('layer2_profiles',{limit:50,offset:nextOffset,query:q,country,method,health});if(seq!==requestSeq.current)return;setRows(r?.items||[]);setPageMeta({total:Number(r?.total||0),limit:Number(r?.limit||50),has_more:Boolean(r?.has_more),summary:r?.summary||{},options:r?.options||{countries:[],methods:[],health:[]}});setOffset(Number(r?.offset||0))}catch(e){if(seq===requestSeq.current)setError(e.message)}finally{if(seq===requestSeq.current)setBusy(false)}}
  useEffect(()=>{load(0)},[])
  useEffect(()=>{const t=setTimeout(()=>load(0),250);return()=>clearTimeout(t)},[q,country,method,health])
  const shown=rows
  const countries=pageMeta.options?.countries||[],methods=pageMeta.options?.methods||[],healths=pageMeta.options?.health||[]
  const counts={profiles:Number(pageMeta.summary?.profiles||0),valid:Number(pageMeta.summary?.valid||0),healthy:Number(pageMeta.summary?.healthy||0)}
  const openDetail=async id=>{setError('');try{setDetail(await adminRead('layer2_profile_detail',{id}))}catch(e){setError(e.message)}}
  const invoke=async body=>{const{data,error:e}=await supabase.functions.invoke('layer2-config-control',{body});if(e)throw e;if(data?.error)throw new Error(data.error);return data}
  const control=async action=>{if(!detail?.profile?.id)return;setControlBusy(true);setError('');try{await invoke({action,profile_id:detail.profile.id});await load();setDetail(await adminRead('layer2_profile_detail',{id:detail.profile.id}))}catch(e){setError(e.message)}finally{setControlBusy(false)}}
  const createVersion=async({configuration,change_control_ref,uat_ref})=>{if(!detail?.profile?.id)return;setControlBusy(true);setError('');try{await invoke({action:'create_version',profile_id:detail.profile.id,configuration,change_control_ref,uat_ref});await load();setDetail(await adminRead('layer2_profile_detail',{id:detail.profile.id}))}catch(e){setError(e.message);throw e}finally{setControlBusy(false)}}
  // v2.15.127: compact style; the internal governance footer, pipeline banner and the button that left the page
  // are gone. Which fetchers a source uses (routing) is now shown and changed in the source's detail panel.
  const pages=Math.max(1,Math.ceil(pageMeta.total/(pageMeta.limit||50)))
  return <div className="m-page-stack l2-profiles" role="region" aria-label="Source profiles">
    <div className="cf-metric-grid"><Metric label="Source profiles" value={counts.profiles} icon={Database}/><Metric label="Valid settings" value={counts.valid} icon={ShieldCheck} tone={counts.valid<counts.profiles?'warning':'success'}/><Metric label="Healthy" value={counts.healthy} icon={Activity} tone={counts.healthy<counts.profiles?'warning':'success'}/><Metric label="Matching filters" value={pageMeta.total} icon={Search}/></div>
    <section className="m-panel">
      <SectionTitle icon={Settings2} title="Source profiles" subtitle="How each source is fetched and read, and which fetchers it uses. Open a source to see its settings, history and fetchers. Changes create a new version; nothing here changes catalogue values directly." action={<Button compact onClick={()=>load()} disabled={busy}><RefreshCw size={14}/>Refresh</Button>}/>
      <div className="l2-filters"><span className="pq-search"><Search size={14}/><input type="search" aria-label="Search profiles" placeholder="Search source, provider or problem…" value={q} onChange={e=>setQ(e.target.value)}/></span><select aria-label="Country filter" value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{countries.map(x=><option key={x} value={x}>{x}</option>)}</select><select aria-label="Acquisition method filter" value={method} onChange={e=>setMethod(e.target.value)}><option value="">All methods</option>{methods.map(x=><option key={x} value={x}>{human(x)}</option>)}</select><select aria-label="Health filter" value={health} onChange={e=>setHealth(e.target.value)}><option value="">All health</option>{healths.map(x=><option key={x} value={x}>{human(x)}</option>)}</select></div>
      {error&&<div className="fr-error" role="alert">{error}</div>}
      {busy&&!rows.length?<Loading label="Loading source profiles…"/>:shown.length?<div className="cf-table-wrap"><table className="cf-table l2-list"><thead><tr><th>Source</th><th>Country</th><th>Method</th><th>For</th><th>Settings</th><th>Health</th><th>Last success</th><th className="num">Pages found</th><th>Problem</th></tr></thead><tbody>{shown.map(r=><tr key={r.profile_id} className="l2-row" onClick={()=>openDetail(r.profile_id)}><td><button type="button" className="l2-open" onClick={e=>{e.stopPropagation();openDetail(r.profile_id)}}>{r.source_label}</button><small className="l2-sub">{r.profile_key}</small></td><td>{r.country_code||'—'}</td><td>{human(r.acquisition_method)}</td><td>{r.affected_provider_name||human(r.target_entity_type)}</td><td><StatusChip value={r.validation_status} tone={r.validation_status==='valid'?'success':'warning'} label={`v${r.current_version||'—'} · ${human(r.validation_status||'unknown')}`}/></td><td><StatusChip value={r.health} tone={r.health==='healthy'?'success':r.health==='stale'?'warning':'neutral'} label={human(r.health||'unknown')}/></td><td>{dateTime(r.last_success_at)}</td><td className="num">{r.last_inventory_count==null?'—':fmtNumber(r.last_inventory_count)}</td><td className="l2-problem">{blocker(r)}</td></tr>)}</tbody></table></div>:<Empty text="No source profiles match these filters."/>}
      {pageMeta.total>(pageMeta.limit||50)&&<div className="m-pager"><span>Page <strong>{Math.floor(offset/(pageMeta.limit||50))+1}</strong> of {pages} · {fmtNumber(pageMeta.total)} profiles</span><div><Button compact disabled={offset===0||busy} onClick={()=>load(Math.max(0,offset-pageMeta.limit))}>Previous</Button><Button compact disabled={!pageMeta.has_more||busy} onClick={()=>load(offset+pageMeta.limit)}>Next</Button></div></div>}
    </section>
    {detail&&<Drawer data={detail} rank={rank} busy={controlBusy} onClose={()=>setDetail(null)} onControl={control} onCreateVersion={createVersion}/>}
  </div>
}

// v2.15.127: fetchers for one source (moved here from Scrapers & fetchers). Read: admin_read layer2_provider_routes
// and layer2_acquisition_providers; write: layer2-provider-control upsert_route (PIM Admin, rank 5, same payload as
// before); test: layer2-acquire {action:'acquire', profile_id}.
function Fetchers({profileId,rank}){
  const[routes,setRoutes]=useState(null),[providers,setProviders]=useState([]),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[run,setRun]=useState(null)
  const load=async()=>{try{const[r,p]=await Promise.all([adminRead('layer2_provider_routes',{profile_id:profileId}),adminRead('layer2_acquisition_providers')]);setRoutes(r||[]);setProviders((p||[]).filter(x=>x.enabled))}catch(e){setErr(e.message)}}
  useEffect(()=>{setRoutes(null);setRun(null);load()},[profileId])
  const control=async(action,payload)=>{const{data,error}=await supabase.functions.invoke('layer2-provider-control',{body:{action,payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
  const add=async p=>{setBusy(true);setErr('');try{await control('upsert_route',{profile_id:profileId,provider_id:p.id,priority:((routes||[]).length+1)*10,enabled:true,required_capabilities:{},request_overrides:{},evidence_policy:{capture_raw:true,capture_html:true,capture_screenshot_on_failure:true,capture_screenshot_on_extraction_failure:true},fallback_on:['blocked','timeout','403','429','5xx','extraction_failed'],change_control_ref:CC});await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
  const test=async()=>{setBusy(true);setErr('');setRun(null);try{const{data,error}=await supabase.functions.invoke('layer2-acquire',{body:{action:'acquire',profile_id:profileId}});if(error)throw error;if(data?.error)throw new Error(data.error);setRun(data)}catch(e){setErr(e.message)}finally{setBusy(false)}}
  const used=new Set((routes||[]).map(r=>r.provider_id)),free=providers.filter(p=>!used.has(p.id))
  return <div className="l2-section" data-l2-fetchers><h3>Fetchers for this source</h3><p className="l2-note">Tried in this order; the next one is used only when a page is blocked, times out or cannot be read. Fetchers themselves (keys, limits) are set on Scrapers &amp; fetchers.</p>
    {err&&<div className="fr-error" role="alert">{err}</div>}
    {routes===null?<Loading compact label="Loading fetchers…"/>:routes.length?<ol className="l2-fetchers">{routes.map(r=><li key={r.id}><strong>{r.display_name}</strong><small>{r.credential_configured||r.adapter_type==='direct_http'?'Ready':'Key missing'}{r.enabled===false?' · off':''}</small></li>)}</ol>:<Empty text="No fetcher set for this source yet."/>}
    <div className="l2-controlbar">{rank>=4&&<Button compact disabled={busy||!(routes||[]).length} onClick={test}><Play size={13}/>Test fetch one page</Button>}
      {rank>=5&&free.length>0&&<select aria-label="Add a fetcher" value="" disabled={busy} onChange={e=>{const p=free.find(x=>x.id===e.target.value);if(p)add(p)}}><option value="">Add a fetcher as the last step…</option>{free.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select>}</div>
    {run&&<p className="l2-run" role="status">Fetched with {run.provider_key}: HTTP {run.http_status}. Saved as evidence {String(run.evidence_id||'').slice(0,8)}.</p>}
  </div>
}

function Drawer({data,rank,busy,onClose,onControl,onCreateVersion}){
  const p=data.profile||{},v=data.current_version||{},history=data.history||[],cfg=v.configuration||{},previous=history.find(h=>Number(h.version_no)===Number(v.version_no)-1),diff=configDiff(cfg,previous?.configuration||null)
  const[editing,setEditing]=useState(false),[text,setText]=useState(JSON.stringify(cfg,null,2)),[cc,setCc]=useState(CC),[uat,setUat]=useState(''),[editError,setEditError]=useState('')
  useEffect(()=>{setText(JSON.stringify(cfg,null,2));setEditing(false);setEditError('')},[v.id])
  const save=async()=>{setEditError('');try{const parsed=JSON.parse(text);await onCreateVersion({configuration:parsed,change_control_ref:cc,uat_ref:uat});setEditing(false)}catch(e){setEditError(e.message||'Unable to create configuration version.')}}
  return <aside className="l2-drawer" aria-label="Layer 2 profile detail"><div className="l2-drawer-head"><div><span className="l2-kicker">{p.profile_key}</span><h2>{p.source_label||'Layer 2 profile'}</h2></div><button className="l2-btn" onClick={onClose}><X size={15}/></button></div><div className="l2-drawer-body">
    <div className="l2-grid"><Fact label="Country" value={p.country_code}/><Fact label="Acquisition" value={human(p.acquisition_method)}/><Fact label="Affected Provider" value={p.affected_provider_name||'Source-scoped / not Provider-linked'}/><Fact label="Target entity" value={human(p.target_entity_type)}/><Fact label="Authority" value={p.authority_class}/><Fact label="Current version" value={`v${v.version_no||'—'} · ${v.validation_status||'unknown'}`}/><Fact label="Last successful run" value={dateTime(p.last_success_at)}/><Fact label="Last failure" value={dateTime(p.last_failure_at)}/><Fact label="Freshness SLA" value={p.freshness_sla_hours?`${p.freshness_sla_hours} hours`:'Not set'}/><Fact label="Schedule" value={p.schedule_text}/><Fact label="Inventory" value={p.last_inventory_count==null?'Not yet inventoried':`${p.last_inventory_count} · ${dateTime(p.last_inventory_at)}`}/><Fact label="Blocker / last error" value={p.last_error||(!p.enabled?'Disabled':p.paused?'Paused':'None')}/></div>
    <Fetchers profileId={p.id} rank={rank}/>
    <div className="l2-section"><h3>Settings (no secrets)</h3><div className="l2-config">{SAFE_KEYS.filter(k=>cfg[k]!==undefined).map(k=><div className="l2-config-row" key={k}><small>{human(k)}</small><code>{render(cfg[k])}</code></div>)}</div></div>
    <div className="l2-section"><h3>Changes from previous version</h3>{previous?diff.length?<div className="l2-config">{diff.map(d=><div className="l2-config-row" key={d.key}><small>{human(d.key)}</small><code>Previous: {render(d.before)}{`\n`}Current: {render(d.after)}</code></div>)}</div>:<p className="l2-note">No semantic configuration changes detected.</p>:<p className="l2-note">Initial version — no predecessor.</p>}</div>
    <div className="l2-section"><h3>Configuration history</h3><table className="l2-history"><thead><tr><th>Version</th><th>Status</th><th>Hash</th><th>Change Control</th><th>UAT</th><th>Created</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>v{h.version_no}</td><td><Badge value={h.validation_status}/></td><td>{String(h.configuration_hash||'').slice(0,12)}…</td><td>{h.change_control_ref||'—'}</td><td>{h.uat_ref||'—'}</td><td>{dateTime(h.created_at)}</td></tr>)}</tbody></table></div>
    <div className="l2-section"><h3>Traceability</h3><div className="l2-grid"><Fact label="Recent Jobs" value={(data.recent_jobs||[]).length}/><Fact label="Recent Evidence" value={(data.recent_evidence||[]).length}/></div></div>
    {rank>=5&&<div className="l2-section"><h3>Govern configuration</h3>{!editing?<button className="l2-btn" disabled={busy} onClick={()=>setEditing(true)}>Create new version</button>:<div className="l2-editor"><label>Non-secret configuration JSON<textarea aria-label="Layer 2 configuration JSON" value={text} onChange={e=>setText(e.target.value)} rows={18}/></label><div className="l2-editor-grid"><label>Change Control<input value={cc} onChange={e=>setCc(e.target.value)}/></label><label>UAT reference<input value={uat} onChange={e=>setUat(e.target.value)} placeholder="optional until UAT"/></label></div><p className="l2-note">The server rejects secret-like keys and unsafe/incomplete settings before creating the immutable version. Acquisition method and target entity are stable profile identity; create a different profile to change either.</p>{editError&&<div className="l2-error">{editError}</div>}<div className="l2-controlbar"><button className="l2-btn" disabled={busy} onClick={save}>Validate & create version</button><button className="l2-btn" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></div>}</div>}
    {rank>=6?<div className="l2-controlbar"><button className="l2-btn" disabled={busy} onClick={()=>onControl('validate')}>Validate current</button>{p.paused?<button className="l2-btn" disabled={busy} onClick={()=>onControl('resume')}>Resume</button>:<button className="l2-btn" disabled={busy} onClick={()=>onControl('pause')}>Pause</button>}{p.enabled?<button className="l2-btn danger" disabled={busy} onClick={()=>onControl('disable')}>Disable</button>:<button className="l2-btn" disabled={busy} onClick={()=>onControl('enable')}>Enable</button>}</div>:<p className="l2-note">Operational pause/disable controls require Platform Admin.</p>}
  </div></aside>
}

const Fact=({label,value})=><div className="l2-fact"><small>{label}</small><strong>{value??'—'}</strong></div>
const Badge=({value})=><span className={`l2-badge ${String(value||'').toLowerCase()}`}>{human(value||'unknown')}</span>
const human=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const render=v=>v===undefined?'—':typeof v==='string'?v:JSON.stringify(v,null,2)
const dateTime=v=>v?fmtDateTime(v):'—'
const blocker=r=>r.validation_status!=='valid'?(r.validation_result?.errors?.[0]||'Configuration invalid'):!r.enabled?'Disabled':r.paused?'Paused':r.health==='stale'?'Not refreshed on time':r.last_error||'—'
function configDiff(current,previous){if(!previous)return[];const keys=[...new Set([...Object.keys(previous),...Object.keys(current)])].sort();return keys.filter(k=>JSON.stringify(previous[k])!==JSON.stringify(current[k])).map(k=>({key:k,before:previous[k],after:current[k]}))}

const root=document.getElementById('layer2-platform-root');if(root)createRoot(root).render(<Entry/>)
