import React,{useEffect,useMemo,useState}from'react'
import{Activity,RefreshCw,Search,ShieldCheck,SlidersHorizontal}from'lucide-react'
import{adminRead,supabase}from'./lib/supabase'
import'./layer2-dispatcher-tuning.css'

const fmt=n=>n==null?'—':Number(n).toLocaleString(undefined,{maximumFractionDigits:1})
const pct=(a,b)=>b>0?`${(100*a/b).toFixed(1)}%`:'—'
const when=v=>v?new Date(v).toLocaleString():'—'

export default function Layer2DispatcherTuning({rank,onError=()=>{}}){
 const[query,setQuery]=useState(''),[profiles,setProfiles]=useState([]),[profileId,setProfileId]=useState(''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[reason,setReason]=useState(''),[draft,setDraft]=useState({batch_size:10,max_concurrency:1,stale_after_minutes:30,max_paid_attempts_per_entity:2}),[saved,setSaved]=useState('')
 const providerControl=async(payload)=>{const{data,error}=await supabase.functions.invoke('layer2-provider-control',{body:{action:'profile_options',payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
 const load=async id=>{if(!id)return;setBusy(true);setSaved('');try{const x=await adminRead('layer2_dispatcher_tuning',{profile_id:id});setData(x);const p=x?.policy||{};setDraft({batch_size:Number(p.batch_size??10),max_concurrency:Number(p.max_concurrency??1),stale_after_minutes:Number(p.stale_after_minutes??30),max_paid_attempts_per_entity:Number(p.max_paid_attempts_per_entity??2)})}catch(e){onError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{let live=true;const t=setTimeout(async()=>{try{const r=await providerControl({query,limit:10,offset:0});if(!live)return;const items=r?.items||[];setProfiles(items);if(!profileId&&items[0]?.profile_id)setProfileId(items[0].profile_id);else if(profileId&&!items.some(x=>x.profile_id===profileId)&&items[0]?.profile_id)setProfileId(items[0].profile_id)}catch(e){if(live)onError(e.message)}},200);return()=>{live=false;clearTimeout(t)}},[query])
 useEffect(()=>{load(profileId)},[profileId])
 const latest=data?.recent_runs?.[0]
 const prior=data?.recent_runs?.[1]
 const guard=data?.system_guardrails||{}
 const effectiveWave=Math.min(Number(draft.batch_size||1),Number(guard.transport_wave_cap||4))
 const signal=useMemo(()=>{if(!latest)return 'No comparable run yet.';if(Number(latest.blocked_count||0)>0)return 'Blocked outcomes exist; review failure classes before increasing throughput.';if(Number(latest.avg_response_ms||0)>25000)return 'Provider latency is high; preserve conservative concurrency and compare another run before increasing load.';if(Number(latest.active_items||0)>0)return 'Run is active. Policy edits apply to later runs because each batch retains its policy snapshot.';return 'Latest comparable run is terminal. Compare throughput, latency, retries and Evidence before changing settings.'},[latest])
 const save=async()=>{if(rank<5)return;const r=reason.trim();if(r.length<5){onError('Enter a governance reason of at least 5 characters.');return}const vals={batch_size:Number(draft.batch_size),max_concurrency:Number(draft.max_concurrency),stale_after_minutes:Number(draft.stale_after_minutes),max_paid_attempts_per_entity:Number(draft.max_paid_attempts_per_entity)};if(!Number.isInteger(vals.batch_size)||vals.batch_size<1||vals.batch_size>500)return onError('Batch size must be 1–500.');if(!Number.isInteger(vals.max_concurrency)||vals.max_concurrency<1||vals.max_concurrency>8)return onError('Max concurrency must be 1–8.');if(!Number.isInteger(vals.stale_after_minutes)||vals.stale_after_minutes<5||vals.stale_after_minutes>240)return onError('Stale threshold must be 5–240 minutes.');if(!Number.isInteger(vals.max_paid_attempts_per_entity)||vals.max_paid_attempts_per_entity<0||vals.max_paid_attempts_per_entity>5)return onError('Max paid attempts must be 0–5.');setSaving(true);try{const{data:rsp,error}=await supabase.functions.invoke('layer2-config-control',{body:{action:'update_policy',profile_id:profileId,patch:{...vals,_governance_reason:r}}});if(error)throw error;if(rsp?.error)throw new Error(rsp.error);setSaved('Saved for subsequent runs; current running batches retain their existing policy snapshot.');setReason('');await load(profileId)}catch(e){onError(e.message)}finally{setSaving(false)}}
 return <section className="ldt" aria-label="Layer 2 dispatcher tuning">
  <header className="ldt-head"><div><span>Administration · Runtime control</span><h3><SlidersHorizontal size={17}/> Dispatcher tuning & run metrics</h3><p>Compare recent runs and tune bounded Layer 2 dispatcher policy. Vendor rate, timeout, credentials and quota remain in Scraper Config.</p></div><button className="m-secondary compact" onClick={()=>load(profileId)} disabled={busy}><RefreshCw size={13}/>Refresh</button></header>
  <div className="ldt-guard"><ShieldCheck size={17}/><div><strong>Manual governed tuning only.</strong><span>The runtime transport safety cap is {guard.transport_wave_cap??4} items per ordinary invocation ({guard.scraper_first_wave_cap??2} scraper-first). Admin settings cannot bypass this guardrail.</span></div></div>
  <label className="ldt-search"><Search size={14}/><input aria-label="Search dispatcher profiles" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search provider or extraction profile…"/></label>
  <label className="ldt-field">Profile<select aria-label="Dispatcher tuning profile" value={profileId} onChange={e=>setProfileId(e.target.value)}>{profiles.map(p=><option key={p.profile_id} value={p.profile_id}>{p.source_label} · {p.country_code||'—'} · {p.profile_key}</option>)}</select></label>
  {data&&<>
   <div className="ldt-metrics"><Metric label="Effective transport wave" value={`${effectiveWave} / ${guard.transport_wave_cap??4}`}/><Metric label="Configured batch size" value={draft.batch_size}/><Metric label="Run concurrency" value={draft.max_concurrency}/><Metric label="Stale recovery" value={`${draft.stale_after_minutes} min`}/><Metric label="Paid attempts / entity" value={draft.max_paid_attempts_per_entity}/></div>
   <div className="ldt-signal"><Activity size={16}/><div><strong>Decision signal</strong><span>{signal}</span>{latest&&<small>Latest: {fmt(latest.processed_count)}/{fmt(latest.target_count)} processed · {fmt(latest.throughput_items_per_min)} items/min · response {fmt(latest.avg_response_ms)} ms · extraction {fmt(latest.avg_extraction_ms)} ms · retries {fmt(latest.retry_count)} · Evidence {fmt(latest.evidence_count)} · fields {pct(latest.fields_resolved,latest.fields_targeted)}.</small>}</div></div>
   <RunTable runs={(data.recent_runs||[]).slice(0,8)}/>
   <div className="ldt-providers"><h4>Provider runtime — last 24h</h4>{(data.providers||[]).map(p=><div key={p.provider_key}><strong>{p.display_name}</strong><span>Priority {p.priority} · concurrency {p.vendor_concurrency} · rate {p.rate_limit_per_minute??'default'}/min · timeout {p.timeout_seconds}s</span><small>{fmt(p.success_24h)}/{fmt(p.attempts_24h)} succeeded · failures {fmt(p.failed_24h)} · 429s {fmt(p.http_429_24h)} · avg {fmt(p.avg_attempt_ms_24h)} ms</small></div>)}</div>
   {rank>=5&&<div className="ldt-editor"><h4>Tune subsequent runs</h4><div className="ldt-grid"><Num label="Batch size" min={1} max={500} value={draft.batch_size} set={v=>setDraft(x=>({...x,batch_size:v}))}/><Num label="Max concurrent runs" min={1} max={8} value={draft.max_concurrency} set={v=>setDraft(x=>({...x,max_concurrency:v}))}/><Num label="Stale recovery (minutes)" min={5} max={240} value={draft.stale_after_minutes} set={v=>setDraft(x=>({...x,stale_after_minutes:v}))}/><Num label="Max paid attempts / entity" min={0} max={5} value={draft.max_paid_attempts_per_entity} set={v=>setDraft(x=>({...x,max_paid_attempts_per_entity:v}))}/></div><label className="ldt-field">Governance reason<textarea rows="2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why this tuning change is justified by run evidence"/></label><p className="ldt-note">Configured batch size can exceed the transport wave cap for total run scope, but each invocation remains bounded to {guard.transport_wave_cap??4}. Changes never rewrite an in-flight batch snapshot.</p>{saved&&<div className="ldt-saved">{saved}</div>}<button className="m-primary" disabled={saving||busy||!profileId} onClick={save}>{saving?'Saving…':'Save governed tuning'}</button></div>}
   {(data.recent_tuning||[]).length>0&&<details className="ldt-history"><summary>Recent tuning history</summary>{data.recent_tuning.map((x,i)=><div key={`${x.created_at}-${i}`}><strong>{when(x.created_at)}</strong><span>{x.governance_reason}</span><small>{(x.changed_fields||[]).join(', ')}</small></div>)}</details>}
  </>}
 </section>
}
function Metric({label,value}){return <div><small>{label}</small><strong>{value??'—'}</strong></div>}
function Num({label,min,max,value,set}){return <label className="ldt-field">{label}<input type="number" min={min} max={max} step="1" value={value} onChange={e=>set(e.target.value)}/><small>{min}–{max}</small></label>}
function RunTable({runs}){return <div className="ldt-runs"><h4>Latest comparable runs</h4><div className="ldt-table-wrap"><table><thead><tr><th>Started</th><th>Status</th><th>Policy</th><th>Progress</th><th>Items/min</th><th>Response</th><th>Extract</th><th>Retries</th><th>Evidence</th><th>Fields</th><th>L2 / L3 / blocked</th></tr></thead><tbody>{runs.length?runs.map(r=><tr key={r.id}><td>{when(r.started_at||r.created_at)}</td><td>{r.status}</td><td>b{r.policy_snapshot?.batch_size??'—'} · c{r.policy_snapshot?.max_concurrency??'—'} · a{r.policy_snapshot?.max_paid_attempts_per_entity??'—'}</td><td>{fmt(r.processed_count)}/{fmt(r.target_count)}</td><td>{fmt(r.throughput_items_per_min)}</td><td>{fmt(r.avg_response_ms)} ms</td><td>{fmt(r.avg_extraction_ms)} ms</td><td>{fmt(r.retry_count)}</td><td>{fmt(r.evidence_count)}</td><td>{pct(r.fields_resolved,r.fields_targeted)}</td><td>{fmt(r.resolved_l2_count)} / {fmt(r.escalated_l3_count)} / {fmt(r.blocked_count)}</td></tr>):<tr><td colSpan="11">No comparable runs.</td></tr>}</tbody></table></div></div>}
