import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{Database,RefreshCw,Settings2,ShieldCheck,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import'./layer2-platform.css'

const VERSION='1.0.0'
const CC='CF-CHG-20260823-029'
const SAFE_KEYS=['acquisition_method','base_domain','discovery_url','url_patterns','inclusion_rules','exclusion_rules','pagination','headers','authentication','rate_limit_per_minute','concurrency','timeout_seconds','retry','robots_policy','allowed_mime_types','max_payload_mb','parser_profile','target_entity_type','mapping_strategy','stable_identifier_strategy','regulatory_code_extraction','evidence_required','freshness_sla_hours','schedule','content_change_policy','source_authority','operational_owner','change_control_ref']

function Entry(){
  const[rank,setRank]=useState(0),[open,setOpen]=useState(false)
  useEffect(()=>{let live=true;const resolve=async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setRank(0);return}const ctx=await api.context();if(live)setRank(Number(ctx?.role_rank||0))}catch{if(live)setRank(0)}};resolve();const{data}=supabase.auth.onAuthStateChange(()=>resolve());return()=>{live=false;data.subscription.unsubscribe()}},[])
  if(rank<4)return null
  return <><button className="l2-launcher" onClick={()=>setOpen(true)} title="Open Layer 2 enrichment configuration"><Settings2 size={15}/><span>Layer 2 Config</span></button>{open&&<Console rank={rank} onClose={()=>setOpen(false)}/>}</>
}

function Console({rank,onClose}){
  const[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[country,setCountry]=useState(''),[method,setMethod]=useState(''),[health,setHealth]=useState(''),[detail,setDetail]=useState(null),[controlBusy,setControlBusy]=useState(false)
  const load=async()=>{setBusy(true);setError('');try{setRows(await adminRead('layer2_profiles')||[])}catch(e){setError(e.message)}finally{setBusy(false)}}
  useEffect(()=>{load()},[])
  const shown=useMemo(()=>rows.filter(r=>{const text=[r.profile_key,r.source_label,r.country_code,r.acquisition_method,r.domain,r.target_entity_type].filter(Boolean).join(' ').toLowerCase();return(!q||text.includes(q.toLowerCase()))&&(!country||r.country_code===country)&&(!method||r.acquisition_method===method)&&(!health||r.health===health)}),[rows,q,country,method,health])
  const countries=[...new Set(rows.map(r=>r.country_code).filter(Boolean))].sort(),methods=[...new Set(rows.map(r=>r.acquisition_method).filter(Boolean))].sort(),healths=[...new Set(rows.map(r=>r.health).filter(Boolean))].sort()
  const counts={profiles:rows.length,valid:rows.filter(r=>r.validation_status==='valid').length,healthy:rows.filter(r=>r.health==='healthy').length,jobs:rows.reduce((n,r)=>n+Number(r.job_count||0),0),evidence:rows.reduce((n,r)=>n+Number(r.evidence_count||0),0)}
  const openDetail=async id=>{setError('');try{setDetail(await adminRead('layer2_profile_detail',{id}))}catch(e){setError(e.message)}}
  const control=async action=>{if(!detail?.profile?.id)return;setControlBusy(true);setError('');try{const{data,error:e}=await supabase.functions.invoke('layer2-config-control',{body:{action,profile_id:detail.profile.id}});if(e)throw e;if(data?.error)throw new Error(data.error);await load();setDetail(await adminRead('layer2_profile_detail',{id:detail.profile.id}))}catch(e){setError(e.message)}finally{setControlBusy(false)}}
  return <div className="l2-shell" role="dialog" aria-modal="true" aria-label="Layer 2 enrichment configuration console"><header className="l2-top"><div><span className="l2-kicker">M2.1 · Layer 2 deterministic enrichment</span><h1>Enrichment Source Configuration</h1><p>Configuration → Acquisition → Evidence → Observation → Canonical Mapping → Review → Search Admission → Publication</p></div><div className="l2-actions"><span>v{VERSION}</span><button onClick={load} title="Refresh"><RefreshCw size={16}/></button><button onClick={onClose} aria-label="Close"><X size={17}/></button></div></header><main className="l2-main">
    <section className="l2-guard"><ShieldCheck size={19}/><div><strong>Configuration is separate from execution.</strong><span>Discovery or successful acquisition never authorises direct canonical mutation. Credentials and service-role secrets are never browser configuration.</span></div></section>
    <div className="l2-cards"><Card label="Profiles" value={counts.profiles}/><Card label="Valid versions" value={counts.valid}/><Card label="Healthy" value={counts.healthy}/><Card label="Associated jobs" value={counts.jobs}/><Card label="Evidence artifacts" value={counts.evidence}/></div>
    <div className="l2-toolbar"><input aria-label="Search profiles" placeholder="Search source, profile, country or target…" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Country filter" value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{countries.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Acquisition method filter" value={method} onChange={e=>setMethod(e.target.value)}><option value="">All methods</option>{methods.map(x=><option key={x}>{human(x)}</option>)}</select><select aria-label="Health filter" value={health} onChange={e=>setHealth(e.target.value)}><option value="">All health</option>{healths.map(x=><option key={x}>{x}</option>)}</select></div>
    <section className="l2-panel">{error&&<div className="l2-error">{error}</div>}{busy?<div className="l2-spinner">Loading Layer 2 profiles…</div>:shown.length?<div className="l2-table-wrap"><table className="l2-table"><thead><tr><th>Source / profile</th><th>Country</th><th>Method</th><th>Target</th><th>Version</th><th>Validation</th><th>Health</th><th>Freshness / inventory</th><th>Jobs</th><th>Evidence</th><th>Owner</th></tr></thead><tbody>{shown.map(r=><tr key={r.profile_id} onClick={()=>openDetail(r.profile_id)}><td><div className="l2-title"><strong>{r.source_label}</strong><span>{r.profile_key}</span></div></td><td>{r.country_code||'—'}</td><td>{human(r.acquisition_method)}</td><td>{human(r.target_entity_type)}</td><td>v{r.current_version||'—'}</td><td><Badge value={r.validation_status}/></td><td><Badge value={r.health}/></td><td><div className="l2-title"><strong>{freshness(r)}</strong><span>{r.last_inventory_count==null?'No inventory':`${Number(r.last_inventory_count).toLocaleString()} items`}</span></div></td><td>{Number(r.job_count||0).toLocaleString()}</td><td>{Number(r.evidence_count||0).toLocaleString()}</td><td>{r.operational_owner||'—'}</td></tr>)}</tbody></table></div>:<div className="l2-empty">No profiles match the current filters.</div>}</section>
    <p className="l2-note">Governance: {CC}. Read access requires Pipeline Operator or higher. Pause/disable/validate controls require Platform Admin and are re-authorised server-side.</p>
  </main>{detail&&<Drawer data={detail} rank={rank} busy={controlBusy} onClose={()=>setDetail(null)} onControl={control}/>}</div>
}

function Drawer({data,rank,busy,onClose,onControl}){const p=data.profile||{},v=data.current_version||{},history=data.history||[],cfg=v.configuration||{};return <aside className="l2-drawer" aria-label="Layer 2 profile detail"><div className="l2-drawer-head"><div><span className="l2-kicker">{p.profile_key}</span><h2>{p.source_label||'Layer 2 profile'}</h2></div><button className="l2-btn" onClick={onClose}><X size={15}/></button></div><div className="l2-drawer-body"><div className="l2-grid"><Fact label="Country" value={p.country_code}/><Fact label="Acquisition" value={human(p.acquisition_method)}/><Fact label="Target" value={human(p.target_entity_type)}/><Fact label="Authority" value={p.authority_class}/><Fact label="Current version" value={`v${v.version_no||'—'} · ${v.validation_status||'unknown'}`}/><Fact label="Freshness SLA" value={p.freshness_sla_hours?`${p.freshness_sla_hours} hours`:'Not set'}/><Fact label="Schedule" value={p.schedule_text}/><Fact label="Inventory" value={p.last_inventory_count==null?'Not yet inventoried':`${p.last_inventory_count} · ${p.last_inventory_at||''}`}/></div><div className="l2-section"><h3>Governed non-secret configuration</h3><div className="l2-config">{SAFE_KEYS.filter(k=>cfg[k]!==undefined).map(k=><div className="l2-config-row" key={k}><small>{human(k)}</small><code>{render(cfg[k])}</code></div>)}</div></div><div className="l2-section"><h3>Configuration history</h3><table className="l2-history"><thead><tr><th>Version</th><th>Status</th><th>Hash</th><th>Change Control</th><th>Created</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>v{h.version_no}</td><td><Badge value={h.validation_status}/></td><td>{String(h.configuration_hash||'').slice(0,12)}…</td><td>{h.change_control_ref||'—'}</td><td>{dateTime(h.created_at)}</td></tr>)}</tbody></table></div><div className="l2-section"><h3>Traceability</h3><div className="l2-grid"><Fact label="Recent Jobs" value={(data.recent_jobs||[]).length}/><Fact label="Recent Evidence" value={(data.recent_evidence||[]).length}/></div></div>{rank>=6?<div className="l2-controlbar"><button className="l2-btn" disabled={busy} onClick={()=>onControl('validate')}>Validate</button>{p.paused?<button className="l2-btn" disabled={busy} onClick={()=>onControl('resume')}>Resume</button>:<button className="l2-btn" disabled={busy} onClick={()=>onControl('pause')}>Pause</button>}{p.enabled?<button className="l2-btn danger" disabled={busy} onClick={()=>onControl('disable')}>Disable</button>:<button className="l2-btn" disabled={busy} onClick={()=>onControl('enable')}>Enable</button>}</div>:<p className="l2-note">Read-only: Platform Admin is required for validation and state controls.</p>}</div></aside>}

const Card=({label,value})=><div className="l2-card"><small>{label}</small><strong>{Number(value||0).toLocaleString()}</strong></div>
const Fact=({label,value})=><div className="l2-fact"><small>{label}</small><strong>{value??'—'}</strong></div>
const Badge=({value})=><span className={`l2-badge ${String(value||'').toLowerCase()}`}>{human(value||'unknown')}</span>
const human=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const render=v=>typeof v==='string'?v:JSON.stringify(v,null,2)
const dateTime=v=>v?new Date(v).toLocaleString():'—'
function freshness(r){if(!r.enabled)return'Disabled';if(r.paused)return'Paused';if(!r.last_success_at)return'No successful run';const age=Math.round((Date.now()-new Date(r.last_success_at).getTime())/3600000);return`${age}h since success`}

const root=document.getElementById('layer2-platform-root');if(root)createRoot(root).render(<Entry/>)
