import React,{useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{BrainCircuit,CalendarClock,Check,ExternalLink,FileCheck2,Link2,RefreshCw,Route,ShieldCheck,X}from'lucide-react'
import{supabase,api}from'./lib/supabase'
import'./m2-3-intelligence.css'

const human=v=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
const when=v=>v?new Date(v).toLocaleString():'—'
const rpc=async(name,args={})=>{const{data,error}=await supabase.rpc(name,args);if(error)throw error;return data}
const askReason=label=>window.prompt(`${label} — reason (required)`,'M2.3 governed human decision')||''

function Entry(){const[rank,setRank]=useState(0),[open,setOpen]=useState(false),[ticker,setTicker]=useState([])
 useEffect(()=>{let live=true;const load=async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){if(live)setRank(0);return}const c=await api.context();if(live)setRank(Number(c?.role_rank||0));if(Number(c?.role_rank||0)>=2){const d=await rpc('important_dates_ticker',{p_country_code:null,p_days:60});if(live)setTicker(d||[])}}catch{}};load();const{data}=supabase.auth.onAuthStateChange(load);return()=>{live=false;data.subscription.unsubscribe()}},[])
 if(rank<3)return null
 const onDashboard=location.hash===''||location.hash==='#dashboard'
 return <>{onDashboard&&ticker.length>0&&<div className="m23-ticker"><CalendarClock size={14}/><strong>Important:</strong><span>{ticker.slice(0,3).map(d=>`${d.country_code} · ${d.title}${d.starts_at?` · ${new Date(d.starts_at).toLocaleDateString()}`:''}`).join('  •  ')}</span><button onClick={()=>setOpen(true)}>Open</button></div>}<button className="m23-launcher" onClick={()=>setOpen(true)}><BrainCircuit size={15}/>M2.3 Intelligence</button>{open&&<Workspace rank={rank} onClose={()=>setOpen(false)}/>}</>}

function Workspace({rank,onClose}){const[tab,setTab]=useState('Layer 3'),[error,setError]=useState('');const tabs=['Layer 3','Layer 4','Refresh','Important Links','Important Dates'];return <div className="m23-shell" role="dialog" aria-label="M2.3 Intelligence"><header><div><small>M2.3 · CF-CHG-20260825-038</small><h1>Layer 3 / Layer 4 / Refresh Intelligence</h1><p>Governed AI suggestions → human terminal decision → targeted refresh.</p></div><button onClick={onClose}><X size={18}/></button></header><nav>{tabs.map(x=><button className={tab===x?'active':''} key={x} onClick={()=>{setTab(x);setError('')}}>{x}</button>)}</nav>{error&&<div className="m23-error">{error}</div>}<main>{tab==='Layer 3'&&<Layer3 rank={rank} onError={e=>setError(e.message||String(e))}/>} {tab==='Layer 4'&&<Layer4 onError={e=>setError(e.message||String(e))}/>} {tab==='Refresh'&&<Refresh onError={e=>setError(e.message||String(e))}/>} {tab==='Important Links'&&<Links rank={rank} onError={e=>setError(e.message||String(e))}/>} {tab==='Important Dates'&&<Dates rank={rank} onError={e=>setError(e.message||String(e))}/>}</main></div>}

function Layer3({rank,onError}){const[profiles,setProfiles]=useState([]),[runs,setRuns]=useState([]),[busy,setBusy]=useState(false),[form,setForm]=useState({evidence_id:'',entity_type:'course',entity_id:'',task_class:'course_description',profile_id:''});const load=async()=>{setBusy(true);try{const[p,r]=await Promise.all([rpc('layer3_model_profiles_admin'),rpc('layer3_recent_interpretations',{p_limit:100})]);setProfiles(p||[]);setRuns(r||[]);setForm(f=>({...f,profile_id:f.profile_id||p?.[0]?.id||''}))}catch(e){onError(e)}finally{setBusy(false)}};useEffect(()=>{load()},[])
 const run=async()=>{setBusy(true);try{const{data,error}=await supabase.functions.invoke('layer3-interpret',{body:{...form,layer2_state:{status:'unresolved'},interpretation_freshness_days:30}});if(error)throw error;if(data?.error)throw new Error(data.error);await load()}catch(e){onError(e)}finally{setBusy(false)}}
 const toggle=async p=>{if(rank<4)return onError(new Error('Administrator role required to change model state'));const reason=askReason(p.paused?'Resume profile':'Pause profile');if(!reason)return;try{await rpc('layer3_model_profile_set_state',{p_profile_id:p.id,p_enabled:p.enabled,p_paused:!p.paused,p_reason:reason});await load()}catch(e){onError(e)}}
 return <div className="m23-stack"><section className="m23-panel"><Head icon={BrainCircuit} title="Governed model profiles" action={<button onClick={load} disabled={busy}><RefreshCw size={14}/>Refresh</button>}/><div className="m23-cards">{profiles.map(p=><article key={p.id}><div className="m23-row"><strong>{p.code}</strong><State value={p.paused?'paused':p.enabled?'enabled':'disabled'}/></div><span>{p.aggregator_provider} · {p.model_identifier}</span><small>{p.prompt_profile_version} · {p.requests_per_minute}/min · {p.requests_per_day}/day · ceiling ${Number(p.cost_ceiling_usd||0).toFixed(4)}</small><small>Validation: {human(p.last_validation_result?.state||'not validated')}</small><button onClick={()=>toggle(p)}>{p.paused?'Resume after validation':'Pause'}</button></article>)}</div></section>
 <section className="m23-panel"><Head icon={FileCheck2} title="Interpret governed Evidence"/><div className="m23-form-grid"><label>Evidence ID<input value={form.evidence_id} onChange={e=>setForm(f=>({...f,evidence_id:e.target.value}))}/></label><label>Entity ID<input value={form.entity_id} onChange={e=>setForm(f=>({...f,entity_id:e.target.value}))}/></label><label>Task<select value={form.task_class} onChange={e=>setForm(f=>({...f,task_class:e.target.value}))}>{['course_description','official_course_url','delivery_mode','duration'].map(x=><option key={x}>{x}</option>)}</select></label><label>Profile<select value={form.profile_id} onChange={e=>setForm(f=>({...f,profile_id:e.target.value}))}>{profiles.map(p=><option key={p.id} value={p.id}>{p.code}</option>)}</select></label></div><p className="m23-note">Unchanged Evidence is rejected before an LLM call. The initial free-router profile stays paused until credentials and quality validation pass.</p><button className="m23-primary" disabled={busy||!form.evidence_id||!form.entity_id||!form.profile_id} onClick={run}>Run eligible interpretation</button></section>
 <section className="m23-panel"><Head icon={Route} title="Recent interpretations"/><Table headers={['State','Task','Eligibility','Model','Cost','Created']} rows={runs.map(r=>[<State value={r.status}/>,r.task_class,human(r.eligibility_reason),r.aggregator_response_model||r.model_identifier,`$${Number(r.estimated_cost_usd||0).toFixed(4)}`,when(r.created_at)])}/></section></div>}

function Layer4({onError}){const[rows,setRows]=useState([]),[busy,setBusy]=useState(false);const load=async()=>{setBusy(true);try{setRows(await rpc('layer4_review_queue',{p_status:'pending',p_limit:100})||[])}catch(e){onError(e)}finally{setBusy(false)}};useEffect(()=>{load()},[]);const decide=async(row,action)=>{const reason=askReason(human(action));if(!reason)return;let final=null;if(action==='edit_and_approve'){const raw=window.prompt('Final JSON value',JSON.stringify(row.proposed_value));if(raw===null)return;try{final=JSON.parse(raw)}catch{return onError(new Error('Final value must be valid JSON'))}}try{await rpc('layer4_review_decide',{p_review_item_id:row.id,p_action:action,p_reason:reason,p_final_value:final});await load()}catch(e){onError(e)}};return <section className="m23-panel"><Head icon={ShieldCheck} title="Terminal human resolution" action={<button onClick={load} disabled={busy}><RefreshCw size={14}/>Refresh</button>}/>{rows.length===0?<Empty text="No pending Layer 4 decisions."/>:<div className="m23-review-list">{rows.map(r=><article key={r.id}><div className="m23-row"><div><strong>{human(r.field_code)}</strong><span>{r.entity_type} · {r.entity_id}</span></div><State value={r.status}/></div><div className="m23-values"><pre>{JSON.stringify(r.before_value,null,2)}</pre><span>→</span><pre>{JSON.stringify(r.proposed_value,null,2)}</pre></div><small>Evidence {r.evidence_id||'—'} · Layer 3 {r.layer3_interpretation_id||'—'}</small><div className="m23-actions">{[['approve','Approve'],['edit_and_approve','Edit & Approve'],['reject','Reject'],['request_more_evidence','More Evidence'],['return_layer2','Return L2'],['return_layer3','Return L3']].map(([a,l])=><button key={a} onClick={()=>decide(r,a)}>{l}</button>)}</div></article>)}</div>}</section>}

function Refresh({onError}){const[data,setData]=useState({policies:[],requests:[]}),[busy,setBusy]=useState(false);const load=async()=>{setBusy(true);try{setData(await rpc('refresh_intelligence_overview',{p_limit:100})||{policies:[],requests:[]})}catch(e){onError(e)}finally{setBusy(false)}};useEffect(()=>{load()},[]);return <div className="m23-stack"><section className="m23-panel"><Head icon={RefreshCw} title="Source/entity freshness policies" action={<button onClick={load} disabled={busy}><RefreshCw size={14}/>Refresh</button>}/><Table headers={['Layer','Country','Target','Class','Next due','State']} rows={(data.policies||[]).map(x=>[`L${x.layer}`,x.country_code||'—',x.entity_id?`${x.entity_type}:${x.entity_id}`:x.source_profile_id||'event',human(x.freshness_class),when(x.next_due_at),<State value={x.enabled?'enabled':'disabled'}/>])}/></section><section className="m23-panel"><Head icon={Route} title="Targeted refresh queue"/><Table headers={['Layer','Trigger','Target','Reason','State','Created']} rows={(data.requests||[]).map(x=>[`L${x.requested_layer}`,human(x.trigger_type),x.entity_id?`${x.entity_type}:${x.entity_id}`:x.source_profile_id,x.reason,<State value={x.status}/>,when(x.created_at)])}/></section></div>}

function Links({rank,onError}){const[rows,setRows]=useState([]),[country,setCountry]=useState(''),[form,setForm]=useState({country_code:'AU',authority_category:'regulatory_authority',authority_name:'',owner_label:'CourseFinder Data Ops',url:'',purpose:'',related_layer:1,verification_days:90,health_status:'unverified'});const load=async()=>{try{setRows(await rpc('important_links_list',{p_country_code:country||null})||[])}catch(e){onError(e)}};useEffect(()=>{load()},[country]);const save=async()=>{try{await rpc('important_link_upsert',{p_id:null,p_country_code:form.country_code,p_authority_category:form.authority_category,p_authority_name:form.authority_name,p_owner_label:form.owner_label,p_url:form.url,p_purpose:form.purpose,p_related_layer:Number(form.related_layer),p_related_source_profile_id:null,p_verification_days:Number(form.verification_days),p_health_status:form.health_status});setForm(f=>({...f,authority_name:'',url:'',purpose:''}));await load()}catch(e){onError(e)}};return <div className="m23-stack"><section className="m23-panel"><Head icon={Link2} title="Important Links directory" action={<input className="m23-country" placeholder="Country" value={country} onChange={e=>setCountry(e.target.value.toUpperCase())}/>}/><div className="m23-link-list">{rows.map(x=><article key={x.id}><div><strong>{x.authority_name}</strong><span>{x.country_code} · {human(x.authority_category)} · owner {x.owner_label}</span><small>{x.purpose}</small></div><div><State value={x.health_status}/><a href={x.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a></div></article>)}</div></section>{rank>=3&&<section className="m23-panel"><Head icon={Check} title="Register governed link"/><div className="m23-form-grid">{[['Country','country_code'],['Authority','authority_name'],['Owner','owner_label'],['URL','url'],['Purpose','purpose']].map(([l,k])=><label key={k}>{l}<input value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}<label>Category<select value={form.authority_category} onChange={e=>setForm(f=>({...f,authority_category:e.target.value}))}>{['regulatory_authority','international_student_immigration','quality_outcomes','official_scholarship','qualification_framework','statistics_data','accepted_provider_course_source','source_health','official_policy_change'].map(x=><option key={x}>{x}</option>)}</select></label></div><button className="m23-primary" onClick={save}>Add governed link</button></section>}</div>}

function Dates({rank,onError}){const[rows,setRows]=useState([]),[form,setForm]=useState({country_code:'AU',event_type:'regulatory_dataset_release',title:'',source_url:'',scope_type:'country_reference',date_precision:'source_vague',starts_at:'',source_wording:'',warning_days:14});const load=async()=>{try{setRows(await rpc('important_dates_ticker',{p_country_code:null,p_days:365})||[])}catch(e){onError(e)}};useEffect(()=>{load()},[]);const save=async()=>{try{await rpc('important_date_upsert',{p_id:null,p_country_code:form.country_code,p_event_type:form.event_type,p_title:form.title,p_source_url:form.source_url,p_evidence_id:null,p_scope_type:form.scope_type,p_source_profile_id:null,p_entity_type:null,p_entity_id:null,p_date_precision:form.date_precision,p_starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,p_ends_at:null,p_timezone:'Australia/Melbourne',p_source_wording:form.source_wording||null,p_warning_days:Number(form.warning_days),p_expires_at:null,p_refresh_layer:null});setForm(f=>({...f,title:'',source_url:'',starts_at:'',source_wording:''}));await load()}catch(e){onError(e)}};return <div className="m23-stack"><section className="m23-panel"><Head icon={CalendarClock} title="Important Dates registry"/><Table headers={['Country','Event','Title','Precision','When','Scope']} rows={rows.map(x=>[x.country_code,human(x.event_type),x.title,human(x.date_precision),when(x.starts_at),human(x.scope_type)])}/></section>{rank>=3&&<section className="m23-panel"><Head icon={CalendarClock} title="Register sourced event"/><div className="m23-form-grid"><label>Country<input value={form.country_code} onChange={e=>setForm(f=>({...f,country_code:e.target.value.toUpperCase()}))}/></label><label>Title<input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></label><label>Source URL<input value={form.source_url} onChange={e=>setForm(f=>({...f,source_url:e.target.value}))}/></label><label>Precision<select value={form.date_precision} onChange={e=>setForm(f=>({...f,date_precision:e.target.value}))}>{['exact','date_range','month','term','year','source_vague'].map(x=><option key={x}>{x}</option>)}</select></label><label>Date/time<input type="datetime-local" value={form.starts_at} onChange={e=>setForm(f=>({...f,starts_at:e.target.value}))}/></label><label>Source wording<input value={form.source_wording} onChange={e=>setForm(f=>({...f,source_wording:e.target.value}))} placeholder="retain vague wording verbatim"/></label></div><p className="m23-note">Vague wording is retained as vague; an exact timestamp is never manufactured. Country-reference events cannot trigger ingestion until a bounded source/entity target is attached.</p><button className="m23-primary" onClick={save}>Add sourced event</button></section>}</div>}

function Head({icon:Icon,title,action}){return <div className="m23-head"><div><Icon size={17}/><h2>{title}</h2></div>{action}</div>}
function State({value}){return <span className={`m23-state s-${String(value||'').replaceAll('_','-')}`}>{human(value||'unknown')}</span>}
function Empty({text}){return <div className="m23-empty">{text}</div>}
function Table({headers,rows}){return <div className="m23-table"><div className="m23-tr head">{headers.map(h=><strong key={h}>{h}</strong>)}</div>{rows.length?rows.map((r,i)=><div className="m23-tr" key={i}>{r.map((v,j)=><span key={j}>{v??'—'}</span>)}</div>):<Empty text="No records."/>}</div>}

const root=document.getElementById('m2-3-intelligence-root');if(root)createRoot(root).render(<Entry/>)