import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, ArrowDown, ArrowUp, BookOpen, Building2, CircleGauge, GraduationCap, LayoutDashboard, ListChecks, LogOut, Search, Settings2, Sparkles, Tags, X } from 'lucide-react'
import { api, supabase } from './lib/supabase'
import RegulatorySettings from './RegulatorySettings'
import './styles.css'
import './catalogue.css'

const nav = [
  ['Overview', [['Dashboard', LayoutDashboard]]],
  ['Catalogue', [['Providers', Building2], ['Courses', GraduationCap], ['Scholarships', Sparkles]]],
  ['PIM Model', [['Attributes', Tags]]],
  ['Data Quality', [['Completeness', CircleGauge], ['Evidence', BookOpen], ['Review Queue', ListChecks]]],
  ['Operations', [['Jobs', Activity], ['Settings', Settings2]]],
]

function App(){
  const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState('Dashboard'),[context,setContext]=useState(null),[error,setError]=useState('')
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session??null);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
  useEffect(()=>{if(session) api.context().then(setContext).catch(e=>setError(e.message));else setContext(null)},[session])
  if(loading) return <div className="boot">Loading Coursefinder Pilot…</div>
  if(!session) return <Login onError={setError}/>
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">CF</div><div><strong>Coursefinder</strong><span>Admin / PIM</span></div></div><nav className="nav">{nav.map(([g,items])=><div className="nav-group" key={g}><div className="nav-label">{g}</div>{items.filter(([l])=>l!=='Settings'||Number(context?.role_rank||0)>=6).map(([l,I])=><button key={l} className={page===l?'nav-item active':'nav-item'} onClick={()=>setPage(l)}><I size={17}/><span>{l}</span></button>)}</div>)}</nav><div className="account-card"><div className="avatar">{(session.user.email?.[0]||'U').toUpperCase()}</div><div className="account-meta"><strong>{context?.role||'Pilot user'}</strong><span>{session.user.email}</span></div><button className="icon-button" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Mumbai Pilot · canonical governance contract</div><h1>{page}</h1></div></header>{error&&<div className="alert"><span>{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}<Page page={page} onError={setError} context={context}/></main></div>
}

function Login({onError}){const [email,setEmail]=useState(''),[password,setPassword]=useState('');async function submit(e){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)onError(error.message)}return <div className="login-page"><div className="login-card"><h1>Coursefinder Admin</h1><p>Canonical catalogue, provenance and PIM governance.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">Sign in</button></form></div></div>}

function Page({page,onError,context}){if(page==='Settings')return Number(context?.role_rank||0)>=6?<RegulatorySettings onError={onError}/>:<Empty text="Platform Admin access required."/>;const C={Dashboard,Providers,Courses,Scholarships,Attributes,Completeness,Evidence,'Review Queue':Reviews,Jobs}[page];return C?<C onError={onError}/>:<Empty text="Not implemented."/>}

function Dashboard({onError}){const [d,setD]=useState(null);useEffect(()=>{api.dashboard().then(setD).catch(e=>onError(e.message))},[]);return <div className="stack"><div className="metric-grid">{[['Providers',d?.providers],['Courses',d?.courses],['Search documents',d?.search_documents],['Attributes',d?.attributes],['Scholarships',d?.scholarships],['Evidence',d?.evidence],['Open reviews',d?.open_reviews],['Jobs',d?.jobs]].map(([l,v])=><div className="metric-card" key={l}><div><span>{l}</span><strong>{v??'—'}</strong></div></div>)}</div><section className="panel"><h3>Governance model</h3><p>Source authority and evidence remain distinct from canonical identity. Lifecycle and publication remain distinct from Search projection. Layer 2 enrichment never redefines Provider or Course identity.</p></section></div>}

function Providers({onError}){
  const emptyFilters={country:'',subdivision:'',lifecycle:'',publication:''}
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[filters,setFilters]=useState(emptyFilters),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null),[page,setPage]=useState(0),[pageSize,setPageSize]=useState(50),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[sort,setSort]=useState('provider'),[direction,setDirection]=useState('asc')
  useEffect(()=>{const timer=setTimeout(async()=>{setLoading(true);try{const d=await api.providerPage({limit:pageSize,offset:page*pageSize,query:q,...filters,sort,direction});setRows(d?.items||[]);setTotal(Number(d?.total||0))}catch(e){onError(e.message)}finally{setLoading(false)}},q?250:0);return()=>clearTimeout(timer)},[page,pageSize,q,filters,sort,direction])
  useEffect(()=>{setPage(0)},[q,pageSize,filters,sort,direction])
  const pages=Math.max(1,Math.ceil(total/pageSize)),from=total?page*pageSize+1:0,to=Math.min((page+1)*pageSize,total)
  const setFilter=(name,value)=>setFilters(f=>({...f,[name]:value}))
  const clearFilters=()=>{setQ('');setFilters(emptyFilters);setSort('provider');setDirection('asc')}
  const changeSort=key=>{if(sort===key)setDirection(d=>d==='asc'?'desc':'asc');else{setSort(key);setDirection('asc')}}
  async function open(r){setSelected(r.id);try{setDetail(await api.providerDetail(r.id))}catch(e){onError(e.message)}}
  function closeDetail(){setDetail(null);setSelected(null)}
  const footer=<Pagination page={page} pages={pages} pageSize={pageSize} total={total} from={from} to={to} onPage={setPage} onPageSize={setPageSize}/>
  const columns=[
    ['Provider','provider'],['Country','country'],['State / Region','subdivision'],['City','city'],['Stable key',null],['Courses','courses'],['Verified','verified'],['Evidence','evidence'],['Lifecycle','lifecycle'],['Publication','publication']
  ]
  return <TableWorkspace title="Provider catalogue" q={q} setQ={setQ} count={total} loading={loading} footer={footer} detail={detail&&<ProviderDetail d={detail} onClose={closeDetail}/>}>
    <div className="decision-toolbar"><div className="filter-grid"><label>Country<input value={filters.country} onChange={e=>setFilter('country',e.target.value.toUpperCase())} placeholder="AU / NZ / CA"/></label><label>State / Region<input value={filters.subdivision} onChange={e=>setFilter('subdivision',e.target.value)} placeholder="VIC / NSW / …"/></label><label>Lifecycle<select value={filters.lifecycle} onChange={e=>setFilter('lifecycle',e.target.value)}><option value="">All</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="retired">Retired</option></select></label><label>Publication<select value={filters.publication} onChange={e=>setFilter('publication',e.target.value)}><option value="">All</option><option value="published">Published</option><option value="draft">Draft</option><option value="review">Review</option></select></label></div><button className="secondary-button" onClick={clearFilters}>Clear filters</button></div>
    <DenseTable headers={columns.map(([label,key])=><SortHeader key={label} label={label} sortKey={key} active={sort===key} direction={direction} onSort={changeSort}/>)}>{rows.map(r=><tr key={r.id} className={selected===r.id?'selected-row':''} onClick={()=>open(r)}><td className="primary-cell">{r.canonical_name}</td><td title={r.country_name||''}>{r.country_code||'—'}</td><td>{r.subdivision_name||r.subdivision_code||'—'}</td><td>{r.city||'—'}</td><td className="mono-cell">{r.stable_key||'—'}</td><td>{r.course_count??0}</td><td>{r.last_verified_at?new Date(r.last_verified_at).toLocaleDateString():'Never'}</td><td><Status value={Number(r.evidence_count||0)>0?`${r.evidence_count} linked`:'None'}/></td><td><Status value={r.lifecycle_status}/></td><td><Status value={r.publication_status}/></td></tr>)}</DenseTable>
  </TableWorkspace>
}
function SortHeader({label,sortKey,active,direction,onSort}){if(!sortKey)return <span>{label}</span>;return <button className={`sort-header ${active?'active':''}`} onClick={()=>onSort(sortKey)}>{label}{active?(direction==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>):null}</button>}
function ProviderDetail({d,onClose}){return <><div className="compact-detail-head"><div><span className="detail-kicker">Provider verification</span><strong>{d.display_name||d.canonical_name||'Provider detail'}</strong></div><button className="icon-button" title="Close detail" onClick={onClose}><X size={16}/></button></div><div className="detail-body compact-detail"><div className="compact-facts"><Fact label="Stable key" value={d.stable_key}/><Fact label="Lifecycle" value={d.lifecycle_status}/><Fact label="Publication" value={d.publication_status}/><Fact label="Search" value={`${d.search_status} · ${d.projected_course_count}/${d.course_count}`}/></div><CompactSection title={`Identifiers · ${d.identifiers?.length||0}`} rows={d.identifiers} text={x=>`${x.scheme}: ${x.identifier}${x.primary?' · primary':''}`}/><CompactSection title={`Registrations · ${d.registrations?.length||0}`} rows={d.registrations} text={x=>`${x.scheme}: ${x.code} · ${x.status||'—'}`}/><CompactSection title={`Sources · ${d.sources?.length||0}`} rows={d.sources} text={x=>`${x.label||x.type} · trust ${x.trust_rank??'—'} · ${x.status||'—'}`}/><CompactSection title={`Evidence · ${d.evidence?.length||0}`} rows={d.evidence} text={x=>`${x.type} · ${x.captured_at||'—'} · ${shortHash(x.hash)}`}/></div></>}

function Courses({onError}){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null);useEffect(()=>{api.courses().then(setRows).catch(e=>onError(e.message))},[]);const shown=filter(rows,q,['canonical_title','provider_name','stable_key','level_code','country_code','lifecycle_status','publication_status']);async function open(r){setSelected(r.id);try{setDetail(await api.courseDetail(r.id))}catch(e){onError(e.message)}}return <TableWorkspace title="Course workspace" q={q} setQ={setQ} count={shown.length} detail={detail&&<CourseDetail d={detail}/>}><DenseTable headers={['Course','Provider','Level','Country','Stable key','Completeness','Lifecycle','Publication'].map(x=><span key={x}>{x}</span>)}>{shown.map(r=><tr key={r.id} className={selected===r.id?'selected-row':''} onClick={()=>open(r)}><td className="primary-cell">{r.canonical_title}</td><td>{r.provider_name||'—'}</td><td>{r.level_code||'—'}</td><td>{r.country_code||'—'}</td><td className="mono-cell">{r.stable_key||'—'}</td><td>{r.completeness_score??0}%</td><td><Status value={r.lifecycle_status}/></td><td><Status value={r.publication_status}/></td></tr>)}</DenseTable></TableWorkspace>}
function CourseDetail({d}){return <div className="detail-body"><Fact label="Stable key" value={d.stable_key}/><Fact label="Lifecycle" value={d.lifecycle_status}/><Fact label="Publication" value={d.publication_status}/><Fact label="Provider" value={d.provider_name}/><Section title="Fees" rows={d.fees} text={x=>`${x.currency||''} ${x.amount??'—'} · ${x.year||'—'} · ${x.audience||'—'}`}/><Section title="Intakes" rows={d.intakes} text={x=>`${x.label||x.start_date||'Intake'} · ${x.status||'—'}`}/></div>}

function Scholarships({onError}){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[detail,setDetail]=useState(null);useEffect(()=>{api.scholarships().then(setRows).catch(e=>onError(e.message))},[]);const shown=filter(rows,q,['name','provider_name','stable_key','audience']);async function open(r){try{setDetail(await api.scholarshipDetail(r.id))}catch(e){onError(e.message)}}return <Workspace title="Relational Scholarship workspace" q={q} setQ={setQ} detail={detail&&<ScholarshipDetail d={detail}/>}>{shown.map(r=><Card key={r.id} title={r.name} sub={`${r.provider_name||'Global'} · ${r.stable_key}`} meta={`${r.scholarship_type||'—'} · ${r.audience||'—'} · ${r.publication_status}`} onClick={()=>open(r)}/>)}</Workspace>}
function ScholarshipDetail({d}){return <div className="detail-body"><Fact label="Stable key" value={d.stable_key}/><Fact label="Lifecycle" value={d.lifecycle_status}/><Fact label="Publication" value={d.publication_status}/><Fact label="Provider" value={d.provider_name||'Global'}/><Section title="Source identifiers" rows={d.identifiers} text={x=>`${x.scheme}: ${x.identifier_value}${x.is_primary?' · primary':''}`}/><Section title="Offering cycles" rows={d.cycles} text={x=>`${x.cycle_code} · ${x.academic_year||'—'} · ${x.status||'—'}`}/><Section title="Application windows" rows={d.windows} text={x=>`${x.label||x.round_code||'Window'} · ${x.opens_at||'—'} → ${x.closes_at||'—'}`}/><Section title="Scopes" rows={d.scopes} text={x=>`${x.include_exclude||'include'} ${x.scope_type}`}/><Section title="Eligibility groups" rows={d.criterion_groups} text={x=>`${x.label||x.group_code} · ${x.conjunction}`}/><Section title="Eligibility criteria" rows={d.criteria} text={x=>`${x.criterion_type} ${x.operator||''} ${x.human_text||x.value_text||''}`}/><Section title="Award tiers" rows={d.award_tiers} text={x=>`${x.label||x.tier_code} · ${x.currency_code||''} ${x.amount??''}${x.percentage!=null?` · ${x.percentage}%`:''}`}/><Section title="Coverage" rows={d.coverage} text={x=>`${x.coverage_type}${x.percentage!=null?` · ${x.percentage}%`:''}${x.amount!=null?` · ${x.currency_code||''} ${x.amount}`:''}`}/><Section title="Evidence" rows={d.evidence} text={x=>`${x.type} · ${x.captured_at||'—'} · ${shortHash(x.hash)}`}/></div>}

function Attributes({onError}){const [tab,setTab]=useState('Definitions'),[rows,setRows]=useState([]);useEffect(()=>{const f={Definitions:api.attributes,Families:api.attributeFamilies,Groups:api.attributeGroups,Options:api.attributeOptions}[tab];f().then(setRows).catch(e=>onError(e.message))},[tab]);return <div className="stack"><div className="section-head"><div><h2>PIM Attribute model</h2><p>UnoPIM-style browse and configuration visibility over the canonical PIM schema.</p></div></div><div className="chip-row">{['Definitions','Families','Groups','Options'].map(t=><button className={tab===t?'chip active':'chip'} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="card-list">{rows.map(r=><Card key={r.id} title={r.name||r.label} sub={r.code||r.attribute_code} meta={tab==='Definitions'?`${r.entity_type} · ${r.group_name||'Ungrouped'} · ${r.data_type}`:tab==='Families'?`${r.entity_type} · ${r.group_count} groups · ${r.attribute_count} attributes`:tab==='Groups'?`${r.entity_type} · ${r.attribute_count} attributes · ${r.family_count} families`:`${r.attribute_name} · ${r.locale||'default'} · ${r.status}`}/>)}</div></div>}

function Completeness({onError}){const [profiles,setProfiles]=useState([]),[courses,setCourses]=useState([]);useEffect(()=>{Promise.all([api.completenessProfiles(),api.completenessCourses(1000)]).then(([p,c])=>{setProfiles(p);setCourses(c)}).catch(e=>onError(e.message))},[]);return <div className="stack"><section className="panel"><h3>Completeness profiles</h3><div className="card-list">{profiles.map(p=><Card key={p.id} title={p.name} sub={`${p.entity_type} · ${p.country_code||'global'} · ${p.channel_code||'all channels'}`} meta={`Publish threshold ${p.minimum_publish_score}% · ${p.mandatory_count}/${p.requirement_count} mandatory`}/>)}</div></section><section className="panel"><h3>Course completeness</h3><div className="card-list">{courses.slice(0,300).map(c=><Card key={c.course_id} title={c.canonical_title} sub={c.provider_name} meta={`${c.completeness_score}% · fee ${yn(c.has_fee)} · intake ${yn(c.has_intake)} · English ${yn(c.has_english)} · scholarship ${yn(c.has_scholarship)}`}/>)}</div></section></div>}
function Evidence({onError}){const [rows,setRows]=useState([]),[q,setQ]=useState('');useEffect(()=>{api.evidence().then(setRows).catch(e=>onError(e.message))},[]);const shown=filter(rows,q,['evidence_type','source_label','source_url','content_hash','entity_id']);return <Workspace title="Evidence Viewer" q={q} setQ={setQ}>{shown.map(r=><Card key={r.id} title={r.evidence_type} sub={`${r.source_label||r.source_type||'Source'} · ${r.captured_at||'—'}`} meta={`${shortHash(r.content_hash)} · ${r.mime_type||'—'} · ${r.supersedes_evidence_id?'supersedes prior evidence':'current lineage'}`}/>)}</Workspace>}
function Reviews({onError}){return <Simple loader={api.reviews} onError={onError} title="Review Queue" fields={['entity_type','reason','status']}/>}function Jobs({onError}){return <Simple loader={api.jobs} onError={onError} title="Jobs" fields={['job_type','country_code','status']}/>}function Simple({loader,onError,title,fields}){const [rows,setRows]=useState([]);useEffect(()=>{loader().then(setRows).catch(e=>onError(e.message))},[]);return <div className="stack"><h2>{title}</h2><div className="card-list">{rows.map((r,i)=><Card key={r.id||i} title={r.name||r.job_type||r.entity_type||title} sub={fields.map(f=>r[f]).filter(Boolean).join(' · ')} meta={r.created_at||r.updated_at||''}/>)}</div></div>}

function TableWorkspace({title,q,setQ,count,detail,children,footer,loading}){return <div className={`course-layout ${detail?'has-detail':'no-detail'}`}><section className="panel full course-list"><div className="panel-title table-title"><div><h2>{title}</h2><p>{count.toLocaleString()} rows · sort, filter, verify, decide</p></div><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, country, state/region, city…"/></div></div>{loading&&<div className="table-loading">Loading…</div>}{children}{footer}</section>{detail&&<aside className="detail-panel compact-panel">{detail}</aside>}</div>}
function DenseTable({headers,children}){return <div className="table-wrap dense-table-wrap"><table className="dense-table"><thead><tr>{headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Pagination({page,pages,pageSize,total,from,to,onPage,onPageSize}){return <div className="pagination"><span>{from.toLocaleString()}–{to.toLocaleString()} of {total.toLocaleString()}</span><div className="pagination-controls"><label>Rows <select value={pageSize} onChange={e=>onPageSize(Number(e.target.value))}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label><button disabled={page<=0} onClick={()=>onPage(page-1)}>Previous</button><strong>{page+1} / {pages}</strong><button disabled={page>=pages-1} onClick={()=>onPage(page+1)}>Next</button></div></div>}
function Status({value}){return <span className={`status-pill status-${String(value||'unknown').toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}>{value||'—'}</span>}
function Workspace({title,q,setQ,detail,children}){return <div className="course-layout"><section className="panel full course-list"><div className="panel-title table-title"><div><h2>{title}</h2><p>Canonical identity, lifecycle, source/evidence and publication remain separate concerns.</p></div>{setQ&&<div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search…"/></div>}</div><div className="card-list">{children}</div></section>{detail&&<aside className="detail-panel">{detail}</aside>}</div>}
function Card({title,sub,meta,onClick}){return <button className="panel" style={{textAlign:'left',cursor:onClick?'pointer':'default'}} onClick={onClick}><strong>{title||'—'}</strong><div>{sub||'—'}</div><small>{meta||''}</small></button>}
function Fact({label,value}){return <div className="fact"><span>{label}</span><strong>{value??'—'}</strong></div>}
function Section({title,rows=[],text}){return <section><h4>{title}</h4>{rows?.length?rows.map((x,i)=><div key={x.id||i} className="object-row">{text(x)}</div>):<Empty text="No records"/>}</section>}
function CompactSection({title,rows=[],text}){return <details className="compact-section"><summary>{title}</summary>{rows?.length?<div className="compact-section-body">{rows.map((x,i)=><div key={x.id||i} className="object-row">{text(x)}</div>)}</div>:<Empty text="No records"/>}</details>}
function Empty({text}){return <p className="muted">{text}</p>}
function filter(rows,q,fields){const s=q.toLowerCase();return rows.filter(r=>!s||fields.some(f=>String(r[f]??'').toLowerCase().includes(s)))}
function shortHash(v){return v?`${v.slice(0,12)}…`:'—'}function yn(v){return v?'Yes':'No'}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>)
