import React, { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, ArrowDown, ArrowUp, BookOpen, Building2, ChevronDown, CircleGauge, ExternalLink, GraduationCap, LayoutDashboard, ListChecks, LogOut, Search, Settings2, Sparkles, Tags, X } from 'lucide-react'
import { api, supabase } from './lib/supabase'
import RegulatorySettings from './RegulatorySettings'
import './styles.css'
import './catalogue.css'
import './decision-ui.css'

const UI_VERSION='1.4.0'
const STATUS_OPTIONS=['active','inactive','retired']
const PUBLICATION_OPTIONS=['published','unpublished','draft','review']
const nav=[
  ['Overview',[['Dashboard',LayoutDashboard]]],
  ['Catalogue',[['Providers',Building2],['Courses',GraduationCap],['Scholarships',Sparkles]]],
  ['PIM Model',[['Attributes',Tags]]],
  ['Data Quality',[['Completeness',CircleGauge],['Evidence',BookOpen],['Review Queue',ListChecks]]],
  ['Operations',[['Jobs',Activity],['Settings',Settings2]]],
]

function App(){
  const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[page,setPage]=useState('Dashboard'),[context,setContext]=useState(null),[error,setError]=useState('')
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session??null);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
  useEffect(()=>{if(session)api.context().then(setContext).catch(e=>setError(e.message));else setContext(null)},[session])
  if(loading)return <div className="boot">Loading Coursefinder Pilot…</div>
  if(!session)return <Login onError={setError}/>
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">CF</div><div><strong>Coursefinder</strong><span>Admin / PIM</span><span className="ui-version">UI v{UI_VERSION}</span></div></div><nav className="nav">{nav.map(([g,items])=><div className="nav-group" key={g}><div className="nav-label">{g}</div>{items.filter(([l])=>l!=='Settings'||Number(context?.role_rank||0)>=6).map(([l,I])=><button key={l} className={page===l?'nav-item active':'nav-item'} onClick={()=>setPage(l)}><I size={17}/><span>{l}</span></button>)}</div>)}</nav><div className="account-card"><div className="avatar">{(session.user.email?.[0]||'U').toUpperCase()}</div><div className="account-meta"><strong>{context?.role||'Pilot user'}</strong><span>{session.user.email}</span></div><button className="icon-button" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></div></aside><main className="main"><header className="topbar"><div><div className="eyebrow">Mumbai Pilot · canonical governance contract</div><h1>{page}</h1></div><div className="topbar-meta"><span className="ui-version">UI v{UI_VERSION}</span></div></header>{error&&<div className="alert"><span>{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}<Page page={page} onError={setError} context={context}/></main></div>
}

function Login({onError}){const [email,setEmail]=useState(''),[password,setPassword]=useState('');async function submit(e){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)onError(error.message)}return <div className="login-page"><div className="login-card"><h1>Coursefinder Admin</h1><p>Canonical catalogue, provenance and PIM governance.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">Sign in</button></form><small>UI v{UI_VERSION}</small></div></div>}

function Page({page,onError,context}){
  if(page==='Settings')return Number(context?.role_rank||0)>=6?<RegulatorySettings onError={onError}/>:<Empty text="Platform Admin access required."/>
  const C={Dashboard,Providers,Courses,Scholarships,Attributes,Completeness,Evidence,'Review Queue':Reviews,Jobs}[page]
  return C?<C onError={onError}/>:<Empty text="Not implemented."/>
}

function Dashboard({onError}){const [d,setD]=useState(null);useEffect(()=>{api.dashboard().then(setD).catch(e=>onError(e.message))},[]);return <div className="stack"><div className="metric-grid">{[['Providers',d?.providers],['Courses',d?.courses],['Search documents',d?.search_documents],['Attributes',d?.attributes],['Scholarships',d?.scholarships],['Evidence',d?.evidence],['Open reviews',d?.open_reviews],['Jobs',d?.jobs]].map(([l,v])=><div className="metric-card" key={l}><div><span>{l}</span><strong>{v??'—'}</strong></div></div>)}</div><section className="panel"><h3>Decision workspace contract</h3><p>UI v{UI_VERSION} standardises searchable combobox filters, sortable dense grids, related-record cross-links, compact right-side verification drawers, source/evidence visibility and no-loss list context across Admin/PIM.</p></section></div>}

function Providers({onError}){
  const empty={country:'',subdivision:'',lifecycle:'',publication:''}
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[filters,setFilters]=useState(empty),[opts,setOpts]=useState({countries:[],subdivisions:[]}),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null),[page,setPage]=useState(0),[size,setSize]=useState(50),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[sort,setSort]=useState('provider'),[direction,setDirection]=useState('asc')
  useEffect(()=>{api.providerFilterOptions(filters.country).then(setOpts).catch(e=>onError(e.message))},[filters.country])
  useEffect(()=>{const t=setTimeout(async()=>{setBusy(true);try{const d=await api.providerPage({limit:size,offset:page*size,query:q,...filters,sort,direction});setRows(d?.items||[]);setTotal(Number(d?.total||0))}catch(e){onError(e.message)}finally{setBusy(false)}},q?200:0);return()=>clearTimeout(t)},[page,size,q,filters,sort,direction])
  useEffect(()=>setPage(0),[q,size,filters,sort,direction])
  async function open(r,tab='summary'){setSelected(r.id);try{const d=await api.providerDetail(r.id);setDetail({...d,_tab:tab})}catch(e){onError(e.message)}}
  const columns=[
    {label:'Provider',key:'provider',render:r=><><span>{r.canonical_name}</span>{r.website&&<External href={r.website}/>}</>},
    {label:'Country',key:'country',render:r=><Country code={r.country_code} name={r.country_name}/>},
    {label:'Currency',key:'currency',render:r=><Currency code={r.currency_code}/>},
    {label:'State / Region',key:'subdivision',render:r=>r.subdivision_name||r.subdivision_code||'—'},
    {label:'City',key:'city',render:r=>r.city||'—'},
    {label:'Stable key',render:r=><span className="mono">{r.stable_key||'—'}</span>},
    {label:'Courses',key:'courses',render:r=><Cross onClick={()=>open(r,'courses')}>{r.course_count??0} courses</Cross>},
    {label:'Verified',key:'verified',render:r=>date(r.last_verified_at)||'Never'},
    {label:'Evidence',key:'evidence',render:r=><Cross onClick={()=>open(r,'evidence')}>{Number(r.evidence_count||0)} evidence</Cross>},
    {label:'Lifecycle',key:'lifecycle',render:r=><Status value={r.lifecycle_status}/>},
    {label:'Publication',key:'publication',render:r=><Status value={r.publication_status}/>},
  ]
  return <DecisionWorkspace title="Provider catalogue" subtitle="Filter → sort → cross-check → decide" rows={rows} total={total} query={q} setQuery={setQ} loading={busy} columns={columns} sort={sort} direction={direction} onSort={key=>toggleSort(key,sort,direction,setSort,setDirection)} page={page} setPage={setPage} pageSize={size} setPageSize={setSize} selected={selected} onRow={r=>open(r)} detail={detail&&<ProviderDrawer d={detail} onClose={()=>{setDetail(null);setSelected(null)}} onError={onError}/>} filters={<><FilterCombobox label="Country" value={filters.country} onChange={v=>setFilters(f=>({...f,country:v,subdivision:''}))} options={(opts.countries||[]).map(x=>({value:x.code,label:`${countryFlag(x.code)} ${x.name}`,meta:x.code}))}/><FilterCombobox label="State / Region" value={filters.subdivision} onChange={v=>setFilters(f=>({...f,subdivision:v}))} options={(opts.subdivisions||[]).map(x=>({value:x.code,label:x.name,meta:x.code}))}/><FilterCombobox label="Lifecycle" value={filters.lifecycle} onChange={v=>setFilters(f=>({...f,lifecycle:v}))} options={simpleOptions(STATUS_OPTIONS)}/><FilterCombobox label="Publication" value={filters.publication} onChange={v=>setFilters(f=>({...f,publication:v}))} options={simpleOptions(PUBLICATION_OPTIONS)}/></>} onClear={()=>{setQ('');setFilters(empty);setSort('provider');setDirection('asc')}}/>
}

function ProviderDrawer({d,onClose,onError}){const [tab,setTab]=useState(d._tab||'summary');useEffect(()=>setTab(d._tab||'summary'),[d.id,d._tab]);return <Drawer title={d.display_name||d.canonical_name||'Provider'} kicker="Provider verification" onClose={onClose} external={d.website} tabs={[['summary','Summary'],['courses',`Courses · ${d.course_count||0}`],['evidence',`Evidence · ${d.evidence?.length||0}`]]} tab={tab} setTab={setTab}>{tab==='courses'?<ProviderRelatedCourses providerId={d.id} onError={onError}/>:tab==='evidence'?<ProviderRelatedEvidence providerId={d.id} onError={onError}/>:<><FactGrid items={[['Country',`${countryFlag(d.country_code)} ${d.country_code||'—'}`],['Stable key',d.stable_key],['Lifecycle',d.lifecycle_status],['Publication',d.publication_status],['Search',`${d.search_status} · ${d.projected_course_count}/${d.course_count}`],['Verified',date(d.last_verified_at)||'Never']]}/><ObjectSection title={`Identifiers · ${d.identifiers?.length||0}`} rows={d.identifiers} text={x=>`${x.scheme}: ${x.identifier}${x.primary?' · primary':''}`}/><ObjectSection title={`Registrations · ${d.registrations?.length||0}`} rows={d.registrations} text={x=>`${x.scheme}: ${x.code} · ${x.status||'—'}`}/><ObjectSection title={`Sources · ${d.sources?.length||0}`} rows={d.sources} text={x=>`${x.label||x.type} · trust ${x.trust_rank??'—'} · ${x.status||'—'}`}/></>}</Drawer>}

function ProviderRelatedCourses({providerId,onError}){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[life,setLife]=useState(''),[pub,setPub]=useState(''),[page,setPage]=useState(0),[total,setTotal]=useState(0),limit=25;useEffect(()=>{const t=setTimeout(()=>api.providerRelatedCourses({providerId,limit,offset:page*limit,query:q,lifecycle:life,publication:pub}).then(d=>{setRows(d?.items||[]);setTotal(Number(d?.total||0))}).catch(e=>onError(e.message)),q?160:0);return()=>clearTimeout(t)},[providerId,page,q,life,pub]);useEffect(()=>setPage(0),[q,life,pub,providerId]);return <RelatedList query={q} setQuery={setQ} filters={<><FilterCombobox compact label="Lifecycle" value={life} onChange={setLife} options={simpleOptions(STATUS_OPTIONS)}/><FilterCombobox compact label="Publication" value={pub} onChange={setPub} options={simpleOptions(PUBLICATION_OPTIONS)}/></>} rows={rows} total={total} page={page} setPage={setPage} limit={limit} render={r=><div className="related-row" key={r.id}><div><strong>{r.display_title||r.canonical_title}</strong><span>{r.course_code||r.stable_key}</span></div><div className="related-row-actions"><Status value={r.lifecycle_status}/>{r.course_url&&<External href={r.course_url}/>}</div></div>}/>} 

function ProviderRelatedEvidence({providerId,onError}){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[type,setType]=useState(''),[page,setPage]=useState(0),[total,setTotal]=useState(0),limit=25;useEffect(()=>{const t=setTimeout(()=>api.providerRelatedEvidence({providerId,limit,offset:page*limit,query:q,evidenceType:type}).then(d=>{setRows(d?.items||[]);setTotal(Number(d?.total||0))}).catch(e=>onError(e.message)),q?160:0);return()=>clearTimeout(t)},[providerId,page,q,type]);useEffect(()=>setPage(0),[q,type,providerId]);const types=[...new Set(rows.map(r=>r.evidence_type).filter(Boolean))];return <RelatedList query={q} setQuery={setQ} filters={<FilterCombobox compact label="Evidence type" value={type} onChange={setType} options={simpleOptions(types)}/>} rows={rows} total={total} page={page} setPage={setPage} limit={limit} render={r=><div className="related-row" key={r.id}><div><strong>{r.evidence_type}</strong><span>{r.source_label||r.source_type||'Source'} · {date(r.captured_at)||'—'} · {shortHash(r.content_hash)}</span></div>{r.source_url&&<External href={r.source_url}/>}</div>}/>} 

function Courses({onError}){
  const empty={country:'',level:'',lifecycle:'',publication:''}
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[filters,setFilters]=useState(empty),[opts,setOpts]=useState({countries:[],levels:[]}),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null),[page,setPage]=useState(0),[size,setSize]=useState(50),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[sort,setSort]=useState('course'),[direction,setDirection]=useState('asc')
  useEffect(()=>{api.courseFilterOptions().then(setOpts).catch(e=>onError(e.message))},[])
  useEffect(()=>{const t=setTimeout(async()=>{setBusy(true);try{const d=await api.coursePage({limit:size,offset:page*size,query:q,...filters,sort,direction});setRows(d?.items||[]);setTotal(Number(d?.total||0))}catch(e){onError(e.message)}finally{setBusy(false)}},q?200:0);return()=>clearTimeout(t)},[page,size,q,filters,sort,direction])
  useEffect(()=>setPage(0),[q,size,filters,sort,direction])
  async function open(r){setSelected(r.id);try{setDetail(await api.courseDetail(r.id))}catch(e){onError(e.message)}}
  async function openProvider(r){try{const d=await api.providerDetail(r.provider_id);setSelected(r.id);setDetail({...d,_provider:true})}catch(e){onError(e.message)}}
  const columns=[
    {label:'Course',key:'course',render:r=><><span>{r.display_title||r.canonical_title}</span>{r.course_url&&<External href={r.course_url}/>}</>},
    {label:'Provider',key:'provider',render:r=><Cross onClick={()=>openProvider(r)}>{r.provider_name}</Cross>},
    {label:'Country',key:'country',render:r=><Country code={r.country_code} name={r.country_name}/>},
    {label:'Currency',render:r=><Currency code={r.currency_code}/>},
    {label:'Level',key:'level',render:r=>r.level_code||'—'},
    {label:'Course code',render:r=><span className="mono">{r.course_code||'—'}</span>},
    {label:'Completeness',key:'completeness',render:r=>`${Number(r.completeness_score||0).toFixed(0)}%`},
    {label:'Verified',key:'verified',render:r=>date(r.last_verified_at)||'Never'},
    {label:'Lifecycle',render:r=><Status value={r.lifecycle_status}/>},
    {label:'Publication',render:r=><Status value={r.publication_status}/>},
  ]
  return <DecisionWorkspace title="Course catalogue" subtitle="Same decision-grid contract as Providers" rows={rows} total={total} query={q} setQuery={setQ} loading={busy} columns={columns} sort={sort} direction={direction} onSort={key=>toggleSort(key,sort,direction,setSort,setDirection)} page={page} setPage={setPage} pageSize={size} setPageSize={setSize} selected={selected} onRow={r=>open(r)} detail={detail&&(detail._provider?<ProviderDrawer d={detail} onClose={()=>{setDetail(null);setSelected(null)}} onError={onError}/>:<CourseDrawer d={detail} onClose={()=>{setDetail(null);setSelected(null)}}/>)} filters={<><FilterCombobox label="Country" value={filters.country} onChange={v=>setFilters(f=>({...f,country:v}))} options={(opts.countries||[]).map(x=>({value:x.code,label:`${countryFlag(x.code)} ${x.name}`,meta:x.code}))}/><FilterCombobox label="Study level" value={filters.level} onChange={v=>setFilters(f=>({...f,level:v}))} options={(opts.levels||[]).map(x=>({value:x.code,label:x.name,meta:x.code}))}/><FilterCombobox label="Lifecycle" value={filters.lifecycle} onChange={v=>setFilters(f=>({...f,lifecycle:v}))} options={simpleOptions(STATUS_OPTIONS)}/><FilterCombobox label="Publication" value={filters.publication} onChange={v=>setFilters(f=>({...f,publication:v}))} options={simpleOptions(PUBLICATION_OPTIONS)}/></>} onClear={()=>{setQ('');setFilters(empty);setSort('course');setDirection('asc')}}/>
}

function CourseDrawer({d,onClose}){return <Drawer title={d.display_title||d.canonical_title||'Course'} kicker="Course verification" onClose={onClose}><FactGrid items={[['Stable key',d.stable_key],['Provider',d.provider_name],['Lifecycle',d.lifecycle_status],['Publication',d.publication_status]]}/><ObjectSection title={`Fees · ${d.fees?.length||0}`} rows={d.fees} text={x=>`${x.currency||''} ${x.amount??'—'} · ${x.year||'—'} · ${x.audience||'—'}`}/><ObjectSection title={`Intakes · ${d.intakes?.length||0}`} rows={d.intakes} text={x=>`${x.label||x.start_date||'Intake'} · ${x.status||'—'}`}/></Drawer>}

function Scholarships({onError}){
  const empty={country:'',lifecycle:'',publication:''}
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[filters,setFilters]=useState(empty),[providerOpts,setProviderOpts]=useState({countries:[]}),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null),[page,setPage]=useState(0),[size,setSize]=useState(50),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[sort,setSort]=useState('scholarship'),[direction,setDirection]=useState('asc')
  useEffect(()=>{api.providerFilterOptions('').then(setProviderOpts).catch(()=>{})},[])
  useEffect(()=>{const t=setTimeout(async()=>{setBusy(true);try{const d=await api.scholarshipPage({limit:size,offset:page*size,query:q,...filters,sort,direction});setRows(d?.items||[]);setTotal(Number(d?.total||0))}catch(e){onError(e.message)}finally{setBusy(false)}},q?200:0);return()=>clearTimeout(t)},[page,size,q,filters,sort,direction])
  useEffect(()=>setPage(0),[q,size,filters,sort,direction])
  async function open(r,tab='summary'){setSelected(r.id);try{const d=await api.scholarshipDetail(r.id);setDetail({...d,_tab:tab})}catch(e){onError(e.message)}}
  async function openProvider(r){if(!r.provider_id)return;try{const d=await api.providerDetail(r.provider_id);setSelected(r.id);setDetail({...d,_provider:true})}catch(e){onError(e.message)}}
  const columns=[
    {label:'Scholarship',key:'scholarship',render:r=><><span>{r.name}</span>{r.source_url&&<External href={r.source_url}/>}</>},
    {label:'Provider',key:'provider',render:r=>r.provider_id?<Cross onClick={()=>openProvider(r)}>{r.provider_name}</Cross>:'Global'},
    {label:'Country',key:'country',render:r=>r.country_code?<Country code={r.country_code} name={r.country_name}/>:'Global'},
    {label:'Currency',render:r=><Currency code={r.currency_code}/>},
    {label:'Award',render:r=>r.award_value_text||'—'},
    {label:'Cycles',render:r=><Cross onClick={()=>open(r,'cycles')}>{r.cycle_count||0} cycles</Cross>},
    {label:'Windows',render:r=><Cross onClick={()=>open(r,'windows')}>{r.window_count||0} windows</Cross>},
    {label:'Evidence',render:r=><Cross onClick={()=>open(r,'evidence')}>{r.evidence_count||0} evidence</Cross>},
    {label:'Updated',key:'updated',render:r=>date(r.updated_at)||'—'},
    {label:'Lifecycle',render:r=><Status value={r.lifecycle_status}/>},
    {label:'Publication',render:r=><Status value={r.publication_status}/>},
  ]
  return <DecisionWorkspace title="Scholarship catalogue" subtitle="Relational records surfaced as a condensed decision grid" rows={rows} total={total} query={q} setQuery={setQ} loading={busy} columns={columns} sort={sort} direction={direction} onSort={key=>toggleSort(key,sort,direction,setSort,setDirection)} page={page} setPage={setPage} pageSize={size} setPageSize={setSize} selected={selected} onRow={r=>open(r)} detail={detail&&(detail._provider?<ProviderDrawer d={detail} onClose={()=>{setDetail(null);setSelected(null)}} onError={onError}/>:<ScholarshipDrawer d={detail} onClose={()=>{setDetail(null);setSelected(null)}}/>)} filters={<><FilterCombobox label="Country" value={filters.country} onChange={v=>setFilters(f=>({...f,country:v}))} options={(providerOpts.countries||[]).map(x=>({value:x.code,label:`${countryFlag(x.code)} ${x.name}`,meta:x.code}))}/><FilterCombobox label="Lifecycle" value={filters.lifecycle} onChange={v=>setFilters(f=>({...f,lifecycle:v}))} options={simpleOptions(STATUS_OPTIONS)}/><FilterCombobox label="Publication" value={filters.publication} onChange={v=>setFilters(f=>({...f,publication:v}))} options={simpleOptions(PUBLICATION_OPTIONS)}/></>} onClear={()=>{setQ('');setFilters(empty);setSort('scholarship');setDirection('asc')}}/>
}

function ScholarshipDrawer({d,onClose}){const [tab,setTab]=useState(d._tab||'summary');useEffect(()=>setTab(d._tab||'summary'),[d.id,d._tab]);const tabs=[['summary','Summary'],['cycles',`Cycles · ${d.cycles?.length||0}`],['windows',`Windows · ${d.windows?.length||0}`],['eligibility',`Eligibility · ${d.criteria?.length||0}`],['awards',`Awards · ${d.award_tiers?.length||0}`],['evidence',`Evidence · ${d.evidence?.length||0}`]];return <Drawer title={d.name||'Scholarship'} kicker="Scholarship verification" onClose={onClose} tabs={tabs} tab={tab} setTab={setTab}>{tab==='cycles'?<ObjectSection title="Offering cycles" rows={d.cycles} text={x=>`${x.cycle_code} · ${x.academic_year||'—'} · ${x.status||'—'}`}/>:tab==='windows'?<ObjectSection title="Application windows" rows={d.windows} text={x=>`${x.label||x.round_code||'Window'} · ${x.opens_at||'—'} → ${x.closes_at||'—'}`}/>:tab==='eligibility'?<><ObjectSection title="Eligibility groups" rows={d.criterion_groups} text={x=>`${x.label||x.group_code} · ${x.conjunction}`}/><ObjectSection title="Criteria" rows={d.criteria} text={x=>`${x.criterion_type} ${x.operator||''} ${x.human_text||x.value_text||''}`}/></>:tab==='awards'?<><ObjectSection title="Award tiers" rows={d.award_tiers} text={x=>`${x.label||x.tier_code} · ${x.currency_code||''} ${x.amount??''}${x.percentage!=null?` · ${x.percentage}%`:''}`}/><ObjectSection title="Coverage" rows={d.coverage} text={x=>`${x.coverage_type}${x.percentage!=null?` · ${x.percentage}%`:''}${x.amount!=null?` · ${x.currency_code||''} ${x.amount}`:''}`}/></>:tab==='evidence'?<ObjectSection title="Evidence" rows={d.evidence} text={x=>`${x.type} · ${x.captured_at||'—'} · ${shortHash(x.hash)}`}/>:<><FactGrid items={[['Stable key',d.stable_key],['Provider',d.provider_name||'Global'],['Lifecycle',d.lifecycle_status],['Publication',d.publication_status]]}/><ObjectSection title="Source identifiers" rows={d.identifiers} text={x=>`${x.scheme}: ${x.identifier_value}${x.is_primary?' · primary':''}`}/><ObjectSection title="Scopes" rows={d.scopes} text={x=>`${x.include_exclude||'include'} ${x.scope_type}`}/></>}</Drawer>}

function Evidence({onError}){
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[type,setType]=useState(''),[opts,setOpts]=useState({types:[]}),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null),[page,setPage]=useState(0),[size,setSize]=useState(50),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[sort,setSort]=useState('captured'),[direction,setDirection]=useState('desc')
  useEffect(()=>{api.evidenceFilterOptions().then(setOpts).catch(e=>onError(e.message))},[])
  useEffect(()=>{const t=setTimeout(async()=>{setBusy(true);try{const d=await api.evidencePage({limit:size,offset:page*size,query:q,evidenceType:type,sort,direction});setRows(d?.items||[]);setTotal(Number(d?.total||0))}catch(e){onError(e.message)}finally{setBusy(false)}},q?180:0);return()=>clearTimeout(t)},[page,size,q,type,sort,direction])
  useEffect(()=>setPage(0),[q,size,type,sort,direction])
  const columns=[
    {label:'Evidence type',render:r=>r.evidence_type},
    {label:'Source',render:r=><>{r.source_label||r.source_type||'Source'}{r.source_url&&<External href={r.source_url}/>}</>},
    {label:'Captured',key:'captured',render:r=>dateTime(r.captured_at)||'—'},
    {label:'MIME',render:r=>r.mime_type||'—'},
    {label:'Hash',render:r=><span className="mono">{shortHash(r.content_hash)}</span>},
    {label:'Entity',render:r=><span className="mono">{shortId(r.entity_id)}</span>},
    {label:'Lineage',render:r=>r.supersedes_evidence_id?'Supersedes prior':'Current'},
  ]
  return <DecisionWorkspace title="Evidence Viewer" subtitle="Private evidence metadata with fast source and lineage validation" rows={rows} total={total} query={q} setQuery={setQ} loading={busy} columns={columns} sort={sort} direction={direction} onSort={key=>toggleSort(key,sort,direction,setSort,setDirection)} page={page} setPage={setPage} pageSize={size} setPageSize={setSize} selected={selected} onRow={r=>{setSelected(r.id);setDetail(r)}} detail={detail&&<Drawer title={detail.evidence_type} kicker="Evidence metadata" onClose={()=>{setDetail(null);setSelected(null)}} external={detail.source_url}><FactGrid items={[['Source',detail.source_label||detail.source_type],['Captured',dateTime(detail.captured_at)],['MIME',detail.mime_type],['Entity',detail.entity_id]]}/><ObjectSection title="Integrity" rows={[detail]} text={x=>`SHA-256 ${x.content_hash||'—'}`}/></Drawer>} filters={<FilterCombobox label="Evidence type" value={type} onChange={setType} options={(opts.types||[]).map(x=>({value:x.code,label:x.name}))}/>} onClear={()=>{setQ('');setType('');setSort('captured');setDirection('desc')}}/>
}

function Reviews({onError}){
  const [rows,setRows]=useState([]),[q,setQ]=useState(''),[domain,setDomain]=useState(''),[status,setStatus]=useState(''),[opts,setOpts]=useState({domains:[],statuses:[]}),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null),[page,setPage]=useState(0),[size,setSize]=useState(50),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[sort,setSort]=useState('priority'),[direction,setDirection]=useState('desc')
  useEffect(()=>{api.reviewFilterOptions().then(setOpts).catch(e=>onError(e.message))},[])
  useEffect(()=>{const t=setTimeout(async()=>{setBusy(true);try{const d=await api.reviewsPage({limit:size,offset:page*size,query:q,domain,status,sort,direction});setRows(d?.items||[]);setTotal(Number(d?.total||0))}catch(e){onError(e.message)}finally{setBusy(false)}},q?180:0);return()=>clearTimeout(t)},[page,size,q,domain,status,sort,direction])
  useEffect(()=>setPage(0),[q,size,domain,status,sort,direction])
  const columns=[
    {label:'Priority',key:'priority',render:r=><strong>{r.priority}</strong>},
    {label:'Domain',render:r=>r.domain||'—'},
    {label:'Field / Reason',render:r=>r.field_code||r.reopen_reason||'—'},
    {label:'Status',render:r=><Status value={r.status}/>},
    {label:'Entity',render:r=><span className="mono">{shortId(r.entity_id)}</span>},
    {label:'Created',render:r=>dateTime(r.created_at)||'—'},
    {label:'Updated',render:r=>dateTime(r.updated_at)||'—'},
  ]
  return <DecisionWorkspace title="Review Queue" subtitle="Exception-first review surface" rows={rows} total={total} query={q} setQuery={setQ} loading={busy} columns={columns} sort={sort} direction={direction} onSort={key=>toggleSort(key,sort,direction,setSort,setDirection)} page={page} setPage={setPage} pageSize={size} setPageSize={setSize} selected={selected} onRow={r=>{setSelected(r.id);setDetail(r)}} detail={detail&&<Drawer title={`${detail.domain||'Review'} · ${detail.field_code||'Item'}`} kicker="Review decision" onClose={()=>{setDetail(null);setSelected(null)}}><FactGrid items={[['Priority',detail.priority],['Status',detail.status],['Entity',detail.entity_id],['Created',dateTime(detail.created_at)],['Updated',dateTime(detail.updated_at)]]}/><ObjectSection title="Reason" rows={[detail]} text={x=>x.reopen_reason||x.field_code||'No narrative reason supplied'}/></Drawer>} filters={<><FilterCombobox label="Domain" value={domain} onChange={setDomain} options={(opts.domains||[]).map(x=>({value:x.code,label:x.name}))}/><FilterCombobox label="Status" value={status} onChange={setStatus} options={(opts.statuses||[]).map(x=>({value:x.code,label:x.name}))}/></>} onClear={()=>{setQ('');setDomain('');setStatus('');setSort('priority');setDirection('desc')}}/>
}

function Attributes({onError}){const [tab,setTab]=useState('Definitions'),[rows,setRows]=useState([]);useEffect(()=>{const f={Definitions:api.attributes,Families:api.attributeFamilies,Groups:api.attributeGroups,Options:api.attributeOptions}[tab];f().then(setRows).catch(e=>onError(e.message))},[tab]);const qRows=rows.slice(0,500);return <div className="decision-panel"><div className="decision-head"><div><h2>PIM Attribute model</h2><p>Configuration uses the same condensed information hierarchy; high-volume entities use decision grids.</p></div></div><div className="chip-row">{['Definitions','Families','Groups','Options'].map(t=><button className={tab===t?'chip active':'chip'} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="decision-table-wrap"><table className="decision-table"><thead><tr><th><span>Name</span></th><th><span>Code</span></th><th><span>Context</span></th></tr></thead><tbody>{qRows.map((r,i)=><tr key={r.id||i}><td className="primary">{r.name||r.label||r.attribute_name||'—'}</td><td className="mono">{r.code||r.attribute_code||'—'}</td><td>{r.entity_type||r.status||'—'}</td></tr>)}</tbody></table></div></div>}

function Completeness({onError}){const [profiles,setProfiles]=useState([]),[courses,setCourses]=useState([]);useEffect(()=>{Promise.all([api.completenessProfiles(),api.completenessCourses(1000)]).then(([p,c])=>{setProfiles(p);setCourses(c)}).catch(e=>onError(e.message))},[]);return <div className="stack"><section className="decision-panel"><div className="decision-head"><div><h2>Completeness profiles</h2><p>{profiles.length} governed profiles</p></div></div>{profiles.length?<div className="decision-table-wrap"><table className="decision-table"><thead><tr><th><span>Profile</span></th><th><span>Entity</span></th><th><span>Country</span></th><th><span>Threshold</span></th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td className="primary">{p.name}</td><td>{p.entity_type}</td><td>{p.country_code||'Global'}</td><td>{p.minimum_publish_score}%</td></tr>)}</tbody></table></div>:<Empty text="No completeness profiles configured"/>}</section><section className="decision-panel"><div className="decision-head"><div><h2>Course completeness</h2><p>Condensed exception scan</p></div></div><div className="decision-table-wrap"><table className="decision-table"><thead><tr><th><span>Course</span></th><th><span>Provider</span></th><th><span>Score</span></th><th><span>Fee</span></th><th><span>Intake</span></th><th><span>English</span></th><th><span>Scholarship</span></th></tr></thead><tbody>{courses.slice(0,500).map(c=><tr key={c.course_id}><td className="primary">{c.canonical_title}</td><td>{c.provider_name}</td><td>{c.completeness_score}%</td><td>{yn(c.has_fee)}</td><td>{yn(c.has_intake)}</td><td>{yn(c.has_english)}</td><td>{yn(c.has_scholarship)}</td></tr>)}</tbody></table></div></section></div>}

function Jobs({onError}){const [rows,setRows]=useState([]),[q,setQ]=useState('');useEffect(()=>{api.jobs().then(setRows).catch(e=>onError(e.message))},[]);const shown=filter(rows,q,['job_type','country_code','status']);return <div className="decision-panel"><div className="decision-head"><div><h2>Jobs</h2><p>Operational runs and status</p></div><SearchBox value={q} onChange={setQ}/></div><div className="decision-table-wrap"><table className="decision-table"><thead><tr><th><span>Job</span></th><th><span>Country</span></th><th><span>Status</span></th><th><span>Created</span></th></tr></thead><tbody>{shown.map((r,i)=><tr key={r.id||i}><td className="primary">{r.job_type||r.name||'Job'}</td><td>{r.country_code||'—'}</td><td><Status value={r.status}/></td><td>{dateTime(r.created_at)||'—'}</td></tr>)}</tbody></table></div></div>}

function DecisionWorkspace({title,subtitle,rows,total,query,setQuery,loading,columns,sort,direction,onSort,page,setPage,pageSize,setPageSize,selected,onRow,detail,filters,onClear}){const pages=Math.max(1,Math.ceil(total/pageSize)),from=total?page*pageSize+1:0,to=Math.min((page+1)*pageSize,total);return <div className={`decision-page ${detail?'has-detail':''}`}><section className="decision-panel"><div className="decision-head"><div><h2>{title}</h2><p>{subtitle} · {total.toLocaleString()} rows · UI v{UI_VERSION}</p></div><div className="decision-tools"><SearchBox value={query} onChange={setQuery}/></div></div><div className="decision-filterbar">{filters}<button className="decision-clear" onClick={onClear}>Clear filters</button></div>{loading&&<div className="loading-bar">Loading filtered results…</div>}<div className="decision-table-wrap"><table className="decision-table"><thead><tr>{columns.map((c,i)=><th key={i}>{c.key?<button className={sort===c.key?'active':''} onClick={()=>onSort(c.key)}>{c.label}{sort===c.key?(direction==='asc'?<ArrowUp size={11}/>:<ArrowDown size={11}/>):null}</button>:<span>{c.label}</span>}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className={selected===r.id?'selected':''} onClick={()=>onRow?.(r)}>{columns.map((c,i)=><td key={i} className={i===0?'primary':''}>{c.render(r)}</td>)}</tr>)}</tbody></table></div><Pager page={page} pages={pages} pageSize={pageSize} total={total} from={from} to={to} setPage={setPage} setPageSize={setPageSize}/></section>{detail&&<aside className="decision-drawer">{detail}</aside>}</div>}

function Drawer({title,kicker,onClose,external,tabs,tab,setTab,children}){return <><div className="drawer-head"><div><span>{kicker}</span><strong>{title}</strong></div><div className="drawer-actions">{external&&<External href={external}/>}<button className="icon-button" onClick={onClose}><X size={15}/></button></div></div>{tabs&&<div className="drawer-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>}<div className="drawer-body">{children}</div></>}

function FilterCombobox({label,value,onChange,options=[],compact=false}){const [open,setOpen]=useState(false),[text,setText]=useState(''),[active,setActive]=useState(0),root=useRef(null);const selected=options.find(o=>o.value===value);useEffect(()=>{setText(selected?.label||selected?.value||'')},[value,selected?.label]);useEffect(()=>{function outside(e){if(root.current&&!root.current.contains(e.target))setOpen(false)}document.addEventListener('mousedown',outside);return()=>document.removeEventListener('mousedown',outside)},[]);const filtered=useMemo(()=>{const s=text.trim().toLowerCase();if(!s||selected&&text===selected.label)return options;return options.filter(o=>`${o.label} ${o.value} ${o.meta||''}`.toLowerCase().includes(s))},[options,text,selected]);function choose(o){onChange(o.value);setText(o.label);setOpen(false)}function key(e){if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(a=>Math.min(a+1,Math.max(0,filtered.length-1)))}else if(e.key==='ArrowUp'){e.preventDefault();setActive(a=>Math.max(0,a-1))}else if(e.key==='Enter'&&open&&filtered[active]){e.preventDefault();choose(filtered[active])}else if(e.key==='Escape')setOpen(false)}return <div className="filter-field" ref={root}>{!compact&&<label>{label}</label>}<div className="combobox"><div className="combobox-control"><input value={text} placeholder={`Type or choose ${label.toLowerCase()}…`} onFocus={()=>setOpen(true)} onChange={e=>{setText(e.target.value);setOpen(true);setActive(0);if(!e.target.value)onChange('')}} onKeyDown={key}/>{value&&<button className="combobox-clear" onClick={()=>{onChange('');setText('');setOpen(true)}} title="Clear"><X size={12}/></button>}<button className="combobox-icon" onClick={()=>setOpen(o=>!o)} title="Open choices"><ChevronDown size={13}/></button></div>{open&&<div className="combobox-menu">{filtered.length?filtered.map((o,i)=><button key={o.value} className={`combobox-option ${i===active?'active':''}`} onMouseEnter={()=>setActive(i)} onClick={()=>choose(o)}><span>{o.label}</span>{o.meta&&<small>{o.meta}</small>}</button>):<div className="combobox-empty">No matching valid values</div>}</div>}</div></div>}

function RelatedList({query,setQuery,filters,rows,total,page,setPage,limit,render}){const pages=Math.max(1,Math.ceil(total/limit));return <div><div className="decision-filterbar" style={{gridTemplateColumns:'minmax(160px,1fr) repeat(2,minmax(120px,1fr))'}}><div className="filter-field"><label>Search</label><SearchBox value={query} onChange={setQuery}/></div>{filters}</div><div className="related-list">{rows.length?rows.map(render):<Empty text="No matching related records"/>}</div><div className="decision-pager"><span>{total.toLocaleString()} related results</span><div><button disabled={page<=0} onClick={()=>setPage(page-1)}>Prev</button><strong>{page+1}/{pages}</strong><button disabled={page>=pages-1} onClick={()=>setPage(page+1)}>Next</button></div></div></div>}

function SearchBox({value,onChange}){return <div className="decision-search"><Search size={14}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="Search…"/></div>}
function Pager({page,pages,pageSize,total,from,to,setPage,setPageSize}){return <div className="decision-pager"><span>{from.toLocaleString()}–{to.toLocaleString()} of {total.toLocaleString()}</span><div><label>Rows <select value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label><button disabled={page<=0} onClick={()=>setPage(page-1)}>Previous</button><strong>{page+1}/{pages}</strong><button disabled={page>=pages-1} onClick={()=>setPage(page+1)}>Next</button></div></div>}
function FactGrid({items}){return <div className="fact-grid">{items.map(([l,v])=><div className="fact-box" key={l}><span>{l}</span><strong>{v??'—'}</strong></div>)}</div>}
function ObjectSection({title,rows=[],text}){return <section className="drawer-section"><h4>{title}</h4>{rows?.length?rows.map((x,i)=><div className="object-line" key={x.id||i}>{text(x)}</div>):<Empty text="No records"/>}</section>}
function Cross({children,onClick}){return <button className="decision-link" onClick={e=>{e.stopPropagation();onClick?.()}}>{children}</button>}
function External({href}){return <a className="external-link" href={safeUrl(href)} target="_blank" rel="noreferrer" title="Open external link" onClick={e=>e.stopPropagation()}><ExternalLink size={13}/></a>}
function Country({code,name}){return <span className="country-tag" title={name||''}>{countryFlag(code)} {code||'—'}</span>}
function Currency({code}){return <span className="currency-tag">{code||'—'}</span>}
function Status({value}){return <span className={`status-pill status-${String(value||'unknown').toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}>{value||'—'}</span>}
function Empty({text}){return <div className="empty-state">{text}</div>}
function simpleOptions(values){return values.map(v=>({value:v,label:title(v)}))}
function toggleSort(key,sort,direction,setSort,setDirection){if(sort===key)setDirection(direction==='asc'?'desc':'asc');else{setSort(key);setDirection('asc')}}
function filter(rows,q,fields){const s=q.toLowerCase();return rows.filter(r=>!s||fields.some(f=>String(r[f]??'').toLowerCase().includes(s)))}
function countryFlag(code){const c=String(code||'').trim().toUpperCase();if(!/^[A-Z]{2}$/.test(c))return '🌐';return String.fromCodePoint(...[...c].map(x=>127397+x.charCodeAt(0)))}
function safeUrl(v){if(!v)return '#';return /^https?:\/\//i.test(v)?v:`https://${v}`}
function title(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function date(v){if(!v)return '';try{return new Date(v).toLocaleDateString()}catch{return String(v)}}
function dateTime(v){if(!v)return '';try{return new Date(v).toLocaleString()}catch{return String(v)}}
function shortHash(v){return v?`${String(v).slice(0,12)}…`:'—'}
function shortId(v){return v?`${String(v).slice(0,8)}…`:'—'}
function yn(v){return v?'Yes':'No'}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>)
