import React,{useEffect,useMemo,useRef,useState}from'react'
import{Clock3,ExternalLink,Play,RefreshCw,Save,Search,Settings2,SlidersHorizontal,RotateCcw,X,ArrowLeft,ArrowRight}from'lucide-react'
import{supabase,api}from'./lib/supabase'
import'./scheduled-jobs-config.css'

const PAGE_SIZE=100
const human=v=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
const when=v=>v?new Date(v).toLocaleString():'—'
const technicalTarget=x=>x?.entity_id?`${x.entity_type}:${x.entity_id}`:x?.source_id?`source:${x.source_id}`:x?.source_profile_id?`profile:${x.source_profile_id}`:'UNBOUNDED'
const targetLabel=x=>x?.source_label||x?.task_label||x?.source_profile_key||(x?.entity_id?`${human(x.entity_type||'entity')} target`:technicalTarget(x)!=='UNBOUNDED'?technicalTarget(x):'Scheduled task')
const creatorLabel=x=>x?.created_by_state==='former_user'?`Former user — ${x?.created_by_display||'unknown'}`:(x?.created_by_display||'System / legacy')
const ownerLabel=x=>x?.owner_state==='former_user'?`Former user — ${x?.owner_display||'unknown'}`:(x?.owner_display||'Unassigned')
const cadenceDays=value=>{const text=String(value||'').trim();if(!text)return'';let hours=0,matched=false;const d=text.match(/(-?\d+(?:\.\d+)?)\s+days?/i);if(d){hours+=Number(d[1])*24;matched=true}const t=text.match(/(?:^|\s)(\d+):(\d{2})(?::(\d{2}(?:\.\d+)?))?(?:\s|$)/);if(t){hours+=Number(t[1])+Number(t[2])/60+Number(t[3]||0)/3600;matched=true}if(!matched||!Number.isFinite(hours)||hours<=0)return'';const days=hours/24;return Number.isInteger(days)?String(days):''}
const localDateTime=value=>{if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
const jobItems=value=>Array.isArray(value)?value:(value?.items||value?.rows||value?.jobs||[])
const jobLayer=row=>row?.layer??row?.requested_layer??String(row?.job_type||'').match(/layer[_ -]?(\d)/i)?.[1]??'—'
const jobName=row=>row?.job_name||row?.job_type||row?.source_label||row?.source_name||row?.source_code||row?.id||'Job'
const jobStarted=row=>row?.started_at||row?.created_at||row?.queued_at||row?.updated_at
const terminalJob=row=>['completed','failed','cancelled','blocked','succeeded','success'].includes(String(row?.status||row?.state||'').toLowerCase())
const jobFinished=row=>row?.completed_at||row?.finished_at||(terminalJob(row)?row?.updated_at:null)
const jobResult=row=>{const accepted=row?.accepted_count??row?.accepted??row?.applied_count,processed=row?.processed_count??row?.processed??row?.selected_count,rejected=row?.rejected_count??row?.rejected??row?.failed_count,bits=[];if(processed!=null)bits.push(`${processed} processed`);if(accepted!=null)bits.push(`${accepted} accepted`);if(rejected!=null)bits.push(`${rejected} rejected/failed`);return bits.join(' · ')||row?.completion_class||row?.failure_class||'—'}
const go=hash=>{location.hash=hash}
const recurringEditable=policy=>String(policy?.freshness_class||'')!=='event-driven'&&cadenceDays(policy?.cadence_interval)!==''
const runEligible=policy=>Number(policy?.layer)<=2&&Boolean(policy?.enabled)

const COLUMN_DEFS={
 task:{label:'Task / Dataset'},layer:{label:'Layer'},country:{label:'Country'},target:{label:'Scheduled Target'},pipeline:{label:'Pipeline'},freshness:{label:'Freshness Policy'},cadence:{label:'Cadence'},next:{label:'Next Run'},status:{label:'Schedule Status'},owner:{label:'Owner'},createdBy:{label:'Created By'},updated:{label:'Updated'},actions:{label:'Actions'}
}
const DEFAULT_COLUMNS=['task','layer','country','target','pipeline','cadence','next','status','owner','createdBy','actions']
const PREF_BASE='cf:scheduler:view:v1'

function Status({value}){return <span className="cf-scheduler-v2__status" data-state={String(value||'').toLowerCase()}>{human(value||'unknown')}</span>}
function Empty({colSpan,text}){return <tr><td colSpan={colSpan} className="cf-scheduler-v2__empty">{text}</td></tr>}

export default function ScheduledJobsWorkspace({onError}){
 const[data,setData]=useState({requests:[],search_signals:[]}),[policySet,setPolicySet]=useState({items:[],total:0}),[policyPage,setPolicyPage]=useState(0),[jobs,setJobs]=useState([]),[rank,setRank]=useState(0),[actorKey,setActorKey]=useState('default'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState(null),[action,setAction]=useState('edit_schedule'),[form,setForm]=useState({cadence:'',nextDue:'',enabled:'',reason:''}),[query,setQuery]=useState(''),[columns,setColumns]=useState(DEFAULT_COLUMNS)
 const loadGeneration=useRef(0)
 const loadPanels=async()=>{const[overviewResult,contextResult,jobsResult]=await Promise.allSettled([supabase.rpc('refresh_intelligence_overview',{p_limit:100}),api.context(),api.jobs(50)]);if(overviewResult.status==='fulfilled'&&!overviewResult.value?.error)setData(overviewResult.value?.data||{requests:[],search_signals:[]});if(contextResult.status==='fulfilled'){const context=contextResult.value;setRank(Number(context?.role_rank||0));setActorKey(String(context?.user_id||context?.actor_id||context?.id||'default'))}if(jobsResult.status==='fulfilled')setJobs(jobItems(jobsResult.value))}
 const load=async(page=policyPage,search=query)=>{const generation=++loadGeneration.current;setBusy(true);setError('');try{const policyResponse=await supabase.rpc('scheduler_policies_list_v1',{p_limit:PAGE_SIZE,p_offset:page*PAGE_SIZE,p_query:search.trim()});if(generation!==loadGeneration.current)return;if(policyResponse.error)throw policyResponse.error;const total=Number(policyResponse.data?.total||0),maxPage=Math.max(0,Math.ceil(total/PAGE_SIZE)-1);if(page>maxPage){await load(maxPage,search);return}setPolicySet({items:Array.isArray(policyResponse.data?.items)?policyResponse.data.items:[],total});setPolicyPage(page)}catch(e){if(generation!==loadGeneration.current)return;setError(e?.message||String(e));onError?.(e?.message||String(e))}finally{if(generation===loadGeneration.current)setBusy(false)}}
 useEffect(()=>{loadPanels();const timer=setTimeout(()=>load(0,query),250);return()=>clearTimeout(timer)},[query])
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(`${PREF_BASE}:${actorKey}`)||'null');if(Array.isArray(saved?.columns)&&saved.columns.every(c=>COLUMN_DEFS[c]))setColumns(saved.columns)}catch{}},[actorKey])
 useEffect(()=>{try{localStorage.setItem(`${PREF_BASE}:${actorKey}`,JSON.stringify({columns}))}catch{}},[actorKey,columns])
 const policies=useMemo(()=>policySet.items.filter(x=>Number(x.layer)>=1&&Number(x.layer)<=3&&technicalTarget(x)!=='UNBOUNDED'),[policySet])
 const requests=Array.isArray(data.requests)?data.requests:[]
 const active=requests.filter(x=>['queued','running'].includes(String(x.status))).length
 const pages=Math.max(1,Math.ceil(policySet.total/PAGE_SIZE))
 const openEditor=(policy,nextAction)=>{setEditing(policy);setAction(nextAction);setMessage('');setError('');setForm({cadence:cadenceDays(policy.cadence_interval),nextDue:localDateTime(policy.next_due_at),enabled:String(Boolean(policy.enabled)),reason:''})}
 const closeEditor=()=>{setEditing(null);setForm({cadence:'',nextDue:'',enabled:'',reason:''})}
 const submit=async()=>{if(!editing||form.reason.trim().length<5){setError('A governance reason of at least 5 characters is required.');return}setBusy(true);setError('');setMessage('');try{const runNow=action==='run_now';let response;if(runNow){if(!runEligible(editing))throw new Error(Number(editing.layer)===3?'Layer 3 on-demand execution requires the governed Layer 3 Evidence/profile run control.':'Enable this schedule before running it on demand.');response=await supabase.rpc('scheduler_policy_run_now_v1',{p_policy_id:editing.id,p_reason:form.reason.trim()})}else{const cadence=Number(form.cadence);if(!recurringEditable(editing))throw new Error('This cadence cannot be safely edited as whole days from this screen.');if(!Number.isInteger(cadence)||cadence<1||cadence>3650)throw new Error('Cadence days must be a whole number from 1 to 3650.');if(!form.nextDue)throw new Error('Next run is required.');response=await supabase.rpc('scheduler_policy_edit_v1',{p_policy_id:editing.id,p_expected_updated_at:editing.updated_at,p_cadence_days:cadence,p_next_due_at:new Date(form.nextDue).toISOString(),p_enabled:form.enabled==='true',p_reason:form.reason.trim()})}if(response.error)throw response.error;setMessage(runNow?(response.data?.existing_active?'An active request already exists for this exact bounded target; it was not duplicated.':'Run requested: a governed manual refresh request was queued without changing the recurring schedule.'):'Schedule updated with durable operator/reason audit.');closeEditor();await load(0,query)}catch(e){setError(e?.message||String(e));onError?.(e?.message||String(e));setBusy(false)}}
 const toggleColumn=id=>setColumns(current=>current.includes(id)?(id==='actions'?current:current.filter(x=>x!==id)):[...current.slice(0,-1),id,'actions'])
 const moveColumn=(id,delta)=>setColumns(current=>{const i=current.indexOf(id),j=i+delta;if(i<0||j<0||j>=current.length||id==='actions'||current[j]==='actions'&&delta>0)return current;const next=[...current];[next[i],next[j]]=[next[j],next[i]];return next})
 const resetView=()=>{setColumns(DEFAULT_COLUMNS);setQuery('')}
 const cell=(p,id)=>({
   task:<td key={id}><strong>{targetLabel(p)}</strong><br/><small>{p.dataset_domain?human(p.dataset_domain):p.acquisition_method?human(p.acquisition_method):'Governed scheduled work'}</small></td>,
   layer:<td key={id}>Layer {p.layer}</td>,
   country:<td key={id}>{p.country_code||'—'}</td>,
   target:<td key={id}><strong>{targetLabel(p)}</strong><br/><small className="cf-scheduler-v2__technical">{technicalTarget(p)}</small></td>,
   pipeline:<td key={id}>{Number(p.layer)===1?'L1 authoritative/reference':Number(p.layer)===2?'L2 → conditional L3/L4':'L3 Evidence interpretation'}</td>,
   freshness:<td key={id}>{human(p.freshness_class)}</td>,
   cadence:<td key={id}>{p.cadence_interval||'Event driven'}</td>,
   next:<td key={id}>{when(p.next_due_at)}</td>,
   status:<td key={id}><Status value={p.enabled?'enabled':'disabled'}/></td>,
   owner:<td key={id}>{ownerLabel(p)}</td>,
   createdBy:<td key={id}>{creatorLabel(p)}</td>,
   updated:<td key={id}>{when(p.updated_at)}</td>,
   actions:<td key={id} className="cf-scheduler-v2__sticky-actions"><div className="cf-scheduler-v2__row-actions"><button disabled={busy||rank<4||!recurringEditable(p)} title={!recurringEditable(p)?'Only recurring whole-day schedules can be edited from this screen.':''} onClick={()=>openEditor(p,'edit_schedule')}><Settings2 size={13}/> Edit schedule</button><button data-primary disabled={busy||rank<4||!runEligible(p)} title={Number(p.layer)===3?'Use Layer 3 for Evidence/profile-governed on-demand execution.':(!p.enabled?'Enable the schedule before an on-demand run.':'')} onClick={()=>openEditor(p,'run_now')}><Play size={13}/> Run on demand</button><button onClick={()=>go({1:'#layer-1-operations',2:'#layer-2-enrichment',3:'#layer-3-ai-interpretation'}[p.layer])}>Open Layer {p.layer}</button></div></td>
 }[id])
 return <div className="m23-stack cf-scheduler-v2-native">
  <section className="m23-panel cf-scheduler-v2">
   <div className="cf-scheduler-v2__head"><div><span className="m-eyebrow">Data Operations · Scheduled Tasks</span><h2>Scheduled Jobs & Run Control</h2><p>Find and manage governed Layer 1–3 schedules by task, dataset, country, target, owner or creator. Technical IDs remain available without being the primary operator label.</p></div><div className="cf-scheduler-v2__actions"><button onClick={()=>{load(policyPage,query);loadPanels()}} disabled={busy}><RefreshCw size={14}/> Refresh</button><button onClick={()=>go('#jobs')}>Open Jobs</button><button onClick={()=>go('#evidence')}>Open Evidence</button></div></div>
   {error&&<div className="cf-scheduler-v2__message" data-error="true">{error}</div>}{message&&<div className="cf-scheduler-v2__message">{message}</div>}
   <div className="cf-scheduler-v2__summary"><article><strong>{policySet.total}</strong><span>{query.trim()?'Matching schedules':'Bounded Layer 1–3 schedules'}</span></article><article><strong>{active}</strong><span>Queued / active refresh requests</span></article><article><strong>{jobs.length}</strong><span>Recent governed Job records</span></article></div>
   <div className="cf-scheduler-v2__links"><button onClick={()=>go('#layer-1-operations')}>Layer 1 — Operations</button><button onClick={()=>go('#layer-2-enrichment')}>Layer 2 — Enrichment</button><button onClick={()=>go('#layer-3-ai-interpretation')}>Layer 3 — AI Interpretation</button></div>
  </section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Schedule Configuration</h3><div className="cf-scheduler-v2__links"><Status value={rank>=4?'operator_controls':'read_only'}/><button disabled={busy||policyPage===0} onClick={()=>load(policyPage-1,query)}>Previous</button><span>Page {policyPage+1} of {pages}</span><button disabled={busy||policyPage+1>=pages} onClick={()=>load(policyPage+1,query)}>Next</button></div></div>
   <div className="cf-scheduler-v2__toolbar"><label className="cf-scheduler-v2__search"><Search size={15}/><input aria-label="Search scheduled tasks" placeholder="Search task, dataset, country, provider, creator, owner or ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><details className="cf-scheduler-v2__columns"><summary><SlidersHorizontal size={14}/> Columns</summary><div className="cf-scheduler-v2__column-menu">{Object.entries(COLUMN_DEFS).map(([id,def])=><div key={id} className="cf-scheduler-v2__column-row"><label><input type="checkbox" checked={columns.includes(id)} disabled={id==='actions'} onChange={()=>toggleColumn(id)}/>{def.label}</label>{columns.includes(id)&&id!=='actions'&&<span><button aria-label={`Move ${def.label} left`} onClick={()=>moveColumn(id,-1)}><ArrowLeft size={12}/></button><button aria-label={`Move ${def.label} right`} onClick={()=>moveColumn(id,1)}><ArrowRight size={12}/></button></span>}</div>)}<button onClick={resetView}><RotateCcw size={13}/> Reset view</button></div></details><span className="cf-scheduler-v2__result-count">{policies.length} shown · {policySet.total} matching</span></div>
   <div className="cf-scheduler-v2__table-wrap"><table><thead><tr>{columns.map(id=><th key={id} className={id==='actions'?'cf-scheduler-v2__sticky-actions':''}>{COLUMN_DEFS[id].label}</th>)}</tr></thead><tbody>{policies.length?policies.map(p=><tr key={p.id}>{columns.map(id=>cell(p,id))}</tr>):<Empty colSpan={columns.length} text={query?'No scheduled tasks match this search.':'No bounded Layer 1–3 policies are visible on this page.'}/>}</tbody></table></div><p className="cf-scheduler-v2__note">Run on demand creates a governed manual refresh request for the exact bounded Layer 1–2 policy without changing cadence or next-run time. Layer 3 remains Evidence/profile/model-qualified. Personal column choices are browser-local UI preferences and never change execution policy.</p></section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Latest Refresh Queue</h3><button onClick={()=>go('#jobs')}>Follow in Jobs</button></div><div className="cf-scheduler-v2__table-wrap"><table><thead><tr><th>Layer</th><th>Trigger</th><th>Target</th><th>Status</th><th>Queued At</th><th>Completed At</th><th>Reason / Result</th></tr></thead><tbody>{requests.length?requests.slice(0,20).map(r=><tr key={r.id}><td>Layer {r.requested_layer}</td><td>{human(r.trigger_type)}</td><td>{targetLabel(r)}<br/><small className="cf-scheduler-v2__technical">{technicalTarget(r)}</small></td><td><Status value={r.status}/></td><td>{when(r.created_at)}</td><td>{when(r.completed_at)}</td><td>{r.reason||r.schedule_error||'—'}</td></tr>):<Empty colSpan={7} text="No recent refresh requests are visible."/>}</tbody></table></div></section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Recent Job Runs</h3><div className="cf-scheduler-v2__links"><button onClick={()=>go('#jobs')}>All Jobs</button><button onClick={()=>go('#evidence')}>Evidence</button></div></div><div className="cf-scheduler-v2__table-wrap"><table><thead><tr><th>Layer</th><th>Job / Source</th><th>Status</th><th>Run Mode</th><th>Started</th><th>Completed</th><th>Result</th><th>Follow</th></tr></thead><tbody>{jobs.length?jobs.slice(0,20).map((r,i)=><tr key={r.id||r.job_id||i}><td>{jobLayer(r)==='—'?'—':`Layer ${jobLayer(r)}`}</td><td><strong>{jobName(r)}</strong><br/><small>{r.id||r.job_id||'—'}</small></td><td><Status value={r.status||r.state}/></td><td>{human(r.run_mode||r.mode||r.trigger_type||'—')}</td><td>{when(jobStarted(r))}</td><td>{when(jobFinished(r))}</td><td>{jobResult(r)}</td><td><div className="cf-scheduler-v2__row-actions"><button onClick={()=>go('#jobs')}>Jobs <ExternalLink size={12}/></button><button onClick={()=>go('#evidence')}>Evidence <ExternalLink size={12}/></button></div></td></tr>):<Empty colSpan={8} text="No recent Job records returned by the governed Jobs read surface."/>}</tbody></table></div></section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Downstream Search Refresh Signals</h3></div><div className="cf-scheduler-v2__table-wrap"><table><thead><tr><th>Entity</th><th>Status</th><th>Created</th><th>Reason</th></tr></thead><tbody>{(data.search_signals||[]).length?(data.search_signals||[]).map(x=><tr key={x.id}><td>{x.entity_type}:{x.entity_id}</td><td><Status value={x.status||'queued'}/></td><td>{when(x.created_at)}</td><td>{x.reason||x.signal_reason||'—'}</td></tr>):<Empty colSpan={4} text="No downstream Search refresh signals."/>}</tbody></table></div></section>
  {editing&&<div className="cf-scheduler-v2-modal" role="dialog" aria-modal="true" aria-label={action==='run_now'?'Run on demand':'Edit schedule'}><div className="cf-scheduler-v2-modal__card"><button className="cf-scheduler-v2-modal__close" aria-label="Close" onClick={closeEditor}><X size={17}/></button><div className="cf-scheduler-v2-modal__title"><Clock3 size={18}/><div><h3>{action==='run_now'?`Run ${targetLabel(editing)} on demand`:`Edit ${targetLabel(editing)} schedule`}</h3><p>Layer {editing.layer} · {editing.country_code||'—'} · {targetLabel(editing)} · {human(editing.freshness_class)}</p><small className="cf-scheduler-v2__technical">{technicalTarget(editing)}</small></div></div>{action==='edit_schedule'&&<div className="cf-scheduler-v2-modal__grid"><label>Cadence (days)<input aria-label="Cadence days" type="number" min="1" max="3650" required value={form.cadence} onChange={e=>setForm(f=>({...f,cadence:e.target.value}))}/></label><label>Next run<input aria-label="Next run" type="datetime-local" required value={form.nextDue} onChange={e=>setForm(f=>({...f,nextDue:e.target.value}))}/></label><label>Schedule status<select aria-label="Schedule status" value={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.value}))}><option value="true">Enabled</option><option value="false">Disabled</option></select></label></div>}<label className="cf-scheduler-v2-modal__reason">Governance reason<textarea aria-label="Governance reason" value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))} placeholder="Required reason for this governed action"/></label>{action==='run_now'&&<p className="cf-scheduler-v2__note">This queues a manual governed request for the exact existing bounded policy and does not change its recurring cadence or next-run time.</p>}<div className="cf-scheduler-v2-modal__actions"><button onClick={closeEditor}>Cancel</button><button data-primary disabled={busy||form.reason.trim().length<5} onClick={submit}><Save size={14}/>{action==='run_now'?'Run on demand':'Save schedule'}</button></div></div></div>}
 </div>
}
