import React,{useEffect,useMemo,useState}from'react'
import{Clock3,ExternalLink,Play,RefreshCw,Save,Settings2,X}from'lucide-react'
import{supabase,api}from'./lib/supabase'
import'./scheduled-jobs-config.css'

const CHANGE='CF-CHG-20260910-092'
const human=v=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
const when=v=>v?new Date(v).toLocaleString():'—'
const target=x=>x?.entity_id?`${x.entity_type}:${x.entity_id}`:x?.source_id?`source:${x.source_id}`:x?.source_profile_id?`profile:${x.source_profile_id}`:'UNBOUNDED'
const cadenceDays=value=>{const m=String(value||'').match(/(\d+)\s+day/i);return m?m[1]:''}
const jobItems=value=>Array.isArray(value)?value:(value?.items||value?.rows||value?.jobs||[])
const jobLayer=row=>row?.layer??row?.requested_layer??String(row?.job_type||'').match(/layer[_ -]?(\d)/i)?.[1]??'—'
const jobName=row=>row?.job_name||row?.job_type||row?.source_label||row?.source_name||row?.source_code||row?.id||'Job'
const jobStarted=row=>row?.started_at||row?.created_at||row?.queued_at||row?.updated_at
const jobFinished=row=>row?.completed_at||row?.finished_at||row?.updated_at
const jobResult=row=>{const accepted=row?.accepted_count??row?.accepted??row?.applied_count,processed=row?.processed_count??row?.processed??row?.selected_count,rejected=row?.rejected_count??row?.rejected??row?.failed_count,bits=[];if(processed!=null)bits.push(`${processed} processed`);if(accepted!=null)bits.push(`${accepted} accepted`);if(rejected!=null)bits.push(`${rejected} rejected/failed`);return bits.join(' · ')||row?.completion_class||row?.failure_class||'—'}
const go=hash=>{location.hash=hash}

function Status({value}){return <span className="cf-scheduler-v2__status" data-state={String(value||'').toLowerCase()}>{human(value||'unknown')}</span>}
function Empty({colSpan,text}){return <tr><td colSpan={colSpan} className="cf-scheduler-v2__empty">{text}</td></tr>}

export default function ScheduledJobsWorkspace({onError}){
 const[data,setData]=useState({policies:[],requests:[],search_signals:[]}),[jobs,setJobs]=useState([]),[rank,setRank]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState(null),[action,setAction]=useState('edit_schedule'),[form,setForm]=useState({cadence:'',nextDue:'',enabled:'',reason:''})
 const load=async()=>{setBusy(true);setError('');try{const overviewPromise=supabase.rpc('refresh_intelligence_overview',{p_limit:100});const contextPromise=api.context();const jobsPromise=api.jobs(50).catch(()=>[]);const[overview,context,recent]=await Promise.all([overviewPromise,contextPromise,jobsPromise]);if(overview.error)throw overview.error;setData(overview.data||{policies:[],requests:[],search_signals:[]});setJobs(jobItems(recent));setRank(Number(context?.role_rank||0))}catch(e){setError(e?.message||String(e));onError?.(e?.message||String(e))}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const policies=useMemo(()=>Array.isArray(data.policies)?data.policies.filter(x=>Number(x.layer)>=1&&Number(x.layer)<=3&&target(x)!=='UNBOUNDED'):[],[data])
 const requests=Array.isArray(data.requests)?data.requests:[]
 const active=requests.filter(x=>['queued','running'].includes(String(x.status))).length
 const openEditor=(policy,nextAction)=>{setEditing(policy);setAction(nextAction);setMessage('');setError('');setForm({cadence:cadenceDays(policy.cadence_interval),nextDue:policy.next_due_at?new Date(policy.next_due_at).toISOString().slice(0,16):'',enabled:String(Boolean(policy.enabled)),reason:''})}
 const closeEditor=()=>{setEditing(null);setForm({cadence:'',nextDue:'',enabled:'',reason:''})}
 const policyArgs=(policy,nextDue,enabled,cadence,reason)=>({p_id:policy.id,p_country_code:policy.country_code||null,p_layer:Number(policy.layer),p_source_id:policy.source_id||null,p_source_profile_id:policy.source_profile_id||null,p_entity_type:policy.entity_type||null,p_entity_id:policy.entity_id||null,p_freshness_class:policy.freshness_class,p_cadence_days:cadence===''?null:Number(cadence),p_next_due_at:nextDue,p_hash_sensitive:Boolean(policy.hash_sensitive),p_important_date_sensitive:Boolean(policy.important_date_sensitive),p_enabled:Boolean(enabled),p_reason:`[${CHANGE}] ${reason}`})
 const submit=async()=>{if(!editing||form.reason.trim().length<5){setError('A governance reason of at least 5 characters is required.');return}setBusy(true);setError('');setMessage('');try{const runNow=action==='run_now';if(runNow&&!editing.enabled)throw new Error('Enable this schedule before running it on demand.');const nextDue=runNow?new Date().toISOString():(form.nextDue?new Date(form.nextDue).toISOString():editing.next_due_at);const cadence=runNow?cadenceDays(editing.cadence_interval):form.cadence;const enabled=runNow?editing.enabled:form.enabled==='true';const{error:rpcError}=await supabase.rpc('refresh_policy_upsert_v2',policyArgs(editing,nextDue,enabled,cadence,form.reason.trim()));if(rpcError)throw rpcError;setMessage(runNow?'Run requested: this exact bounded schedule is due now and will enter the normal governed scheduler queue on its next tick.':'Schedule updated through the governed refresh-policy control.');closeEditor();await load();if(runNow)setTimeout(()=>load(),4000)}catch(e){setError(e?.message||String(e));onError?.(e?.message||String(e))}finally{setBusy(false)}}
 return <div className="m23-stack cf-scheduler-v2-native">
  <section className="m23-panel cf-scheduler-v2">
   <div className="cf-scheduler-v2__head"><div><span className="m-eyebrow">Administration · Scheduling</span><h2>Scheduled Jobs & Run Control</h2><p>Edit governed Layer 1–3 refresh schedules, mark the same bounded target due on demand, and follow queue, Job and Evidence results without replaying arbitrary historical jobs.</p></div><div className="cf-scheduler-v2__actions"><button onClick={load} disabled={busy}><RefreshCw size={14}/> Refresh</button><button onClick={()=>go('#jobs')}>Open Jobs</button><button onClick={()=>go('#evidence')}>Open Evidence</button></div></div>
   {error&&<div className="cf-scheduler-v2__message" data-error="true">{error}</div>}{message&&<div className="cf-scheduler-v2__message">{message}</div>}
   <div className="cf-scheduler-v2__summary"><article><strong>{policies.length}</strong><span>Bounded Layer 1–3 schedules</span></article><article><strong>{active}</strong><span>Queued / active refresh requests</span></article><article><strong>{jobs.length}</strong><span>Recent governed Job records</span></article></div>
   <div className="cf-scheduler-v2__links"><button onClick={()=>go('#layer-1-operations')}>Layer 1 — Regulatory</button><button onClick={()=>go('#layer-2-enrichment')}>Layer 2 — Enrichment</button><button onClick={()=>go('#layer-3-ai-interpretation')}>Layer 3 — AI Interpretation</button></div>
  </section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Schedule Configuration</h3><Status value={rank>=4?'operator_controls':'read_only'}/></div><div className="cf-scheduler-v2__table-wrap"><table><thead><tr><th>Layer</th><th>Country</th><th>Scheduled Target</th><th>Freshness Policy</th><th>Cadence</th><th>Next Run</th><th>Schedule Status</th><th>Actions</th></tr></thead><tbody>{policies.length?policies.map(p=><tr key={p.id}><td>Layer {p.layer}</td><td>{p.country_code||'—'}</td><td><strong>{target(p)}</strong></td><td>{human(p.freshness_class)}</td><td>{p.cadence_interval||'Event driven'}</td><td>{when(p.next_due_at)}</td><td><Status value={p.enabled?'enabled':'disabled'}/></td><td><div className="cf-scheduler-v2__row-actions"><button disabled={busy||rank<4} onClick={()=>openEditor(p,'edit_schedule')}><Settings2 size={13}/> Edit schedule</button><button data-primary disabled={busy||rank<4||!p.enabled} title={!p.enabled?'Enable the schedule before an on-demand run.':''} onClick={()=>openEditor(p,'run_now')}><Play size={13}/> Run on demand</button><button onClick={()=>go({1:'#layer-1-operations',2:'#layer-2-enrichment',3:'#layer-3-ai-interpretation'}[p.layer])}>Open Layer {p.layer}</button></div></td></tr>):<Empty colSpan={8} text="No bounded Layer 1–3 policies are currently visible."/>}</tbody></table></div><p className="cf-scheduler-v2__note">Run on demand marks the selected existing bounded policy due now. The normal scheduler creates and dispatches its refresh request, so Layer-specific Evidence, qualification, identity, publication and Search controls remain unchanged. Historical Jobs are never reset or replayed.</p></section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Latest Refresh Queue</h3><button onClick={()=>go('#jobs')}>Follow in Jobs</button></div><div className="cf-scheduler-v2__table-wrap"><table><thead><tr><th>Layer</th><th>Trigger</th><th>Target</th><th>Status</th><th>Queued At</th><th>Completed At</th><th>Reason / Result</th></tr></thead><tbody>{requests.length?requests.slice(0,20).map(r=><tr key={r.id}><td>Layer {r.requested_layer}</td><td>{human(r.trigger_type)}</td><td>{target(r)}</td><td><Status value={r.status}/></td><td>{when(r.created_at)}</td><td>{when(r.completed_at)}</td><td>{r.reason||r.schedule_error||'—'}</td></tr>):<Empty colSpan={7} text="No recent refresh requests are visible."/>}</tbody></table></div></section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Recent Job Runs</h3><div className="cf-scheduler-v2__links"><button onClick={()=>go('#jobs')}>All Jobs</button><button onClick={()=>go('#evidence')}>Evidence</button></div></div><div className="cf-scheduler-v2__table-wrap"><table><thead><tr><th>Layer</th><th>Job / Source</th><th>Status</th><th>Run Mode</th><th>Started</th><th>Completed</th><th>Result</th><th>Follow</th></tr></thead><tbody>{jobs.length?jobs.slice(0,20).map((r,i)=><tr key={r.id||r.job_id||i}><td>{jobLayer(r)==='—'?'—':`Layer ${jobLayer(r)}`}</td><td><strong>{jobName(r)}</strong><br/><small>{r.id||r.job_id||'—'}</small></td><td><Status value={r.status||r.state}/></td><td>{human(r.run_mode||r.mode||r.trigger_type||'—')}</td><td>{when(jobStarted(r))}</td><td>{when(jobFinished(r))}</td><td>{jobResult(r)}</td><td><div className="cf-scheduler-v2__row-actions"><button onClick={()=>go('#jobs')}>Jobs <ExternalLink size={12}/></button><button onClick={()=>go('#evidence')}>Evidence <ExternalLink size={12}/></button></div></td></tr>):<Empty colSpan={8} text="No recent Job records returned by the governed Jobs read surface."/>}</tbody></table></div></section>
  <section className="m23-panel cf-scheduler-v2"><div className="cf-scheduler-v2__subhead"><h3>Downstream Search Refresh Signals</h3></div><div className="cf-scheduler-v2__table-wrap"><table><thead><tr><th>Entity</th><th>Status</th><th>Created</th><th>Reason</th></tr></thead><tbody>{(data.search_signals||[]).length?(data.search_signals||[]).map(x=><tr key={x.id}><td>{x.entity_type}:{x.entity_id}</td><td><Status value={x.status||'queued'}/></td><td>{when(x.created_at)}</td><td>{x.reason||x.signal_reason||'—'}</td></tr>):<Empty colSpan={4} text="No downstream Search refresh signals."/>}</tbody></table></div></section>
  {editing&&<div className="cf-scheduler-v2-modal" role="dialog" aria-modal="true" aria-label={action==='run_now'?'Run on demand':'Edit schedule'}><div className="cf-scheduler-v2-modal__card"><button className="cf-scheduler-v2-modal__close" aria-label="Close" onClick={closeEditor}><X size={17}/></button><div className="cf-scheduler-v2-modal__title"><Clock3 size={18}/><div><h3>{action==='run_now'?`Run Layer ${editing.layer} on demand`:'Edit schedule'}</h3><p>Layer {editing.layer} · {editing.country_code||'—'} · {target(editing)} · {human(editing.freshness_class)}</p></div></div>{action==='edit_schedule'&&<div className="cf-scheduler-v2-modal__grid"><label>Cadence (days)<input aria-label="Cadence days" type="number" min="1" max="3650" value={form.cadence} onChange={e=>setForm(f=>({...f,cadence:e.target.value}))}/></label><label>Next run<input aria-label="Next run" type="datetime-local" value={form.nextDue} onChange={e=>setForm(f=>({...f,nextDue:e.target.value}))}/></label><label>Schedule status<select aria-label="Schedule status" value={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.value}))}><option value="true">Enabled</option><option value="false">Disabled</option></select></label></div>}<label className="cf-scheduler-v2-modal__reason">Governance reason<textarea aria-label="Governance reason" value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))} placeholder="Required reason for this governed action"/></label>{action==='run_now'&&<p className="cf-scheduler-v2__note">This marks the existing bounded policy due now; the normal governed scheduler performs queue creation and Layer dispatch.</p>}<div className="cf-scheduler-v2-modal__actions"><button onClick={closeEditor}>Cancel</button><button data-primary disabled={busy||form.reason.trim().length<5} onClick={submit}><Save size={14}/>{action==='run_now'?'Run on demand':'Save schedule'}</button></div></div></div>}
 </div>
}