import React,{useEffect,useMemo,useState}from'react'
import{Activity,BrainCircuit,CheckCircle2,Play,RefreshCw,Save,ShieldCheck}from'lucide-react'
import{adminRead,supabase}from'./lib/supabase'
import'./scholarship-ai-control.css'
const fmt=n=>Number(n||0).toLocaleString(),money=n=>`$${Number(n||0).toFixed(4)}`,human=v=>String(v??'—').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())
export default function ScholarshipAiControl({rank=4,country='AU',onError=()=>{}}){const[data,setData]=useState(null),[profile,setProfile]=useState(''),[task,setTask]=useState('scholarship_page_classification'),[limit,setLimit]=useState(3),[busy,setBusy]=useState(false),[active,setActive]=useState(null),[saved,setSaved]=useState('')
 const load=async()=>{try{const d=await adminRead('scholarship_ai',{country_code:country});setData(d);setProfile(p=>d?.profiles?.some(x=>x.id===p)?p:(d?.profiles?.[0]?.id||''))}catch(e){onError(e.message||String(e))}}
 useEffect(()=>{load()},[country])
 const chosen=useMemo(()=>data?.profiles?.find(x=>x.id===profile),[data,profile]);const benchmarkReady=Boolean(chosen&&!chosen.benchmark_pass),governedReady=Boolean(chosen?.benchmark_pass&&!chosen?.paused&&data?.settings?.enabled)
 const invoke=async(body)=>{const{data:r,error}=await supabase.functions.invoke('scholarship-ai-control',{body});if(error)throw error;if(r?.error)throw new Error(r.error);return r}
 const start=async benchmark=>{setBusy(true);setSaved('');try{const r=await invoke({action:'start',country_code:country,task_class:task,profile_id:profile,limit:benchmark?Math.min(limit,5):limit,benchmark,changes_only:true});setActive(r.run_id);setSaved(`${benchmark?'Benchmark':'AI'} run queued · ${r.total_items} changed Evidence item(s).`);if(r.total_items>0){const p=await invoke({action:'process',run_id:r.run_id,max_items:benchmark?Math.min(r.total_items,3):Math.min(r.total_items,5)});setSaved(`${benchmark?'Benchmark':'AI'} batch processed · ${p.run?.processed_items||0}/${p.run?.total_items||0}.`)}await load()}catch(e){onError(e.message||String(e))}finally{setBusy(false)}}
 const process=async id=>{setBusy(true);try{const r=await invoke({action:'process',run_id:id,max_items:5});setActive(id);setSaved(`Processed ${r.run?.processed_items||0}/${r.run?.total_items||0} · ${money(r.run?.cost_usd)}.`);await load()}catch(e){onError(e.message||String(e))}finally{setBusy(false)}}
 const saveSchedule=async enabled=>{if(rank<5)return;setBusy(true);try{const r=await invoke({action:'settings',country_code:country,patch:{enabled, schedule_on_change:true,default_profile_id:profile,default_task_class:task,max_records_per_run:25,daily_budget_usd:1}});setSaved(enabled?'Change-only AI scheduling enabled.':'Scholarship AI scheduling disabled.');await load()}catch(e){onError(e.message||String(e))}finally{setBusy(false)}}
 const q=data?.queue||{},t=data?.telemetry||{},runs=data?.recent_runs||[];return <section className="sai-panel"><div className="sai-head"><div><small>Layer 3 · Scholarship AI</small><h3>AI inference</h3><p>Changed Evidence only. Structured candidates go to review; AI never publishes.</p></div><button onClick={load}><RefreshCw size={14}/>Refresh</button></div><div className="sai-stats"><span><b>{fmt(q.needs_review)}</b> review</span><span><b>{fmt(q.unclassified)}</b> unclassified</span><span><b>{fmt(t.api_calls)}</b> calls</span><span><b>{money(t.cost_usd)}</b> cost</span></div><div className="sai-controls"><label>Task<select value={task} onChange={e=>setTask(e.target.value)}><option value="scholarship_page_classification">Page classification</option><option value="scholarship_detail_extract">Scholarship details</option></select></label><label>Model<select value={profile} onChange={e=>setProfile(e.target.value)}>{(data?.profiles||[]).map(p=><option key={p.id} value={p.id}>{p.model_identifier} · {p.benchmark_pass?'qualified':'benchmark required'}</option>)}</select></label><label>Records<input type="number" min="1" max="100" value={limit} onChange={e=>setLimit(Math.max(1,Math.min(100,Number(e.target.value)||1)))}/></label><div className="sai-actions">{benchmarkReady&&rank>=5&&<button className="primary" disabled={busy||!profile} onClick={()=>start(true)}><BrainCircuit size={14}/>{busy?'Running…':'Test model'}</button>}{governedReady&&<button className="primary" disabled={busy} onClick={()=>start(false)}><Play size={14}/>Run changed</button>}{rank>=5&&chosen?.benchmark_pass&&<button disabled={busy} onClick={()=>saveSchedule(!data?.settings?.enabled)}><Save size={14}/>{data?.settings?.enabled?'Disable schedule':'Enable change schedule'}</button>}</div></div><div className="sai-gate"><ShieldCheck size={15}/><span>{chosen?.benchmark_pass?'Model benchmark passed.':'Model is staged but paused until paid benchmark passes.'} Schedule policy: changes only · default daily budget {money(data?.settings?.daily_budget_usd||1)}.</span></div>{saved&&<div className="sai-ok">{saved}</div>}<div className="sai-runs">{runs.slice(0,6).map(r=>{const pct=r.total_items?Math.round((Number(r.processed_items||0)/Number(r.total_items))*100):100;return <article key={r.id}><div><strong>{human(r.trigger_mode)} · {human(r.task_class)}</strong><small>{fmt(r.processed_items)}/{fmt(r.total_items)} · {fmt(r.api_calls)} calls · {money(r.cost_usd)}</small></div><div className="sai-progress"><span style={{width:`${pct}%`}}/></div><em>{pct}%</em>{['queued','running'].includes(r.status)&&<button disabled={busy} onClick={()=>process(r.id)}>Continue</button>}</article>})}</div></section>}
