import React,{useEffect,useMemo,useState}from'react'
import{Activity,AlertTriangle,BookOpen,Building2,CheckCircle2,ChevronDown,ExternalLink,GraduationCap,Play,RefreshCw,Save,Search,Settings2,ShieldCheck,Sparkles,Workflow,X}from'lucide-react'
import{adminRead,api,supabase}from'./lib/supabase'
import'./scholarship-runtime.css'

const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString():'—'
const human=v=>String(v??'—').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())
const date=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(+d)?String(v):d.toLocaleString()}
const statusTone=v=>['pass','passed','succeeded','completed','published','active','captured'].includes(String(v).toLowerCase())?'ok':['failed','error','rejected','blocked'].includes(String(v).toLowerCase())?'bad':['queued','running','pending','needs_review','review'].includes(String(v).toLowerCase())?'warn':'neutral'
function Status({value}){return <span className={`sr-status ${statusTone(value)}`}>{human(value)}</span>}

export default function ScholarshipRuntimeWorkspace({rank=4,onError=()=>{},navigate=()=>{},adminOnly=false}){
 const[country,setCountry]=useState('AU'),[tab,setTab]=useState(adminOnly?'runtime':'overview'),[runtime,setRuntime]=useState(null),[uat,setUat]=useState(null),[loading,setLoading]=useState(false),[runBusy,setRunBusy]=useState(false),[scopeType,setScopeType]=useState('country'),[providerQuery,setProviderQuery]=useState(''),[providerResults,setProviderResults]=useState([]),[provider,setProvider]=useState(null),[preview,setPreview]=useState(null),[runResult,setRunResult]=useState(null),[reconcile,setReconcile]=useState(null),[settings,setSettings]=useState(null),[settingsBusy,setSettingsBusy]=useState(false),[saved,setSaved]=useState(''),[providerSort,setProviderSort]=useState({key:'candidate_total',dir:'desc'}),[catalogue,setCatalogue]=useState(null),[catQuery,setCatQuery]=useState(''),[catOffset,setCatOffset]=useState(0),[catSort,setCatSort]=useState('scholarship'),[catDir,setCatDir]=useState('asc'),[catPublication,setCatPublication]=useState(''),[catBusy,setCatBusy]=useState(false)
 const load=async()=>{setLoading(true);try{const r=await adminRead('scholarship_runtime',{country_code:country,limit:200});setRuntime(r);setSettings(r?.settings||null);const u=await adminRead('scholarship_runtime_uat',{country_code:country});setUat(u)}catch(e){onError(e.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{if(rank>=4)load()},[country,rank])
 useEffect(()=>{if(scopeType!=='university'){setProvider(null);setProviderQuery('');setProviderResults([]);return}const q=providerQuery.trim();if(q.length<2||provider?.label===q){setProviderResults([]);return}const t=setTimeout(async()=>{try{const x=await api.providerPage({limit:10,offset:0,query:q,country,sort:'provider',direction:'asc'});setProviderResults(x?.items||[])}catch(e){onError(e.message||String(e))}},220);return()=>clearTimeout(t)},[providerQuery,scopeType,country,provider?.label])
 const invokeRuntime=async action=>{if(scopeType==='university'&&!provider?.id){onError('Choose a University before running this scope.');return}setRunBusy(true);setSaved('');try{const{data,error}=await supabase.functions.invoke('scholarship-runtime-control',{body:{action,country_code:country,scope_type:scopeType,scope_id:scopeType==='university'?provider.id:null}});if(error)throw error;if(data?.error)throw new Error(data.detail||data.error);if(action.startsWith('reconcile_')){setReconcile(data.reconciliation||data);setSaved(action==='reconcile_apply'?'Verified first-party details reconciled. New roots remain unpublished.':'Reconciliation preview is read-only.');if(action==='reconcile_apply')await load()}else if(action==='preview')setPreview(data);else{setRunResult(data);setPreview(null);setSaved('Runtime started. Jobs are visible in Recent Jobs and the Job workspace.');await load()}}catch(e){onError(e.message||String(e))}finally{setRunBusy(false)}}
 const saveSettings=async()=>{if(rank<5||!settings)return;setSettingsBusy(true);setSaved('');try{const{data,error}=await supabase.rpc('scholarship_runtime_settings_write',{p_patch:{country_code:country,enabled:Boolean(settings.enabled),detail_batch_limit:Number(settings.detail_batch_limit),auto_dispatch:Boolean(settings.auto_dispatch),catalogue_refresh_hours:Number(settings.catalogue_refresh_hours),detail_refresh_hours:Number(settings.detail_refresh_hours)}});if(error)throw error;setSettings(data);setSaved('Scholarship runtime settings saved and verified.');await load()}catch(e){onError(e.message||String(e))}finally{setSettingsBusy(false)}}
 const loadCatalogue=async()=>{setCatBusy(true);try{const x=await api.scholarshipPage({limit:50,offset:catOffset,query:catQuery,country,publication:catPublication,sort:catSort,direction:catDir});setCatalogue(x)}catch(e){onError(e.message||String(e))}finally{setCatBusy(false)}}
 useEffect(()=>{if(tab==='catalogue')loadCatalogue()},[tab,country,catOffset,catSort,catDir,catPublication])
 useEffect(()=>{if(tab!=='catalogue')return;const t=setTimeout(()=>{setCatOffset(0);loadCatalogue()},260);return()=>clearTimeout(t)},[catQuery])
 const summary=runtime?.summary||{},providers=runtime?.providers||[],countries=(runtime?.countries||[]).map(x=>({value:x.code,label:x.name})),policy=runtime?.policy||{}
 const sortedProviders=useMemo(()=>[...providers].sort((a,b)=>{const k=providerSort.key,dir=providerSort.dir==='asc'?1:-1,aa=a?.[k],bb=b?.[k];if(typeof aa==='number'||typeof bb==='number')return(Number(aa||0)-Number(bb||0))*dir;return String(aa||'').localeCompare(String(bb||''))*dir}),[providers,providerSort])
 const changeProviderSort=key=>setProviderSort(s=>s.key===key?{key,dir:s.dir==='asc'?'desc':'asc'}:{key,dir:'desc'})
 const catRows=catalogue?.items||[],catTotal=Number(catalogue?.total||0)
 return <div className="sr-shell">
  <section className="sr-hero"><div><small>M2.4.5 · Scholarship PIM runtime</small><h2>International Scholarship Operations</h2><p>Acquire first-party Scholarship catalogues at Country or University scope, qualify international detail candidates, retain Evidence and keep publication fail-closed.</p></div><div className="sr-hero-actions"><label>Country<select value={country} onChange={e=>{setCountry(e.target.value);setPreview(null);setRunResult(null);setReconcile(null)}}>{countries.length?countries.map(x=><option key={x.value} value={x.value}>{x.label}</option>):<><option value="AU">Australia</option><option value="NZ">New Zealand</option></>}</select></label><button onClick={load} disabled={loading}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh stats'}</button></div></section>
  {!adminOnly&&<nav className="sr-tabs">{[['overview','Overview'],['runtime','Acquire & fill'],['catalogue','Catalogue'],['uat','UAT']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>}
  {adminOnly&&<nav className="sr-tabs"><button className={tab==='runtime'?'active':''} onClick={()=>setTab('runtime')}>Runtime settings</button><button className={tab==='uat'?'active':''} onClick={()=>setTab('uat')}>UAT</button></nav>}

  {tab==='overview'&&<><section className="sr-stats"><Metric label="Canonical" value={summary.canonical}/><Metric label="International canonical" value={summary.international_canonical}/><Metric label="Discovery candidates" value={summary.candidates}/><Metric label="Detail ready" value={summary.detail_ready}/><Metric label="Needs review" value={summary.needs_review}/><Metric label="Captured source" value={summary.captured_source_records}/><Metric label="Ready to reconcile" value={summary.reconciliation_ready}/><Metric label="Reconciled unpublished" value={summary.reconciled_unpublished}/><Metric label="Mapped Courses" value={summary.mapped_courses}/><Metric label="Net-fee calculations" value={summary.calculations}/></section>
   <section className="sr-panel"><Header title="Provider coverage" text="Operational maturity by University. Sort the columns to find the biggest remaining gaps first." action={<button onClick={()=>navigate('Jobs')}><Workflow size={13}/>Jobs</button>}/><div className="sr-table-wrap"><table><thead><tr><Th label="University" k="provider_name" sort={providerSort} onSort={changeProviderSort}/><Th label="Canonical" k="canonical_total" sort={providerSort} onSort={changeProviderSort}/><Th label="Candidates" k="candidate_total" sort={providerSort} onSort={changeProviderSort}/><Th label="Detail ready" k="detail_ready_total" sort={providerSort} onSort={changeProviderSort}/><Th label="Evidence acquired" k="evidence_acquired_total" sort={providerSort} onSort={changeProviderSort}/><Th label="Review" k="candidate_needs_review_total" sort={providerSort} onSort={changeProviderSort}/><Th label="Mapped" k="canonical_linked_total" sort={providerSort} onSort={changeProviderSort}/><th>Open</th></tr></thead><tbody>{sortedProviders.length?sortedProviders.map(x=><tr key={x.provider_id}><td><strong>{x.provider_name}</strong><small>{x.canonical_to_landscape_pct!=null?`${x.canonical_to_landscape_pct}% landscape coverage`:''}</small></td><td>{fmt(x.canonical_total)}</td><td>{fmt(x.candidate_total)}</td><td>{fmt(x.detail_ready_total)}</td><td>{fmt(x.evidence_acquired_total)}</td><td>{fmt(x.candidate_needs_review_total)}</td><td>{fmt(x.canonical_linked_total)}</td><td><button onClick={()=>navigate('Providers',{id:x.provider_id})}><Building2 size={12}/>Provider</button></td></tr>):<tr><td colSpan="8">No Provider Scholarship statistics for this country yet.</td></tr>}</tbody></table></div></section>
   <section className="sr-panel"><Header title="Recent scope runs" text="Country and University acquisitions remain visible as governed jobs and requests."/><div className="sr-run-list">{(runtime?.recent_runs||[]).map(x=><article key={x.id}><div><strong>{human(x.scope_type)} · {x.metadata?.scope_name||x.country_code}</strong><small>{date(x.requested_at)} · {fmt(x.provider_count)} executable Provider(s)</small></div><Status value={x.status}/></article>)}</div></section></>}

  {tab==='runtime'&&<><section className="sr-panel"><Header title="Acquire Scholarships" text="Use Country for scalable fill or University for targeted verification. Preview is read-only; Start creates governed jobs only."/>
   <div className="sr-runtime-grid"><label>Scope<select value={scopeType} onChange={e=>{setScopeType(e.target.value);setPreview(null);setRunResult(null);setReconcile(null)}}><option value="country">Country</option><option value="university">University</option></select></label>{scopeType==='university'&&<label className="sr-provider-search">University<input value={providerQuery} onChange={e=>{setProviderQuery(e.target.value);if(provider&&e.target.value!==provider.label)setProvider(null)}} placeholder="Search RMIT, Monash, Deakin…"/>{providerResults.length>0&&<div className="sr-results">{providerResults.map(x=><button key={x.id} onClick={()=>{setProvider({id:x.id,label:x.canonical_name||x.display_name||x.provider_name});setProviderQuery(x.canonical_name||x.display_name||x.provider_name);setProviderResults([]);setReconcile(null)}}><strong>{x.canonical_name||x.display_name||x.provider_name}</strong><small>{x.country_code} · {fmt(x.course_count)} Courses</small></button>)}</div>}</label>}<div className="sr-run-actions"><button className="secondary" disabled={runBusy} onClick={()=>invokeRuntime('preview')}><Search size={14}/>Preview</button><button className="primary" disabled={runBusy||settings?.enabled===false} onClick={()=>invokeRuntime('start')}><Play size={14}/>{runBusy?'Running…':'Start governed fill'}</button></div></div>
   <div className="sr-policy"><ShieldCheck size={17}/><div><strong>Locked acquisition safeguards</strong><span>International-only · no automatic canonical mutation · no publication · scraper routes remain in Administration → Scraper Config.</span></div></div>
   {(preview||runResult)&&<RuntimeResult value={preview||runResult}/>} 
  </section>
  <section className="sr-panel"><Header title="Reconcile verified details" text="Promote only verified individual first-party detail records into linked or new unpublished canonical Scholarship roots. Catalogue pages, navigation fragments and duplicates stay out."/>
   <div className="sr-run-actions"><button className="secondary" disabled={runBusy} onClick={()=>invokeRuntime('reconcile_preview')}><Search size={14}/>Preview verified details</button>{rank>=5?<button className="primary" disabled={runBusy} onClick={()=>invokeRuntime('reconcile_apply')}><CheckCircle2 size={14}/>Reconcile unpublished</button>:<span className="sr-policy"><ShieldCheck size={14}/>PIM Admin required to change canonical records.</span>}</div>
   <div className="sr-policy"><ShieldCheck size={17}/><div><strong>Canonical gate</strong><span>First-party detail URL + international audience + Evidence + confidence threshold + navigation/catalogue exclusion. Publication remains blocked.</span></div></div>
   {reconcile&&<ReconciliationResult value={reconcile}/>} {saved&&<div className="sr-success">{saved}</div>}
  </section>
  <SettingsPanel rank={rank} settings={settings} setSettings={setSettings} busy={settingsBusy} save={saveSettings} policy={policy}/></>}

  {tab==='catalogue'&&<section className="sr-panel"><Header title="Scholarship catalogue" text="Search across Scholarship, University, description, award, type and year. Sort by the fields that matter operationally."/>
   <div className="sr-catalogue-controls"><label className="search"><Search size={14}/><input value={catQuery} onChange={e=>setCatQuery(e.target.value)} placeholder="Search Scholarship, University, award, description or year…"/>{catQuery&&<button onClick={()=>setCatQuery('')}><X size={12}/></button>}</label><label>Publication<select value={catPublication} onChange={e=>{setCatPublication(e.target.value);setCatOffset(0)}}><option value="">All</option><option value="published">Published</option><option value="unpublished">Unpublished</option><option value="review">Review</option><option value="draft">Draft</option></select></label></div>
   <div className="sr-table-wrap wide"><table><thead><tr><CatTh label="Scholarship" k="scholarship" sort={catSort} dir={catDir} set={(k,d)=>{setCatSort(k);setCatDir(d)}}/><CatTh label="University" k="provider" sort={catSort} dir={catDir} set={(k,d)=>{setCatSort(k);setCatDir(d)}}/><th>Description</th><CatTh label="Award" k="award" sort={catSort} dir={catDir} set={(k,d)=>{setCatSort(k);setCatDir(d)}}/><CatTh label="Year" k="year" sort={catSort} dir={catDir} set={(k,d)=>{setCatSort(k);setCatDir(d)}}/><CatTh label="Close" k="close" sort={catSort} dir={catDir} set={(k,d)=>{setCatSort(k);setCatDir(d)}}/><CatTh label="Mapped Courses" k="courses" sort={catSort} dir={catDir} set={(k,d)=>{setCatSort(k);setCatDir(d)}}/><CatTh label="Evidence" k="evidence" sort={catSort} dir={catDir} set={(k,d)=>{setCatSort(k);setCatDir(d)}}/><th>State</th></tr></thead><tbody>{catBusy&&!catRows.length?<tr><td colSpan="9">Loading Scholarships…</td></tr>:catRows.length?catRows.map(x=><tr key={x.id} onClick={()=>navigate('Scholarships',{id:x.id})}><td><strong>{x.name}</strong><small>{human(x.scholarship_type)} · {human(x.audience)}</small></td><td>{x.provider_name||'—'}</td><td className="desc">{x.description_excerpt||'No description captured.'}</td><td>{x.award_percentage!=null?`${x.award_percentage}%`:x.award_amount!=null?`${x.award_currency_code||''} ${fmt(x.award_amount)}`:x.award_value_text||'—'}</td><td>{x.academic_year||'—'}</td><td>{x.application_close_date||'—'}</td><td>{fmt(x.mapped_course_count)}</td><td>{fmt(x.evidence_count)}</td><td><Status value={x.publication_status}/></td></tr>):<tr><td colSpan="9">No matching Scholarships.</td></tr>}</tbody></table></div><div className="sr-pager"><span>{fmt(catTotal)} matching · page {Math.floor(catOffset/50)+1}</span><div><button disabled={catOffset===0} onClick={()=>setCatOffset(x=>Math.max(0,x-50))}>Previous</button><button disabled={catOffset+50>=catTotal} onClick={()=>setCatOffset(x=>x+50)}>Next</button></div></div></section>}

  {tab==='uat'&&<section className="sr-panel"><Header title="Scholarship runtime UAT" text="Live checks validate security, Evidence, international-only acquisition, guarded canonical reconciliation, cross-reference and fail-closed calculations." action={<button onClick={load}><RefreshCw size={13}/>Re-run</button>}/><div className={`sr-uat-head ${uat?.status==='pass'?'pass':'fail'}`}><ShieldCheck size={20}/><div><strong>{uat?.status==='pass'?'UAT PASS':'UAT requires attention'}</strong><span>{fmt(uat?.passed)} passed · {fmt(uat?.failed)} failed · {date(uat?.tested_at)}</span></div></div><div className="sr-uat-list">{(uat?.checks||[]).map(x=><article key={x.code}><span>{x.passed?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>}</span><div><strong>{human(x.code)}</strong><small>{x.description}</small></div><Status value={x.passed?'pass':'fail'}/></article>)}</div></section>}
 </div>
}

function Header({title,text,action}){return <div className="sr-head"><div><h3>{title}</h3><p>{text}</p></div>{action}</div>}
function Metric({label,value}){return <div className="sr-metric"><small>{label}</small><strong>{fmt(value)}</strong></div>}
function Th({label,k,sort,onSort}){return <th><button onClick={()=>onSort(k)}>{label}{sort.key===k?<span>{sort.dir==='asc'?' ↑':' ↓'}</span>:null}</button></th>}
function CatTh({label,k,sort,dir,set}){return <th><button onClick={()=>set(k,sort===k&&dir==='asc'?'desc':'asc')}>{label}{sort===k?<span>{dir==='asc'?' ↑':' ↓'}</span>:null}</button></th>}
function RuntimeResult({value}){const c=value.catalogue||{},d=value.detail||{};return <div className="sr-result"><div><small>Catalogue</small><strong>{fmt(c.jobs_queued??c.jobs_if_started??c.executable_provider_count)}</strong><span>{c.action==='preview'?'jobs if started':'jobs queued'} · route gap {fmt(c.catalogue_or_route_gap)}</span></div><div><small>International detail</small><strong>{fmt(d.jobs_queued??d.detail_ready)}</strong><span>{d.action==='preview'?'detail-ready candidates':'detail jobs queued'} · review {fmt(d.needs_review)}</span></div><div><small>Publication</small><strong>Blocked</strong><span>No automatic canonical mutation or publication.</span></div></div>}
function ReconciliationResult({value}){const preview=value.action==='preview';return <div className="sr-result"><div><small>{preview?'Ready':'Processed'}</small><strong>{fmt(preview?value.ready:value.processed)}</strong><span>{preview?`${fmt(value.new_unpublished_roots)} new · ${fmt(value.existing_matches)} existing`:`${fmt(value.created_unpublished)} created · ${fmt(value.linked_existing)} linked`}</span></div><div><small>Review protected</small><strong>{fmt(preview?value.generic_or_catalogue_review:value.review_reclassified)}</strong><span>Catalogue/navigation candidates remain outside canonical fill.</span></div><div><small>Publication</small><strong>Blocked</strong><span>Reconciliation can create unpublished roots only.</span></div></div>}
function SettingsPanel({rank,settings,setSettings,busy,save,policy}){if(!settings)return null;return <section className="sr-panel"><Header title="Basic runtime settings" text="Only settings that operators need to maintain. Credentials, vendor rate limits and route order remain in Scraper Config."/>{rank<5?<div className="sr-policy"><ShieldCheck size={16}/><span>Settings are read-only for Pipeline Operators. PIM Admin or Platform Admin can change them.</span></div>:<div className="sr-settings"><label className="check"><input type="checkbox" checked={settings.enabled!==false} onChange={e=>setSettings(x=>({...x,enabled:e.target.checked}))}/><span><strong>Runtime enabled</strong><small>Allow new Scholarship acquisition jobs for this country.</small></span></label><label>Detail jobs per batch<input type="number" min="1" max="100" value={settings.detail_batch_limit??25} onChange={e=>setSettings(x=>({...x,detail_batch_limit:e.target.value}))}/><small>Default 25. Scheduler still bounds immediate dispatch.</small></label><label className="check"><input type="checkbox" checked={settings.auto_dispatch!==false} onChange={e=>setSettings(x=>({...x,auto_dispatch:e.target.checked}))}/><span><strong>Auto-dispatch qualified details</strong><small>Start qualified international detail jobs after scope firing.</small></span></label><label>Catalogue refresh hours<input type="number" min="1" max="2160" value={settings.catalogue_refresh_hours??168} onChange={e=>setSettings(x=>({...x,catalogue_refresh_hours:e.target.value}))}/></label><label>Detail refresh hours<input type="number" min="1" max="2160" value={settings.detail_refresh_hours??168} onChange={e=>setSettings(x=>({...x,detail_refresh_hours:e.target.value}))}/></label><button className="primary save" disabled={busy} onClick={save}><Save size={14}/>{busy?'Saving…':'Save settings'}</button></div>}<div className="sr-policy"><Settings2 size={16}/><div><strong>Managed elsewhere</strong><span>Scraper API keys, quotas, concurrency and route priority → Administration / Scraper Config. International-only and publication-blocked safeguards are locked policy, not editable toggles.</span></div></div></section>}