CREATE OR REPLACE FUNCTION security.admin_layer1_operations_read(p_args jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'pg_catalog', 'security', 'pipeline', 'ref', 'auth'
AS $function$
declare v_rank integer; v_country text:=upper(nullif(p_args->>'country_code','')); v_result jsonb;
begin
 if auth.uid() is null then raise exception 'authentication required' using errcode='42501'; end if;
 select security.current_role_rank() into v_rank;
 if coalesce(v_rank,0)<4 then raise exception 'pipeline_operator role required' using errcode='42501'; end if;
 with src as (
  select s.id source_id,coalesce(co.iso_alpha2::text,case when s.metadata->>'scope'='global' then 'GLOBAL' end) country_code,coalesce(co.name,case when s.metadata->>'scope'='global' then 'Global' end) country_name,s.label source_label,s.source_type,s.url source_url,s.status source_status,s.trust_rank,s.last_checked_at,s.last_success_at,s.last_failure_at,s.last_error,s.metadata->>'dataset_class' dataset_class,s.metadata->>'source_system' source_system,(s.metadata->>'edition_year')::integer edition_year,s.metadata->>'acquisition_mode' acquisition_mode,s.metadata->>'scope' source_scope,
   o.authority_name,o.authority_domains,o.expected_format,o.expected_count_kind,o.active,o.paused,o.verification_cadence_days,o.ingestion_cadence_days,o.variance_warn_percent,o.variance_block_percent,o.min_expected_records,o.max_expected_records,o.previous_accepted_count,o.last_expected_count,o.previous_accepted_hash,o.last_source_hash,o.last_verified_at,o.verification_status,o.verification_message,o.variance_percent,o.variance_decision,o.next_verification_at,o.next_ingestion_at,o.last_schedule_status,o.last_schedule_error,o.consecutive_failures,o.updated_at,
   coalesce((select max(v.version_no) from pipeline.layer1_source_operation_versions v where v.source_id=s.id),0) source_config_version,
   case when o.last_verified_at is null then 'never_verified' when o.paused then 'paused' when o.verification_status in ('blocked','failed') then 'unhealthy' when exists(select 1 from pipeline.layer1_run_queue q where q.source_id=s.id and q.status='running' and coalesce(q.heartbeat_at,q.started_at,q.requested_at)<now()-interval '30 minutes') then 'stuck' when o.next_verification_at is not null and o.next_verification_at<now() then 'stale' else 'healthy' end source_health,
   case when o.paused then 'Source processing is paused.' when exists(select 1 from pipeline.layer1_run_queue q where q.source_id=s.id and q.status='running' and coalesce(q.heartbeat_at,q.started_at,q.requested_at)<now()-interval '30 minutes') then 'Running job heartbeat is stale; Platform Admin may recover it after confirming the prior worker is no longer active.' when o.verification_status='blocked' then 'Resolve source authority/count blocker before run.' when o.verification_status='failed' then 'Revalidate source before run.' when o.last_verified_at is null then 'Validate source before run.' when o.next_verification_at is not null and o.next_verification_at<now() then 'Source verification is stale; recheck before run.' when o.variance_decision='warn' then 'Review variance warning; explicit acknowledgement required for APPLY.' else 'Source is eligible for governed queueing.' end next_action,
   (select jsonb_build_object('id',q.id,'mode',q.mode,'status',q.status,'requested_at',q.requested_at,'started_at',q.started_at,'completed_at',q.completed_at,'current_stage',q.current_stage,'heartbeat_at',q.heartbeat_at,'stuck',q.status='running' and coalesce(q.heartbeat_at,q.started_at,q.requested_at)<now()-interval '30 minutes','expected_count',q.expected_count,'processed_count',q.processed_count,'progress_percent',case when q.expected_count is null or q.expected_count=0 then null else round(least(100,(q.processed_count::numeric/q.expected_count::numeric)*100),1) end,'queue_position',case when q.status='queued' then 1 else null end,'runtime_seconds',case when q.started_at is null then null else greatest(0,round(extract(epoch from (coalesce(q.completed_at,now())-q.started_at))::numeric,1)) end,'created_count',q.created_count,'updated_count',q.updated_count,'unchanged_count',q.unchanged_count,'rejected_count',q.rejected_count,'conflicted_count',q.conflicted_count,'failed_count',q.failed_count,'resume_cursor',q.resume_cursor,'actual_job_id',q.actual_job_id,'retry_of_run_id',q.retry_of_run_id,'error_text',q.error_text,'result',q.result) from pipeline.layer1_run_queue q where q.source_id=s.id order by q.requested_at desc limit 1) latest_run,
   (select count(*)::bigint from pipeline.layer1_run_queue q where q.source_id=s.id and q.status='queued') queue_depth,
   (select count(*)::bigint from pipeline.evidence_artifacts e where e.source_id=s.id) evidence_count,
   (select max(e.captured_at) from pipeline.evidence_artifacts e where e.source_id=s.id) latest_evidence_at,
   (select max(j.completed_at) from pipeline.jobs j where j.source_id=s.id and j.status='completed') latest_job_success_at,
   (select count(*)::bigint from pipeline.jobs j where j.source_id=s.id and j.status='running' and j.started_at<now()-interval '30 minutes') stale_running_jobs,
   p.enabled schedule_enabled,p.cadence_interval,p.next_due_at schedule_next_due_at,p.freshness_class schedule_freshness_class,p.hash_sensitive schedule_hash_sensitive,p.updated_at schedule_policy_updated_at
  from pipeline.layer1_source_operations o join pipeline.sources s on s.id=o.source_id left join ref.countries co on co.id=s.country_id left join pipeline.refresh_policies p on p.layer=1 and p.source_id=s.id where v_country is null or co.iso_alpha2=v_country or (v_country='GLOBAL' and s.metadata->>'scope'='global')
 )
 select jsonb_build_object('sources',coalesce(jsonb_agg(to_jsonb(src) order by country_code,source_label),'[]'::jsonb),'retention',jsonb_build_object('transient_run_queue_days',30,'governed_evidence_deleted_by_housekeeping',false,'source_versions_deleted_by_housekeeping',false),'stuck_threshold_minutes',30,'alerts',jsonb_build_object('stale_source','next verification overdue','abnormal_variance','configured warn/block thresholds','failed_validation','verification_status failed/blocked','stuck_job','queue heartbeat older than 30 minutes','repeated_failure','consecutive_failures > 1','schedule_failure','source operation schedule error','storage_growth','Evidence count and storage capacity remain governed by Evidence operations'),'authority_model','Layer 1 regulatory/authoritative; downstream layers cannot redefine identity.') into v_result from src;
 return v_result;
end $function$
;