-- CF-247 Phase 2 (8 Oct 2026, Platform Admin: "Do nzqa then prism and qilt"): PRISMS SA4 enrolments and the four QILT national report
-- tables become register adapters for statistics published as Excel workbooks (format xlsx_tables), one per dataset family, all switched
-- off. The spec says which sheet, rows and columns are read, how a cell is read (a count with "<5" suppressed, or an estimate with its
-- confidence interval) and the record key. Layer 1 (prisms-au-etl v0.2.0, qilt-au-etl v0.3.0) keeps running unchanged.
-- Side-by-side replay on the six stored workbooks (worker v0.17.22, register_xlsx.ts): the adapter spec against a verbatim copy of the
-- Layer 1 reader. A run uses its family's adapter; the QILT SES 2024 workbook replays under the SES family adapter.
insert into pipeline.register_adapters(source_id, code, label, country_code, spec)
values
  ('37f1776c-77a3-4083-8ec7-7d76ad7a9ad8', 'au_prisms_sa4', 'PRISMS International Student Enrolments by SA4', 'AU', '{"format":"xlsx_tables","value":"count_lt5","key":"prisms-sa4:{period}:row:{row}:{metric}","checks":[{"row":0,"col":0,"regex":"International Student Enrolments and Commencements by SA4"},{"row":1,"col":0,"regex":"\\bPRISMS\\b"}],"period":{"row":1,"col":0,"regex":"Year-to-date\\s+([A-Za-z]+)\\s+(\\d{4})"},"reported_rows":{"row":4,"col":0,"regex":"Row Count:\\s*([\\d,]+).*Total Enrolments:\\s*([\\d,]+).*Total Commencements:\\s*([\\d,]+)"},"lookups":{"state_code":"AU-{STATE}","study_area":true},"tables":[{"sheet":"Data","header":["state","sa4 name","abs remoteness area","sector","broad field of education","enrolments","commencements"],"dims":{"state":0,"sa4":1,"remoteness":2,"sector":3,"broad_field":4},"blank_when_empty":["state","sa4","sector","broad_field"],"metrics":[[5,"enrolments"],[6,"commencements"]]}]}'::jsonb),
  ('d817ea87-a96c-4e06-adbf-f6c957344d87', 'au_qilt_gos', 'QILT Graduate Outcomes Survey', 'AU', '{"format":"xlsx_tables","edition_from_path":"/(\\d{4})/[0-9a-f]{64}\\.xlsx$","label_norm":"qilt","value":"estimate_ci","key":"{sheet}|{row}|{metric}","tables":[{"sheet":"LF_UG_UNI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"UG","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"fte"],[3,"oe"],[4,"lf"],[5,"salary"]]},{"sheet":"LF_PGC_UNI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"PGC","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"fte"],[3,"oe"],[4,"lf"],[5,"salary"]]},{"sheet":"LF_PGR_UNI_3YP_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"PGR","year_from_offset":-2,"year_to_offset":0,"metrics":[[2,"fte"],[3,"oe"],[4,"lf"],[5,"salary"]]},{"sheet":"LF_UG_NUHEI_3YP_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"UG","year_from_offset":-2,"year_to_offset":0,"metrics":[[2,"fte"],[3,"oe"],[4,"lf"],[5,"salary"]]},{"sheet":"LF_PGC_NUHEI_3YP_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"PGC","year_from_offset":-2,"year_to_offset":0,"metrics":[[2,"fte"],[3,"oe"],[4,"lf"],[5,"salary"]]}]}'::jsonb),
  ('c6ba9a2b-4a9b-43cb-99c6-2cdf4c5e90ed', 'au_qilt_ses', 'QILT Student Experience Survey', 'AU', '{"format":"xlsx_tables","edition_from_path":"/(\\d{4})/[0-9a-f]{64}\\.xlsx$","label_norm":"qilt","value":"estimate_ci","key":"{sheet}|{row}|{metric}","tables":[{"sheet":"FOCUS_UG_UNI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"UG","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"skills_development"],[3,"peer_engagement"],[4,"teaching_quality_engagement"],[5,"student_support_services"],[6,"learning_resources"],[7,"overall_educational_experience"]]},{"sheet":"FOCUS_PGC_UNI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"PGC","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"skills_development"],[3,"peer_engagement"],[4,"teaching_quality_engagement"],[5,"student_support_services"],[6,"learning_resources"],[7,"overall_educational_experience"]]},{"sheet":"FOCUS_UG_NUHEI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"UG","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"skills_development"],[3,"peer_engagement"],[4,"teaching_quality_engagement"],[5,"student_support_services"],[6,"learning_resources"],[7,"overall_educational_experience"]]},{"sheet":"FOCUS_PGC_NUHEI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"PGC","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"skills_development"],[3,"peer_engagement"],[4,"teaching_quality_engagement"],[5,"student_support_services"],[6,"learning_resources"],[7,"overall_educational_experience"]]}]}'::jsonb),
  ('84bd8ff0-4932-49bd-bb99-f09cf118a0c6', 'au_qilt_gosl', 'QILT Graduate Outcomes Survey – Longitudinal', 'AU', '{"format":"xlsx_tables","edition_from_path":"/(\\d{4})/[0-9a-f]{64}\\.xlsx$","label_norm":"qilt","value":"estimate_ci","key":"{sheet}|{row}|{metric}","tables":[{"sheet":"STMT2_UG_UNI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"UG","year_from_offset":0,"year_to_offset":0,"metrics":[[3,"medium_fte"],[5,"medium_oe"]]},{"sheet":"STMT2_PGC_UNI_1Y_INST_CI","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"PGC","year_from_offset":0,"year_to_offset":0,"metrics":[[3,"medium_fte"],[5,"medium_oe"]]},{"sheet":"SAL_UG_UNI_1Y_INST_FIG","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"UG","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"medium_salary"]]},{"sheet":"SAL_PGC_UNI_1Y_INST_FIG","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"PGC","year_from_offset":0,"year_to_offset":0,"metrics":[[2,"medium_salary"]]}]}'::jsonb),
  ('a37a569c-105e-4d9e-b802-44b68ff7ecc6', 'au_qilt_ess', 'QILT Employer Satisfaction Survey', 'AU', '{"format":"xlsx_tables","edition_from_path":"/(\\d{4})/[0-9a-f]{64}\\.xlsx$","label_norm":"qilt","value":"estimate_ci","key":"{sheet}|{row}|{metric}","tables":[{"sheet":"EMPSAT_ALL_UNI_3YP","first_row":4,"label_col":1,"skip_labels":["standard deviation","mean","median","minimum","maximum","national","all institutions","all universities","all nuheis"],"skip_regex":["^all (universities|nuheis|institutions)$","^back to index$"],"cohort":"ALL","year_from_offset":-2,"year_to_offset":0,"metrics":[[2,"foundation_skills"],[3,"adaptive_skills"],[4,"collaborative_skills"],[5,"technical_skills"],[6,"employability_skills"],[7,"overall_satisfaction"]]}]}'::jsonb)
on conflict (source_id) do nothing;

update pipeline.register_adapters set notes = 'Phase 2 register adapter for statistics published as an Excel workbook. Not switched on: the Layer 1 reader stays in charge until the side-by-side replay passes and a Platform Admin switches it.'
 where code in ('au_prisms_sa4', 'au_qilt_gos', 'au_qilt_ses', 'au_qilt_gosl', 'au_qilt_ess') and notes is null;

insert into pipeline.register_replay_runs(source_id, label, storage_path, zip_hash, keep_fields, created_at)
select a.source_id, x.label, e.storage_path, e.content_hash, false, now() + make_interval(secs => x.n)
  from (values ('au_prisms_sa4', 'layer2a/AU/prisms/sa4/2025-12/', 'PRISMS SA4 December 2025', 0),
               ('au_qilt_gos', 'layer2a/AU/qilt/qilt_gos/2025/', 'QILT GOS 2025', 1),
               ('au_qilt_ses', 'layer2a/AU/qilt/qilt_ses/2024/', 'QILT SES 2024', 2),
               ('au_qilt_ses', 'layer2a/AU/qilt/qilt_ses/2025/', 'QILT SES 2025', 3),
               ('au_qilt_gosl', 'layer2a/AU/qilt/qilt_gosl/2025/', 'QILT GOS-L 2025', 4),
               ('au_qilt_ess', 'layer2a/AU/qilt/qilt_ess/2025/', 'QILT ESS 2025', 5)) x(code, prefix, label, n)
  join pipeline.register_adapters a on a.code = x.code
  join lateral (select ev.storage_path, ev.content_hash from pipeline.evidence_artifacts ev
                 where ev.storage_path like x.prefix || '%.xlsx' order by ev.created_at desc limit 1) e on true;
