-- CF-198 — bounded verified first-party detail seeds from newly captured UQ/UWA catalogue Evidence.
insert into pipeline.layer2_scholarship_discovery_candidates(source_id,evidence_id,source_profile_version_id,scholarship_url,observed_title,status,classification,classification_reason,classified_at,detail_target_url)
select * from (values
  ('cea3dd59-e764-4dbc-ba5b-118b7a76ab49'::uuid,'db43eff0-3d88-4d8e-8341-8f6ecc6785d7'::uuid,'22c0a776-9588-4d7d-b337-5c5f2a810466'::uuid,'https://scholarships.uq.edu.au/scholarship/uq-international-excellence-scholarship','UQ International Excellence Scholarship','discovered','detail_ready','CF-198 bounded verified first-party international detail from captured UQ catalogue Evidence',now(),'https://scholarships.uq.edu.au/scholarship/uq-international-excellence-scholarship'),
  ('7e5ce339-6f44-4687-8074-6e031d47b971'::uuid,'bd19c745-c784-498e-8f04-62514e1358ac'::uuid,'bc985554-2be6-4d69-bbc3-80af8ddd3df0'::uuid,'https://www.uwa.edu.au/study/scholarships-and-fees/scholarships/international-scholarships/global-excellence-scholarship','Global Excellence Scholarship','discovered','detail_ready','CF-198 bounded verified first-party international detail from captured UWA catalogue Evidence',now(),'https://www.uwa.edu.au/study/scholarships-and-fees/scholarships/international-scholarships/global-excellence-scholarship'),
  ('7e5ce339-6f44-4687-8074-6e031d47b971'::uuid,'bd19c745-c784-498e-8f04-62514e1358ac'::uuid,'bc985554-2be6-4d69-bbc3-80af8ddd3df0'::uuid,'https://www.uwa.edu.au/study/scholarships-and-fees/scholarships/international-scholarships/international-student-award','International Student Award','discovered','detail_ready','CF-198 bounded verified first-party international detail from captured UWA catalogue Evidence',now(),'https://www.uwa.edu.au/study/scholarships-and-fees/scholarships/international-scholarships/international-student-award')
) v(source_id,evidence_id,source_profile_version_id,scholarship_url,observed_title,status,classification,classification_reason,classified_at,detail_target_url)
where not exists(select 1 from pipeline.layer2_scholarship_discovery_candidates d where d.source_id=v.source_id and rtrim(lower(d.scholarship_url),'/')=rtrim(lower(v.scholarship_url),'/'));
comment on table pipeline.layer2_scholarship_discovery_candidates is 'Layer 2 Scholarship discovery candidates. CF-198 adds only bounded verified first-party UQ/UWA detail seeds backed by newly captured catalogue Evidence; automatic publication remains prohibited.';
