insert into pipeline.layer2_acquisition_providers(provider_key,display_name,adapter_type,base_url,auth_scheme,auth_field_name,capabilities,request_template,enabled,priority,rate_limit_per_minute,concurrency,timeout_seconds,operational_owner,change_control_ref)
values
('scraperapi','ScraperAPI','scraper_api','https://api.scraperapi.com/','query_param','api_key','{"raw":true,"html":true,"json":true,"proxy":true,"anti_bot":true,"javascript":true,"screenshot":true}'::jsonb,'{"target_url_parameter":"url","static_query":{"render":"true"},"response_adapter":"passthrough","supports_screenshot_query":"screenshot"}'::jsonb,true,30,60,2,60,'Platform Operations','CF-CHG-20260823-029'),
('firecrawl','Firecrawl','browser_api','https://api.firecrawl.dev/v2/scrape','bearer','Authorization','{"raw":true,"html":true,"json":true,"markdown":true,"proxy":true,"anti_bot":true,"javascript":true,"screenshot":true,"document_parse":true}'::jsonb,'{"method":"POST_JSON","target_url_field":"url","static_body":{"formats":["markdown","html","screenshot"]},"response_adapter":"firecrawl_v2"}'::jsonb,true,40,30,2,90,'Platform Operations','CF-CHG-20260823-029'),
('zenrows','ZenRows (JS render + premium proxy)','scraper_api','https://api.zenrows.com/v1/','query_param','apikey','{"raw":true,"html":true,"json":true,"proxy":true,"anti_bot":true,"javascript":true,"premium_proxy":true,"screenshot":false}'::jsonb,'{"target_url_parameter":"url","static_query":{"js_render":"true","premium_proxy":"true"},"response_adapter":"passthrough"}'::jsonb,true,50,60,2,90,'Platform Operations','CF-CHG-20260823-029'),
('custom-gateway','Custom gateway ({url} template)','custom',null,'header','X-API-Key','{"raw":true,"html":true,"json":true,"proxy":true,"anti_bot":false,"javascript":false,"screenshot":false}'::jsonb,'{"target_url_parameter":"url","response_adapter":"generic"}'::jsonb,false,90,null,1,60,'Platform Operations','CF-CHG-20260823-029')
on conflict(provider_key) do update set display_name=excluded.display_name,adapter_type=excluded.adapter_type,base_url=excluded.base_url,auth_scheme=excluded.auth_scheme,auth_field_name=excluded.auth_field_name,capabilities=excluded.capabilities,request_template=excluded.request_template,priority=excluded.priority,rate_limit_per_minute=excluded.rate_limit_per_minute,concurrency=excluded.concurrency,timeout_seconds=excluded.timeout_seconds,operational_owner=excluded.operational_owner,updated_at=now();

update pipeline.layer2_acquisition_providers
set auth_field_name='token',capabilities=capabilities || '{"screenshot":true}'::jsonb,request_template=request_template || '{"static_query":{"render":"true"},"response_adapter":"passthrough","supports_screenshot_query":"screenShot"}'::jsonb,updated_at=now()
where provider_key='scrape-do';

with eligible as (select id from pipeline.layer2_source_profiles where acquisition_method in ('website','course_catalogue','course_detail','fee_schedule','intake_calendar','english_requirements','scholarship_catalogue','search_endpoint')), p as (select id,provider_key from pipeline.layer2_acquisition_providers where provider_key in ('scraperapi','firecrawl','zenrows'))
insert into pipeline.layer2_profile_provider_routes(profile_id,acquisition_provider_id,priority,enabled,required_capabilities,request_overrides,evidence_policy,fallback_on,change_control_ref)
select e.id,p.id,case p.provider_key when 'scraperapi' then 30 when 'firecrawl' then 40 when 'zenrows' then 50 end,true,'{}'::jsonb,'{}'::jsonb,case when p.provider_key='firecrawl' then '{"capture_raw":true,"capture_html":true,"capture_screenshot_on_failure":true,"capture_screenshot_on_extraction_failure":true}'::jsonb else '{"capture_raw":true,"capture_html":true,"capture_screenshot_on_failure":false,"capture_screenshot_on_extraction_failure":false}'::jsonb end,'["blocked","timeout","403","429","5xx","extraction_failed"]'::jsonb,'CF-CHG-20260823-029'
from eligible e cross join p
on conflict(profile_id,acquisition_provider_id) do update set priority=excluded.priority,enabled=excluded.enabled,required_capabilities=excluded.required_capabilities,request_overrides=excluded.request_overrides,evidence_policy=excluded.evidence_policy,fallback_on=excluded.fallback_on,updated_at=now();