-- M2.1 country/course completeness + provider comparison foundation
-- Live migration: m2_1_country_completeness_provider_trial_foundation
create table if not exists pipeline.layer2_country_completeness_profiles (
  id uuid primary key default gen_random_uuid(), country_id uuid not null references ref.countries(id), profile_key text not null,
  version_no integer not null default 1 check (version_no > 0), factual_domains jsonb not null default '[]'::jsonb,
  decision_context_domains jsonb not null default '[]'::jsonb, trial_policy jsonb not null default '{}'::jsonb, active boolean not null default true,
  change_control_ref text not null default 'CF-CHG-20260823-029', created_at timestamptz not null default now(), unique(country_id,profile_key,version_no));
create table if not exists pipeline.layer2_completeness_trials (
  id uuid primary key default gen_random_uuid(), country_id uuid not null references ref.countries(id), completeness_profile_id uuid not null references pipeline.layer2_country_completeness_profiles(id),
  provider_id uuid references catalogue.providers(id), trial_mode text not null default 'adaptive_provider_batch' check (trial_mode in ('adaptive_provider_batch','country_batch','compare_all')),
  requested_batch_size integer not null default 10 check (requested_batch_size between 1 and 100), status text not null default 'planned' check (status in ('planned','running','completed','blocked','cancelled')),
  baseline_summary jsonb not null default '{}'::jsonb, result_summary jsonb not null default '{}'::jsonb, recommendation jsonb not null default '{}'::jsonb,
  change_control_ref text not null default 'CF-CHG-20260823-029', uat_ref text, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists pipeline.layer2_completeness_trial_courses (
  id uuid primary key default gen_random_uuid(), trial_id uuid not null references pipeline.layer2_completeness_trials(id) on delete cascade, course_id uuid not null references catalogue.courses(id), provider_id uuid not null references catalogue.providers(id),
  sample_rank integer not null, selection_reason text not null default 'adaptive_completeness_sample', baseline_factual jsonb not null default '{}'::jsonb, post_factual jsonb not null default '{}'::jsonb,
  baseline_context jsonb not null default '{}'::jsonb, post_context jsonb not null default '{}'::jsonb,
  status text not null default 'selected' check (status in ('selected','acquiring','extracted','resolved','blocked','layer3_required','layer4_required')), created_at timestamptz not null default now(), unique(trial_id,course_id), unique(trial_id,sample_rank));
create table if not exists pipeline.layer2_provider_trial_results (
  id uuid primary key default gen_random_uuid(), trial_id uuid not null references pipeline.layer2_completeness_trials(id) on delete cascade, trial_course_id uuid not null references pipeline.layer2_completeness_trial_courses(id) on delete cascade,
  acquisition_provider_id uuid not null references pipeline.layer2_acquisition_providers(id), provider_attempt_id uuid references pipeline.layer2_provider_attempts(id), domain_key text not null,
  acquisition_success boolean, gatekeeping_bypassed boolean, javascript_rendered boolean, evidence_quality_score numeric check (evidence_quality_score between 0 and 1), deterministic_extraction_success boolean,
  correctness_status text check (correctness_status is null or correctness_status in ('unverified','correct','incorrect','ambiguous')), latency_ms integer check (latency_ms is null or latency_ms >= 0),
  request_count integer not null default 1 check (request_count >= 0), vendor_cost_usd numeric check (vendor_cost_usd is null or vendor_cost_usd >= 0), fields_targeted integer not null default 0 check (fields_targeted >= 0),
  fields_resolved integer not null default 0 check (fields_resolved >= 0), layer3_required boolean not null default false, layer4_required boolean not null default false, blocker text, metrics jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists idx_l2_trials_country_provider on pipeline.layer2_completeness_trials(country_id,provider_id,created_at desc);
create index if not exists idx_l2_trial_courses_trial_status on pipeline.layer2_completeness_trial_courses(trial_id,status,sample_rank);
create index if not exists idx_l2_provider_trial_results_trial_provider on pipeline.layer2_provider_trial_results(trial_id,acquisition_provider_id,domain_key);
alter table pipeline.layer2_country_completeness_profiles enable row level security; alter table pipeline.layer2_completeness_trials enable row level security; alter table pipeline.layer2_completeness_trial_courses enable row level security; alter table pipeline.layer2_provider_trial_results enable row level security;
revoke all on pipeline.layer2_country_completeness_profiles,pipeline.layer2_completeness_trials,pipeline.layer2_completeness_trial_courses,pipeline.layer2_provider_trial_results from anon,authenticated;
insert into pipeline.layer2_country_completeness_profiles(country_id,profile_key,version_no,factual_domains,decision_context_domains,trial_policy,active,change_control_ref)
select id,'au-international-course-v1',1,'["identity","regulatory","course_url","provider_current_tuition","intakes","english_requirements","campus_delivery","description","verification"]'::jsonb,'["scholarships","qilt_provider","qilt_study_area","prisms_provider","prisms_state"]'::jsonb,'{"initial_batch_size":10,"expand_if_success_gte":0.90,"validate_again_if_success_gte":0.70,"diagnose_below":0.70,"audience":"international"}'::jsonb,true,'CF-CHG-20260823-029' from ref.countries where trim(iso_alpha2)='AU' on conflict (country_id,profile_key,version_no) do nothing;
insert into pipeline.layer2_country_completeness_profiles(country_id,profile_key,version_no,factual_domains,decision_context_domains,trial_policy,active,change_control_ref)
select id,'nz-international-course-v1',1,'["identity","regulatory","course_url","provider_current_tuition","intakes","english_requirements","campus_delivery","description","verification"]'::jsonb,'["scholarships","provider_outcomes","student_flow","state_region_context"]'::jsonb,'{"initial_batch_size":10,"expand_if_success_gte":0.90,"validate_again_if_success_gte":0.70,"diagnose_below":0.70,"audience":"international","note":"NZ regulatory semantics must not be relabelled as CRICOS"}'::jsonb,true,'CF-CHG-20260823-029' from ref.countries where trim(iso_alpha2)='NZ' on conflict (country_id,profile_key,version_no) do nothing;
create or replace function pipeline.layer2_course_factual_snapshot(p_course_id uuid) returns jsonb language sql stable security invoker set search_path=pipeline,catalogue,public as $$ select jsonb_build_object('course_id',c.id,'identity',case when c.stable_key is not null and c.provider_id is not null and coalesce(c.canonical_title,c.display_title) is not null then 'present' else 'ambiguous' end,'course_url',case when coalesce(c.course_url,(select cl.url from catalogue.course_links cl where cl.course_id=c.id and coalesce(cl.status,'active')='active' order by cl.is_primary desc nulls last,cl.created_at desc limit 1)) is not null then 'present' else 'not_yet_enriched' end,'provider_current_tuition',case when exists(select 1 from catalogue.course_fees f where f.course_id=c.id and f.audience='international' and f.fee_type='provider_current_tuition' and coalesce(f.status,'active')='active') then 'present' else 'not_yet_enriched' end,'intakes',case when exists(select 1 from catalogue.course_intakes i where i.course_id=c.id and coalesce(i.status,'active')='active') then 'present' else 'not_yet_enriched' end,'english_requirements',case when exists(select 1 from catalogue.course_english_requirements e where e.course_id=c.id and coalesce(e.status,'active')='active') then 'present' else 'not_yet_enriched' end,'campus_delivery',case when exists(select 1 from catalogue.course_campuses cc where cc.course_id=c.id) then 'present' else 'not_yet_enriched' end,'description',case when nullif(btrim(c.description),'') is not null then 'present' else 'not_yet_enriched' end,'verification',case when c.last_verified_at is null then 'not_yet_enriched' when c.last_verified_at < now()-interval '180 days' then 'stale' else 'present' end) from catalogue.courses c where c.id=p_course_id $$;
create or replace function pipeline.layer2_course_decision_context_snapshot(p_course_id uuid) returns jsonb language sql stable security invoker set search_path=pipeline,catalogue,public as $$ select jsonb_build_object('course_id',c.id,'qilt_provider',case when exists(select 1 from catalogue.provider_outcomes po where po.provider_id=c.provider_id) then 'present' else 'not_available' end,'qilt_study_area',case when exists(select 1 from catalogue.provider_outcomes po where po.provider_id=c.provider_id and po.external_study_area_id is not null) then 'present' else 'not_available' end,'prisms_provider',case when exists(select 1 from catalogue.student_flow_observations sf where sf.provider_id=c.provider_id) then 'present' else 'not_available' end,'prisms_state',case when exists(select 1 from catalogue.student_flow_observations sf where sf.subdivision_id is not null) then 'present' else 'not_available' end,'context_is_course_grain',false) from catalogue.courses c where c.id=p_course_id $$;
-- service-only trial creation is refined by the subsequent control-sampling migration.
