import{test,expect}from'@playwright/test'
import{attachRuntimeEvidence,assertNoServerErrors,loginAsUatUser,milestoneScreenshot,observeRuntime,writeRunEnvironment,DETERMINISTIC_UI_TIMEOUT}from'./support/runtime-evidence.mjs'

async function finish(testInfo,runtime){await attachRuntimeEvidence(testInfo,runtime);assertNoServerErrors(runtime)}
async function openCatalogue(page,hash,heading){await page.evaluate(h=>{location.hash=h},hash);await expect(page.getByRole('heading',{name:heading,exact:true})).toBeVisible({timeout:DETERMINISTIC_UI_TIMEOUT})}

test.describe('CF-061 QILT PRISMS comparison experience @deployed',()=>{
 test.beforeAll(async()=>{await writeRunEnvironment({suite:'cf-061-qilt-prisms-comparison-deployed',change_control:'CF-CHG-20260901-061'})})

 test('Provider comparison aligns QILT cards for two selected universities',async({page},testInfo)=>{const runtime=observeRuntime(page);try{
  await loginAsUatUser(page)
  await expect(page.locator('.m-release-pill')).toContainText('v2.15.40')
  await openCatalogue(page,'#providers','Providers')
  const search=page.locator('.m-searchbox input').first()
  await search.fill('Charles Darwin University')
  const row=page.locator('.m-table tbody tr').filter({hasText:'Charles Darwin University'}).first()
  await expect(row).toBeVisible({timeout:DETERMINISTIC_UI_TIMEOUT})
  await row.click()
  const compare=page.getByTitle('Compare this provider')
  await expect(compare).toBeVisible()
  await compare.click()

  await expect(page.getByRole('heading',{name:'Compare providers',exact:true})).toBeVisible()
  await expect(page.getByText('1 / 6 selected',{exact:true})).toBeVisible()

  const compareSearch=page.locator('.cf-compare-search input')
  await compareSearch.fill('Curtin University')
  const add=page.locator('.cf-compare-results button').filter({hasText:'Curtin University'}).first()
  await expect(add).toBeVisible()
  const response=page.waitForResponse(r=>{if(!r.url().includes('/rest/v1/rpc/admin_read'))return false;try{return r.request().postDataJSON()?.p_operation==='contextual_compare'}catch{return false}})
  await add.click()
  await expect(page.getByText('2 / 6 selected',{exact:true})).toBeVisible()
  await expect.poll(()=>page.evaluate(()=>location.hash)).toContain('ids=')
  const payload=await(await response).json()
  expect(Number(payload.total)).toBe(2)
  expect(Number(payload.max_items)).toBe(6)
  expect(payload.items.map(x=>x.name)).toEqual(['Charles Darwin University','Curtin University'])
  expect(payload.items.every(x=>x.contextual_insights?.student_outcomes?.granularity==='provider')).toBeTruthy()

  await expect(page.locator('.cf-compare-entity').filter({hasText:'Charles Darwin University'})).toBeVisible()
  await expect(page.locator('.cf-compare-entity').filter({hasText:'Curtin University'})).toBeVisible()
  await expect(page.locator('.cf-compare-value').first()).toBeVisible()
  await expect(page.getByText('International student flow',{exact:true})).toBeVisible()
  const heroStyle=await page.locator('.cf-compare-hero').evaluate(el=>({background:getComputedStyle(el).backgroundColor,border:getComputedStyle(el).borderTopColor}))
  expect(heroStyle.background).toBe('rgb(23, 32, 51)')
  expect(heroStyle.border).toBe('rgb(37, 50, 74)')
  await milestoneScreenshot(page,testInfo,'cf-061-provider-comparison')
  await page.setViewportSize({width:900,height:800})
  await expect(page.locator('.cf-compare-shell')).toBeVisible()
  await expect(page.locator('.cf-compare-scroll')).toBeVisible()
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('heading',{name:'Compare providers',exact:true})).toBeVisible()
  const overflow=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:document.documentElement.clientWidth,inner:document.querySelector('.cf-compare-scroll')?.scrollWidth||0,innerClient:document.querySelector('.cf-compare-scroll')?.clientWidth||0}))
  expect(overflow.body).toBeLessThanOrEqual(overflow.viewport+2)
  expect(overflow.inner).toBeGreaterThanOrEqual(overflow.innerClient)
  await milestoneScreenshot(page,testInfo,'cf-061-provider-comparison-mobile')
 }finally{await finish(testInfo,runtime)}})

 test('Course comparison can select any university before choosing courses',async({page},testInfo)=>{const runtime=observeRuntime(page);try{
  await loginAsUatUser(page)
  await page.evaluate(()=>{location.hash='#compare?type=course'})
  await expect(page.getByRole('heading',{name:'Compare courses',exact:true})).toBeVisible({timeout:DETERMINISTIC_UI_TIMEOUT})
  const providerSearch=page.getByLabel('Search universities or providers')
  await expect(providerSearch).toBeVisible()
  const providerResponse=page.waitForResponse(r=>{if(!r.url().includes('/rest/v1/rpc/admin_read'))return false;try{return r.request().postDataJSON()?.p_operation==='providers_page'}catch{return false}})
  await providerSearch.fill('Adelaide University')
  const providerPayload=await(await providerResponse).json()
  const provider=(providerPayload?.items||[]).find(x=>(x.canonical_name||x.display_name||x.name)==='Adelaide University')||(providerPayload?.items||[])[0]
  expect(provider?.id).toBeTruthy()
  const choose=page.locator('.cf-compare-results.provider-results button').filter({hasText:'Adelaide University'}).first()
  await expect(choose).toBeVisible({timeout:DETERMINISTIC_UI_TIMEOUT})
  const coursesResponse=page.waitForResponse(r=>{if(!r.url().includes('/rest/v1/rpc/admin_read'))return false;try{const b=r.request().postDataJSON();return b?.p_operation==='courses_page'&&b?.p_args?.provider_id===String(provider.id)}catch{return false}})
  await choose.click()
  await expect(page.locator('.cf-provider-selected')).toContainText('Adelaide University')
  const coursePayload=await(await coursesResponse).json()
  expect((coursePayload?.items||[]).length).toBeGreaterThan(0)
  expect((coursePayload?.items||[]).every(x=>x.provider_name==='Adelaide University')).toBeTruthy()
  await expect(page.locator('.cf-compare-results.course-results button').first()).toBeVisible({timeout:DETERMINISTIC_UI_TIMEOUT})
  await milestoneScreenshot(page,testInfo,'cf-079-course-compare-provider-first')
 }finally{await finish(testInfo,runtime)}})

 test('Course detail keeps QILT as Provider context and opens Course comparison',async({page},testInfo)=>{const runtime=observeRuntime(page);try{
  await loginAsUatUser(page)
  await openCatalogue(page,'#courses','Courses')
  const search=page.locator('.m-searchbox input').first()
  await search.fill('Advanced Diploma of Accounting')
  const row=page.locator('.m-table tbody tr').filter({hasText:'Advanced Diploma of Accounting'}).filter({hasText:'RMIT'}).first()
  await expect(row).toBeVisible({timeout:DETERMINISTIC_UI_TIMEOUT})
  const detailResponse=page.waitForResponse(r=>{if(!r.url().includes('/rest/v1/rpc/admin_read'))return false;try{return r.request().postDataJSON()?.p_operation==='course_detail'}catch{return false}})
  await row.click()
  const detail=await(await detailResponse).json()
  expect(detail.contextual_insights?.student_outcomes?.granularity).toBe('provider_context')
  expect(Number(detail.contextual_insights?.student_outcomes?.total||0)).toBeGreaterThan(0)
  await expect(page.locator('.ci-outcome-card').first()).toBeVisible()
  await expect(page.getByText(/National benchmark/i).first()).toBeVisible()

  const compare=page.getByTitle('Compare this course')
  await expect(compare).toBeVisible()
  const compareResponse=page.waitForResponse(r=>{if(!r.url().includes('/rest/v1/rpc/admin_read'))return false;try{return r.request().postDataJSON()?.p_operation==='contextual_compare'}catch{return false}})
  await compare.click()
  const payload=await(await compareResponse).json()
  expect(Number(payload.total)).toBe(1)
  expect(payload.items[0]?.contextual_insights?.student_outcomes?.granularity).toBe('provider_context')
  await expect(page.getByRole('heading',{name:'Compare courses',exact:true})).toBeVisible()
  await expect(page.getByText(/QILT outcomes and PRISMS student-flow context/i)).toBeVisible()
  await milestoneScreenshot(page,testInfo,'cf-061-course-comparison')
 }finally{await finish(testInfo,runtime)}})
})
