import{test,expect}from'@playwright/test'
import fs from'node:fs/promises'

const read=path=>fs.readFile(path,'utf8')

test.describe('CF-093 Scheduled Tasks operator contract',()=>{
 test('task-first search, attribution and personal columns stay additive to CF-092',async()=>{
  const workspace=await read('src/ScheduledJobsWorkspace.jsx')
  const migration=await read('supabase/migrations/20260911052000_cf_093_scheduler_operator_attribution.sql')
  const reviewFix=await read('supabase/migrations/20260911053600_cf_093_codex_review_fixes.sql')
  const secondReviewFix=await read('supabase/migrations/20260910213556_cf_093_resolved_actor_search_semantics.sql')
  const entityLabelFix=await read('supabase/migrations/20260910215546_cf_093_scheduler_entity_labels.sql')
  const literalSearchFix=await read('supabase/migrations/20260910221808_cf_093_literal_scheduler_search.sql')
  const appliedFinalizer=await read('supabase/migrations/20260910232606_cf_093_scheduler_search_finalizer.sql')
  const replayFinalizer=await read('supabase/migrations/20260911054000_cf_093_scheduler_search_finalizer.sql')
  const css=await read('src/scheduled-jobs-config.css')

  for(const text of ['Task / Dataset','Search scheduled tasks','Created By','Owner','Columns','Reset view','Scheduled Target','Cadence','Next Run','Schedule Status','Actions'])expect(workspace).toContain(text)
  for(const text of ['technicalTarget','targetLabel','created_by_display','created_by_state','owner_display','localStorage','cf:scheduler:view:v1'])expect(workspace).toContain(text)
  expect(workspace).toContain("supabase.rpc('scheduler_policy_run_now_v1'")
  expect(workspace).toContain("supabase.rpc('scheduler_policy_edit_v1'")
  expect(workspace).toContain("supabase.rpc('scheduler_policies_list_v1'")
  expect(workspace).toContain('p_query:search.trim()')
  expect(workspace).toContain("technicalTarget(x)!=='UNBOUNDED'?technicalTarget(x):'Scheduled task'")
  expect(workspace).toContain('does not change its recurring cadence or next-run time')
  expect(workspace).toContain('Layer 3 remains Evidence/profile/model-qualified')
  expect(workspace).toContain('const loadGeneration=useRef(0)')
  expect(workspace).toContain('const generation=++loadGeneration.current')
  expect(workspace).toContain('if(generation!==loadGeneration.current)return')
  expect(workspace).toContain('if(generation===loadGeneration.current)setBusy(false)')
  expect(workspace).toContain('const panelGeneration=useRef(0)')
  expect(workspace).toContain('const loadPanels=async()=>{const generation=++panelGeneration.current')
  expect(workspace).toContain('if(generation!==panelGeneration.current)return')
  expect(workspace).toContain('hydratedActorKey')
  expect(workspace).toContain('if(hydratedActorKey!==actorKey)return')
  expect(workspace).toContain('setHydratedActorKey(actorKey)')
  expect(workspace).toContain('Promise.allSettled')
  expect(workspace).toContain('const policyResponse=await supabase.rpc')
  expect(workspace).toContain('if(page>maxPage){await load(maxPage,search);return}')
  expect(workspace).toContain('closeEditor();const policyReload=load(0,query);if(runNow)await loadPanels();await policyReload')
  expect(workspace).not.toContain('if(runNow)await loadPanels();await load(0,query)')
  expect(workspace).not.toContain('finally{setBusy(false)}}')

  for(const text of ['created_by_display_snapshot','created_by_email_snapshot','actor_display_snapshot','actor_email_snapshot','System / legacy','System / automation','former_user','security invoker','curator role required'])expect(migration.toLowerCase()).toContain(text.toLowerCase())
  expect(migration).not.toContain('created_by_email_snapshot as created_by_email')
  expect(migration).not.toContain('actor_email_snapshot as actor_email')

  expect(reviewFix).toContain('p_query text default')
  expect(reviewFix).toContain("v_query text:=lower(trim(coalesce(p_query,'')))")
  expect(reviewFix).toContain('limit v_limit offset v_offset')
  expect(reviewFix).toContain('au.deleted_at is null')
  expect(reviewFix).toContain('au.banned_until is null or au.banned_until <= now()')
  expect(reviewFix).toContain('drop function if exists public.scheduler_policies_list_v1(integer,integer)')
  expect(reviewFix).toContain('security invoker')
  expect(reviewFix).toContain('curator role required')
  expect(reviewFix).toContain('revoke all on function public.scheduler_policies_list_v1(integer,integer,text) from public,anon')

  expect(secondReviewFix).toContain('security.scheduler_actor_display(p.owner_user_id)')
  expect(secondReviewFix).toContain('security.scheduler_actor_display(p.created_by)')
  expect(secondReviewFix).toContain('au.deleted_at is null')
  expect(secondReviewFix).toContain('au.banned_until is null or au.banned_until <= now()')

  expect(entityLabelFix).toContain('create or replace function security.scheduler_entity_display')
  for(const entity of ["when 'provider'","when 'course'","when 'campus'","when 'scholarship'"])expect(entityLabelFix).toContain(entity)
  expect(entityLabelFix).toContain('security.scheduler_entity_display(p.entity_type,p.entity_id)')
  expect(entityLabelFix).toContain('revoke all on function security.scheduler_entity_display(text,uuid) from public,anon,authenticated')

  for(const sql of [literalSearchFix,appliedFinalizer,replayFinalizer]){
   expect(sql).toContain("replace(replace(replace(lower(trim(coalesce(p_query,'')))")
   expect(sql).toContain('security.scheduler_entity_display(p.entity_type,p.entity_id)')
   expect(sql).toContain('security.scheduler_actor_display(p.owner_user_id)')
   expect(sql).toContain('security.scheduler_actor_display(p.created_by)')
  }
  expect(replayFinalizer).toContain("lower(coalesce(lp.domain,'')) like")
  expect(replayFinalizer).toContain("lower(replace(coalesce(lp.domain,''),'_',' ')) like")
  expect(replayFinalizer).toContain("lower('Former user — '||coalesce(p.created_by_display_snapshot")
  expect(replayFinalizer).toContain("lower('Former user — '||coalesce(p.owner_display_snapshot")
  expect(css).toContain('cf-scheduler-v2__sticky-actions')
 })
})
