import{test,expect}from'@playwright/test'
import fs from'node:fs'

const sql=fs.readFileSync('supabase/migrations/20260911095142_cf_093_scheduler_exact_scope_codex_finalizer.sql','utf8')
const routeFinalizer=fs.readFileSync('supabase/migrations/20260911095420_cf_093_scheduler_runtime_route_credential_finalizer.sql','utf8')
const runtimeFinalizer=fs.readFileSync('supabase/migrations/20260911103931_cf_093_scheduler_runtime_semantics_finalizer.sql','utf8')
const bridgeScopeFinalizer=fs.readFileSync('supabase/migrations/20260911105517_cf_093_scheduler_browser_bridge_and_scope_binding_finalizer.sql','utf8')
const queryIpv4Finalizer=fs.readFileSync('supabase/migrations/20260911111431_cf_093_scheduler_query_binding_and_ipv4_finalizer.sql','utf8')
const discoveryFailClosedFinalizer=fs.readFileSync('supabase/migrations/20260911114056_cf_093_scheduler_discovery_failclosed_and_runtime_parser_finalizer.sql','utf8')

test('CF-093 exact-scope finalizer preserves narrow authority and closes Codex runtime gaps',()=>{
 expect(sql).toContain('scheduler_workflow_scope_snapshot_v2')
 expect(sql).toContain("md5(string_agg(profile_id::text||':'||course_id::text||':'||coalesce(source_url,'<discover>')")
 expect(sql).toContain("'scope_fingerprint',counts.scope_fingerprint")
 expect(sql).toContain("Layer 2 scope changed while preview was being constructed; preview again")
 expect(sql).toContain("Layer 2 runnable scope changed after preview; preview again before dispatch")
 expect(sql).toContain("coalesce(j.result->>'scope_fingerprint','')=v_live_fingerprint")
 expect(sql).toContain("coalesce(j.result->'profile_ids','[]'::jsonb)=to_jsonb(v_live_profiles)")

 expect(sql).toContain("lower(coalesce(ap.provider_key,''))<>'parsebot'")
 expect(routeFinalizer).toContain('left join vault.decrypted_secrets ds on ds.id=ap.vault_secret_id')
 expect(routeFinalizer).toContain("lower(coalesce(ap.provider_key,''))<>'parsebot'")
 expect(routeFinalizer).toContain("lower(coalesce(ap.auth_scheme,'none'))='none'")
 expect(routeFinalizer).toContain("nullif(ds.decrypted_secret,'') is not null")
 expect(sql).toContain("target_url !~* '^https://")
 expect(sql).toContain("discovery_strategy,search_url_template")
 expect(sql).toContain("discovery_strategy,catalogue_url")

 expect(sql).toContain("from public.layer2_scope_courses(v_country,case when p_state_id is null then 'country' else 'state' end,p_state_id)")
 expect(sql).toContain("'scope_source','layer2_executable_provider_scope'")

 expect(runtimeFinalizer).toContain('scheduler_workflow_https_host_v1')
 expect(runtimeFinalizer).toContain('v_port>65535')
 expect(runtimeFinalizer).toContain('scheduler_workflow_queueable_url_allowed_v1')
 expect(runtimeFinalizer).toContain("target.host=h.host or target.host like '%.'||h.host")
 expect(runtimeFinalizer).toContain("coalesce(pc#>>'{budget_status,allowed}','true')<>'false'")
 expect(runtimeFinalizer).toContain("lower(coalesce(pc->>'provider_key',''))='direct-http' or nullif(pc->>'estimated_request_cost_usd','') is not null")
 expect(runtimeFinalizer).toContain("coalesce(e->>'status','') not in ('started','discovery_started')")
 expect(runtimeFinalizer).toContain("coalesce((e->>'target_count')::integer,-1)<>coalesce((e->>'requested_count')::integer,-2)")
 expect(runtimeFinalizer).toContain("v_post_snapshot:=security.scheduler_workflow_scope_snapshot_v2")
 expect(runtimeFinalizer).toContain("coalesce(v_post_snapshot->>'scope_fingerprint','')<>v_preview_fingerprint")
 expect(runtimeFinalizer).toContain('Layer 2 dispatch did not start the exact previewed work for every profile')

 expect(bridgeScopeFinalizer).toContain("v_match[1] ~ '^[0-9.]+$'")
 expect(bridgeScopeFinalizer).toContain('v_octet>255')
 expect(bridgeScopeFinalizer).toContain('current_version_id::text')
 expect(bridgeScopeFinalizer).toContain("'<discover:'||coalesce(discovery_target,'')||'>'")
 expect(bridgeScopeFinalizer).toContain("discovery_strategy,search_url_template")
 expect(bridgeScopeFinalizer).toContain("discovery_strategy,catalogue_url")
 expect(bridgeScopeFinalizer).toContain('grant execute on function security.scheduler_workflow_run_now_v2_browser_bridge(uuid,text,text,text,uuid,text,text) to authenticated')
 expect(bridgeScopeFinalizer).toContain('revoke all on function security.scheduler_workflow_run_now_v2_browser_bridge(uuid,text,text,text,uuid,text,text) from public,anon')

 expect(queryIpv4Finalizer).toContain("v_part !~ '^(0|[1-9][0-9]{0,2})$'")
 expect(queryIpv4Finalizer).toContain("c.course_code,c.canonical_title,c.display_title")
 expect(queryIpv4Finalizer).toContain("':query-inputs:'||coalesce(course_code,'')||':'||coalesce(canonical_title,'')||':'||coalesce(display_title,'')")
 expect(queryIpv4Finalizer).toContain('current_version_id::text')

 expect(discoveryFailClosedFinalizer).toContain('preview_bound_async_discovery_not_supported')
 expect(discoveryFailClosedFinalizer).toContain("pc->>'base_url'")
 expect(discoveryFailClosedFinalizer).toContain("0x[0-9a-f]+")
 expect(discoveryFailClosedFinalizer).toContain('jsonb_agg(')
 expect(discoveryFailClosedFinalizer).toContain('jsonb_build_array(')
 expect(discoveryFailClosedFinalizer).toContain("where s.source_url is null")
 expect(discoveryFailClosedFinalizer).toContain('scheduler_workflow_queueable_url_allowed_v1')

 expect(sql).toContain("v_workflow <> 'course_facts_l2'")
 expect(sql).toContain("only AU Layer 2 Course Facts is currently authorised for this builder")
 expect(sql).toContain("v_mode <> 'acquisition_only'")
 expect(sql).toContain("Conditional Layer 3/L4 orchestration is not yet qualified")
 expect(sql).toContain("Country/state schedules are not advertised")
 expect(runtimeFinalizer).toContain("v_mode <> 'acquisition_only'")
 expect(runtimeFinalizer).toContain("security.current_role_rank() < 4")
 expect(runtimeFinalizer).not.toContain("automatic_governed_pipeline','label','Automatic governed pipeline','enabled',true")
 expect(runtimeFinalizer).not.toContain("reprocess_governed_evidence','label','Reprocess governed Evidence','enabled',true")
})
