import{test,expect}from'@playwright/test'
import fs from'node:fs'

const read=p=>fs.readFileSync(p,'utf8')

test('CF-093 target builder exposes only server-authorised AU Layer 2 Course Facts slice',()=>{
 const index=read('index.html')
 const ui=read('src/scheduler-workflow-builder-entry.jsx')
 const migration=read('supabase/migrations/20260911021144_cf_093_scheduler_workflow_builder_slice.sql')
 const aclFix=read('supabase/migrations/20260911021847_cf_093_scheduler_workflow_bridge_acl_fix.sql')
 const previewFix=read('supabase/migrations/20260911022312_cf_093_scheduler_workflow_preview_token_idempotency.sql')

 expect(index).toContain('/src/scheduler-workflow-builder-entry.jsx')
 expect(ui).toContain("const WORKFLOW_KEY='course_facts_l2'")
 expect(ui).toContain("const AU='AU'")
 expect(ui).toContain("scheduler_workflow_scope_options_v1")
 expect(ui).toContain("scheduler_workflow_preview_v1")
 expect(ui).toContain("scheduler_workflow_run_now_v2")
 expect(ui).not.toContain("scheduler_workflow_run_now_v1',{p_workflow_key")
 expect(ui).toContain("p_preview_token:preview.preview_token")
 expect(ui).toContain("Preview governed scope")
 expect(ui).toContain("Run acquisition + deterministic Layer 2")
 expect(ui).toContain("Automatic L2 → conditional L3/L4 and Evidence reprocessing remain disabled here")
 expect(ui).not.toContain("refresh_policy_upsert_v2")

 expect(migration).toContain("security.current_role_rank() < 4")
 expect(migration).toContain("only AU Layer 2 Course Facts is currently authorised for this builder")
 expect(migration).toContain("v_mode <> 'acquisition_only'")
 expect(migration).toContain("Conditional Layer 3/L4 orchestration is not yet qualified")
 expect(migration).toContain("Country/state schedules are not advertised")
 expect(migration).toContain("language sql\nsecurity invoker")

 expect(aclFix).toContain("grant execute on function security.scheduler_workflow_scope_options_v1_browser_bridge")
 expect(aclFix).toContain("grant execute on function security.scheduler_workflow_preview_v1_browser_bridge")
 expect(aclFix).toContain("to authenticated")
 expect(aclFix).toContain("from anon")
 expect(aclFix).not.toContain("to anon")

 expect(previewFix).toContain("revoke all on function public.scheduler_workflow_run_now_v1")
 expect(previewFix).toContain("create or replace function public.scheduler_workflow_run_now_v2")
 expect(previewFix).toContain("p_preview_token uuid")
 expect(previewFix).toContain("preview token does not match the exact requested workflow target")
 expect(previewFix).toContain("previewed scope has no executable Layer 2 work")
 expect(previewFix).toContain("pg_advisory_xact_lock")
 expect(previewFix).toContain("idempotent_replay")
 expect(previewFix).toContain("existing_recent_dispatch")
 expect(previewFix).toContain("j.created_at >= now()-interval '10 minutes'")
})

test('CF-093 builder preserves server preview-before-dispatch, stale-state guards and truthful follow-through',()=>{
 const ui=read('src/scheduler-workflow-builder-entry.jsx')
 const previewFix=read('supabase/migrations/20260911022312_cf_093_scheduler_workflow_preview_token_idempotency.sql')

 expect(ui).toContain("if(!preview?.preview_token){setError('Preview the governed scope before running it.')")
 expect(ui).toContain("preview?.executable!==true")
 expect(ui).toContain("execution_block_reason")
 expect(ui).toContain("governance reason of at least 5 characters")
 expect(ui).toContain("location.hash='#jobs'")
 expect(ui).toContain("location.hash='#evidence'")
 expect(ui).toContain("previewGeneration=useRef(0)")
 expect(ui).toContain("setPreview(null);setMessage('');previewGeneration.current+=1")
 expect(ui).toContain("if(generation!==previewGeneration.current)return")
 expect(ui).toContain("optionGeneration=useRef(0)")
 expect(ui).toContain("Existing recent governed dispatch reused")
 expect(ui).toContain("Follow Jobs/Evidence for underlying work status")

 expect(previewFix).toContain("'scheduler_workflow_preview','course_facts','completed'")
 expect(previewFix).toContain("'expires_at',now()+interval '15 minutes'")
 expect(previewFix).toContain("'change_control_ref','CF-CHG-20260910-093'")
 expect(previewFix).toContain("public.layer2_operator_scope_service(v_actor,'start'")
 expect(previewFix).not.toContain("'scheduler_workflow_run','course_facts','completed'")
})
