import { test, expect } from '@playwright/test'
import fs from 'node:fs'

// Decision 155 (part 1): Layer 1 runs are advanced in the background and the card shows live truth.
test('Layer 1 background runs: driver-safe control, live card status, readable failures',async()=>{
  const control=fs.readFileSync('supabase/functions/layer1-operations-control/index.ts','utf8')
  expect(control).toContain('const VERSION="layer1-operations-control-v1.6.0"')
  expect(control).toContain('svc_layer1_run_claim')
  expect(control).toContain('svc_pilot_consume_nonce",{p_function:FN')
  expect(control).toContain('internal callers may only continue a run')
  expect(control).toContain('const RETRY_MINUTES=[1,2,4,8,15]')
  expect(control).toContain('p_stage:"retry_waiting"')
  // workers are called with the service identity, never a user's sign-in token
  expect(control).not.toMatch(/authorization:`Bearer \$\{token\}`/)
  const nz=fs.readFileSync('supabase/functions/layer1-nz-live/index.ts','utf8')
  expect(nz).toContain('const VERSION="layer1-nz-live-v1.2.1"')
  expect(nz).toContain(String.raw`.replace(/^(https?:\/\/)+/i,"https://")`)
  expect(nz).toContain('svc_layer1_evidence_by_hash')
  expect(nz).toContain('if(doApply&&!hasMore)catalogueStats')
  const card=fs.readFileSync('src/layer1-operations-entry.jsx','utf8')
  expect(card).toContain('function RunStatus(')
  expect(card).toContain('<RunStatus source={source} rank={rank} busy={busy} onRetry={retry} onRefresh={onRefresh}/>')
  expect(card).toContain("const done=Math.max(0,Number(r?.resume_cursor||0))")
  expect(card).toContain('Runs in the background. You can close this page')
  expect(card).toContain("idempotency_key:`run:${source.source_id}:${mode}:${Date.now()}`")
  expect(card).not.toContain('progress_percent')
  // ranking family card: operational edition is the newest ingested one, titled with its year (CF-068)
  expect(card).toContain('const current=xs.find(x=>x.edition_is_current!==false&&hasData(x))')
  expect(card).toContain('source_label:`${rankingFamilyLabel(current)}${current.edition_year?` ${current.edition_year}`:\'\'}`')
  const flow=fs.readFileSync('.github/workflows/deploy-edge-functions.yml','utf8')
  for(const f of ['[layer1-operations-control]=false','[layer1-nz-live]=true','[layer1-register-etl]=true'])expect(flow).toContain(f)
  const mig=fs.readFileSync('supabase/migrations/20260927030000_layer1_background_run_driver.sql','utf8')
  expect(mig).toContain("cron.schedule('layer1-run-driver'")
})

// Decision 155 steps 2, 5, 6 and 7: change-based apply, evidence clean-up, departures, automatic ingestion.
test('Layer 1 change-based apply, departures and automatic ingestion are wired end to end',async()=>{
  const control=fs.readFileSync('supabase/functions/layer1-operations-control/index.ts','utf8')
  expect(control).toContain('svc_layer1_plan_slice')
  expect(control).toContain('JSON.stringify({plan:true,runId,apply})')
  expect(control).toContain('svc_layer1_plan_finish')
  const depth=fs.readFileSync('supabase/functions/layer1-au-depth/index.ts','utf8')
  expect(depth).toContain('const VERSION="layer1-au-depth-v1.7.0"')
  expect(depth).toContain('async function courseFingerprints(')
  expect(depth).toContain('svc_layer1_plan_changes')
  expect(depth).toContain('svc_layer1_plan_mark_applied')
  expect(depth).toContain('async function storedRegister(')
  const facts=fs.readFileSync('supabase/functions/layer1-au-cricos-facts/index.ts','utf8')
  expect(facts).toContain('const VERSION="layer1-au-cricos-facts-v1.2.0"')
  expect(facts).toContain('storedPath=clean(body.evidencePath)')
  const dedupe=fs.readFileSync('supabase/functions/evidence-storage-dedupe/index.ts','utf8')
  expect(dedupe).toContain('svc_evidence_dedupe_next')
  expect(dedupe).toContain('verify_sample')
  const card=fs.readFileSync('src/layer1-operations-entry.jsx','utf8')
  expect(card).toContain('function Departures(')
  expect(card).toContain("supabase.rpc('layer1_approve_departures'")
  expect(card).toContain('const PlanLine=')
  expect(card).toContain('Automatic ingestion')
  const flow=fs.readFileSync('.github/workflows/deploy-edge-functions.yml','utf8')
  for(const f of ['[layer1-au-cricos-facts]=false','[evidence-storage-dedupe]=false'])expect(flow).toContain(f)
  for(const m of ['20260928010000_layer1_change_based_apply.sql','20260928020000_layer1_departures_automatic.sql','20260928030000_evidence_storage_dedupe.sql','20260928040000_layer1_auto_ingest.sql'])expect(fs.existsSync(`supabase/migrations/${m}`)).toBe(true)
})
