// CF-247 v2.15.177 (Decision 252, Platform Admin 4 Oct 2026 13:37): OpenRouter observed, not capped by the platform;
// a notice on each layer when a toolset it depends on hits a limit or times out; Serper and ScrapingBee saials across
// every country; every variable a setting the Platform Admin changes in the UI.
import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { mockAdmin } from './support/admin-mock.mjs'

const read = p => readFileSync(new URL(`../../${p}`, import.meta.url), 'utf8')

test('migrations shaped: observe mode guarded by md5, notices from logs, sample runs record only', () => {
  const samples = ['20261004000700_cf247_toolset_trial_tables', '20261004000710_cf247_toolset_trial_settings', '20261004000720_cf247_toolset_trial_services', '20261004000730_cf247_toolset_trial_backlog',
    '20261004000740_cf247_toolset_trial_write', '20261004000750_cf247_trial_close_probe', '20261004000760_cf247_trial_release_leases', '20261004000770_cf247_trial_run_status',
    '20261004000780_cf247_trial_record', '20261004000790_cf247_trial_next', '20261004000800_cf247_trial_results_read', '20261004000900_cf247_toolset_keys_plans_sample_runs']
  for (const f of ['20261004000600_cf247_toolset_limits_and_notices', ...samples]) {
    const m = read(`supabase/migrations/${f}.sql`)
    for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
    expect(m).not.toMatch(/insert into catalogue\.|update catalogue\.|admitted_value/)
  }
  const a = read('supabase/migrations/20261004000600_cf247_toolset_limits_and_notices.sql')
  for (const h of ['15fcf19b03b42539a912dd0ee1501bf7', 'c081a641b616aa3cc2859730468ff56a', 'ae1a34a92116682c5477cf22bf38f7bb']) expect(a).toContain(`is distinct from '${h}'`)
  expect(a).toContain("('openrouter', 'OpenRouter (AI models)', 'ai', '{3}', null, 'observe',")
  expect(a).toContain("select coalesce((select t.enforcement is distinct from 'observe' from pipeline.platform_toolsets t where t.key = p_toolset), true)")
  expect(a).toContain("raise exception 'Platform Admin required'")
  const b = samples.map(f => read(`supabase/migrations/${f}.sql`)).join('\n')
  expect(b).toContain("pg.read_status in ('needs_render', 'blocked')")
  expect(b).not.toMatch(/read_status in \([^)]*robots_disallowed/)
  expect(b).toMatch(/'serper', 'Serper \(web search, trial\)'[\s\S]*?, false, 'Platform Operations'/)
  // Decision 252 amended (14:26): no trial wording; keys carry plan limits set in the UI; renamed, not recreated
  const k = read('supabase/migrations/20261004000900_cf247_toolset_keys_plans_sample_runs.sql')
  expect(k).toContain('alter table pipeline.toolset_trial_runs rename to toolset_sample_runs;')
  for (const key of ['plan_name', 'plan_credits', 'plan_renews_monthly', 'plan_counted_from', 'plan_reserve', 'plan_max_concurrency']) expect(k).toContain(`('serper', '${key}'`)
  expect(k).toContain("display_name = 'Serper (web search)'")
  // the migration tool reads a semicolon inside text as the end of a statement: none in any text value
  for (const m of k.replace(/--[^\n]*/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(m[0]).not.toContain(';')
})

test('routing worker: the credit floor comes from the register, not a constant', () => {
  const w = read('supabase/functions/layer3-model-routing/index.ts')
  expect(w).not.toContain('CREDIT_FLOOR_USD')
  expect(w).toContain('rpc("svc_layer3_credit_policy", {})')
  expect(w).toContain('pol.enforce && c.remaining < pol.floor')
})

test('sample-run worker: classifiers, plan limits respected, no constants for limits, no trial wording', async () => {
  const t = read('supabase/functions/toolset-runner/index.ts')
  expect(t.toLowerCase()).not.toContain('trial')
  expect(t).toContain('Math.min(Number(s.sample_concurrency) || 1, planMax)')
  for (const k of ['sample_seconds_per_call', 'sample_concurrency', 'title_match_min', 'course_query', 'provider_query', 'render_js', 'premium_proxy', 'wait_ms', 'directory_hosts']) expect(t).toContain(`s.${k}`)
  const { execFileSync } = await import('node:child_process'); const os = await import('node:os'); const path = await import('node:path')
  const out = path.join(os.tmpdir(), `toolset-runner-${process.pid}.mjs`)
  execFileSync('node_modules/.bin/esbuild', ['supabase/functions/toolset-runner/index.ts', '--bundle', '--format=esm', '--platform=neutral', '--external:npm:*', '--external:jsr:*', `--outfile=${out}`])
  const src = readFileSync(out, 'utf8').replace(/^import .*$/gm, '').replace(/Deno\.serve\([\s\S]*$/, '')
  const mod = await import('data:text/javascript;base64,' + Buffer.from(src + '\nexport { classifyCourseSearch, classifyProviderSearch, classifyRender, titleScore, fill };').toString('base64'))
  expect(mod.fill('{course} {provider}', { course: 'Bachelor of Nursing', provider: 'Example University' })).toBe('Bachelor of Nursing Example University')
  const c = mod.classifyCourseSearch({ course: 'Bachelor of Nursing', domain: 'example.edu.au', earlier_candidate: 'https://www.example.edu.au/study/nursing/' },
    [{ title: 'Bachelor of Nursing | Example University', link: 'https://www.example.edu.au/study/nursing', position: 1 }], 0.6)
  expect(c).toMatchObject({ outcome: 'found_on_provider_site', same_as_earlier_candidate: true })
  expect(mod.classifyCourseSearch({ course: 'Bachelor of Nursing', domain: 'example.edu.au' }, [{ title: 'Nursing degrees', link: 'https://studyportals.com/x' }], 0.6).outcome).toBe('other_sites_only')
  expect(mod.classifyProviderSearch({ provider: 'Lakeside College' }, [{ title: 'Lakeside College - Facebook', link: 'https://facebook.com/lakeside' }, { title: 'Lakeside College | Home', link: 'https://lakeside.ca/' }], 0.6, ['facebook.com'])).toMatchObject({ outcome: 'likely_official_site', suggested_site: 'https://lakeside.ca' })
  const r = mod.classifyRender({ course: 'Master of Data Science', code: '012345K' }, 200, '<html><title>Master of Data Science</title><body><h1>Master of Data Science</h1><p>Intakes: February and July. IELTS 6.5. A$42,000 a year.</p></body></html>', 0.6)
  expect(r).toMatchObject({ outcome: 'rendered_course_page', markers: { intake: true, english: true, tuition: true } })
  expect(mod.classifyRender({ course: 'X' }, 403, '<html>Access denied</html>', 0.6).outcome).toBe('blocked')
})

test('browser: notices on the layer page, acknowledged with a reason', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.accept('Seen; reviewing the batch size'))
  await page.goto('/#layer-2-discovery')
  const strip = page.locator('[data-layer-notices="2"]')
  await expect(strip.locator('[data-notice="scheduled_jobs:2:timeout:scholarship-nationality"]')).toContainText('hit the database time limit')
  await expect(strip.locator('.tn-seen summary')).toHaveText('1 acknowledged')
  await strip.locator('[data-notice="scheduled_jobs:2:timeout:scholarship-nationality"]').getByRole('button', { name: 'Acknowledge' }).click()
  await expect.poll(() => page.l3calls.find(c => c.toolsets === 'ack')?.args).toMatchObject({ notice_key: 'scheduled_jobs:2:timeout:scholarship-nationality', reason: 'Seen; reviewing the batch size' })
  await page.goto('/#layer-3-ai')
  await expect(page.locator('[data-layer-notices="3"]')).toContainText('the key\'s own spending limit')
})

test('browser: Models & services — OpenRouter observe only, key and plan limits, settings by section, sample runs started and continued', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.accept('Decision 252 sample'))
  await page.goto('/#models-services')
  const or = page.locator('[data-toolset="openrouter"]')
  await expect(or.locator('[data-toolset-mode="openrouter"]')).toContainText('Observe only')
  await expect(or.locator('[data-openrouter]')).toContainText('Balance US$27.67')
  await or.getByRole('button', { name: 'Switch to stop at limits' }).click()
  await expect.poll(() => page.l3calls.find(c => c.toolsets === 'enforcement')?.args).toMatchObject({ toolset: 'openrouter', enforcement: 'stop' })
  const q = page.locator('[data-toolset-setting="serper.course_query"]')
  await q.getByRole('textbox').fill('"{course}" {provider}')
  await q.getByRole('button', { name: 'Save' }).click()
  await expect.poll(() => page.l3calls.find(c => c.toolsets === 'setting')?.args).toMatchObject({ toolset: 'serper', key: 'course_query', value: '"{course}" {provider}' })
  const cc = page.locator('[data-toolset-setting="serper.sample_countries"]')
  await cc.getByRole('textbox').fill('AU, NZ, CA, GB')
  await cc.getByRole('button', { name: 'Save' }).click()
  await expect.poll(() => page.l3calls.filter(c => c.toolsets === 'setting').map(c => c.args.value)).toContainEqual(['AU', 'NZ', 'CA', 'GB'])
  await expect(page.locator('[data-toolset-key="scrapingbee"]')).toContainText('No key saved')
  const plan = page.locator('[data-toolset-plan="serper"]')
  await expect(plan).toContainText('Free plan')
  await expect(plan).toContainText('48 of 2,500 credits used since 2026-10-04')
  await expect(page.locator('[data-toolset-key="serper"]')).toContainText('Replace the key on Environment & integrations')
  for (const sec of ['Key and plan limits', 'How the service is used', 'Sample runs']) await expect(page.locator(`[data-toolset-section="serper:${sec}"]`)).toBeVisible()
  const credits = page.locator('[data-toolset-setting="serper.plan_credits"]')
  await credits.getByRole('textbox').fill('50000')
  await credits.getByRole('button', { name: 'Save' }).click()
  await expect.poll(() => page.l3calls.filter(c => c.toolsets === 'setting').map(c => c.args)).toContainEqual(expect.objectContaining({ toolset: 'serper', key: 'plan_credits', value: '50000' }))
  await expect(page.locator('[data-toolsets]')).not.toContainText(/trial/i)
  const tr = page.locator('[data-toolset-samples]')
  await expect(tr.getByRole('button', { name: 'Run a sample with ScrapingBee: Read pages that need a browser' })).toBeDisabled()
  await tr.getByRole('button', { name: 'Run a sample with Serper: Find provider websites' }).click()
  await expect.poll(() => page.l3calls.find(c => c.sample === 'start')?.args).toMatchObject({ toolset: 'serper', purpose: 'find_provider_site' })
  await expect.poll(() => page.l3calls.find(c => c.runnerKick)?.runnerKick).toMatchObject({ action: 'run', run_id: '7d1e0000-0000-4000-8000-000000000002' })
  await tr.locator('[data-sample-run="7d1e0000-0000-4000-8000-000000000001"]').getByRole('button', { name: 'Continue' }).click()
  await expect.poll(() => page.l3calls.filter(c => c.runnerKick).length).toBe(2)
  await expect(tr.locator('[data-sample-results] [data-sample-outcome="found_on_provider_site"]')).toContainText('14 (70%)')
  await expect(tr.locator('[data-sample-projection]')).toContainText('US$7.33')
})

// Decision 252 steps 1 and 2 (v2.15.179): search pass into the identity check; addresses repaired from stored results
test('search pass: migration shaped, worker binds found pages only for a pass, never replaces a confirmed page', () => {
  const m = read('supabase/migrations/20261004001100_cf247_search_pass_and_link_repair.sql')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  for (const h of ['12c2663ee54572ddde516881d2d5aa76', '17cbb1540acdcdd9f01cd9a73e7ac79b', 'eaac20b00a5b42d145ba5604ac084577']) expect(m).toContain(`is distinct from '${h}'`)
  expect(m).toContain("if v_pg.course_id is not null and v_pg.status = 'bound' and (v_pg.read_status = 'read' or v_pg.identity_basis is not null) then return 'already_confirmed'")
  expect(m).toContain("k.field = 'official_url'")
  expect(m).not.toMatch(/insert into catalogue\.|update catalogue\./)
  for (const lit of m.replace(/--[^\n]*/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(lit[0]).not.toContain(';')
  const w = read('supabase/functions/toolset-runner/index.ts')
  expect(w).toContain('if (batch.applies && res.outcome === "found_on_provider_site")')
  expect(w).toContain('rpc("svc_toolset_sample_continue", { p_run_id: runId })')
})

test('browser: search pass panel — start with a reason, pages sent to the identity check, repairs listed', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.accept('Decision 252 step 1'))
  await page.goto('/#models-services')
  const p = page.locator('[data-search-pass]')
  await expect(p.locator('[data-pass-links] [data-pass-state="verified"]')).toContainText('64')
  await expect(p.locator('[data-pass-repairs]')).toContainText('392')
  await p.getByRole('button', { name: 'Run the search pass' }).click()
  await expect.poll(() => page.l3calls.find(c => c.pass)?.pass).toMatchObject({ p_reason: 'Decision 252 step 1' })
})

// Decision 253 (v2.15.180): Firecrawl only, by use case, for target universities; every run call logged for support
test('firecrawl use cases: migrations shaped, md5-guarded, nothing admitted, settings drive every option', () => {
  const files = ['20261004001200_cf247_firecrawl_use_cases', '20261004001210_cf247_firecrawl_targets_type_fix', '20261004001220_cf247_firecrawl_course_like_pages']
  const m = files.map(f => read(`supabase/migrations/${f}.sql`)).join('\n')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  expect(m).not.toMatch(/insert into catalogue\.|update catalogue\./)
  for (const lit of m.replace(/--[^\n]*/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(lit[0]).not.toContain(';')
  for (const line of m.split('\n')) if (/^\s*update\s+\S+\s+(\w+\s+)?set\b/i.test(line)) expect(line).toMatch(/\bwhere\b/i)
  for (const h of ['21113f0647869a59432f922c5092da86', '2400c446114c5d22deb8ee6719cbbfc1']) expect(m).toContain(`is distinct from '${h}'`)
  for (const k of ['target_countries', 'target_name_pattern', 'target_exclude_pattern', 'target_min_courses', 'target_registers', 'target_only', 'read_statuses', 'read_proxy', 'read_wait_ms', 'read_timeout_ms', 'read_location', 'read_credits_per_run', 'find_query', 'find_results', 'find_min_title_match', 'find_retry_refused', 'find_credits_per_run', 'run_concurrency', 'run_batch_per_call', 'run_auto_continue', 'read_url_pattern', 'read_skip_url_pattern'])
    expect(m).toContain(`('firecrawl', '${k}'`)
  expect(m).toContain("k.field = 'official_url'")
  expect(m).toContain("raise exception 'Platform Admin required'")
  const w = read('supabase/functions/coverage-sweep/index.ts')
  expect(w).toContain('if (!isTarget(providerId)) return false;')
  expect(w).toContain('await rpc("svc_fc_call_log", { p: { ...log, outcome } })')
  for (const k of ['run_batch_per_call', 'run_concurrency', 'read_proxy', 'find_min_title_match']) expect(w).toContain(`s.${k}`)
  const f = read('supabase/functions/coverage-sweep/firecrawl.ts')
  for (const k of ['read_proxy', 'read_wait_ms', 'read_timeout_ms', 'read_location', 'find_query', 'find_results']) expect(f).toContain(`s.${k}`)
  expect(f).toContain('"scrapeId"')
})

test('firecrawl helpers: request bodies from settings, search candidates on the university site, call record for support', async () => {
  const { execFileSync } = await import('node:child_process'); const os = await import('node:os'); const path = await import('node:path')
  const out = path.join(os.tmpdir(), `fc-helpers-${process.pid}.mjs`)
  execFileSync('node_modules/.bin/esbuild', ['supabase/functions/coverage-sweep/firecrawl.ts', '--format=esm', `--outfile=${out}`])
  const mod = await import(out)
  expect(mod.scrapeBody('https://x.edu.au/c', { read_proxy: 'auto', read_wait_ms: 3000, read_timeout_ms: 60000, read_location: true }, 'AU')).toEqual({ url: 'https://x.edu.au/c', formats: ['rawHtml'], onlyMainContent: false, proxy: 'auto', waitFor: 3000, timeout: 60000, location: { country: 'AU' } })
  expect(mod.searchBody({ course: 'Bachelor of Arts', domain: 'uq.edu.au' }, { find_query: '{course} site:{domain}', find_results: 5 }, 'AU')).toEqual({ query: 'Bachelor of Arts site:uq.edu.au', limit: 5, country: 'AU' })
  const c = mod.searchCandidates({ course: 'Bachelor of Arts', domain: 'uq.edu.au' }, [{ url: 'https://study.uq.edu.au/arts', title: 'Bachelor of Arts - UQ' }, { url: 'https://idp.com/a', title: 'Bachelor of Arts' }], 0.6)
  expect(c).toMatchObject({ outcome: 'found_on_provider_site', candidates: ['https://study.uq.edu.au/arts'] })
  const rec = mod.callRecord(200, { success: true, data: { html: '<p>x</p>', metadata: { statusCode: 403, scrapeId: 's1', creditsUsed: 5, proxyUsed: 'stealth' } } }, new Headers({ 'x-request-id': 'r1' }), 900, null)
  expect(rec).toMatchObject({ success: true, scrape_id: 's1', credits_used: 5, proxy_used: 'stealth', page_status: 403 })
  expect(rec.meta['header_x-request-id']).toBe('r1')
  expect(mod.readOutcome(rec, '<p>x</p>', 5)).toBe('blocked')
  expect(mod.readOutcome(mod.callRecord(null, null, null, 5, 'TimeoutError: aborted'), '', 0)).toBe('timeout')
})

test('browser: Firecrawl work — plan from Firecrawl, runs started with a reason, targets, support report copied', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.type() === 'prompt' && d.message().startsWith('Add credits') ? d.accept('500') : d.accept('Decision 253 run'))
  await page.goto('/#models-services')
  for (const sec of ['Target universities', 'Read pages', 'Find pages', 'Runs']) await expect(page.locator(`[data-toolset-section="firecrawl:${sec}"]`)).toBeVisible()
  const w = page.locator('[data-firecrawl-work]')
  await expect(w.locator('[data-firecrawl-plan]')).toContainText('490,846 of 500,000 credits left')
  await expect(w.getByRole('button', { name: 'Find pages (3,975 waiting)' })).toBeDisabled()
  await w.getByRole('button', { name: 'Read pages (1,102 waiting)' }).click()
  await expect.poll(() => page.l3calls.find(c => c.firecrawl === 'start')?.args).toMatchObject({ use_case: 'read_page', reason: 'Decision 253 run' })
  await expect(w.locator('[data-firecrawl-run="fc000000-0000-4000-8000-000000000002"] [data-run-outcome="found_on_provider_site"]')).toContainText('260')
  await w.locator('[data-firecrawl-run="fc000000-0000-4000-8000-000000000001"]').getByRole('button', { name: 'Continue' }).click()
  await expect.poll(() => page.l3calls.find(c => c.firecrawl === 'continue')?.args).toMatchObject({ run_id: 'fc000000-0000-4000-8000-000000000001', add_credits: 500 })
  const t = page.locator('[data-firecrawl-targets]')
  await expect(t).toContainText('The University of Sydney')
  await t.locator('[data-firecrawl-target="u3"]').getByRole('button', { name: 'Add' }).click()
  await expect.poll(() => page.l3calls.find(c => c.firecrawl === 'target')?.args).toMatchObject({ provider_id: 'u3', included: true })
  const r = page.locator('[data-firecrawl-report]')
  await expect(r.locator('[data-report-errors]')).toContainText('01a10555-0b96-720b-9ea2-dfe988faa072')
  await expect(r.locator('[data-report-totals]')).toContainText('461')
  await expect(page.locator('[data-toolsets]')).not.toContainText(/trial/i)
})

test('university adapters: migrations shaped, worker uses adapters, nothing admitted without the country rule', async () => {
  const files = ['20261004001230_cf247_firecrawl_target_cache', '20261004001240_cf247_university_adapters', '20261004001250_cf247_adapters_in_reader']
  const m = files.map(f => read(`supabase/migrations/${f}.sql`)).join('\n')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  expect(m).not.toMatch(/insert into catalogue\.|update catalogue\.|coverage_admission_countries set/)
  for (const lit of m.replace(/--[^\n]*/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(lit[0]).not.toContain(';')
  for (const line of m.split('\n')) if (/^\s*update\s+\S+\s+(\w+\s+)?set\b/i.test(line)) expect(line).toMatch(/\bwhere\b/i)
  expect(m).toContain("if p_identity not in ('adapter_code', 'adapter_title') or p_candidates is null then return 'nothing'")
  expect(m).toContain("k.field = 'official_url'")
  const w = read('supabase/functions/coverage-sweep/index.ts')
  expect(w).toContain('rpc("svc_uni_adapters", {})')
  expect(w).toContain('!(adDirect?.json_found && adDirect.identity)')
  const { execFileSync } = await import('node:child_process'); const os = await import('node:os'); const path = await import('node:path')
  const out = path.join(os.tmpdir(), `adapters-${process.pid}.mjs`)
  execFileSync('node_modules/.bin/esbuild', ['supabase/functions/coverage-sweep/adapters.ts', '--bundle', '--format=esm', `--outfile=${out}`])
  const mod = await import(out)
  const data = { props: { pageProps: { pageContent: { title: 'Bachelor of Accounting and Finance', cricos_code: null, ielts_overall_score: 6.5 } } } }
  const html = `<html><head><title>BAF Bachelor of Accounting and Finance - Example</title></head><body><h1>Handbook</h1><script id="__NEXT_DATA__" type="application/json">${JSON.stringify(data)}</script></body></html>`
  const a = { json_source: '__NEXT_DATA__', json_paths: { title: 'props.pageProps.pageContent.title', code: 'props.pageProps.pageContent.cricos_code', ielts_overall: 'props.pageProps.pageContent.ielts_overall_score' } }
  const r = mod.applyAdapter(a, html, { title: 'Bachelor of Accounting and Finance', code: '065056B', country: 'AU' }, 'x')
  expect(r).toMatchObject({ identity: 'adapter_title', json_found: true })
  expect(r.candidates.english.ielts_overall).toBe(6.5)
  expect(mod.applyAdapter(a, html, { title: 'Bachelor of Accounting and Finance (Honours)', code: '000000X', country: 'AU' }, 'x').identity).toBeNull()
  expect(mod.applyAdapter({ title_strip: '^[A-Z]{2,8}\\s+' }, html, { title: 'Bachelor of Accounting and Finance', code: '', country: 'AU' }, 'x').identity).toBe('adapter_title')
  expect(mod.jsonFind(data, '^(title|cricos_code)$')).toEqual(['props.pageProps.pageContent.title: Bachelor of Accounting and Finance', 'props.pageProps.pageContent.cricos_code: null'])
})

test('browser: university adapter — preview on stored pages, save and apply with a reason', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.accept('Decision 253 adapter'))
  await page.goto('/#models-services')
  const t = page.locator('[data-firecrawl-targets]')
  await t.locator('[data-firecrawl-target="u1"]').getByRole('button', { name: 'Adapter' }).click()
  const ed = page.locator('[data-adapter-editor="u1"]')
  await ed.locator('[data-adapter-settings] > summary').click()
  await expect(ed.locator('[data-adapter-preview]')).toContainText('adapter_title')
  await expect(ed.locator('[data-adapter-applied]')).toContainText('refused pages confirmed (adapter_title) 41')
  await ed.getByRole('textbox', { name: 'Taken off page titles' }).fill('^[A-Z]{2,8}\\s+')
  await ed.getByRole('button', { name: 'Preview on stored pages' }).click()
  await expect.poll(() => page.l3calls.find(c => c.adapter === 'preview')?.args).toMatchObject({ provider_id: 'u1', adapter: { title_strip: '^[A-Z]{2,8}\\s+', json_source: '__NEXT_DATA__' } })
  await ed.getByRole('button', { name: 'Save' }).click()
  await expect.poll(() => page.l3calls.find(c => c.adapter === 'save')?.args?.reason).toBe('Decision 253 adapter')
  await ed.getByRole('button', { name: 'Apply' }).click()
  await expect.poll(() => page.l3calls.find(c => c.adapter === 'apply')?.args?.provider_id).toBe('u1')
})

// Decision 253 amended (Platform Admin 17:19): admit from adapters after testing, per adapter; refuse archived and test sites
test('adapter admission and refused hosts: per-adapter switch gates admission, hand-entered values untouched, logged', () => {
  const m = read('supabase/migrations/20261004001260_cf247_adapter_admission_and_refused_hosts.sql')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  for (const lit of m.replace(/--[^\n]*/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(lit[0]).not.toContain(';')
  for (const line of m.split('\n')) if (/^\s*update\s+\S+\s+(\w+\s+)?set\b/i.test(line)) expect(line).toMatch(/\bwhere\b/i)
  expect(m).toContain("is distinct from 'e780e135bc2e801de598b6d4234c5ae8'")
  expect(m).toContain("and not exists (select 1 from pipeline.uni_adapters u where u.provider_id = p_provider_id and u.enabled and u.admit) then false")
  expect(m).toContain('alter table pipeline.uni_adapters add column if not exists admit boolean not null default false')
  expect(m).toContain("foreach k in array array['official_url', 'english', 'intakes']")
  expect(m.match(/source_type = 'manual_entry'/g).length).toBeGreaterThanOrEqual(3)
  expect(m.match(/k\.field = 'official_url'/g).length).toBeGreaterThanOrEqual(2)
  expect(m).toContain('insert into pipeline.refused_host_changes')
})

test('browser: adapter — test what it would admit, switch admission on with a reason, ask for an improvement', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.accept('Checked 10 pages against the handbook'))
  await page.goto('/#models-services')
  const list = page.locator('[data-university-adapters]')
  await expect(list.locator('[data-adapter-row="u1"]')).toContainText('Testing — not admitting')
  await list.locator('[data-adapter-row="u1"]').getByRole('button', { name: 'Open' }).click()
  const r = page.locator('[data-adapter-review="u1"]')
  await expect(r.locator('[data-adapter-confirmed]')).toContainText('121373J')
  await expect(r.locator('[data-adapter-admit]')).toContainText('Not admitting yet')
  await r.getByRole('button', { name: 'Admit from this adapter' }).click()
  await expect.poll(() => page.l3calls.find(c => c.adapterControl === 'admit')?.args).toMatchObject({ provider_id: 'u1', admit: true, reason: 'Checked 10 pages against the handbook' })
  await r.getByRole('textbox', { name: 'Improvement request' }).fill('IELTS is in the entry requirements tab')
  await r.getByRole('button', { name: 'Send request' }).click()
  await expect.poll(() => page.l3calls.find(c => c.adapterControl === 'request')?.args?.request).toBe('IELTS is in the entry requirements tab')
  await expect(r.locator('[data-adapter-requests]')).toContainText('Intakes are under Start dates')
})

test('firecrawl panel reads kept figures (fast), adapters listed on their own', () => {
  const m = read('supabase/migrations/20261004001270_cf247_firecrawl_panel_fast.sql')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  for (const lit of m.replace(/--[^\n]*/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(lit[0]).not.toContain(';')
  const read_ = m.slice(m.indexOf('create or replace function public.admin_firecrawl_read'))
  expect(read_.slice(0, read_.indexOf('end $f$'))).not.toContain('firecrawl_targets_v1')
  expect(m).toContain("from security.firecrawl_targets_fast() t")
  const ui = read('src/FirecrawlWork.jsx')
  expect(ui).toContain('id="university-adapters"')
})

// Platform Admin 21:50 (Flinders): text patterns, extra fields, intakes admitted from the adapter's own reading only
test('adapter patterns: migration shaped, intakes and adapter English need the admit switch, patterns read the international block', async () => {
  const m = read('supabase/migrations/20261004001280_cf247_adapter_patterns_and_intakes.sql')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  for (const lit of m.replace(/--[^\n]*/g, '').replace(/\$s\$[\s\S]*?\$s\$/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(lit[0]).not.toContain(';')
  for (const line of m.split('\n')) if (/\bupdate\s+\S+\s+set\b/i.test(line)) expect(line).toMatch(/\bwhere\b/i)
  expect(m).toContain("is distinct from '2043cdcd8cf89b27c83197a6d11f6ca9'")
  expect(m).toContain("and pg.c->>'intakes_by'='adapter' and exists (select 1 from pipeline.uni_adapters u where u.provider_id=pg.provider_id and u.enabled and u.admit)")
  expect(m).toContain("coalesce(pg.c->>'english_by','')<>'adapter' or exists")
  expect(m).toContain("array['intakes']")
  const os = await import('node:os'), path = await import('node:path'), { execFileSync } = await import('node:child_process')
  const out = path.join(os.tmpdir(), `adapters-p-${process.pid}.mjs`)
  execFileSync('node_modules/.bin/esbuild', ['supabase/functions/coverage-sweep/adapters.ts', '--bundle', '--format=esm', `--outfile=${out}`])
  const mod = await import(out)
  const A = { patterns: {
    intakes: 'CRICOS(?: code)?:?\\s*[0-9]{6}[A-Z](?:.|\\n){0,250}?Start dates(?:[^>]{0,120}>)?((?:\\s*[–-]?\\s*(?:January|February|March|April|May|June|July|August|September|October|November|December)\\b)+)',
    fee: 'CRICOS(?: code)?:?\\s*[0-9]{6}[A-Z](?:.|\\n){0,250}?Annual (?:indicative )?fee(?:.|\\n){0,60}?\\$([0-9][0-9,]+)(?![0-9,])(?!\\s*\\((?:CSP|FFP)\\))',
    campus: 'CRICOS(?: code)?:?\\s*[0-9]{6}[A-Z](?:.|\\n){0,200}?Delivery mode\\s*:?\\s*(.{2,80}?)\\s+(?:Duration|Deferrable|Annual|Start)' } }
  const html = '<title>Study X</title><h1>Bachelor X</h1><p>Delivery mode In person: Tonsley Annual indicative fee 2026 : $9,537 (CSP) Start dates – March – July</p><p>CRICOS code 111210M Delivery mode In person: Tonsley Duration 5 years full-time Annual fee 2026 : $9,537 (CSP) 2026: $47,300 Start dates – March – October Entry requirements</p>'
  const r = mod.applyAdapter(A, html, { title: 'x', code: '111210M', country: 'AU' }, 'v')
  expect(r.identity).toBe('cricos_code')
  expect(r.candidates).toMatchObject({ intakes: ['March', 'October'], intakes_by: 'adapter', fee_by: 'adapter', adapter_extra: { campus: 'In person: Tonsley' } })
  expect(r.candidates.fee.value).toBe(47300)
  expect(mod.applyAdapter({}, html, { title: 'x', code: '111210M', country: 'AU' }, 'v').candidates.intakes_by).toBeUndefined()
  const w = read('supabase/functions/coverage-sweep/index.ts')
  expect(w).toContain('Object.keys(adHit.patterns_found || {}).length > 0')
})

test('browser: adapter — patterns saved, readings on CRICOS-confirmed pages shown with extra fields', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.accept('Flinders study pages'))
  await page.goto('/#models-services')
  await page.locator('[data-university-adapters] [data-adapter-row="u1"]').getByRole('button', { name: 'Open' }).click()
  const r = page.locator('[data-adapter-review="u1"]')
  await expect(r.locator('[data-adapter-readings]')).toContainText('111210M')
  await expect(r.locator('[data-adapter-readings]')).toContainText('campus: In person: Tonsley')
  await expect(r.locator('[data-adapter-readings]')).toContainText('pattern')
  const ed = page.locator('[data-adapter-editor="u1"]')
  await ed.locator('[data-adapter-settings] > summary').click()
  await ed.getByRole('textbox', { name: 'Patterns' }).fill('{"intakes":"Start dates(.{0,40})"}')
  await ed.getByRole('textbox', { name: 'Pick' }).fill('{"intakes":"last"}')
  await ed.getByRole('button', { name: 'Save' }).click()
  await expect.poll(() => page.l3calls.find(c => c.adapter === 'save')?.args?.adapter).toMatchObject({ patterns: { intakes: 'Start dates(.{0,40})' }, pick: { intakes: 'last' } })
})

// Flinders apply (4 Oct 2026): unsafe "any text" patterns refused, Apply stays inside an edge call's processor time
test('adapter safety: overlapping patterns refused, apply reads within the processor-time limit and carries on', () => {
  for (const f of ['20261004001290_cf247_adapter_pattern_safety', '20261004001300_cf247_adapter_apply_continue']) {
    const m = read(`supabase/migrations/${f}.sql`)
    for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
    for (const lit of m.replace(/--[^\n]*/g, '').matchAll(/'(?:[^']|'')*'/g)) expect(lit[0]).not.toContain(';')
  }
  expect(read('supabase/migrations/20261004001290_cf247_adapter_pattern_safety.sql')).toContain("is distinct from '55c5749c2ca4994a4549d99dad63b56e'")
  expect(read('supabase/migrations/20261004001290_cf247_adapter_pattern_safety.sql')).toContain("position('.|\\s' in p) > 0")
  const w = read('supabase/functions/coverage-sweep/index.ts')
  expect(w).toContain('const ADAPTER_CPU_MS = 900')
  expect(w).toContain('rpc("svc_adapter_apply_continue", { p_provider_id: String(body.provider_id || ""), p_after: after })')
  expect(w).toContain('let after: string | null = body.after ? String(body.after) : null')
})

test('adapter patterns: Flinders layouts (comma and ampersand start dates, foundation programs), capitalised months only', async () => {
  const os = await import('node:os'), path = await import('node:path'), { execFileSync } = await import('node:child_process')
  const out = path.join(os.tmpdir(), `adapters-f-${process.pid}.mjs`)
  execFileSync('node_modules/.bin/esbuild', ['supabase/functions/coverage-sweep/adapters.ts', '--bundle', '--format=esm', `--outfile=${out}`])
  const mod = await import(out)
  const C = 'CRICOS(?: code)?:?\\s*[0-9]{6}[A-Z]'
  const A = { patterns: { intakes: C + '(?:.|\\n){0,250}?Start dates(?:[^>]{0,80}aria-expanded[^>]{0,12}>)?\\s*((?:.|\\n){0,120}?)\\s*(?:Annual|Delivery|Entry|Student|Information|Duration|Availability|Deferrable|Start dates|Save course|SATAC|CRICOS|$)' } }
  const run = (code, t) => mod.applyAdapter(A, `<title>x</title><h1>x</h1><p>${t}</p>`, { title: 'x', code, country: 'AU' }, 'v').candidates
  expect(run('109332H', 'CRICOS code 109332H Duration 8 or 12 months Start Dates February - 12 month program June & October - 8 month program Delivery Mode Full-time').intakes).toEqual(['February', 'June', 'October'])
  expect(run('094009B', 'Start dates March, July Annual indicative fees (2025) $4,656 (CSP) CRICOS 094009B Duration 0.5 Years Start dates March, July Annual indicative fees (2026) $20,700').intakes).toEqual(['March', 'July'])
  const may = run('111111A', 'CRICOS 111111A Duration 3 years Start dates may vary, see the website. Annual fee $40,000')
  expect(may.intakes_by).toBeUndefined()
})

// Platform Admin 22:43: admitting adapters collapsed with their switches stated, adapter readings replace held values
// except those entered by hand, better pages found, every target university evaluated for its next step
test('adapter overwrite, better pages and evaluation: migrations shaped, hand-entered values kept', () => {
  for (const f of ['20261004001310_cf247_adapter_overwrite_and_better_pages', '20261004001320_cf247_adapter_evaluation']) {
    const m = read(`supabase/migrations/${f}.sql`)
    for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
    for (const line of m.split('\n')) if (/\bupdate\s+\S+\s+set\b/i.test(line)) expect(line).toMatch(/\bwhere\b/i)
  }
  const m = read('supabase/migrations/20261004001310_cf247_adapter_overwrite_and_better_pages.sql')
  expect(m).toContain("is distinct from '151e73570a4ce33435647073a8047d4b'")
  expect(m).toContain("k.field in ('intakes', 'intake')")
  expect(m).toContain("and source_id is not null and intake_label <> all (v_itk)")
  expect(m).toContain("join pipeline.uni_adapters u on u.provider_id = pg.provider_id and u.enabled and u.admit")
  expect(m).toContain("k.field = 'official_url') then return 'entered_by_hand'")
  expect(read('supabase/migrations/20261004001320_cf247_adapter_evaluation.sql')).toContain("'eval_field_share'")
})

test('browser: admitting adapter collapsed with its switches, evaluation lists the next step per university', async ({ page }) => {
  await mockAdmin(page)
  await page.goto('/#models-services')
  const done = page.locator('[data-adapter-done="u9"]')
  await expect(done.locator('summary')).toContainText('Flinders University (AU) · Adapter enabled · Admission on')
  await expect(done).not.toHaveAttribute('open', '')
  await expect(page.locator('[data-adapter-list] [data-adapter-row="u9"]')).toHaveCount(0)
  await expect(page.locator('[data-adapter-list] [data-adapter-row="u1"]')).toBeVisible()
  const ev = page.locator('[data-adapter-eval]')
  await expect(ev.locator('[data-eval-row="u2"]')).toContainText('Adapter for start dates')
  await expect(ev.locator('[data-eval-row="u3"]')).toContainText('Adapter for page data')
  await ev.locator('[data-eval-row="u2"]').getByRole('button', { name: 'Set up adapter' }).click()
  await expect(page.locator('[data-adapter-editor="u2"]')).toBeVisible()
})

test('better page refused by the identity check is undone: earlier page bound again, logged, hand-entered links kept', () => {
  const m = read('supabase/migrations/20261004001330_cf247_better_page_revert.sql')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  for (const line of m.split('\n')) if (/\bupdate\s+\S+\s+set\b/i.test(line)) expect(line).toMatch(/\bwhere\b/i)
  expect(m).toContain("where pg.basis = 'firecrawl_upgrade' and pg.read_status = 'identity_mismatch'")
  expect(m).toContain("k.field = 'official_url'")
  expect(m).toContain("'better page refused by the identity check: earlier page bound again'")
})

// Platform Admin 23:41: fees admitted from an admitting adapter, the visual builder with a pinned model and a daily AI allowance
test('adapter fees and builder: migration shaped, hand-entered fees kept, model pinned by setting, daily allowance enforced', async () => {
  const m = read('supabase/migrations/20261004001340_cf247_adapter_fees_and_builder.sql')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  for (const line of m.split('\n')) if (/\bupdate\s+\S+\s+set\b/i.test(line)) expect(line).toMatch(/\bwhere\b/i)
  expect(m).toContain("is distinct from 'd6bc6366ca49095f401718a423ef4f77'")
  expect(m).toContain("k.field in ('tuition', 'fee', 'fees')")
  expect(m).toContain("and source_id is not null and coalesce(fee_year, 0) = coalesce(v_fy, 0) and amount <> v_fee")
  expect(m).toContain("'\"qwen/qwen3-30b-a3b-instruct-2507\"'")
  expect(m).toContain('the AI allowance for today is used')
  const w = read('supabase/functions/coverage-sweep/index.ts')
  expect(w).toContain('if (out?.model && !String(out.model).startsWith(model)) err = `answered by ${out.model}, not the pinned model`')
  expect(w).toContain('layer2/${["NZ", "CA"].includes(it.country) ? it.country : "AU"}/firecrawl/search/${runId}/${it.id}.json.gz')
  const os = await import('node:os'), path = await import('node:path'), { execFileSync } = await import('node:child_process')
  const out = path.join(os.tmpdir(), `builder-${process.pid}.mjs`)
  execFileSync('node_modules/.bin/esbuild', ['supabase/functions/coverage-sweep/builder.ts', '--bundle', '--format=esm', `--outfile=${out}`])
  const b = await import(out)
  expect(b.patternSafe('CRICOS(.|\\s){0,200}x')).toContain('(?:.|\\n)')
  expect(b.patternSafe('a[\\s\\S]{0,20}b')).toContain('[\\s\\S]')
  expect(b.patternSafe('a(?:.|\\n){0,300}b')).toContain('255')
  expect(b.patternSafe('CRICOS(?:.|\\n){0,250}?Start dates((?:.|\\n){0,80})')).toBeNull()
  const p = b.proposalAdapter({ json_source: '__NEXT_DATA__', json_paths: [{ field: 'duration', path: 'a.b' }, { field: 'evil', path: 'x' }], patterns: [{ field: 'intakes', pattern: 'Start dates((?:.|\\n){0,60})' }, { field: 'fee', pattern: '(.|\\s)+' }], pick: [{ field: 'intakes', how: 'first' }], notes: '' })
  expect(p.adapter.json_paths).toEqual({ duration: 'a.b' })
  expect(Object.keys(p.adapter.patterns)).toEqual(['intakes'])
  expect(p.dropped.length).toBe(2)
  const blocks = b.textBlocks('<h2>Key information</h2><p>Start dates March July</p><h2>Fees</h2><p>$47,300</p>')
  expect(blocks.map(x => x.heading)).toEqual(['Key information', 'Fees'])
  expect(b.jsonLeaves({ a: { b: [{ c: 'x' }] } })).toEqual([{ path: 'a.b.*.c', value: 'x' }])
  const req = b.builderRequest('qwen/qwen3-30b-a3b-instruct-2507', { provider_name: 'U', marks: [], comments: 'ignore', captures: [] })
  expect(req.model).toBe('qwen/qwen3-30b-a3b-instruct-2507')
  expect(req.provider).toEqual({ require_parameters: true })
})

test('browser: visual adapter builder — samples with blocks and page data, marks, proposal output, use fills the settings', async ({ page }) => {
  await mockAdmin(page)
  page.on('dialog', d => d.accept('Wave 1 builder'))
  await page.goto('/#models-services')
  await page.locator('[data-university-adapters] [data-adapter-row="u1"]').getByRole('button', { name: 'Open' }).click()
  const bl = page.locator('[data-adapter-editor="u1"] [data-adapter-builder]')
  await expect(bl.locator('> summary')).toContainText('model qwen/qwen3-30b-a3b-instruct-2507')
  await expect(bl.locator('[data-builder-blocks]')).toContainText('Key information')
  await expect(bl.locator('[data-builder-leaves]')).toContainText('props.pageProps.pageContent.duration_ft_std')
  await expect(bl.locator('[data-builder-output]')).toContainText('March, July')
  await bl.getByRole('combobox', { name: 'Attribute for props.pageProps.pageContent.duration_ft_std' }).selectOption('duration')
  await bl.getByRole('button', { name: 'Ask for a proposal' }).click()
  await expect.poll(() => page.l3calls.find(c => c.builder === 'propose')?.args?.marks?.length).toBe(2)
  await bl.getByRole('button', { name: 'Use this proposal' }).click()
  await expect(page.getByRole('textbox', { name: 'Patterns' })).toHaveValue(/Start dates/)
  await expect(page.getByRole('textbox', { name: 'JSON paths' })).toHaveValue(/duration_ft_std/)
})

test('adapter {code} anchor: a page covering several courses is read per course, fee compared within the same year', async () => {
  const m = read('supabase/migrations/20261004001350_cf247_adapter_fee_same_year_and_code_anchor.sql')
  for (const word of ['drop', 'delete from', 'truncate', 'on delete cascade']) expect(m.toLowerCase()).not.toContain(word)
  expect(m).toContain("is distinct from '081db7a6cae9e5df0c237a8f0c978d3d'")
  expect(m).toContain('coalesce(f.fee_year, 0) = coalesce(v_fy, 0)')
  const os = await import('node:os'), path = await import('node:path'), { execFileSync } = await import('node:child_process')
  const out = path.join(os.tmpdir(), `adapters-c-${process.pid}.mjs`)
  execFileSync('node_modules/.bin/esbuild', ['supabase/functions/coverage-sweep/adapters.ts', '--bundle', '--format=esm', `--outfile=${out}`])
  const mod = await import(out)
  const A = { patterns: { fee: '{code}(?:.|\\n){0,250}?Annual (?:indicative )?fee(?:.|\\n){0,60}?\\$([0-9][0-9,]+)(?![0-9,])' } }
  const t = '<title>x</title><h1>x</h1><p>Graduate Certificate CRICOS 094009B Annual indicative fees (2026) $19,900 Master CRICOS 094010X Annual indicative fees (2026) $39,800</p>'
  expect(mod.applyAdapter(A, t, { title: 'x', code: '094009B', country: 'AU' }, 'v').candidates.fee).toMatchObject({ value: 19900, fee_year: 2026 })
  expect(mod.applyAdapter(A, t, { title: 'x', code: '094010X', country: 'AU' }, 'v').candidates.fee).toMatchObject({ value: 39800, fee_year: 2026 })
  expect(mod.withCode('{code}x', 'A.B')).toBe('A\\.Bx')
  expect(mod.withCode('{code}x', '')).toBeNull()
})
