import fs from'node:fs/promises'
import{test,expect}from'@playwright/test'

test.describe('CF-093 admin dispatcher tuning contract',()=>{
 test('sanitized admin read exposes comparable metrics and fixed transport guardrails',async()=>{
  const base=await fs.readFile('supabase/migrations/20260914210000_cf_093_admin_dispatcher_tuning_metrics.sql','utf8')
  const perf=await fs.readFile('supabase/migrations/20260914213000_cf_093_dispatcher_tuning_read_performance.sql','utf8')
  const sql=`${base}\n${perf}`
  expect(sql).toContain('admin_layer2_dispatcher_tuning_read_v1')
  expect(sql).toContain("'transport_wave_cap',4")
  expect(sql).toContain("'scraper_first_wave_cap',2")
  expect(sql).toContain("'pg_net_timeout_ms',120000")
  expect(perf).toContain("'active_window_items_per_min'")
  expect(perf).toContain("'wall_throughput_items_per_min'")
  expect(perf).toContain("'recent_completed_60m'")
  expect(perf).toContain("pa.created_at>=now()-interval '24 hours'")
  expect(sql).toContain("'avg_response_ms'")
  expect(sql).toContain("'avg_extraction_ms'")
  expect(sql).toContain("'evidence_count'")
  expect(sql).toContain("'fields_resolved'")
  expect(sql).not.toMatch(/'request_url'\s*,/)
  expect(sql).not.toMatch(/'source_url'\s*,/)
  expect(sql).not.toMatch(/'storage_path'\s*,/)
  expect(sql).not.toMatch(/'raw_payload'\s*,/)
  expect(sql).not.toMatch(/'result'\s*,/)
  expect(sql).not.toMatch(/'error'\s*,/)
 })
 test('policy updates remain rank-gated, reason-mandatory and accurately auditable',async()=>{
  const edge=await fs.readFile('supabase/functions/layer2-config-control/index.ts','utf8')
  const base=await fs.readFile('supabase/migrations/20260914210000_cf_093_admin_dispatcher_tuning_metrics.sql','utf8')
  const hardening=await fs.readFile('supabase/migrations/20260914214500_cf_093_dispatcher_tuning_audit_hardening.sql','utf8')
  expect(edge).toContain('if(rank<5)return reply(req,403,{error:"pim_admin_role_required"})')
  expect(edge).toContain('"max_concurrency"')
  expect(edge).toContain('"stale_after_minutes"')
  expect(edge).toContain('"_governance_reason"')
  expect(edge).toContain('if(String(patch._governance_reason||"").trim().length<5)return reply(req,400,{error:"governance_reason_required"})')
  expect(base).toContain('pipeline.layer2_tuning_events')
  expect(hardening).toContain("if v_rank<5 then raise exception 'pim_admin role required'")
  expect(hardening).toContain("if v_reason is null or length(v_reason)<5 then raise exception 'governance reason required'")
  expect(hardening).toContain("v_before->k is distinct from v_after->k")
  expect(hardening).toContain('before_policy')
  expect(hardening).toContain('after_policy')
  expect(hardening).toContain("'audit_recorded',true")
 })
 test('admin UI separates vendor settings from dispatcher controls and never offers auto tuning',async()=>{
  const ui=await fs.readFile('src/Layer2DispatcherTuning.jsx','utf8')
  const host=await fs.readFile('src/layer2-provider-entry.jsx','utf8')
  expect(host).toContain("import Layer2DispatcherTuning from'./Layer2DispatcherTuning'")
  expect(host).toContain('<Layer2DispatcherTuning rank={rank} onError={setError}/>')
  expect(ui).toContain('Dispatcher tuning & run metrics')
  expect(ui).toContain('Vendor rate, timeout, credentials and quota remain in Scraper Config')
  expect(ui).toContain('Manual governed tuning only')
  expect(ui).toContain('Latest comparable runs')
  expect(ui).toContain('active_window_items_per_min')
  expect(ui).toContain('wall_throughput_items_per_min')
  expect(ui).toContain('Governance reason')
  expect(ui).toContain('Changes never rewrite an in-flight batch snapshot')
  expect(ui).not.toContain('autoTune')
  expect(ui).not.toContain('routing_strategy:')
 })
})
