import { test, expect } from '@playwright/test'
import { attachRuntimeEvidence, assertNoServerErrors, clickPrimaryNav, loginAsUatUser, milestoneScreenshot, observeRuntime, writeRunEnvironment } from './support/runtime-evidence.mjs'

async function finish(testInfo,runtime){await attachRuntimeEvidence(testInfo,runtime);assertNoServerErrors(runtime)}
async function selectMatching(select,re){await expect.poll(async()=>await select.locator('option').allTextContents(),{timeout:45000,message:`Waiting for source option ${re}`}).toEqual(expect.arrayContaining([expect.stringMatching(re)]));const options=select.locator('option');const count=await options.count();for(let i=0;i<count;i++){const o=options.nth(i),label=(await o.textContent())||'';if(re.test(label)){const value=await o.getAttribute('value');await select.selectOption(value??{label});return}}throw new Error(`No option matched ${re}`)}
function sourceControl(page){return page.locator('.l2p-panel').filter({has:page.getByRole('heading',{name:'Provider routing & fallback',exact:true})}).locator('select').first()}
async function openProviders(page){await clickPrimaryNav(page,'Layer 2 Operations');const ops=page.getByRole('dialog',{name:'Layer 2 Operations'});await expect(ops).toBeVisible({timeout:45000});await ops.getByRole('button',{name:/Configure/i}).click();await expect(ops).toBeHidden({timeout:15000});await expect(page.getByRole('heading',{name:'Layer 2 Acquisition Providers'})).toBeVisible({timeout:45000});await expect(sourceControl(page)).toBeVisible({timeout:45000})}

test.describe('CourseFinder deployed Layer 2 acquisition-provider acceptance @deployed',()=>{
  test.beforeAll(async()=>{if(!process.env.UAT_BASE_URL)throw new Error('UAT_BASE_URL is required');if(!process.env.UAT_EMAIL||!process.env.UAT_PASSWORD)throw new Error('UAT credentials are required');await writeRunEnvironment({suite:'deployed-layer2-provider-v1.6',change_control:'CF-CHG-20260823-029'})})
  test('provider registry and source routing are visible without exposing credentials',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);await openProviders(page);await expect(page.getByText(/Credentials are write-only and acquisition URLs are source-bound/i)).toBeVisible();for(const name of ['Direct HTTP','Scrape.do','ScraperAPI','Firecrawl','ZenRows (JS render + premium proxy)','Custom gateway ({url} template)'])await expect(page.getByText(name,{exact:true}).first()).toBeVisible();const source=sourceControl(page);await selectMatching(source,/RMIT/i);for(const name of ['Direct HTTP','Scrape.do','ScraperAPI','Firecrawl','ZenRows (JS render + premium proxy)'])await expect(page.getByText(name,{exact:true}).last()).toBeVisible({timeout:45000});expect((await page.locator('body').innerText())).not.toMatch(/sb_secret_|service_role|SUPABASE_SERVICE_ROLE_KEY/i);await milestoneScreenshot(page,testInfo,'layer2-provider-routing-v1-6')}finally{await finish(testInfo,runtime)}})
  test('bounded direct Course acquisition creates versioned Evidence through the governed source route',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);await openProviders(page);const source=sourceControl(page);await selectMatching(source,/RMIT/i);await page.getByRole('button',{name:/Run bounded acquisition/i}).click();const result=page.locator('.l2p-run');await expect(result).toContainText('Acquisition PASS',{timeout:90000});await expect(result).toContainText('Direct HTTP');await expect(result).toContainText(/Evidence/i);await milestoneScreenshot(page,testInfo,'layer2-provider-acquisition-pass-v1-6')}finally{await finish(testInfo,runtime)}})
  test('provider detail preserves the write-only credential boundary for the UAT operator',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);await openProviders(page);const providerButton=page.locator('.l2p-provider-list > button').filter({hasText:'Scrape.do'}).first();await expect(providerButton).toBeVisible();await providerButton.click();const drawer=page.locator('.l2p-drawer');await expect(drawer).toBeVisible();await expect(drawer.getByText(/Configured in Vault|Not configured/)).toBeVisible();const password=drawer.locator('input[type="password"][placeholder*="Stored in Vault"]');if(await password.count())await expect(password).toHaveValue('');expect((await drawer.innerText())).not.toMatch(/sb_secret_|service_role|SUPABASE_SERVICE_ROLE_KEY/i);await milestoneScreenshot(page,testInfo,'layer2-provider-credential-boundary-v1-6')}finally{await finish(testInfo,runtime)}})
})
