import { test, expect } from '@playwright/test'
import { attachRuntimeEvidence, assertNoServerErrors, loginAsUatUser, milestoneScreenshot, observeRuntime, writeRunEnvironment } from './support/runtime-evidence.mjs'
import { openLayer2 } from './support/navigation.mjs'

async function finish(testInfo,runtime){await attachRuntimeEvidence(testInfo,runtime);assertNoServerErrors(runtime)}

test.describe('CourseFinder deployed Layer 2 operations maturity @deployed',()=>{
 test.beforeAll(async()=>{if(!process.env.UAT_BASE_URL)throw new Error('UAT_BASE_URL is required');if(!process.env.UAT_EMAIL||!process.env.UAT_PASSWORD)throw new Error('UAT credentials are required');await writeRunEnvironment({suite:'deployed-layer2-operations-m2-4-2-v1.2',change_control:'CF-CHG-20260827-044'})})
 test('routine Layer 2 workspace exposes country to university sync and quarantines acquisition internals',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);const dialog=await openLayer2(page);await expect(dialog.getByRole('heading',{name:'Layer 2 — Enrichment'})).toBeVisible();await expect(dialog.getByRole('heading',{name:'Sync Course enrichment'})).toBeVisible();const country=dialog.getByLabel('Layer 2 sync country'),uni=dialog.getByLabel('Layer 2 sync university');await expect(country).toBeVisible();await expect(country).toHaveValue('AU');await expect(uni).toBeVisible();const labels=await uni.locator('option').allTextContents();expect(labels.join(' ')).toMatch(/RMIT/i);expect(labels.join(' ')).toMatch(/Queensland/i);expect(labels.join(' ')).toMatch(/Federation/i);for(const label of ['Catalogue','Ready to sync','Needs discovery','Run concurrency'])await expect(dialog.getByText(label,{exact:true}).first()).toBeVisible();await expect(dialog.getByRole('button',{name:/Discover & sync|Sync now|Run active/})).toBeVisible();await expect(dialog.getByRole('button',{name:/Run bounded trial/i})).toHaveCount(0);await expect(dialog.getByText(/Acquisition vendors and routing stay automatic/i)).toBeVisible();await expect(dialog.getByText(/NZ Course enrichment:/)).toBeVisible();await milestoneScreenshot(page,testInfo,'layer2-simple-sync-m2-4-2')}finally{await finish(testInfo,runtime)}})
 test('governed profile policy distinguishes run concurrency from acquisition-vendor concurrency',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);const dialog=await openLayer2(page);await dialog.getByRole('button',{name:'Schedule & run policy'}).first().click();const modal=page.locator('.l2o-card');await expect(modal).toBeVisible();await expect(modal.getByText('Run concurrency',{exact:true})).toBeVisible();const c=modal.locator('input[type="number"]').nth(1);await expect(c).toHaveAttribute('min','1');await expect(c).toHaveAttribute('max','8');await expect(modal.getByText(/Acquisition-vendor concurrency.*configured separately/i)).toBeVisible();await expect(modal.getByRole('button',{name:/delete|reset|truncate/i})).toHaveCount(0);await modal.getByRole('button',{name:'Cancel'}).click()}finally{await finish(testInfo,runtime)}})
})
