import fs from 'node:fs/promises'
import { test, expect } from '@playwright/test'
import { attachRuntimeEvidence, assertNoServerErrors, loginAsUatUser, milestoneScreenshot, observeRuntime, writeRunEnvironment } from './support/runtime-evidence.mjs'
import { openLayer2 } from './support/navigation.mjs'

async function finish(testInfo,runtime){await attachRuntimeEvidence(testInfo,runtime);assertNoServerErrors(runtime)}
async function firecrawlDrawer(page){const b=page.locator('.l2p-provider-list > button').filter({hasText:'Firecrawl'}).first();await expect(b).toBeVisible();await b.click();const d=page.locator('.l2p-drawer');await expect(d).toBeVisible();return d}

test.describe('CourseFinder deployed Layer 2 operations maturity @deployed',()=>{
 test.beforeAll(async()=>{if(!process.env.UAT_BASE_URL)throw new Error('UAT_BASE_URL is required');if(!process.env.UAT_EMAIL||!process.env.UAT_PASSWORD)throw new Error('UAT credentials are required');await writeRunEnvironment({suite:'deployed-layer2-operations-m2-4-2-v1.7',change_control:'CF-CHG-20260827-044'})})

 test('routine Layer 2 workspace exposes Country State University scope with one governed sync action',async({page},testInfo)=>{const runtime=observeRuntime(page);try{
  await loginAsUatUser(page);const dialog=await openLayer2(page)
  await expect(dialog.getByRole('heading',{name:'Layer 2 — Enrichment'})).toBeVisible()
  await expect(dialog.getByRole('heading',{name:'Sync Course enrichment'})).toBeVisible()
  const country=dialog.getByLabel('Layer 2 sync country'),scope=dialog.getByLabel('Layer 2 fetch scope')
  await expect(country).toHaveValue('AU');await expect(scope).toHaveValue('country');const countryLabels=await country.locator('option').allTextContents();expect(countryLabels.join(' ')).toMatch(/Australia.*Canada.*New Zealand/i)
  const scopeLabels=await scope.locator('option').allTextContents();expect(scopeLabels.join(' ')).toMatch(/Country.*State.*University/i)
  for(const label of ['Layer 1 Institutions','Layer 1 Courses','L2 Qualified','Needs qualification','Ready with governed URL'])await expect(dialog.getByText(label,{exact:true}).first()).toBeVisible()
  await expect(dialog.getByRole('button',{name:/Qualify next wave|Discover & sync|Sync now/})).toBeVisible()

  await scope.selectOption('state')
  const state=dialog.getByLabel('Layer 2 sync state');await expect(state).toBeVisible()
  await state.click()
  const stateList=dialog.getByRole('listbox',{name:'State options'});await expect(stateList).toBeVisible()
  await expect(stateList.getByRole('option',{name:'Queensland',exact:true})).toBeVisible()
  await stateList.getByRole('option',{name:'Queensland',exact:true}).click()
  await expect(dialog.getByText('Institutions included in this State',{exact:true})).toBeVisible()
  await expect(dialog.getByText('The University of Queensland',{exact:true})).toBeVisible()

  await scope.selectOption('university')
  const uni=dialog.getByLabel('Layer 2 sync university');await expect(uni).toBeVisible()
  await uni.click()
  const uniList=dialog.getByRole('listbox',{name:'University options'});await expect(uniList).toBeVisible()
  await expect(uniList.getByRole('option').filter({hasText:'The University of Queensland'})).toBeVisible()
  await expect(dialog.getByText(/Direct HTTP.*Firecrawl.*remaining configured providers/i)).toBeVisible()
  await expect(dialog.getByRole('button',{name:/Run bounded trial/i})).toHaveCount(0)
  await expect(dialog.getByRole('heading',{name:'Blockers / required actions'})).toBeVisible()
  await expect(dialog.getByText(/need Layer 2 source qualification before full sync/i)).toBeVisible()
  await milestoneScreenshot(page,testInfo,'layer2-a9-scope-sync')
 }finally{await finish(testInfo,runtime)}})

 test('routine Layer 2 screen quarantines engineering controls behind one Advanced configuration entry',async({page},testInfo)=>{const runtime=observeRuntime(page);try{
  await loginAsUatUser(page);const dialog=await openLayer2(page)
  await expect(dialog.getByRole('button',{name:/Advanced configuration/i})).toHaveCount(1)
  await expect(dialog.getByRole('heading',{name:'Scope / eligible records'})).toHaveCount(0)
  await expect(dialog.getByRole('heading',{name:'Provider / source performance'})).toHaveCount(0)
  await expect(dialog.getByRole('heading',{name:'Queue / concurrency'})).toHaveCount(0)
  await expect(dialog.getByRole('button',{name:/Schedule & run policy/i})).toHaveCount(0)
  await expect(dialog.getByRole('button',{name:/Advanced provider config/i})).toHaveCount(0)
  await expect(dialog.getByText(/provider credentials|route priority|vendor concurrency/i)).toHaveCount(0)
  await expect(dialog.getByRole('button',{name:/delete|reset|truncate/i})).toHaveCount(0)
 }finally{await finish(testInfo,runtime)}})

 test('advanced acquisition provider controls stay quarantined from the routine rank-4 workspace',async({page},testInfo)=>{const runtime=observeRuntime(page);try{
  await loginAsUatUser(page);const dialog=await openLayer2(page)
  await expect(dialog.getByRole('button',{name:/Advanced configuration/i})).toHaveCount(1)
  const providerLauncher=page.locator('.l2p-launcher')
  await expect(providerLauncher).toBeAttached()
  await expect(providerLauncher).toBeHidden()
  await expect(page.getByRole('heading',{name:'Layer 2 Acquisition Providers'})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Edit provider settings'})).toHaveCount(0)
  await milestoneScreenshot(page,testInfo,'layer2-provider-controls-quarantined')
 }finally{await finish(testInfo,runtime)}})


 test('A10 Course Provider filter is server-paged and does not auto-focus on coarse pointer',async({page},testInfo)=>{const runtime=observeRuntime(page);try{
  await page.addInitScript(()=>{const native=window.matchMedia.bind(window);window.matchMedia=q=>q==='(pointer:fine)'?{matches:false,media:q,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return false}}:native(q)})
  await loginAsUatUser(page)
  await page.evaluate(()=>{location.hash='#courses'})
  await expect(page.getByRole('heading',{name:'Courses',exact:true})).toBeVisible()
  const provider=page.locator('.m-filter-select').filter({hasText:'Provider'}).first()
  const request1=page.waitForResponse(r=>{if(!r.url().includes('/rest/v1/rpc/admin_read'))return false;try{const b=r.request().postDataJSON();return b?.p_operation==='catalogue_filter_page'&&b?.p_args?.filter_kind==='provider'}catch{return false}})
  await provider.locator('button.m-filter-button').click()
  const response1=await request1
  const body1=await response1.json()
  expect(body1.limit).toBe(10);expect(body1.items.length).toBeLessThanOrEqual(10)
  const search=provider.locator('.m-filter-search input')
  await expect(search).toBeVisible();await expect(search).not.toBeFocused()
  if(Number(body1.total||0)>10)await expect(provider.getByText(/1 \/ \d+/)).toBeVisible()
  const request2=page.waitForResponse(r=>{if(!r.url().includes('/rest/v1/rpc/admin_read'))return false;try{const b=r.request().postDataJSON();return b?.p_operation==='catalogue_filter_page'&&b?.p_args?.filter_kind==='provider'&&String(b?.p_args?.query||'').includes('University')}catch{return false}})
  await search.fill('University')
  const response2=await request2
  const body2=await response2.json()
  expect(body2.limit).toBe(10);expect(body2.items.length).toBeLessThanOrEqual(10);expect(Number(body2.total||0)).toBeGreaterThan(10)
  await milestoneScreenshot(page,testInfo,'a10-course-provider-paged-filter')
 }finally{await finish(testInfo,runtime)}})

 test('Layer 2 recovery and reference contracts remain checked in',async()=>{
  const cancelSql=await fs.readFile('supabase/migrations/20260827221500_m2_4_2_cancel_reconcile_guard.sql','utf8')
  expect(cancelSql).toContain("if v_existing='cancelled'")
  expect(cancelSql).toContain("v_status:='cancelled'")
  expect(cancelSql).toMatch(/revoke all on function public\.layer2_run_batch_reconcile\(uuid\) from public,anon,authenticated/i)
  expect(cancelSql).toMatch(/grant execute on function public\.layer2_run_batch_reconcile\(uuid\) to service_role/i)

  const rmitReverifySql=await fs.readFile('supabase/migrations/20260827225000_m2_4_2_rmit_detail_cricos_reverification.sql','utf8')
  expect(rmitReverifySql).toContain('pre_detail_verification_status')
  expect(rmitReverifySql).toContain('layer2-scope-discover-scheduled-v1.3.0')
  expect(rmitReverifySql).toContain("status='candidate'")
  expect(rmitReverifySql).toContain('selected=false')

  const opsSql=await fs.readFile('supabase/migrations/20260827224000_m2_4_2_layer2_refresh_housekeeping.sql','utf8')
  expect(opsSql).toContain('coursefinder-layer2-refresh-dispatcher')
  expect(opsSql).toContain('coursefinder-layer2-housekeeping')
  expect(opsSql).toContain('governed_evidence_deleted')
  expect(opsSql).toContain("enabled,change_control_ref,updated_at")
  expect(opsSql).toContain("true,true,false,'CF-CHG-20260827-044'")

  const alertAclSql=await fs.readFile('supabase/migrations/20260827225500_m2_4_2_layer2_alert_acl_reconcile.sql','utf8')
  expect(alertAclSql).toMatch(/grant execute on function security\.layer2_operational_alerts_read\(\) to authenticated,service_role/i)

  const providerUi=await fs.readFile('src/layer2-provider-entry.jsx','utf8')
  expect(providerUi).toContain('Vendor concurrency')
  expect(providerUi).toContain('Rate / timeout')
  expect(providerUi).toContain('rank>=6')
  expect(providerUi).toContain('Credentials are write-only and provider concurrency is separate from run concurrency.')

  const alertSql=await fs.readFile('supabase/migrations/20260827224500_m2_4_2_layer2_operational_alerts.sql','utf8')
  expect(alertSql).toContain('layer2_ops_alerts')
  expect(alertSql).toContain('provider_quota_reserve')
  expect(alertSql).toContain('provider_failure_streak')
  expect(alertSql).toMatch(/grant execute on function security\.layer2_operational_alerts_read\(\) to authenticated,service_role/i)

  const idemSql=await fs.readFile('supabase/migrations/20260827223500_m2_4_2_discovery_terminal_outcome_idempotency.sql','utf8')
  expect(idemSql).toContain("dc.status in ('exact_match','likely_match','ambiguous','identity_mismatch','current_page_not_found')")
  expect(idemSql).toMatch(/grant execute on function public\.layer2_discovery_context\(uuid,integer\) to service_role/i)

  const toeflSql=await fs.readFile('supabase/migrations/20260827223000_m2_4_2_toefl_ibt_apply_mapping.sql','utf8')
  expect(toeflSql).toContain("TOEFL_IBT")
  expect(toeflSql).toContain("layer2_apply_course_candidate")
  expect(toeflSql).toMatch(/grant execute on function public\.layer2_apply_course_candidate\(uuid,boolean\) to service_role/i)

  const layer2ScopeSql=await fs.readFile('supabase/migrations/20260827232000_a10_layer2_paged_scope_options.sql','utf8')
  expect(layer2ScopeSql).toContain('layer2_scope_options_page_service')
  expect(layer2ScopeSql).toContain('layer2_scope_countries_service')
  expect(layer2ScopeSql).toContain('least(greatest(coalesce(p_limit,10),1),10)')
  expect(layer2ScopeSql).toContain("v_def:=replace(v_def,v_old,'')")
  const scaleScopeSql=await fs.readFile('supabase/migrations/20260827235500_m2_4_2_a11_layer1_catalogue_scale_scope.sql','utf8')
  expect(scaleScopeSql).toContain('layer2_scale_scope_service')
  expect(scaleScopeSql).toContain("'scope_source','layer1_catalogue'")
  expect(scaleScopeSql).toContain("p_action='qualify_wave'")
  expect(scaleScopeSql).toContain("'canonical_mutation_authorised',false")
  const scaleExecSql=await fs.readFile('supabase/migrations/20260827235700_m2_4_2_a11_qualification_execution_reconcile.sql','utf8')
  expect(scaleExecSql).toContain('qualification_candidate')
  expect(scaleExecSql).toContain('layer2_scale_qualification_prepare')
  expect(scaleExecSql).toContain('layer2_scale_pattern_dispatch')
  expect(scaleExecSql).toContain('layer2_scale_pattern_reconcile')
  expect(scaleExecSql).toContain('layer2_scale_cross_layer_handoff')
  expect(scaleExecSql).toContain('blocked_pending_dedicated_source_pattern_layer3_profile_benchmark')
  expect(scaleExecSql).toContain("'canonical_mutation_authorised',false")
  expect(scaleExecSql).toContain("'search_mutation_authorised',false")
  expect(scaleExecSql).toContain("'publication_mutation_authorised',false")
  expect(scaleExecSql).toMatch(/revoke all on function public\.layer2_scale_qualification_prepare\(uuid\) from public,anon,authenticated/i)
  expect(scaleExecSql).toMatch(/grant execute on function public\.layer2_scale_qualification_prepare\(uuid\) to service_role/i)


  const sourcePatternSql=await fs.readFile('supabase/migrations/20260827235800_m2_4_2_a11_layer3_source_pattern_profile.sql','utf8')
  expect(sourcePatternSql).toContain("'openrouter-source-pattern-v1'")
  expect(sourcePatternSql).toContain("array['source_pattern']")
  expect(sourcePatternSql).toContain("'m2.4.2-source-pattern-v1'")
  expect(sourcePatternSql).toContain('candidate_url_must_be_same_host')
  expect(sourcePatternSql).toContain('candidate_url_must_be_evidence_link')
  expect(sourcePatternSql).toContain("'canonical")
  expect(sourcePatternSql).toMatch(/revoke all on function public\.layer3_source_pattern_benchmark_profile_service\(\) from public,anon,authenticated/i)
  expect(sourcePatternSql).toMatch(/grant execute on function public\.layer3_source_pattern_benchmark_profile_service\(\) to service_role/i)

  const sourcePatternBlockedSql=await fs.readFile('supabase/migrations/20260827235900_m2_4_2_a11_source_pattern_benchmark_blocked.sql','utf8')
  expect(sourcePatternBlockedSql).toContain("'source_pattern_benchmark_blocked'")
  expect(sourcePatternBlockedSql).toContain("'canonical_mutation_authorised',false")
  expect(sourcePatternBlockedSql).toContain("'search_mutation_authorised',false")
  expect(sourcePatternBlockedSql).toContain("'publication_mutation_authorised',false")
  expect(sourcePatternBlockedSql).toContain("paused=true")

  const sourcePatternWorker=await fs.readFile('supabase/functions/layer3-source-pattern-benchmark/index.ts','utf8')
  expect(sourcePatternWorker).toContain('layer3-source-pattern-benchmark-v1.0.6')
  expect(sourcePatternWorker).toContain('x-cf-run-nonce')
  expect(sourcePatternWorker).toContain('candidate_not_in_evidence_links')
  expect(sourcePatternWorker).toContain('same_host_required')
  expect(sourcePatternWorker).toContain('negative_control_must_be_null')
  expect(sourcePatternWorker).toContain('reasoning:{effort:"none",exclude:true}')
  expect(sourcePatternWorker).toContain('response_format:{type:"json_schema"')

  const scaleWorker=await fs.readFile('supabase/functions/layer2-scale-qualify-scheduled/index.ts','utf8')
  expect(scaleWorker).toContain('layer2-scale-qualify-scheduled-v1.0.1')
  expect(scaleWorker).toContain('x-cf-run-nonce')
  expect(scaleWorker).toContain('svc_pilot_consume_nonce')
  expect(scaleWorker).toContain('.schema("pipeline").rpc')
  expect(scaleWorker).toContain('canonical_mutation_authorised:false')

  const syncControl=await fs.readFile('supabase/functions/layer2-sync-control/index.ts','utf8')
  expect(syncControl).toContain("action==='scope_options_page'")
  expect(syncControl).toContain("action==='qualify_scope'")
  expect(syncControl).toContain("layer2_scale_scope_service")
  expect(syncControl).toContain("p_limit:pageLimit")

  const pagedFilterSql=await fs.readFile('supabase/migrations/20260827231500_a10_paged_catalogue_filters.sql','utf8')
  expect(pagedFilterSql).toContain("v_limit integer:=least(greatest(coalesce(nullif(p_args->>'limit','')::integer,10),1),10)")
  expect(pagedFilterSql).toContain("'has_more'")
  expect(pagedFilterSql).toContain("catalogue_filter_page")

  const matureUi=await fs.readFile('src/mature-main.jsx','utf8')
  expect(matureUi).toContain('function PagedFilterSelect')
  expect(matureUi).toContain("matchMedia?.('(pointer:fine)')")
  expect(matureUi).not.toContain('<input autoFocus')
  expect(matureUi).toContain('slice(safePage*10,safePage*10+10)')

  const l2Ui=await fs.readFile('src/layer2-operations-entry.jsx','utf8')
  expect(l2Ui).toContain('Institutions included in this State')
  expect(l2Ui).toContain('function PagedScopeSelect')
  expect(l2Ui).toContain('function ScopeUniversityList')
  expect(l2Ui).toContain("action:'scope_options_page'")

  const discovery=await fs.readFile('supabase/functions/layer2-scope-discover-scheduled/index.ts','utf8')
  expect(discovery).toContain('layer2-scope-discover-scheduled-v1.3.0')
  expect(discovery).toContain('courseBudgetMs')
  expect(discovery).toContain('invocationBudgetMs=80000')
  expect(discovery).toContain('continuation_request_id')
  expect(discovery).toContain('consumedSet')
  expect(discovery).toContain('courseIds.filter')
  expect(discovery).toContain('invocationRemainingMs')
  expect(discovery).toContain('budgetCapMs')
  expect(discovery).toContain('layer2_discovery_context_scope')
  expect(discovery).toContain('verifyCandidateDetail')
  expect(discovery).toContain('detail_cricos_verified')
  expect(discovery).toContain('course_url_identity_verification')
  expect(discovery).toContain('identity-verification.html')
 })

})
