import { test, expect } from '@playwright/test'
import { attachRuntimeEvidence, assertNoServerErrors, loginAsUatUser, milestoneScreenshot, observeRuntime, writeRunEnvironment } from './support/runtime-evidence.mjs'
import { openLayer2Advanced } from './support/navigation.mjs'

async function finish(testInfo,runtime){await attachRuntimeEvidence(testInfo,runtime);assertNoServerErrors(runtime)}

test.describe('CourseFinder deployed Layer 2 platform acceptance @deployed',()=>{
 test.beforeAll(async()=>{if(!process.env.UAT_BASE_URL)throw new Error('UAT_BASE_URL is required');if(!process.env.UAT_EMAIL||!process.env.UAT_PASSWORD)throw new Error('UAT credentials are required');await writeRunEnvironment({suite:'deployed-layer2-platform-v1.6',change_control:'CF-CHG-20260823-029'})})
 test('advanced source configuration is reachable through accepted Layer 2 navigation and exposes governed Course/Scholarship profiles',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);await openLayer2Advanced(page);await expect(page.getByText('Configuration is separate from execution.')).toBeVisible();await expect(page.getByText(/RMIT/i).first()).toBeVisible();await expect(page.getByText(/Queensland/i).first()).toBeVisible();await expect(page.getByText(/Federation/i).first()).toBeVisible();await expect(page.getByText(/Study Australia/i).first()).toBeVisible();await expect(page.getByLabel('Search profiles')).toBeVisible();await expect(page.getByLabel('Country filter')).toBeVisible();await expect(page.getByLabel('Acquisition method filter')).toBeVisible();await expect(page.getByLabel('Health filter')).toBeVisible();await page.getByLabel('Search profiles').fill('Federation');await expect(page.locator('.l2-table tbody tr')).toHaveCount(1);await expect(page.locator('.l2-table tbody tr').first()).toContainText(/Federation/i);await milestoneScreenshot(page,testInfo,'layer2-profile-list-v1-6')}finally{await finish(testInfo,runtime)}})
 test('profile detail shows safe versioned configuration, diff, traceability and governed editor',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);await openLayer2Advanced(page);await page.getByLabel('Search profiles').fill('Federation');const row=page.locator('.l2-table tbody tr').first();await expect(row).toBeVisible();await row.click();const drawer=page.locator('aside.l2-drawer');await expect(drawer).toBeVisible();await expect(drawer.getByText('Governed non-secret configuration')).toBeVisible();await expect(drawer.getByText('Changes from previous version')).toBeVisible();await expect(drawer.getByText('Configuration history')).toBeVisible();await expect(drawer.getByText('Traceability')).toBeVisible();await expect(drawer.getByText(/Evidence Required/i)).toBeVisible();await expect(drawer.getByText(/Content Change Policy/i)).toBeVisible();const configText=await drawer.locator('.l2-config').first().innerText();expect(configText).not.toMatch(/(^|\n)(password|token|api key|client secret|authorization|cookie)(\n|$)/i);const createVersion=drawer.getByRole('button',{name:'Create new version'});if(await createVersion.count()){await createVersion.click();await expect(drawer.getByLabel('Layer 2 configuration JSON')).toBeVisible();await expect(drawer.getByRole('button',{name:'Validate & create version'})).toBeVisible();await drawer.getByRole('button',{name:'Cancel'}).click()}await milestoneScreenshot(page,testInfo,'layer2-profile-detail-v1-6')}finally{await finish(testInfo,runtime)}})
})
