import { test, expect } from '@playwright/test'
// Clean-up batch 2 (9 Oct 2026): per-source routing and the test fetch were retired with Source profiles; the provider registry checks stay.
import { attachRuntimeEvidence, assertNoServerErrors, loginAsUatUser, milestoneScreenshot, observeRuntime, writeRunEnvironment } from './support/runtime-evidence.mjs'
import { openLayer2Providers } from './support/navigation.mjs'

async function finish(testInfo,runtime){await attachRuntimeEvidence(testInfo,runtime);assertNoServerErrors(runtime)}
async function openProviders(page){await openLayer2Providers(page);await expect(page.locator('.l2p-provider-list').first()).toBeVisible()}

test.describe('CourseFinder deployed Layer 2 acquisition-provider acceptance @deployed',()=>{
  test.beforeAll(async()=>{if(!process.env.UAT_BASE_URL)throw new Error('UAT_BASE_URL is required');if(!process.env.UAT_EMAIL||!process.env.UAT_PASSWORD)throw new Error('UAT credentials are required');await writeRunEnvironment({suite:'deployed-layer2-provider-v1.9',change_control:'CF-CHG-20260823-029'})})
  test('provider registry is visible without exposing credentials',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);await openProviders(page);await expect(page.getByText(/Credentials stay write-only/i)).toBeVisible();const list=page.locator('.l2p-provider-list').first();for(const name of ['Firecrawl','Scrape.do'])await expect(list.getByText(name).first()).toBeVisible({timeout:45000});expect((await page.locator('body').innerText())).not.toMatch(/sb_secret_|service_role|SUPABASE_SERVICE_ROLE_KEY/i);await milestoneScreenshot(page,testInfo,'layer2-provider-routing-v1-9')}finally{await finish(testInfo,runtime)}})
  test('provider detail preserves the write-only credential boundary for the UAT operator',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);await openProviders(page);const providerButton=page.locator('.l2p-provider-list > button').filter({hasText:'Scrape.do'}).first();await expect(providerButton).toBeVisible();await providerButton.click();const drawer=page.locator('.l2p-drawer');await expect(drawer).toBeVisible();await expect(drawer.getByText(/Configured in Vault|Not configured/)).toBeVisible();const password=drawer.locator('input[type="password"][placeholder*="Stored in Vault"]');if(await password.count())await expect(password).toHaveValue('');expect((await drawer.innerText())).not.toMatch(/sb_secret_|service_role|SUPABASE_SERVICE_ROLE_KEY/i);await milestoneScreenshot(page,testInfo,'layer2-provider-credential-boundary-v1-9')}finally{await finish(testInfo,runtime)}})
})
