import { test, expect } from '@playwright/test'
import {attachRuntimeEvidence,assertNoServerErrors,loginAsUatUser,milestoneScreenshot,observeRuntime,writeRunEnvironment} from './support/runtime-evidence.mjs'
import {openScholarshipSelection} from './support/navigation.mjs'

async function finish(testInfo,runtime){await attachRuntimeEvidence(testInfo,runtime);assertNoServerErrors(runtime)}

test.describe('CourseFinder deployed Scholarship decision-support acceptance @deployed',()=>{
 test.beforeAll(async()=>{if(!process.env.UAT_BASE_URL)throw new Error('UAT_BASE_URL is required for deployed acceptance.');if(!process.env.UAT_EMAIL||!process.env.UAT_PASSWORD)throw new Error('UAT credentials are required.');await writeRunEnvironment({suite:'deployed-scholarship-selection-v2',change_control:'CF-CHG-20260825-036'})})
 test('labels sourced facts, derived scope score and unresolved eligibility without eligibility inference',async({page},testInfo)=>{const runtime=observeRuntime(page);try{await loginAsUatUser(page);const dialog=await openScholarshipSelection(page);await dialog.getByLabel('Course ID').fill('55874f1f-6741-40e9-adc5-689c9f1df0a7');await dialog.getByRole('button',{name:/Find scholarship candidates/i}).click();await expect(dialog.getByText('Eligibility inference permitted: NO',{exact:true})).toBeVisible();await expect(dialog.getByText('RMIT David Phillips Memorial Scholarship',{exact:true})).toBeVisible();await expect(dialog.getByText('RMIT English Language Bursary for Latin American Students',{exact:true})).toBeVisible();await expect(dialog.getByText('RMIT Irana Turynska Scholarship',{exact:true})).toBeVisible();await expect(dialog.getByText('Australia Awards Scholarships',{exact:true})).toBeVisible();await expect(dialog.getByRole('heading',{name:'SOURCE FACT',exact:true}).first()).toBeVisible();await expect(dialog.getByRole('heading',{name:'DERIVED SCORE',exact:true}).first()).toBeVisible();await expect(dialog.getByRole('heading',{name:'MISSING / UNRESOLVED',exact:true}).first()).toBeVisible();await expect(dialog.getByText(/eligibility UNRESOLVED/i).first()).toBeVisible();await milestoneScreenshot(page,testInfo,'m2-3-scholarship-selection')}finally{await finish(testInfo,runtime)}})
})
